### ISSUE TITLE
[Episode 3] Counter Card does not appear to work

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#103]
This may just be bad RNG on our parts, but nobody seems to have had the counter (or counter +) card be successful online.

Counter specifically has a 70% chance of reflecting damage back, as per the in-game description below.

![image](https://github.com/fuzziqersoftware/newserv/assets/33199242/a4598ea8-18db-4491-89da-e1fcb7cb2e25)

No logs currently, but can go fetch some if it would help.

**Comment by fuzziqersoftware** [comment]
I think this was caused by the same bug as #105 - at least, the Counter and Counter+ cards seem to work properly for me after fixing that bug. Please reopen this if it's still not working.
