### ISSUE TITLE
[Episode 3] Decimals are rounding up instead of being truncated

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#104]
In the offline game, and according to players who have played on SEGA's official servers too, whenever decimals occur, they are truncated, however this is not occurring online and all damage appears to be rounding up instead.

While not exactly "proof" either because SEGA always lies, they also have an in-game tutorial which says that everything should truncate:

![image](https://github.com/fuzziqersoftware/newserv/assets/33199242/3fa5f49b-337f-40c2-ae84-9646ff8e6c99)
![image](https://github.com/fuzziqersoftware/newserv/assets/33199242/457ca13c-1156-4c09-adbe-1cf3050508d3)
![image](https://github.com/fuzziqersoftware/newserv/assets/33199242/35e24758-5c58-4fd0-afdc-ec422965b799)
![image](https://github.com/fuzziqersoftware/newserv/assets/33199242/9192b3ab-76e9-4abe-92b7-0f14c4f65179)
![image](https://github.com/fuzziqersoftware/newserv/assets/33199242/27c807ff-b01b-4ec9-aa05-8daa27627ad3)
![image](https://github.com/fuzziqersoftware/newserv/assets/33199242/ad88d20a-6d3a-41d6-bcff-a86879aec68a)

As usual, let me know if there's anything that would be worth me logging.

**Comment by fuzziqersoftware** [comment]
This is fixed now. We were doing `round(x / y)` where x and y are both integers, so the integer division + truncation was happening first and round() was doing nothing.
