### ISSUE TITLE
[Episode 3] Investigate Tempest behavior when no cards have >= 8 HP

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#105]
When used online, the Tempest card is affecting story characters even though it shouldn't be, per the card description:

![image](https://github.com/fuzziqersoftware/newserv/assets/33199242/5b46da57-e3c0-44f5-8886-e7a482386616)
![image](https://github.com/fuzziqersoftware/newserv/assets/33199242/4778ad01-ba58-4de4-93f7-3919631461ae)
![image](https://github.com/fuzziqersoftware/newserv/assets/33199242/8b43e49a-b979-4a0f-9f7f-8bb0b1879eea)
![image](https://github.com/fuzziqersoftware/newserv/assets/33199242/7982cb2c-f522-4c51-8626-497674a31379)
![image](https://github.com/fuzziqersoftware/newserv/assets/33199242/5c70ac4c-1a33-48f1-bda1-823be0c22c36)

All the other rules are being respected, just not the SC block.

Let me know if you need anything further.

**Comment by fuzziqersoftware** [comment]
I'm surprised this bug didn't cause more extensive problems; the bug caused the server to use the wrong condition code when applying special effects, so I'd expect many more effects to apply when they shouldn't or not apply when they should as a result of this. Anyway, it should be fixed now.

I've also discovered something weird... it appears that if you use Tempest and there are no candidates (FCs with >= 8 HP), then your SC hits all characters on the field for (SC's AP) damage. This also happens offline, so it's technically vanilla behavior, but it's almost certainly still a bug. I'm going to leave this open as a reminder to look into it.

**Comment by fuzziqersoftware** [comment]
I've changed my mind here... I think newserv's goal for Episode 3 should be to replicate offline behavior, so I've decided to leave Tempest as-is even though it's kind of broken.
