### ISSUE TITLE
[Episode 3] VIP Auction Fails to Start

### ISSUE THREAD

**Issue by ShiftaDeband** [fuzziqersoftware/newserv#106]
Background: Built on Ubuntu, running on a Digital Ocean droplet with a public IP. Built from the repo, I also installed psog and resource-dasm (and Netpbm). All four test clients are on the same computer, but I believe I've tested this before using different devices (mix of real hardware, Wii with Nintendont, Dolphin instances).

Whenever the host tries to start a VIP auction, the counter will tell other clients that the host is saving. After that, all clients are taken to a screen where the VIP auction would begin, but stays at this background and does not progress.

Here's a screencap: https://www.youtube.com/watch?v=wV4JH21lVFw

And here's a recent video from Kayak showing expected behavior: https://www.youtube.com/watch?v=0NPc1WNyzKk

[Log attached](https://github.com/fuzziqersoftware/newserv/files/12541265/vipauction.txt). Wondering if some kind of command isn't being sent correctly here?

Please let me know if I can provide anything else to assist!

**Comment by fuzziqersoftware** [comment]
Thanks for the report; this is fixed now. We were treating the EF command like the AC command (so we waited for all players to send it), but it turns out that unlike AC, only the leader sends EF.
