### ISSUE TITLE
[Episode 3] Curse card cannot be played

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#108]
Attempting to play the Curse card causes the game to back up to prior to the selection of the card.

See video and logs below. The log begins just before selecting the weapon, then the player says "Word 1", and selects the weapon. Let me know if you need anything more.

As can be seen by the video as well, this is an unreleased card, but definitely works offline.

[message.txt](https://github.com/fuzziqersoftware/newserv/files/12563008/message.txt)

https://github.com/fuzziqersoftware/newserv/assets/33199242/bb748507-def0-4538-ac20-cca5dad30b53

**Comment by fuzziqersoftware** [comment]
This is fixed now. I had incorrectly delabeled one case while reverse-engineering the card usability conditions.
