### ISSUE TITLE
[Episode 3] MV adjustments do not appear to work

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#109]
A Recobox card with the Earth Bind ability was played online against a COM Kylria, however it appeared to have no effect and she was able to move 2 tiles instead of the card description of 1.

I have no logs or video at the moment, but can go get the information if required.

EDIT: Epsilon's stall ability also does not appear to have any effect, so it's most likely MV adjustments.

**Comment by fuzziqersoftware** [comment]
This is fixed now. The issue was that for targeting modes that affect cards owned by multiple players, we were replacing the set of found cards when looking at the next player, instead of merging the sets of found cards for each player together.
