### ISSUE TITLE
Instructions for external connections

### ISSUE THREAD

**Issue by drifty914** [fuzziqersoftware/newserv#11]
Thanks for this great piece of software. I'm able to get things to work with a GC PSO1+2 on my local network but having issues forwarding external connections to the server. Would it be possible to provide in the main README some basic needs for external connections? For example the ports that need to be open, does port forwarding for a login connection need to happen on a particular port? Also, does an external user need to set their DNS to what is listed as the "ExternalAddress" in the config file? Is it an issue if that's the same as the "LocalAddress" if not using PSO+?

**Comment by fuzziqersoftware** [comment]
I've (finally) gotten around to working on this project again, and I've added some instructions in the readme about this. Feel free to reopen this issue if the directions are unclear or insufficient.
