### ISSUE TITLE
[Episode 3] Explosion ability does not proc

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#111]
This has only been tested on 018B "Gi Gue Bazooka".

When an item with the ability "Explosion" is killed, it is meant to hit all enemy cards in a circle around it for damage, but this is not occurring online. This also applies to 027D "MA60 Vise", but haven't tested this card online.

Note that 01EC "Mericarol" has a different Explosion from offline testing - this Explosion will *also* affect ally cards.

As usual, let me know if you need any play testing information!

**Comment by fuzziqersoftware** [comment]
This also appears to be fixed by #109.
