### ISSUE TITLE
[Episode 3] Error processing client command: array index out of bounds

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#113]
Making an issue so info doesn't get lost lol

Sometimes during an action phase, a player will disconnect and the above error will appear in the server logs. Fuzziqer has advised that ideally, it would be best to know how the action phase went and what cards were in play, so here's some screenshots.

It appears to happen a lot with Devil Whim from both Pollux and Castor.

![image](https://github.com/fuzziqersoftware/newserv/assets/33199242/a6b73112-1869-4b78-b50c-730a4a87fa92)

(Player 2, Creinu, disconnected in this one)

![image](https://github.com/fuzziqersoftware/newserv/assets/33199242/afb0e21d-bdb4-40a5-a518-a33045cefd72)

![image](https://github.com/fuzziqersoftware/newserv/assets/33199242/70318c11-b076-473e-8d7c-2008af853127)

**Comment by fuzziqersoftware** [comment]
I think this is actually fixed now. At least, I haven't been able to reproduce it since fa48b587, and I haven't heard of it happening again since then. Please reopen this if you do see it again.
