### ISSUE TITLE
[Blue Burst] Blue Burst names display as incorrectly in the lobby to non-BB clients

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#114]
Was messing around out of boredom, and the USA Episode 3 client sees Blue Burst player names as "---", and a language flag and name in chat bubbles.

I suspect this would happen on all the console clients, so not sure what to categorise this under.

Not sure if this matters, but the BB client is TethVer12513.

![Screenshot_20230910_114658](https://github.com/fuzziqersoftware/newserv/assets/33199242/b55fcf49-4cc1-4d50-8e55-1039815af0bf)
![Screenshot_20230910_114511](https://github.com/fuzziqersoftware/newserv/assets/33199242/33fb7b10-5fe0-4b20-a7a0-1a992fbf2bc5)

**Comment by fuzziqersoftware** [comment]
This is fixed now. Looks like it had been broken by the recent change to handle long names on GC.
