### ISSUE TITLE
[Episode 3] The server appears to be handwaving HP restore calculations for Drain

### ISSUE THREAD

**Issue by SparkeeLecaro** [fuzziqersoftware/newserv#116]
I ran some tests on both the Drain ability (via cards like Sange&Yasha and Delsaber) and the Drain action card. I encountered the same problem with both sources across multiple different instances: FCs using Drain were restored to full health after the attack, rather than restoring HP equal to 1/3rd of the damage dealt. As an example (and the most egregious demonstration of the problem), a Nano Dragon at 3/18 HP using the Drain card hit a Durandal for 4 damage and healed 15 HP.

**Comment by fuzziqersoftware** [comment]
This is fixed now. Classic uninitialized memory bug - we didn't clear the sum to zero before adding up the total attack damage, so it was often some very large value, which then gets clamped to the card's max HP.
