### ISSUE TITLE
[Episode 3] Madness damages Hunter SCs through items

### ISSUE THREAD

**Issue by SparkeeLecaro** [fuzziqersoftware/newserv#117]
The "Madness" action card has a small mistake on the server, in that it's currently able to damage Hunter characters through any equipment they might have. The "Ripple" effect damages all (ally and opponent) cards within a 3x3 grid around the user, and the "Rampage" effect inflicts damage to all equipped items on a Hunter SC, both of which are working correctly. However, the server seems to be identifying the Hunter SC itself, behind their equipment, as a valid target, which shouldn't be the case.

**Comment by fuzziqersoftware** [comment]
This is fixed now. We were looking at the wrong card definition to determine if the affected card was a Hunters SC, so we always added it to the target list even if items were equipped.
