### ISSUE TITLE
Quest Questions

### ISSUE THREAD

**Issue by b0n3zx** [fuzziqersoftware/newserv#12]
First off, I have this running on a VM with a bridge and works flawlessly.  I keep finding PSO 1&2 quests in gci format and would like to add them to the server.  Mainly the Item Creator quest.  will the server show the quest or would I have to download it from the server?  How does that work with .gci files??

**Comment by b0n3zx** [comment]
[https://github.com/b0n3zx/PSOquest](github/b0n3zx/PSOquest)

These files were downloaded from gbatemp, but I have other files I have found also, but the item creator one was the one I was looking at most.

Unless there is someway to use the $item command on gc version? I couldnt get the last set of code to finish due to the text box limitation.  I know other version I could do this with but I have 3 kids that play it with me on wii's on our now home pso server.

**Comment by fuzziqersoftware** [comment]
To anyone finding this ticket - newserv now supports decoding GCI quests, including those that are encrypted, using the `decode-gci` command-line option.
