### ISSUE TITLE
[Blue Burst] One Person Mode fails to proceed

### ISSUE THREAD

**Issue by Sazonde99** [fuzziqersoftware/newserv#120]
![image](https://github.com/fuzziqersoftware/newserv/assets/123838641/654d73f8-0164-4ed0-8402-4a536edd62f0)

This is done on a default TethVer12513 client. Server using same files.

Logs:
[EP1.txt](https://github.com/fuzziqersoftware/newserv/files/12580117/EP1.txt)
[EP2.txt](https://github.com/fuzziqersoftware/newserv/files/12580118/EP2.txt)
[EP4.txt](https://github.com/fuzziqersoftware/newserv/files/12580119/EP4.txt)

**Comment by fuzziqersoftware** [comment]
This appears to have been fixed at some point - I can create solo mode games in all episodes. Please reopen this issue if it still doesn't work.
