### ISSUE TITLE
[Episode I&II] 'Your level is too low for this difficulty' segmentation fault

### ISSUE THREAD

**Issue by ShiftaDeband** [fuzziqersoftware/newserv#123]
Good afternoon! As always, thank you for all you do - it's great seeing this project.

I was messing around on PSO Episode I&II on the GameCube on a newly created character. I tried to create a team without a password with the 'ultimate' difficulty. When I do this, I expect that the server will tell me I am too low for this difficulty, but when I create the team, newserv tries to return a command, but throws a segmentation fault.

```
I 2614 2023-09-12 16:22:50 - [Commands] Received from C-3 (Basek) (version=GC command=C1 flag=03)
0000 | C1 03 30 00 00 00 00 00 00 00 00 00 09 45 41 00 |   0          EA
0010 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |
0020 | 00 00 00 00 00 00 00 00 00 00 00 00 03 00 00 01 |
I 2614 2023-09-12 16:22:50 - [Commands] Sending to C-3 (Basek) (version=GC command=01 flag=00)
0000 | 01 00 38 00 00 00 00 00 00 00 00 00 59 6F 75 72 |   8         Your
0010 | 20 6C 65 76 65 6C 20 69 73 20 74 6F 6F 0A 6C 6F |  level is too lo
0020 | 77 20 66 6F 72 20 74 68 69 73 0A 64 69 66 66 69 | w for this diffi
0030 | 63 75 6C 74 79 00 00 00                         | culty
Segmentation fault
```

Let me know if I can do anything else to assist.

**Comment by fuzziqersoftware** [comment]
Thanks for the report - it looks like I broke this when I added Episode 3 EXP overrides recently. create_game_generic can return null in exactly this situation, and we didn't check for null before trying to set the EXP override values. This is fixed now.
