### ISSUE TITLE
Server compiling and running without error, but need help getting dolphin to use it

### ISSUE THREAD

**Issue by fstltna** [fuzziqersoftware/newserv#13]
I have PSO 1&2 in dolphin, and my private server is up and waiting for connections, but how do I connect from my desktop computer to the server in a datacenter?

**Comment by fuzziqersoftware** [comment]
When this issue was opened, it wasn't easy to set this up, but now Dolphin has an HLE BBA implementation, and the instructions in the readme have been updated to describe how to use it with newserv.
