### ISSUE TITLE
[Dreamcast/PC] Crossplay

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#133]
I suspect this is non-trivial and most likely out of scope - what's the possibility of the Dreamcast/PC versions of PSO having crossplay? This is simply curiosity, zero pressure from me.

**Comment by fuzziqersoftware** [comment]
I've never tried this, but I suspect there would only be minor bugs. I'll add this to the to-do list and probably get to it sometime soon.

**Comment by mileskanda** [comment]
I tried this today. PC and DC (flycast emulator).
Players can exist together only in lobby. But if you create a team on DC for example, PC player wouldn't see this team so can't connect.

**Comment by fuzziqersoftware** [comment]
I've changed the 6x70 command so it should work now - I got a DCv2 and PC character into the same game and they could see each other walking around. I've also rewritten the quest index system so quests are now indexed by number; the server should now send the appropriate version of the quest to each client. There are probably many more cross-play bugs yet to be found, though...

**Comment by mileskanda** [comment]
I tried yesterday connect from PC and DC (flycast) - players can play in one team together, tha works! Thank you!

**Comment by fuzziqersoftware** [comment]
There are likely some more issues to find (e.g. are there items that exist on DC but not in PC, or vice versa?). If you come across any, please feel free to open new issues here.
