### ISSUE TITLE
[General] qst write file command has incorrect size

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#139]
Attempted to decode and also load a quest file I have with newserv, and got the above error in both cases.

This file loads fine in Tethealla, and also inside Qedit.

[This is the file in question](https://github.com/fuzziqersoftware/newserv/files/12840317/q126-1p-bb.qst.zip), it is the Good Luck event quest for BB in Japanese.

EDIT: Looking at TODO.md, I'm going to assume this is related to the 6xDE BB subcommand, so this is probably something you know about already.

**Comment by fuzziqersoftware** [comment]
This is because whatever tool generated this QST file put a larger size in the write file commands within the QST, which newserv didn't expect. This is fixed now.
