### ISSUE TITLE
Adding quests ?

### ISSUE THREAD

**Issue by sirdankz** [fuzziqersoftware/newserv#14]
So I've successfully installed fuzziqer in Ubuntu. Only thing is that I have some .bin and .Dat quest I want to add. On windows there is a index.ini file but in Ubuntu there is not. Help please

**Comment by fuzziqersoftware** [comment]
There's no quest index file (.ini) on the current version of newserv. Instead, put the .bin and .dat files in the quests folder and rename them appropriately. newserv will get the quest name and description from the quest's .bin file. The filenames should be like this:

`<TYPE><NUMBER>-<VERSION>.bin` (for battle, challenge, or Episode 3 quests)
OR
`q<NUMBER>-<CATEGORY>-<VERSION>.bin` (for all other quests)

<TYPE> can be b (battle), c (challenge), e (Episode 3)
<NUMBER> can be any unused 3-digit number
<CATEGORY> is only needed for type q quests; category can be ret (retrieval), ext (extermination), evt (event), shp (shop), vr (VR), twr (tower), dl (download), or 1p (solo)
<VERSION> can be d1 (DCv1), dc, pc, gc, gc3 (Episode 3), or bb

For example, GC quest 59 (Lost ICE SPINNER, in the retrieval category) is named q059-ret-gc.bin.

**Comment by sirdankz** [comment]
Will having q059-ret-gc.bin and a different quest as q059-vr-gc.bin have any conflicts?

**Comment by fuzziqersoftware** [comment]
For reference (anyone finding this issue in the future), you can make yourself an admin when you add your license in the server's shell. You'll want to use the `privileges=root` option.
