### ISSUE TITLE
[General] Quest version is in a different category/episode

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#142]
In the event that a quest number is indexed across more than 1 version in different categories, the server spits out the following error when indexing the quests:
```
I 568782 2023-10-16 01:39:34 - [StaticGameData] (q027-1p-bb.bin) Created BB_V4 quest 27 "Seat of the Heart" (Episode 2, Solo (11), not joinable)
W 568782 2023-10-16 01:39:34 - [StaticGameData] Failed to index quest file q027-dl-gc.bin (quest version is in a different category)
```
In this case, Seat of the Heart is a solo-only quest in BB, whereas online in GC it will need to go somewhere else (currently in default newserv it's just a Download), which will always conflict. Admittedly Seat of the Heart on GC has a much higher number (222 I think?), but I was following previous convention where the same quest is given BB's number across all of them in newserv.

This issue also occurs between Episode 3 download quests and other quests too, so since I added Caelum 1 for download, this conflicts with the first Episode 4 government quest on BB:
```
W 568782 2023-10-16 01:39:35 - [StaticGameData] Failed to index quest file q701-gv4-bb.bin (quest version is in a different category)
```

This is more an issue with the quest files possibly, but a lot of BB quests never defined their episodes properly, and relied on the BB map designation to sort that out. This causes strange errors when adding quests which are in other versions, such as:
```
I 568782 2023-10-16 01:39:34 - [StaticGameData] (q231-vr-bb.bin) Created BB_V4 quest 231 "Respective Tomorrow" (Episode 1, Virtual Reality (5), not joinable)                                                                               
W 568782 2023-10-16 01:39:34 - [StaticGameData] Failed to index quest file q231-vr-gc.bin (quest version is in a different episode)    
```
This might not be something to fix though, and the quest files just dealing with. I want to say I have official files from the official servers but I cannot say 100%, though I can't imagine why people would edit the Episode flag.

**Comment by fuzziqersoftware** [comment]
There are multiple issues here, which are all similar but slightly different.

First, different categories - I suspect this isn't worth fixing, and we should just reassign the quest numbers. However, a possible fix could be to treat the download menu as the solo menu in BB, which might make sense based on how the game works. If this doesn't make the code unnecessarily complicated, I might do it.

Second, Ep3 quests conflicting with non-Ep3 quests - this is annoying. Ideally Episode 3 download quests wouldn't use the same quest system as non-Ep3, and would go in a separate location. I'll split the quest index into two to fix this, so Episode 3 download quests will go somewhere in system/ep3 instead.

Third, different metadata across game versions - I've gone back and forth in my mind about whether to fix this or not. On the one hand, it'd be nice for the existing quest files to just work without modification, but on the other hand, it'd also be nice if the quest files had correct metadata (e.g. episode settings) in their headers. Does anything break if you change the episode number in the quest headers to make them consistent across PSO versions?

**Comment by Matt-Swift** [comment]
I actually had a conversation with Ender regarding this, and he did some debugging, and the 0x14 offset in the BB header (which is `episode` in newserv) is not read by the client in any way - which would potentially track with the BB quest files not defining this byte in the header. The client simply loads everything in memory after reading function 0; Tethealla gets around this server-side by having the quest episode be known through the quest directory location (e.g. quest/ep1, quest/ep2).

I can change the episode header for missing quests, but should I? Seems like that would be inaccurate and simply for newserv.

**Comment by fuzziqersoftware** [comment]
I've actually already fixed this, but haven't pushed it because it's blocked behind another change; I'll leave this open until it's pushed. Once it's pushed, the server will disassemble the start label from each quest's script, find the set_episode opcode, and use the argument to that instead of the header field. So, the header field should become mostly irrelevant after that.

**Comment by fuzziqersoftware** [comment]
This should be fixed now. Please reopen this if there are any quests for which the server still can't figure out the correct episode.
