### ISSUE TITLE
[Episode 3] EXP Decoy from Ransom sometimes fails to proc

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#145]
The Ransom assist card is meant to block all damage (I think?) as long as the defending team has EXP, however this doesn't seem to always be the case. I'm assuming this is bugged, unless there is criteria that can bypass it.

Off the top of my head, the only scenario I can remember is:

- Ino'lis used Gibarta on herself to attack Rufina.
- Rufina had 3 HP, and her team mate was the one that had Ransom in play.
- The attack did 3 damage, but it was not blocked despite the enemy team having plenty of EXP.

**Comment by fuzziqersoftware** [comment]
I played around with Ransom a bit online, and it seems to be working as intended in the cases I tried. Ransom applies only to the player on whom it's set, even though it uses the team's shared EXP, so at first glance it makes sense that it wouldn't apply here. I don't have a lot of confidence that Ransom always works like it's supposed to, though; if you find a reproducible case, let me know.
