### ISSUE TITLE
[Dreamcast/PC] Unable to load other player models in lobby under certain circumstances

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#146]
The circumstance appears to be if someone is in the lobby and is using an outfit that is V3+ exclusive, but it doesn't /always/ proc in this case.

Here is a log of a V2 player entering lobby with a few other players.

[lobby.txt](https://github.com/fuzziqersoftware/newserv/files/13061989/lobby.txt)

As an aside, Matt is Episode III.

**Comment by fuzziqersoftware** [comment]
This is actually the same issue as #147; will comment there.
