### ISSUE TITLE
[Dreamcast/PC] HUcaseal and FOmar still load as Ninja in lobby

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#147]
As title, RAmarl is loading correctly as HUnewearl however.

**Comment by fuzziqersoftware** [comment]
It seems the client fairly extensively validates the PlayerVisualConfig structure when loading a new player into the lobby. It checks costume, skin, face, head, and hair, validates the name color (along with a needlessly-complex checksum), and checks the section ID, character class, and class flags. The server now ensures that each player's visual config will pass these checks, adjusting it if necessary before sending it. (This also means that PC players should now see correct name colors even without the name colors patch.)
