### ISSUE TITLE
[Dreamcast] Serial generator notes

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#148]
The shell command says that domain is for V1/2, and subdomain is for region (J/U/E), however I did some quick testing generating serials for each version to see what would be accepted by the generator and got the following:

```
JPv1: Anything gets accepted for this version it seems, would suspect domain 0 though
JPv2: Domain 0, Subdomain 1
USv1: Domain 1, Subdomain 1
USv2: Domain 1, Subdomain 1 (yes, both US versions use the same serials, not a typo)
EUv1: Domain 2, Subdomain 2
EUv2: Domain 2, Subdomain 1
```
No obvious pattern here from what I can tell other than domain being for region.

**Comment by fuzziqersoftware** [comment]
Thanks for testing these - I've updated the instructions.
