### ISSUE TITLE
[Episode I & II] Error processing client command: player data is not loaded when accessing download quests

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#149]
When accessing a download quest category the above error is shown. This happens on US 1.02, but does not happen on US E3.

The below command is sent directly after choosing a quest category; the prior command is the server sending the category list.

```
I 732140 2023-10-22 11:14:13 - [Commands] Received from C-1 (version=GC command=10 flag=00)
0000 | 10 00 0C 00 66 00 00 66 03 00 00 00             |     f  f        
W 732140 2023-10-22 11:14:13 - [Server] Error processing client command: player data is not loaded
I 732140 2023-10-22 11:14:13 - [Server] Client disconnected: C-1 on fd 38
I 732140 2023-10-22 11:14:13 - [C-1] Deleted
```

**Comment by fuzziqersoftware** [comment]
This is fixed now. Download quests now require the client's language setting, and we were getting the client language from the player data, which isn't loaded until just before the lobby except on Episode 3. Now, we get the language from the login command instead.
