### ISSUE TITLE
Dolphin GC Local Connection

### ISSUE THREAD

**Issue by ryu777mtg** [fuzziqersoftware/newserv#151]
Dolphin version is from beta release 5.0-19870 x64
newserv version is from the release page (2023-10-21) macOS / Windows [release-windows-amd64.zip](https://github.com/fuzziqersoftware/newserv/releases/download/v2023-10-21/release-windows-amd64.zip)

Issue running the newserv on same machine with Dolphin emulator will not connect to server.

Unless I'm doing something wrong I have tried using a multitude of setting changings according to the config.json including some of the following methods:

- Setting LocalAddress to 127.0.0.1 and of the same IP of local machine found via ipconfig /all command using cmd.exe
- Running the newserv.exe regularly and with admin perms
- Tried messing with the IPStackListen settings but using the  ["/tmp/dolphin-tap"] as directed by the config and then running the newserv.exe will crash after run.
- I have not tried running the newserv.exe in a Cygwin terminal yet 
- Tried using the 127.0.0.1 and same IP of local machine for the Broadband Adapter HLE setting for Dolphin
- I have also tried adding 127.0.0.1 and same IP of local machine for the IPStackListen

`"/tmp/dolphin-tap" Is the setting that when added to the IPStackListen crashes the newserv.exe`

For the IPStackListen if you are able to put multiple options in between the [] would it be denoted as say the following:

`["/tmp/dolphin-tap", "127.0.0.1", "XXX.XXX.XXX.XXX"]`

Or do you not separate with commas and just use space or a tab etc. Their was no indication on how to put that in the already blank []
Just want to make sure the settings are getting input correctly as I only tested with on option at a time.

One more thing to note I did try using OpenVPN https://swupdate.openvpn.org/community/releases/openvpn-install-2.4.11-I602-Win10.exe when using the Dolphin Broadband Adapter TAP I changed the MAC to the MAC of the generated OpenVPN tap device found using ipconfig /all in cmd.exe. Not sure if I was supposed to but when monitoring I could see when the device came active but it would never connect to DNS

The closest I got was the screen saying connecting to DNS server then it just fails out. Not sure if this is because the server and emulator running on same machine. I tried reading all the documentation at front page but I feel like it may need to be updated with the current release of Dolphin if possible.

If anyone has had success running Dolphin and the Windows server on same machine and connecting to the server please help me in determine my mistakes to make this work

Thanks for any help

PS On a side note I can confirm that the newserv works fine on a Raspberry Pi 4 using 2023-05-03-raspios-bullseye-arm64-lite.img however that's a separate machine on the network from where the Dolphin emulator is running.

**Comment by ryu777mtg** [comment]
So if I'm understanding correctly

Install OpenVPN for TAP
Set the BBA TAP MAC inside Dolphin to the MAC of the newly generated OpenVPN TAP
Go to network adapters and set a static IP for the TAP adapter.
For simplicity sake say the router scheme is 192.168.0.XXX which in  most cases is one of the standard defaults and if that is the default set the static ip to say something like the following:
192.168.0.123 ip
255.255.255.0 subnet
192.168.0.1 assuming this is the gateway
Say your local machine has the following:
192.168.0.100 ip
255.255.255.0 subnet
192.168.0.1 gateway

This should give a local adapter of 192.168.0.100 and a tap adapter of 192.168.0.123 then bridge the connections.
Once I do this I loose the local ip of 192.168.0.100 as the bride then generates a new local ip.

If this is proper way from what I'm understanding,
Should I use the ip of 192.168.0.100 for the newserv LocalAddress or should I use the new bridge ip?

Then within the game go to the network config and set the following:
Manual IP set to the Tap of 192.168.0.123
Subnet of 255.255.255.0
Gateway of 192.168.0.1
DNS 1 and DNS 2 set to the 192.168.0.100 or the bridge ip depending on what's set in the newserv config.json

I've still yet to get a successful connection using both devices on same machine maybe this is long since stopped working...

Thanks again for the response.

**Comment by ryu777mtg** [comment]
> I can give it a try again, I would need to set up a Windows VM for a proper test environment however.

Please do when you have the time it would be much appreciated also if you don't mind noting which versions of software used for Dolphin, OpenVPN or whatever you use for TAP adapter, and if you use the precompile release of newserv for windows or if you compile from source. 

I also feel like some things may have changed for setup which may be why it's not working for me but I've tried quite a bit of combinations.

**Comment by ryu777mtg** [comment]
> I got connected with a stock install of a Windows 10 22H2 ISO in a VM
This could be my issue I'm using Windows 11 Pro 64 bit

Thanks for the info as I can see some of what settings I put in wrong either way it doesn't seem to work on Windows 11 for me when bridging the networks as instructed I get an error.

![image](https://github.com/fuzziqersoftware/newserv/assets/22566763/5a3016c2-e9aa-401c-aa1c-f5cf7f04fba4)

**Comment by ryu777mtg** [comment]
No I'm connected via ethernet and I have also reset all network settings and rebooted and still get this message.
![image](https://github.com/fuzziqersoftware/newserv/assets/22566763/60c9e62a-e96d-4519-ba8b-dacae2016d2d)
This is the TAP adapter from OpenVPN I'm trying to use as well:
![image](https://github.com/fuzziqersoftware/newserv/assets/22566763/a5723536-f896-4ad0-871c-88bd9266eae8)
![image](https://github.com/fuzziqersoftware/newserv/assets/22566763/43fbfa69-eb9d-4861-b6c7-fdb5252dbb7c)
As you can see I only have the TAP Windows to be installed fully. Version of Open VPN is in the images as well.
![image](https://github.com/fuzziqersoftware/newserv/assets/22566763/9a379a63-721d-4f10-9ec6-e3eef9d60127)
The only two I select is the OpenVPN TAP-Windows6 which gets a configured IP and subnet the other I select is the Ethernet then right click and bridge connections then error.

**Comment by ryu777mtg** [comment]
> For what it's worth, I also install OpenVPN fully rather than a custom install.
Does that mean you just do the default install method? I think with this version it will install like 3 adapters doing so. I was just trying to avoid having the clutter if possible.

> Had a quick look around, and this solution may help you create a network bridge.

Lol I've already looked into that but for some reason even using admin account when you get to the ren repository repository.old it says invalid permission in the cmd terminal so I'm unable to go further with that.

Exact version of Windows
Microsoft Windows 11 Pro Version 10.0.22621 Build 22621

**Comment by Matt-Swift** [comment]
Following up on this:

I'm not sure why I didn't try this before, but you can use an AR code to dodge the DNS entirely and connect directly to your local server on the same system without any extra tools.

You can find a link to AR codes for all the GC versions here: https://ragol.org/localnewserv

These codes specifically connect you to 127.0.0.1 and are for the purpose of connecting to a server on your own PC.

I haven't tested to see if any versions of PSO will fail if connecting on the same network (i.e. different PC on same network), but this should let you do local server goodness.

**Comment by fuzziqersoftware** [comment]
I assume this has been resolved or abandoned at this point, but if not, feel free to reopen it.
