### ISSUE TITLE
[Blue Burst] Running the server with default settings ends up with Server Full errors

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#156]
I've managed to successfully compile and run the server on windows via cygwin, however, upon starting the server and following the basic instructions to set for BB in the main README I'm totally stuck in a 916 Server is Full error window while trying to login.

The client i'm using is the Tethealla one, I havent modified anything other than copying the GSL and maps into the patch server data folder.

The server boots up correctly with the default settings, and I can see activity coming from the client in the server console but I just cannot pass this error screen.

Is there something else that needs to be done in the client or in the server config files that isn't documented anywhere? 
![Capture](https://github.com/fuzziqersoftware/newserv/assets/5244595/f04c6ccf-30ed-4eb7-8dc3-979d458e2450)

**Comment by Matt-Swift** [comment]
Do you have TCP port 12004 open? TethVer12513 attempts to connect on this port after the patch server, although in config.json for newserv it is listed under the proxy list, so it's understandable if you don't.

**Comment by nolrinale** [comment]
Firewall is disabled, and running a simple netstat I can tell ports 12004, 12005 are LISTENING so they are open for sure.

The client is set to connnect by default to 127.0.0.1 checked the exe via hex editor just to make sure.

Kinda out of ideas at this point what could it be.

**Comment by fuzziqersoftware** [comment]
The last command in the screenshot is redirecting the client to connect to 255.255.255.255, which probably means LocalAddress isn't set correctly in config.json. You probably want to set LocalAddress to either 127.0.0.1 or you PC's local IP address.

**Comment by nolrinale** [comment]
Setting LocalAddress to 127.0.0.1 did the trick now the client can connect properly, thank you guys, till next ticket.
