### ISSUE TITLE
Quest won't download, Game breaking server glitches

### ISSUE THREAD

**Issue by sirdankz** [fuzziqersoftware/newserv#16]
This could maybe all be caused by non of the quest being able to be downloaded even in solo. Always ends in a softlock

1.players can only connect to each other by the host of the lobby using the "$maxlevel" command otherwise the game sends a message saying "player level to high to join"

2.when the above^ happens. The host can hold b+x+start to reset the game but the guest will still see the host stuck at the quest counter.

3.when above^ happens and the guest leaves the game. Reconnecting the host to the main lobby the host can still see his old lobby up showing 2/4 players without anyone actually being there

4.players can now see each other at quest counter but once selecting a quest to download, the host softlocks and the guest never gets the downloading screen change

This could maybe be a result of me building the servers wrong?

I first built (psosg) then I copied over the folders and files from inside of (masternewserv.zip) over to the (psosg) folder.

I then ran "cmake . && make" inside of the (psosg) folder containing the files built from

**Comment by fuzziqersoftware** [comment]
I fixed the max level check just now. The other issues sound like bugs that were fixed a couple of weeks ago - 94c5802c fixes disconnect handling and ca1b5372 fixes quest loading. Do these issues still occur after download and building a clean copy from master?

**Comment by sirdankz** [comment]
Nice!
I just reinstalled everything using the newest build for phosg and newserv. I still get the issues with the quests. Even trying to play solo I cannot load any quest. I always end up soft locking once I click on a quest that I want to download.

**Comment by fuzziqersoftware** [comment]
There was a bug causing the quest to be sent as a download quest instead of a normal quest when loaded from a game. This is fixed now, and I can load quests normally again when testing locally, even with multiple players.

I'm using Dolphin and the IP stack interface to test (not a real GameCube or tap adapter), and there's an odd behavior I've noticed where quest loading appears to hang partway through, but eventually completes after taking 20 seconds or so. Let me know if this happens for you too; I have an idea that might fix it.

**Comment by sirdankz** [comment]
Everything seems to work perfectly now, even when I play 1 player from a real wii and player 2 on dolphin emulator on some custom quest I added . I think it only hangs to load a quest when the file is a large file. Its happened to me before using another server. Thank you very much for fixing this so fast. Much appreciated.

**Comment by fuzziqersoftware** [comment]
Re: drop rates and EXP - on BB, drop rates can be changed in the drop table JSON file (system/blueburst/rare-table.json), but the EXP multiplier can't be changed. There is a way to do this, but newserv doesn't implement it (yet) - I've added it to the to-do list.
