### ISSUE TITLE
[Dreamcast] QST file fails to load

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#164]
I know how much you love this quest format, and thus I post an issue about it to make your day.

A DC qst file will spit out the following error:
```
(q070-dl-dc-j.qst) Failed to index quest file: (qst contains write commnd for non-open file) 
```
Sample files:
[Archive.zip](https://github.com/fuzziqersoftware/newserv/files/13244471/Archive.zip)

**Comment by fuzziqersoftware** [comment]
Thanks for the report; this is fixed now. There isn't a perfect way to detect DC vs. V3 QST files, but I've implemented a heuristic that should work in all reasonable cases.
