### ISSUE TITLE
[Blue Burst] All characters share the same Symbol Chats

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#165]
Symbol Chats should be independent for each character/s, upon creating a character in the first slot modify or delete one of the sample symbol chat parts, then, create another character in the last slot and upon checking it's symbol chats you will notice you will have the same ones from the first character.

**Comment by fuzziqersoftware** [comment]
The save file format has been changed, and this is now fixed. New-style save files (.psochar files) will not share symbol chats with each other.
