### ISSUE TITLE
[Blue Burst] Destroying a box while playing an Episode 4 quest ends up disconnecting the Player

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#176]
While playing Episode 4 and loading a quest such as War Of Limits in the Underground Desert, if any of the players in the party attempt to break a box they will receive an Error 100 message and get disconnected from the game. 

[Episode42PlayerQuestBoxKillDCed.txt](https://github.com/fuzziqersoftware/newserv/files/13283713/Episode42PlayerQuestBoxKillDCed.txt)

**Comment by fuzziqersoftware** [comment]
This should be fixed by 7d0438f.

**Comment by nolrinale** [comment]
Can confirm is fixed since https://github.com/fuzziqersoftware/newserv/commit/7d0438f149705348573148642b96a0db3f7e0be2 closing this ticket
