### ISSUE TITLE
[Blue Burst] Attempting to play Cmode Stage 1 ends up disconnecting both players

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#178]
Creating a new Challenge Mode room and loading Stage 1 in Episode 1, both players ends up getting disonnected with an Error No.100

[Cmode2PlayerStage1BB.txt](https://github.com/fuzziqersoftware/newserv/files/13283853/Cmode2PlayerStage1BB.txt)

**Comment by fuzziqersoftware** [comment]
This should be fixed by cabd03a8. The DF commands sent at the beginning of a Challenge stage should now work; the DF commands sent at the end are not yet tested. (The logic is fairly simple, so I'd be surprised if they didn't work.)
