### ISSUE TITLE
[Blue Burst] Coren is missing from Pioneer 2

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#180]
In PSOBB theres an NPC which is actually the original party leader's Tekker placed right outside the Shopping Districts called Coren, this NPC offers the players the possibility to gamble their mesetas to get unique rare items depending on the day of the week by asking for 1000 meseta, 10000 meseta or 100000 meseta for the highest chance of rewards.

This NPC appears only in online mode Episode 1, 2 and 4 without loading any quest. 

![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/4f7be6e0-4fc2-49ac-8919-5c82ec491621)

DEMO VIDEO
https://www.nicovideo.jp/watch/sm2220860

**Comment by ShiftaDeband** [comment]
Oh, that's interesting - I thought Coren was a custom add-on for one of the private servers, not something that was implemented in PSOBB (likely JP only?). Do you have a wayback source for that screenshot? I'm assuming PSOBB JP Online Manual?

**Comment by nolrinale** [comment]
I was a JPBB player myself for the whole duration of the game till it's closure in 2010 so all the data I offer for this project is from first hand experience. 

The original source from where I got this snapshot is from the official site entry
https://web.archive.org/web/20060616063435/http://psobb.jp/questinfo/200605/0530.html

**Comment by ShiftaDeband** [comment]
Not challenging you here, apologies if it came off that way - I appreciate the insight and history, I just didn't realize it was a real NPC on the JP servers. 

That's great info, thank you for sharing.

**Comment by Matt-Swift** [comment]
Coren being "missing" means that the map files provided with the clients and newserv do not have Coren defined in them.

Question is: Does anyone have the map files that include Coren? Otherwise, he would have to be manually edited in which is dirty.

As for Coren functionality, it appears that the command has been documented, although it appears that newserv does not respond to F960 currently, which means that the gambles are not implemented.

**Comment by nolrinale** [comment]
I've loaded my original map files from the latest JPBB client and hes still missing here, if you also have these files give it a try and set them in the patch server see if he loads for you, but i've been unable to load him I already told fuzzi about this a while ago too.

**Comment by Matt-Swift** [comment]
I don't have it myself, but Coren should be defined in the `map_city00_00e.dat` and `map_city02_00_00e.dat` files (with the `map_city_XX_j.bin` files defining Coren in the map script). The latest release of the Tethealla client does not have these, and I am pretty sure Ephinea we had to manually edit Coren in and base the recreation off old videos as the map files containing him didn't seem to be around anywhere. It is possible they were never on the patch server and simply loaded in memory from the server on room creation, although I don't know quite enough to know if that was possible.

**Comment by nolrinale** [comment]
Do you have a tool to open those .dat files so I can verify in a readable format somehow? I will triple check what i have here and open yet another PR to include the missing files

**Comment by Matt-Swift** [comment]
Qedit can do it, just import floor data and set it to enemies only.

**Comment by nolrinale** [comment]
I was unable to load him not even with the files from my backup, in fact heres the data folder from the latest client backup with the modified dates 
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/bfef80ec-889e-43e4-b673-fc72eff7565f)
I sorted everything by modified date so you can clearly see the client files that sega had updated till almost the very end (September 2010) the last time they updated city maps to touch anything there was back in 2008 

The map files we have I think already contain him because he was implemented back in May 2006 (you can verify in the link I posted above) so by that logic everything we have that is beyond that date must have him already included somewhere.

I've noticed there are also several .bin map files for the labo and the city maybe they in their insanity decided to implement the NPC differently in those files?? or they injected him into the client via some weird command that we dont know it exist yet bypassing all the map files??

**Comment by Matt-Swift** [comment]
Can you upload  the following files because I'm curious:

`map_city00_00e.dat`
`map_city02_00_00e.dat`
`map_city_on_j.bin`
`map_city_off_e.bin`

Not at home at the moment so there's probably some .bin files for Episode II/IV as well, though not sure what their names are.

**Comment by nolrinale** [comment]
Sending you all files that begin with map_ just in case:
[JPBB MAP FILES.zip](https://github.com/fuzziqersoftware/newserv/files/13312108/JPBB.MAP.FILES.zip)

I highly doubt hes in the data.gsl its latest modified date is Dec 29 2004 and as far I know sega just placed all the episode 4 meshes, textures, map files just outside of it themselves.

But if you need it too let me know and I will attch it over here too

**Comment by Matt-Swift** [comment]
Coren's script data is defined in the map_city .bin files at function 880, so this client definitely has him, but he isn't part of the map files.

Not sure why - as I mentioned prior, we just had to recreate him in the map file on Ephinea, I would be very surprised if SEGA did something like send a new .dat file for the map when making a game, but maybe...?

**Comment by nolrinale** [comment]
From what you are telling me and comparing what I have here the culprit of all this problem seems very likely to be some sort of unknown function the client has to create NPC's on the fly without requiring any local supporting files. 

It would make sense because Coren's logic is also generated live by the server every time you roll a dice and to generate the rewards for you, likewise both Black Paper Deal's quests also request the server functions to generate the rewards via another method which is not the usual drop tables. 

As far I know these two elements are the only real "Server Side" stuff PSOBB had at the time, that is, flow controlled entirely by the server

The Mystery Deepens....

**Comment by nolrinale** [comment]
Coren variables are inside:
map_city_on_j.bin (EP1 Pioneer 2)
map_labo_on_j.bin (EP2 Pioneer 2)
map_city02_on_j.bin (EP4 Pioneer2)

With a hex editor search for the string `<meseta_slot_prize>` in these files

**Comment by fuzziqersoftware** [comment]
newserv can disassemble and compile quest scripts; here is the disassembled map file: [map_city_on_j.txt](https://github.com/fuzziqersoftware/newserv/files/13721636/map_city_on_j.txt) (search for bb_send_6xE2 to find where the prize is requested)

Probably the only thing that needs to be done here is to implement the 6xE2 subcommand; the client expects a 6xE3 in response, which isn't hard, but I don't know what items to choose from to generate it. Can you provide more details on how Coren is supposed to work? Specifically, is [the Ephinea prize list](https://ephinea.pioneer2.net/corens-prize-list/) the same as the vanilla prize list? And what are the approximate probabilities of getting each item?

**Comment by Matt-Swift** [comment]
The Ephinea prize list is based off vanilla, but it's modified. There's a known list here (in Japanese): https://wikiwiki.jp/psobb/%E6%B5%81%E6%B5%AA%E5%95%86%E4%BA%BA%E3%82%B3%E3%83%AC%E3%83%B3%E5%90%9B

I don't know any other sources of Coren's items.

As for rates, it goes without saying that this is also not known. Ephinea follows a system like this:

- 4% to get chosen tier
- If fail, 8% to get tier-1
- If fail, 12% to get tier-2

If all 3 fail, grant random consumable from the item shop (no scape or grinders, however).

**Comment by nolrinale** [comment]
The wikiwiki prize list is correct and complete, it separates the items by day of week, type and category.

As for functionality it's slightly off it should be like this

- Select from any 1000, 10000, 100000 meseta
- The chance to get a rare item is always 100%, however the tier rarity is random, for example if you pay 100000 meseta you have more chance to get an item from the 100k tier rather than the 10k tier or 1k tier. (we can decide here an approximate % for example "60% - 30% - 10%" for each tier)
- If the prize is a weapon the weapon is given untekked as SPECIAL WEAPON and without any bonus % (hit, element,etc.)

This should cover all the Coren functionality

**Comment by nolrinale** [comment]
Tested the files and indeed hes appearing now!! of course it says `sub command 6xE2` is missing followed by a "Server Send Error" message but at the very least the game continues normal operation afterwards
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/3231defc-4666-4d14-9129-6df1dad7ccaf)

But in EP2 hes not saying anything at all ... and I just double checked and his functions are also present in the map_labo so i dont know what could be wrong here 

![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/39cecbb4-3c03-47e0-a67f-e2fb39bb9c3b)

**Comment by nolrinale** [comment]
I've noticed the NPC is located slightly off...are these modded files? heres a pic of him in episode 2 in the official server

![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/f655d86a-83dc-48df-9963-534fd541e443)

Compared to the pic above hes in a different place in my screenshot 

Maybe is possible to find another approach to make this NPC appear? could it be rather than 'force' it via modded files make him appear gracefully from the game itself??

**Comment by nolrinale** [comment]
This feature have been implemented in commits https://github.com/fuzziqersoftware/newserv/commit/82aaf4cd34a15fae40683b49200a362ccf675e3a, https://github.com/fuzziqersoftware/newserv/commit/40c0953ebc3a9528d83220c375e5e8564eb188c4, https://github.com/fuzziqersoftware/newserv/commit/b17dd5b19616c19c52b4338225c776bafe6aa27b and PR https://github.com/fuzziqersoftware/newserv/commit/0a4527340d83e9064553d828db09fb1c63bc687d

The config.json sample file includes all the Items taken from the Ephinea's list and ability to adjust the success %'s.
It might be necessary to update in another PR the Item Prize List with the correct retail ones later on.
