### ISSUE TITLE
[Blue Burst] Missing 6xDC commands while fighting Saint Million

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#181]
During a fight with Saint Million Episode 4 ultimate, every time he summons any kind of minion either his missiles, the little spinning guys or the tornadoes a weird `Sub 6xDC missing` is thrown in the console. 

Attaching screenshots and logs
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/b379f4ff-8450-48ef-9b99-b1f688aa23e7)

[SaintMillionMissingData.txt](https://github.com/fuzziqersoftware/newserv/files/13301155/SaintMillionMissingData.txt)

**Comment by fuzziqersoftware** [comment]
This should be fixed by 38c0d97.
