### ISSUE TITLE
[Blue Burst] Episode 4 Government quest Reward Boxes only drops Sabers

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#183]
At the end of several PSOBB Gov quests the game spawns boxes as a reward, in this case while playing Episode 4 quest 9-7 in Hard the reward boxes after clearing the quest only dropped Sabers.

Attached Log 
[EP4GovQuestRewardBoxOnlySaber.txt](https://github.com/fuzziqersoftware/newserv/files/13302644/EP4GovQuestRewardBoxOnlySaber.txt)

**Comment by fuzziqersoftware** [comment]
I believe this was caused by a bug with specialized box contents, which was fixed today in 768bdb5b.
