### ISSUE TITLE
[Blue Burst] Unwrapping Armors/Weapons from Gallon's Shop ends up in Error 100

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#184]
Creating an Episode 2 room and loading Gallon's Shop quest, we proceed to buy 3 kinds of items, a tech disk, an armor, a weapon from the shopping district.

Then we head to the Gallon's shop and pay him 10000 meseta to wrap these items as presents White/Pink. We begin to open the presents, we open the Present with the Tech Disk and we get the Disk back, we open the present with either the Armor or the Weapon and we get an Error 100.

Attached log 

[EP2GallonsUnwrappingArmorWeapCrash.txt](https://github.com/fuzziqersoftware/newserv/files/13302803/EP2GallonsUnwrappingArmorWeapCrash.txt)

**Comment by fuzziqersoftware** [comment]
This has been fixed by 97661070.
