### ISSUE TITLE
[Blue Burst] Missing 6x1B commands while fighting Enemy Characters in EP4 Restless Lion Quest

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#185]
Loading the solo mode EP4 quest Restless Lion which pits you against other enemy hunters with their own weapons and attacks, upon engaging with them in the underground desert the console will begin to spit out the message `Sub 6x1B missing`  however upon defeating the enemy character and the normal monsters around you are still able to pickup their weapons from the dead bodies without issues and the weapons have their stats set correctly.

Log
[EP4RestlessLionMissingCommandPVPCharEngage.txt](https://github.com/fuzziqersoftware/newserv/files/13302931/EP4RestlessLionMissingCommandPVPCharEngage.txt)

**Comment by fuzziqersoftware** [comment]
This is fixed by 3ea65ccc.
