### ISSUE TITLE
[Blue Burst] Missing Command 6xE0 while receiving EP4 Black Paper & Black Paper #2 rewards

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#186]
Upon creating a Solo Episode 4 room we load either Dangerous Deal with Black Paper quest OR An Even more Dangerous Deal with Black Paper 

This quest requires the player to carry a Photon Crystal in the inventory to start, so we generate one with $item PHOTON CRYSTAL

Upon completing the quest and killing the last enemy a red box should appear with your reward, instead in this case the server will spit out the error `Sub 6xE0 missing`  and no reward box is dropped. 

P.D: Also Depositing/Withdrawing crystals from the Players Bank ends up in the Bank destroying the crystals so I assume the bank is broken too its also included in this log file. 

Attached Log
[EP4BlackPaperDealNoCrystalBankError.txt](https://github.com/fuzziqersoftware/newserv/files/13312328/EP4BlackPaperDealNoCrystalBankError.txt)

[EP4MissingCommandBPD2.txt](https://github.com/fuzziqersoftware/newserv/files/13312552/EP4MissingCommandBPD2.txt)

**Comment by fuzziqersoftware** [comment]
This should be fixed now. Note that you have to add QuestF95ERewardItems in config.json to define what the items should be; there's an example of this in config.example.json.
