### ISSUE TITLE
[Blue Burst] Error No. 100 or `Missing Enemy Killed` messages while killing monsters in Cmode Episode 1

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#187]
Upon starting a cmode room with 2 players, we access the first stage, we kill the first monster that appeared which was a Booma and then we got both error no. 100.

We tried a 2nd time, this time we skipped the booma and went straight for the rappy int he first room, upon killing the Rappy we got an error message saying `missing enemy killed` but the game continued as usual.

We then defeated the Booma and we got disconnected again.

Cannot proceed with cmode

Attached Log
[2PlayerCmodeMonsterKillDCed.txt](https://github.com/fuzziqersoftware/newserv/files/13312648/2PlayerCmodeMonsterKillDCed.txt)

Session 2 Log
[2PlayerCmodeDcedMissingEnemyRappy.txt](https://github.com/fuzziqersoftware/newserv/files/13312738/2PlayerCmodeDcedMissingEnemyRappy.txt)

**Comment by fuzziqersoftware** [comment]
This one was difficult, since there was a lot of logic on the client that the server has to duplicate precisely. It should be working now, but I've only tested with Episode 1 stage 1 so far. I'm fairly confident in my implementation, but please reopen this if it doesn't work for you.
