### ISSUE TITLE
[General] Non-English quests are not fallen back to

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#188]
This is mostly relating to Japanese quests - I have a few Japanese-only quests up (as there's no translations currently), and they are not visible by anyone unless they are playing in Japanese.

I suspect the way the way you'd want it to work is that it tries to find quest for language, then searches the rest in order if not found?

**Comment by nolrinale** [comment]
If its in psobb what im doing is renaming the JP quests with E rather than J to make them appear in game.

**Comment by fuzziqersoftware** [comment]
This should be fixed now - you should see all quests available for your PSO version, even if there isn't a version in your language. The language priority list is: your language, then English, then Japanese, then German, then French, then Spanish (this is the same order as the internal values of the languages, except English is moved up).
