### ISSUE TITLE
9c821b2 Compile Error

### ISSUE THREAD

**Issue by MADrewry** [fuzziqersoftware/newserv#191]
When running make to compile the latest version (9c821b2) it exits with the following error:

[  1%] Building CXX object CMakeFiles/newserv.dir/src/ReceiveCommands.cc.o
/home/michael/newserv/src/ReceiveCommands.cc: In function ‘void on_DF_BB(std::shared_ptr<Client>, uint16_t, uint32_t, std::string&)’:
/home/michael/newserv/src/ReceiveCommands.cc:3304:46: error: comparison of integer expressions of different signedness: ‘const ssize_t’ {aka ‘const int’} and ‘unsigned int’ [-Werror=sign-compare]
 3304 |       if (l->quest->challenge_template_index != cmd.template_index) {
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/newserv.dir/build.make:832: CMakeFiles/newserv.dir/src/ReceiveCommands.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/newserv.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by fuzziqersoftware** [comment]
Thanks; this is fixed now. Strange that it didn't fail locally for me, or in GitHub Actions.

**Comment by MADrewry** [comment]
I'm running on 32bit Raspberry Pi OS, maybe there some difference in the compiler?
