### ISSUE TITLE
[Blue Burst] Quests fail to download, also Quest categories show as 3 character abbreviations in menu

### ISSUE THREAD

**Issue by MADrewry** [fuzziqersoftware/newserv#192]
Since the latest build I cannot download any quests, and the menus show only 3 character abbreviations and not full titles. Game log and screenshot attached.

[gamelog.zip](https://github.com/fuzziqersoftware/newserv/files/13330875/gamelog.zip)
![IMG_2003](https://github.com/fuzziqersoftware/newserv/assets/40810747/e2f9dd7d-fd95-44e4-b066-b76c328026d2)

**Comment by fuzziqersoftware** [comment]
This is because the format of QuestCategories in config.json has changed. You can fix this by updating QuestCategories in your config.json to look like the one in the example config.

**Comment by MADrewry** [comment]
Thanks, should have thought of that myself with all of the changes that have been made. Working after modifying my config.json
