### ISSUE TITLE
[Blue Burst] Quests aren't organized by Episode 

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#195]
Continuing the previous ticket, with the new rework done to the quest system I understand the main goal was to be able to succesfully load the quests with their correct episode parameter.

However after testing today I created a new Episode 4 room in Normal and went straight to the Hunter's Guild counter and I still can access the quests from episode 1 and 2 from an Episode 4 room.

Likewise for Gov quests Momoka displays all the categories of all episodes by default

The correct behavior should be to display only the quests related to that room's episode setting.
Am I doing something wrong?

**Comment by Matt-Swift** [comment]
You're not, this is just how newserv does quests - the entire list is loaded in every episode. Whether it will change is up to fuzziqer, I know for example that SCHT lets you load all quests from any episode too (although not on BB).

**Comment by nolrinale** [comment]
This behavior will be needed in the future for when the BB gov quest progression system gets implemented, likewise for the episode 1 solo mode quests progression system.

We had the system working like this on latest schtserv, it wasnt trivial tho I will make a technical document with all the use cases to make it work properly here in a future PR.

But for the time being lets close this one too.
