### ISSUE TITLE
[Blue Burst] Several incorrect drops from all Boxes in Gov Quest 4-1

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#197]
Starting a new VH game Episode 1 Gov Quest 4-1 which walks you through Mines 2 and Ruins 1 the Drops from boxes are all over the place with boxes dropping red boxes (weapons), Sabers and even Presents!

In the final area of Ruins 1 after going through the sparkly warp before entering the final room with several enemy waves you will also find many boxes which should drop only recovery items (to prepare you for the final enemy room) in this case they dropped a variety of items from armors to meseta to recovery/tool items.

![pso1700041029](https://github.com/fuzziqersoftware/newserv/assets/5244595/aec63b95-8ac6-4bda-b041-956b75e19297)

The full 4-1 quest recording
[VH4-1QuestIncorrectBoxDrops.txt](https://github.com/fuzziqersoftware/newserv/files/13363172/VH4-1QuestIncorrectBoxDrops.txt)

**Comment by fuzziqersoftware** [comment]
I wasn't able to reproduce this behavior, but I did find a bug that is likely to be the cause, which is fixed by 1b29f205. Please try this again when you get a chance and let me know if it's working for you.

**Comment by nolrinale** [comment]
Fixed in the latest commit https://github.com/fuzziqersoftware/newserv/commit/35aa6fba011c0ff47d26f6f4db512d2bb1c6ca81
