### ISSUE TITLE
[Blue Burst] Disconnected while dropping/picking up items in Cmode

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#199]
We started a new Cmode session Episode 1 Stage 1, we decided to drop some items to switch between characters, monofluids and scape dolls, by accident, the player 2 picked up the items i had dropped then got disconnected. 

Log
[CMODE2PlayerItemDced.txt](https://github.com/fuzziqersoftware/newserv/files/13365018/CMODE2PlayerItemDced.txt)

**Comment by fuzziqersoftware** [comment]
Did you or the other player do anything in the game before starting the challenge quest? Specifically, did either of you open any shop or tekk any item? If so, this is likely the same bug as #161; if not, I'll investigate further.

**Comment by nolrinale** [comment]
We did absolutely nothing but starting the server, creating the room and selecting the quest, we played for a little bit and once I (P1) picked up a Power Material I dropped it and told P2 to pick it up then P2 client got disconected, then I got a weird textbox (see pic) and shortly after the game continued but only with me. 

Log 2nd session
[CMODE2PlayerItemDcedP2Round2.txt](https://github.com/fuzziqersoftware/newserv/files/13394240/CMODE2PlayerItemDcedP2Round2.txt)

**Comment by nolrinale** [comment]
3rd Round

We started yet another session and P2 attempted to drop their Scape Doll, P2 got disconnected in front of my eyes and I got the weird Cmode explanation msg box again.

It seems to be it only happens to all the clients minus the Host (P1)

**Comment by fuzziqersoftware** [comment]
This has been fixed by 7ab98f41.
