### ISSUE TITLE
Is red ring available ?

### ISSUE THREAD

**Issue by sirdankz** [fuzziqersoftware/newserv#20]
Is the item red ring available? 
If it is not can you please make it available ?

**Comment by fuzziqersoftware** [comment]
To my knowledge, the red ring is not available by default on PSO GC. Item drops are actually controlled by the client, but it's possible for the server to override them (some other servers do this). I haven't implemented this functionality in newserv yet; I'll leave this open as a reminder.

**Comment by sirdankz** [comment]
Reminder...

**Comment by fuzziqersoftware** [comment]
Red ring is still not available. The server now generates a drop check command when the boss is defeated, but it seems this isn't sufficient for the item to actually appear. I suspect we'd have to implement full drop chart overrides to support this.

**Comment by sirdankz** [comment]
Okay I see that in the commands after defeating a boss.  
Having red ring drop on after defeating 
Dark Falz in any quest or without a quest would be amazing. 
Alot of OG pso players miss this feature.
Having a full drop chart would be amazing in addition. Thanks again.

**Comment by sirdankz** [comment]
I found a PSO GC Item Code List. Would that help out implementing a full drop chart?

**Comment by sirdankz** [comment]
I put a $20 bounty for this issue on bountysource.com .  I know $20 isn't much at all for the work you've been doing but I'll be trying to add more funds into the bounty as I get more money to spare or if anyone else in my pso server donates. Here's the link https://app.bountysource.com/issues/116539122-is-red-ring-available

**Comment by fuzziqersoftware** [comment]
I've added server drops on non-BB versions to the to-do list, but it's unlikely this will be implemented anytime soon. If anyone else finds this and wants to work on it, PRs are welcome.
