### ISSUE TITLE
[Blue Burst] Units equipped beyond the 1st slot will always get unequipped after a relogin

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#200]
If you happen to have an armor with 2 or more slots if you try to equip more than 2 units and then after, log out from the game ,in the next login you will only have the first unit equipped and all the others unequipped so you have to equip them again every time you log out. 

Before
![pso1700053758](https://github.com/fuzziqersoftware/newserv/assets/5244595/d6060b11-4df0-46ef-822b-fb9b01599c34)

After
![pso1700053805](https://github.com/fuzziqersoftware/newserv/assets/5244595/6017c2fa-9748-4547-ba1b-7728737d58a0)

Log 
[UnitUnequipBugRelogin.txt](https://github.com/fuzziqersoftware/newserv/files/13365126/UnitUnequipBugRelogin.txt)

**Comment by fuzziqersoftware** [comment]
This has been fixed by be6fd251 and f9973768.
