### ISSUE TITLE
[Blue Burst] Selecting "Try Again" in CMODE only ports the Player 1 back to the game

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#206]
Created a new Challenge Mode session Stage 1, this time we decided to drop our Scape Dolls and deliberately die to trigger the Tomb to get more recovery items, however, after dying and returning to the city Player 1 pressed "Try Again" so we could retry the challenge and this time he got ported back to the forest, leaving me behind in the city stuck with the message boxes

In this log there's also 2 missing sub commands which I believe might be the cause of this problem Missing Command `6x9D` and `6x97`

Session Log
[2PlayerCMODETryAgainStuck2P.txt](https://github.com/fuzziqersoftware/newserv/files/13404306/2PlayerCMODETryAgainStuck2P.txt)

**Comment by fuzziqersoftware** [comment]
This has been fixed by 34666ee2.
