### ISSUE TITLE
[Blue Burst] Attacking an enemy with a weapon with King or Master Skill ends up in Error 100

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#208]
Equipping a King's Striker and attempting to hit an enemy with it using the 3rd EX attack ends up disconnecting you instantly with Error 100

Same error happens with a weapon with Master skill

Log 
[EXAttackKingStriker.txt](https://github.com/fuzziqersoftware/newserv/files/13404856/EXAttackKingStriker.txt)

[EXAttackMasterRod.txt](https://github.com/fuzziqersoftware/newserv/files/13404896/EXAttackMasterRod.txt)

**Comment by fuzziqersoftware** [comment]
This is fixed by f8280e5f.
