### ISSUE TITLE
PSO BB login than server crush

### ISSUE THREAD

**Issue by Sancaros** [fuzziqersoftware/newserv#21]
newserv> I 2247623 2022-05-12 05:05:30 - [Server] Client fd 31 connected via fd 10 (bb-patch (Patch, patch_server) on port 11000)
I 2247623 2022-05-12 05:05:30 - Sending (version=Patch command=0002 flag=00000000)
0000000000000000 | 4C 00 02 00 50 61 74 63 68 20 53 65 72 76 65 72 | L   Patch Server
0000000000000010 | 2E 20 43 6F 70 79 72 69 67 68 74 20 53 6F 6E 69 | . Copyright Soni
0000000000000020 | 63 54 65 61 6D 2C 20 4C 54 44 2E 20 32 30 30 31 | cTeam, LTD. 2001
0000000000000030 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0000000000000040 | 00 00 00 00 F6 9B 35 35 50 8E 24 FA             |       55P $     
I 2247623 2022-05-12 05:05:30 - Received (version=Patch command=0002 flag=00000000)
0000000000000000 | 04 00 02 00                                     |                 
I 2247623 2022-05-12 05:05:30 - Sending (version=Patch command=0004 flag=00000000)
0000000000000000 | 04 00 04 00                                     |                 
I 2247623 2022-05-12 05:05:30 - Received (version=Patch command=0004 flag=00000000)
0000000000000000 | 70 00 04 00 00 00 00 00 00 00 00 00 00 00 00 00 | p               
0000000000000010 | 73 61 ** ** ** ** ** 73 00 00 00 00 00 00 00 00 | sa****s        
0000000000000020 | 37 ** ** ** ** ** ** 31 00 00 00 00 00 00 00 00 | 7******1        
0000000000000030 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0000000000000040 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0000000000000050 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0000000000000060 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
I 2247623 2022-05-12 05:05:30 - Sending (version=Patch command=0013 flag=00000000)
0000000000000000 | 90 01 13 00 09 00 43 00 37 00 6E 00 65 00 77 00 |       C 7 n e w 
0000000000000010 | 73 00 65 00 72 00 76 00 20 00 70 00 61 00 74 00 | s e r v   p a t 
0000000000000020 | 63 00 68 00 20 00 73 00 65 00 72 00 76 00 65 00 | c h   s e r v e 
0000000000000030 | 72 00 0A 00 0A 00 54 00 68 00 69 00 73 00 20 00 | r     T h i s   
0000000000000040 | 73 00 65 00 72 00 76 00 65 00 72 00 20 00 69 00 | s e r v e r   i 
0000000000000050 | 73 00 20 00 6E 00 6F 00 74 00 20 00 61 00 66 00 | s   n o t   a f 
0000000000000060 | 66 00 69 00 6C 00 69 00 61 00 74 00 65 00 64 00 | f i l i a t e d 
0000000000000070 | 20 00 77 00 69 00 74 00 68 00 2C 00 20 00 73 00 |   w i t h ,   s 
0000000000000080 | 70 00 6F 00 6E 00 73 00 6F 00 72 00 65 00 64 00 | p o n s o r e d 
0000000000000090 | 20 00 62 00 79 00 2C 00 20 00 6F 00 72 00 20 00 |   b y ,   o r   
00000000000000A0 | 69 00 6E 00 20 00 61 00 6E 00 79 00 0A 00 6F 00 | i n   a n y   o 
00000000000000B0 | 74 00 68 00 65 00 72 00 20 00 77 00 61 00 79 00 | t h e r   w a y 
00000000000000C0 | 20 00 63 00 6F 00 6E 00 6E 00 65 00 63 00 74 00 |   c o n n e c t 
00000000000000D0 | 65 00 64 00 20 00 74 00 6F 00 20 00 53 00 45 00 | e d   t o   S E 
00000000000000E0 | 47 00 41 00 20 00 6F 00 72 00 20 00 53 00 6F 00 | G A   o r   S o 
00000000000000F0 | 6E 00 69 00 63 00 20 00 54 00 65 00 61 00 6D 00 | n i c   T e a m 
0000000000000100 | 2C 00 20 00 61 00 6E 00 64 00 20 00 69 00 73 00 | ,   a n d   i s 
0000000000000110 | 20 00 6F 00 77 00 6E 00 65 00 64 00 0A 00 61 00 |   o w n e d   a 
0000000000000120 | 6E 00 64 00 20 00 6F 00 70 00 65 00 72 00 61 00 | n d   o p e r a 
0000000000000130 | 74 00 65 00 64 00 20 00 63 00 6F 00 6D 00 70 00 | t e d   c o m p 
0000000000000140 | 6C 00 65 00 74 00 65 00 6C 00 79 00 20 00 69 00 | l e t e l y   i 
0000000000000150 | 6E 00 64 00 65 00 70 00 65 00 6E 00 64 00 65 00 | n d e p e n d e 
0000000000000160 | 6E 00 74 00 6C 00 79 00 2E 00 0A 00 0A 00 4C 00 | n t l y .     L 
0000000000000170 | 69 00 63 00 65 00 6E 00 73 00 65 00 20 00 63 00 | i c e n s e   c 
0000000000000180 | 68 00 65 00 63 00 6B 00 20 00 4F 00 4B 00 00 00 | h e c k   O K   
I 2247623 2022-05-12 05:05:30 - Sending (version=Patch command=0009 flag=00000000)
0000000000000000 | 44 00 09 00 2E 00 00 00 00 00 00 00 00 00 00 00 | D   .           
0000000000000010 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0000000000000020 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0000000000000030 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0000000000000040 | 00 00 00 00                                     |                 
I 2247623 2022-05-12 05:05:30 - Sending (version=Patch command=0009 flag=00000000)
0000000000000000 | 44 00 09 00 64 61 74 61 00 00 00 00 00 00 00 00 | D   data        
0000000000000010 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0000000000000020 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0000000000000030 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0000000000000040 | 00 00 00 00                                     |                 
I 2247623 2022-05-12 05:05:30 - Sending (version=Patch command=0009 flag=00000000)
0000000000000000 | 44 00 09 00 73 63 65 6E 65 00 00 00 00 00 00 00 | D   scene       
0000000000000010 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0000000000000020 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0000000000000030 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0000000000000040 | 00 00 00 00                                     |                 
I 2247623 2022-05-12 05:05:30 - Sending (version=Patch command=000A flag=00000000)
0000000000000000 | 04 00 0A 00                                     |                 
I 2247623 2022-05-12 05:05:30 - Sending (version=Patch command=000A flag=00000000)
0000000000000000 | 04 00 0A 00                                     |                 
I 2247623 2022-05-12 05:05:30 - Sending (version=Patch command=000A flag=00000000)
0000000000000000 | 04 00 0A 00                                     |                 
I 2247623 2022-05-12 05:05:30 - Sending (version=Patch command=0012 flag=00000000)
0000000000000000 | 04 00 12 00                                     |                 
I 2247623 2022-05-12 05:05:30 - [Server] Client on fd 31 disconnected
I 2247623 2022-05-12 05:05:31 - [Server] Client fd 31 connected via fd 8 (bb-init (BB, data_server_bb) on port 12000)
I 2247623 2022-05-12 05:05:31 - Sending (version=BB command=0003 flag=00000000)
0000000000000000 | 88 01 03 00 00 00 00 00 50 68 61 6E 74 61 73 79 |         Phantasy
0000000000000010 | 20 53 74 61 72 20 4F 6E 6C 69 6E 65 20 42 6C 75 |  Star Online Blu
0000000000000020 | 65 20 42 75 72 73 74 20 47 61 6D 65 20 53 65 72 | e Burst Game Ser
0000000000000030 | 76 65 72 2E 20 43 6F 70 79 72 69 67 68 74 20 31 | ver. Copyright 1
0000000000000040 | 39 39 39 2D 32 30 30 34 20 53 4F 4E 49 43 54 45 | 999-2004 SONICTE
0000000000000050 | 41 4D 2E 00 00 00 00 00 00 00 00 00 00 00 00 00 | AM.             
0000000000000060 | 00 00 00 00 00 00 00 00 EF 7B 13 72 12 D5 A6 A2 |          { r    
0000000000000070 | EE BC D4 AC 99 31 35 E2 26 0E DB BF 81 F5 1A 1D |      15 &       
0000000000000080 | 2D A5 C8 FB 16 DC 69 AE BD E8 EF B6 24 B4 33 99 | -     i     $ 3 
0000000000000090 | 61 84 DE 5A FA 6D 35 FF 70 62 0F C2 DB FC 35 E8 | a  Z m5 pb    5 
00000000000000A0 | A4 0F 8B 77 56 74 B3 C1 C3 F1 65 FD AA 4F 3F ED |    wVt    e  O? 
00000000000000B0 | 7A 0E 49 F3 8D AC 5E 54 FD 93 1C 97 05 0B 08 AC | z I   ^T        
00000000000000C0 | 66 00 45 CF 05 02 A2 9F 54 68 69 73 20 73 65 72 | f E     This ser
00000000000000D0 | 76 65 72 20 69 73 20 69 6E 20 6E 6F 20 77 61 79 | ver is in no way
00000000000000E0 | 20 61 66 66 69 6C 69 61 74 65 64 2C 20 73 70 6F |  affiliated, spo
00000000000000F0 | 6E 73 6F 72 65 64 2C 20 6F 72 20 73 75 70 70 6F | nsored, or suppo
0000000000000100 | 72 74 65 64 20 62 79 20 53 45 47 41 20 45 6E 74 | rted by SEGA Ent
0000000000000110 | 65 72 70 72 69 73 65 73 20 6F 72 20 53 4F 4E 49 | erprises or SONI
0000000000000120 | 43 54 45 41 4D 2E 20 54 68 65 20 70 72 65 63 65 | CTEAM. The prece
0000000000000130 | 64 69 6E 67 20 6D 65 73 73 61 67 65 20 65 78 69 | ding message exi
0000000000000140 | 73 74 73 20 6F 6E 6C 79 20 69 6E 20 6F 72 64 65 | sts only in orde
0000000000000150 | 72 20 74 6F 20 72 65 6D 61 69 6E 20 63 6F 6D 70 | r to remain comp
0000000000000160 | 61 74 69 62 6C 65 20 77 69 74 68 20 70 72 6F 67 | atible with prog
0000000000000170 | 72 61 6D 73 20 74 68 61 74 20 65 78 70 65 63 74 | rams that expect
0000000000000180 | 20 69 74 2E 00 00 00 00                         |  it.            
double free or corruption (!prev)
Aborted

when PSO BB login than server crush

**Comment by fuzziqersoftware** [comment]
It works for me, so there must be something different about your setup that's triggering a bug in newserv. Unfortunately, these kinds of bugs can be hard to investigate... can you tell me more about your setup? Specifically:
- What version of PSOBB are you using? Is it the original client, Schthack, Ephinea, or something else...?
- What OS are you running newserv on?
- What version of newserv are you running? (The result of `git log -1` will suffice to answer this)
- Does it crash every time? If so, does it always crash at the same place?
- Can you get a stacktrace from the crash? (Run `gdb newserv` or `lldb newserv`, then type `r` at the debugger prompt to start it - you'll end up at a debugger prompt again when it crashes, and you can then type `bt` to get a stacktrace)

**Comment by Sancaros** [comment]
ubuntu server LTS20.04
TethVer12513 version exe

**Comment by fuzziqersoftware** [comment]
This should be fixed now. If you pull master and rebuild newserv, it should no longer crash when a BB client connects.

Overall, though, BB support is still very incomplete. I'm working on it, but probably a lot of things (even basic things) won't work yet.
