### ISSUE TITLE
[PC] Challenge does not seem to be initialising new inventory state with item tracking

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#210]
Had a disconnection after using a monomate in Challenge, with the error "item not present".

Grabbed the logs, it appears that the server believes the players have their normal inventory, which obviously is not quite right!

Log of game below.

[Challenge.txt](https://github.com/fuzziqersoftware/newserv/files/13416243/Challenge.txt)

**Comment by fuzziqersoftware** [comment]
This was fixed recently by cd4c0623. Please reopen this ticket if it still happens.

**Comment by Matt-Swift** [comment]
This error still exists I'm afraid, just tried to play a Challenge game and then exploded on using a monomate.
