### ISSUE TITLE
[Blue Burst] CCA Main Gate malfunction is always unlocked

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#213]
So this one is a very tricky one 

Let's create an EP2 Normal room, walk towards the lab and go straight into Central Control Area, upon arriving you will notice the main gate has it's 3 main locks already deactivated, so you can just walk straight into the dam area.
![Screenshot from 2023-11-20 23-16-40](https://github.com/fuzziqersoftware/newserv/assets/5244595/14cfe057-74b5-4b7a-b178-d8503ac3e61f)

However, I create another room, this time in Very Hard which I know has gov quest 6-5 already completed, this quest enables Elly to appear in Pioneer 2 Lab area, you go straight to CCA like in the previous room and you will notice the gate this time has 1 lock remaining to be deactivated.
![Screenshot from 2023-11-20 23-18-06](https://github.com/fuzziqersoftware/newserv/assets/5244595/c604ce05-98b7-4f1d-89ee-a9707435ea31)

The correct behavior is that the door must always have it's 3 locks activated upon arrival regardless of difficulty or game mode.

Log including both sessions
[EP2CCABrokenDoorEllyFlag.txt](https://github.com/fuzziqersoftware/newserv/files/13419940/EP2CCABrokenDoorEllyFlag.txt)

**Comment by fuzziqersoftware** [comment]
On my character, the three locks are correctly activated on both Normal and Very Hard (I didn't check other levels). During the recent .psochar file format update, the quest flags field was corrected to be in the right location; if your character was created before that, then you might have incorrect quest flags left over from the old format. If you make a new character, do you still see this incorrect behavior?

**Comment by nolrinale** [comment]
Created a new character in a new account just to make sure and quickly went to check the door, it has it's 3 locks but I was going to attempt to clear quest 6-5 to test further noticed the character had no items whatsoever its already reported over here https://github.com/fuzziqersoftware/newserv/issues/215

Will check this one again later

**Comment by nolrinale** [comment]
Creating a new character and account with the new character format from latest commits fixed the issue, the door is always closed like should be regardless of quest, difficulty or story progress
