### ISSUE TITLE
[Blue Burst] Breaking boxes in CMODE as P2 ends up disconnecting P1

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#214]
Create a new challenge mode session Episode 1 Stage 1, we left Player 1 (host) idling at the beginning of the stage and began to kill the monsters of the first room with Player 2, there are 3 boxes and a switch in this room we broke the boxes and upon picking up an item P1 got disconnected with Error 100 and P2 was shown the usual weird Challenge Explanation Msg Box, after a while the game continues with only P2 online. 

Log 

[CMODE2PBoxDropIncorrectTool.txt](https://github.com/fuzziqersoftware/newserv/files/13429710/CMODE2PBoxDropIncorrectTool.txt)

**Comment by fuzziqersoftware** [comment]
This is fixed by 267c2ca0. It turns out it's not specific to Challenge mode, but is more likely to occur there.
