### ISSUE TITLE
[Blue Burst] New characters are being generated without Items nor default Palette

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#215]
Created a brand new account, created a character, the character does not have anything in it's inventory neither has any default action set in the palette.

![pso1700651231](https://github.com/fuzziqersoftware/newserv/assets/5244595/b6261a47-2c9e-4ab2-989d-d39fdf4e0a35)
![pso1700651244](https://github.com/fuzziqersoftware/newserv/assets/5244595/8c2ff2cc-5a0c-488e-81fd-827112f99b86)

Log
[NewCharacterNoItems.txt](https://github.com/fuzziqersoftware/newserv/files/13438545/NewCharacterNoItems.txt)

**Comment by fuzziqersoftware** [comment]
This has been fixed by 9097abf3.

**Comment by nolrinale** [comment]
It is still happening I don't know why, just in case i created a new account and started the server from scratch again. Heres a complete log of the whole flow creating 4 different characters of all the 3 main classes just to make sure.
[NewAccount4EmptyChars.txt](https://github.com/fuzziqersoftware/newserv/files/13465295/NewAccount4EmptyChars.txt)
