### ISSUE TITLE
[Blue Burst] Lobby 14/15 soccer markers persist while switching Lobbies

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#216]
Visit either Lobby 14 or 15 (the soccer ones) then assign yourself a marker of any color in this case I assign "Green", walk to the teleporter and port back to any other lobby, the marker stays enabled regardless which lobby you visit. 

![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/2b1b3d6f-5d83-405c-879f-adb2cd181cc8)

![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/52c3367a-d60d-4c3f-a1a7-9bec2b236324)

**Comment by fuzziqersoftware** [comment]
This was originally intentional, but I've changed my mind. The behavior is fixed by 10e5dc47.
