### ISSUE TITLE
[Blue Burst] Missing sub command 6xCC while donating items for Team Points

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#217]
Pickup any rare weapon in a normal room in any episode while you belong to a Team, donate the item for Team Points from the F12 Team Menu, you will get a message about the missing sub command `6xCC` 

Log 
[TeamDonateItemsMisscommand.txt](https://github.com/fuzziqersoftware/newserv/files/13441020/TeamDonateItemsMisscommand.txt)

**Comment by fuzziqersoftware** [comment]
This has been implemented by 6af05274.
