### ISSUE TITLE
[Blue Burst] Difficulty levels are slightly off

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#218]
For PSOBB the levels to access the new difficulties were changed a little bit to accommodate for the difficulty increase of the monsters strength and areas in Episode 4

So should be like this:

Episode 1
Normal - Lv1
Hard - Lv20
Very Hard - Lv50
Ultimate - Lv90

Episode 2
Normal - Lv1
Hard - Lv30
Very Hard - Lv60
Ultimate - Lv100

Episode 4
Normal - Lv1
Hard - Lv40
Very Hard - Lv70
Ultimate - Lv110

**Comment by fuzziqersoftware** [comment]
Required levels can now be defined in config.json, as of 501a048a.
