### ISSUE TITLE
[Blue Burst] Player names of 10 characters are truncated to --- upon next logon

### ISSUE THREAD

**Issue by MADrewry** [fuzziqersoftware/newserv#219]
Characters created on an older account, prior to the newest builds no longer show names in any location, even if I create a new character. Characters created on a new account (created after the latest build) show names correctly. Also as noted by nolrinale in issue #215 new characters created on either an old or new account have no items. (FYI I am running on the 1.24.3 client) (screenshot of name issue attached)

![NoName](https://github.com/fuzziqersoftware/newserv/assets/40810747/a8a9c51e-444a-43ca-9545-cd5a090a61ec)

**Comment by nolrinale** [comment]
The save data structure was changed in the latest commits so you must wipe all these old accounts and begin from scratch

**Comment by MADrewry** [comment]
Pretty much as I suspected but was looking for confirmation. Names show up fine after following above instructions. Closing this issue.

**Comment by MADrewry** [comment]
I am going to reopen this as I am still having the invisible name issue after all. If I delete all data from the licenses and players folders as described above, then create a new account and character, the name displays correctly. However if I exit the game then return to the same account and character the name no longer displays. I did not log this but will do so if needed.

**Comment by nolrinale** [comment]
Please use the TetheallaClient12513 this is the one we are using to do all our testing

**Comment by MADrewry** [comment]
The problem persists in the TetheallaClient12513. Same procedure as before. Deleted old account and player data. created new account and new player using character name from a previous account. Name showed up on first login, but after logging out and back the name was missing. Problem does not appear to occur with character names I have not previously used. Game log attached.

[gamelog.zip](https://github.com/fuzziqersoftware/newserv/files/13456648/gamelog.zip)

**Comment by nolrinale** [comment]
I was able to replicate the issue, this happens when you create a character name with a full length of 10 characters regardless if it ends in a letter, number or ASCII symbol the name will be truncated as `---` upon next login.

If you create a character with a name length of 9 characters or less this issue wont happen.

Please update the title of this issue to reflect this behavior.

**Comment by MADrewry** [comment]
Thanks for the explanation, I didn't even consider name length as the issue, all my old characters had 10 character name lengths so it didn't enter my mind. Poor testing method on my part. Topic updated.

**Comment by fuzziqersoftware** [comment]
This has been fixed by b5dbf252.
