### ISSUE TITLE
PSO GC - Player 1 is added as player 2

### ISSUE THREAD

**Issue by clint-david** [fuzziqersoftware/newserv#22]
Latest version #(f1d10b7ff8660436c064ccc01b25b2b067ecf3e4) adds player 1 in the player 2 spot. Does not cause any functional issues (only minimal testing completed).

Player has blue tag and appears in player 2 spot during/after cut scenes/warps (i.e. player is off center). Need to test with second player and proxy still.

**Comment by fuzziqersoftware** [comment]
This was actually intentional - I did this to make it more obvious which bytes represent the client ID in various commands, since it wouldn't be zero if the player wasn't in the first slot in the game/lobby. I changed it back today and made the behavior optional.

**Comment by clint-david** [comment]
Ahhh, understood. That is a useful feature; when I was first trying to understand the command structure I used logs and the second player data a lot to see the bounds of each player in the bytes. Thank you for explaining!
