### ISSUE TITLE
[Episode 3] 00F3 Punishment card skips defence phase

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#220]
When the Punishment card is used online, the defence phase is skipped and the targets are unable to defend. I tested this offline and I was able to defend as you'd expect.

I compared this card with 0215 Virus, and the only real difference (other than damage / cost target) is that the name parameter is 72 for Punishment, and B5 for Virus, which I highly doubt is related to the issue.

**Comment by fuzziqersoftware** [comment]
I couldn't reproduce this - I tried both Virus and Punishment, and each time I got a Defense phase. Can you give more details about the situation? (Which cards were in play at the time Defense was skipped?)
