### ISSUE TITLE
[Blue Burst] Error 100 after killing a monster during gov quest 1-1

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#225]
During quest 1-1 from the Government ones there's a chance you can get disconnected after killing monsters for a while, in this case I got disconnected after killing a booma in the forest.

Log
[1-1QuestKillCertainEnemyDced.txt](https://github.com/fuzziqersoftware/newserv/files/13465632/1-1QuestKillCertainEnemyDced.txt)

**Comment by fuzziqersoftware** [comment]
This bug was introduced very recently, and has been fixed by 220259b0.
