### ISSUE TITLE
[Dreamcast NTE] Other player character data doesn't load properly

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#226]
If two players join a game in Dreamcast NTE, they will join but you cannot see any of the other players, although data is sent between the players (chat messages, movement, etc).

Log attached of a game make and player joining.

[ntejoin.txt](https://github.com/fuzziqersoftware/newserv/files/13465690/ntejoin.txt)

**Comment by fuzziqersoftware** [comment]
This is likely fixed by a3d67731, but I can't test this easily myself.

**Comment by Matt-Swift** [comment]
This appears to be resolved, we did a full forest free roam, will make new tickets if any other issues crop up.
