### ISSUE TITLE
[Blue Burst] Can't invite people to join a Team

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#228]
Creating a New Team and attempting to invite a new member via de Team -> Invite Team member the list is empty

![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/c415b125-6ed0-4824-afb8-9593ade4b2f4)

**Comment by fuzziqersoftware** [comment]
This has been fixed by 9ea84d71.
