### ISSUE TITLE
[Blue Burst] Team Status messages aren't shown in Team Chat Window

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#229]
When a team is created, a member invited, a member is leaving, a member connects to the game, the system let's everyone in the Team know about these actions via the Team Chat Window 

There might be other status messages too but I cannot remember them from the top of my head please check `unitxt_j` for those

I think this one might require to fix the previous https://github.com/fuzziqersoftware/newserv/issues/227 first

**Comment by fuzziqersoftware** [comment]
This has been fixed. Note that these messages are generated by the client; the Tethealla client generates garbled messages, probably because it uses the Japanese templates with English strings.
