### ISSUE TITLE
[Blue Burst] Team Names aren't being displayed in the lobby after pressing Tab

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#230]
You can check other players Teams while in the lobby by pressing the Tab key a few times, however after I created a Team I press Tab and I cannot see the Team Name on top of my character. 

It looks like it shows first if nobody leaves the lobby but if someone attempts to connect, switch lobby/block, join a party, the Team names disappear in both clients.

In this picture, both characters are masters of their own teams but only the Team name of one is being shown (the one that didnt left the lobby)

![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/dffce5e0-d82e-4873-8a38-702a0ad8e699)

Might be necessary to refresh the team names display for everyone present in the lobby each time a change happens in the lobby

**Comment by fuzziqersoftware** [comment]
This should be fixed by 1a5e56c0 and 2c24cce7.
