### ISSUE TITLE
[Blue Burst] Government Quest Progression System not implemented

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#240]
[DRAFT]
This one might take a while but I'm leaving it documented over here while I fix Typos, Wording and Erratas later

This is the final challenge for newserv on the PSOBB side to have a complete PSOBB experience

Since PSOBB is an online only game, they had to redo the quest progression system from PSOGC, this time it requires players to unlock new areas by completing the Government quests, these quests which can be taken at The Principal counter for Episode 1 and 4 and The Lab in Episode 2 must be completed in order.

Several things needs to be controlled at a server level and at client level

At server level

-If you access any of the Gov quest counters you will be presented with a list of 3 quest categories which are the 3 main stories of PSOBB for each Episode, this is incorrect and the correct behavior shall be presenting only the category which belongs to the episode in that specific room so creating a Normal Episode 1 room should display as a category "The Hero In Red" and hide the other 2 for their respective episodes counters

-Gov Quests must be completed in order and not being presented all at once like currently happens, so a brand new player should be able to only select quest `1-1 Planet Ragol` only if it's playing in an Episode 1 room, same situation for Episodes 2 and 4
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/b83914d2-f1ca-43dd-8429-780c9f73f8e8)

-Certain gov quests can be Joined while in progress from the lobby this is a new system implemented with these quests for BB which didn't existed on PSOGC, however newserv must be able to track the joining player's current quest progress before letting them join the room, if the lobby player haven't completed any quest yet and the room player is doing quest 1-3 for example, the lobby player will be presented with an error message letting them know they haven't progressed enough to join that room (check the `unitxt_e` for the specific message)

-Let's say we have a room with 4 players, where between those players, Player 1 has completed up to quest 2-2, Player 2 until quest 4-1, Player 3 until 3-3 and Player 4 until 1-2 the server should display the quest list of the player with the **least progress being made**, in this case Player 4 so everyone can choose up to quest 1-2, if Player 4 leaves the room, the quest list updates to the next minimum player which is Player 1 and so on....

-Gov quests progress are also Difficulty independent, that means the progress gets reset back to the first quest if you create a new room in Hard, Vhard or Ultimate, think of it as each Difficulty being a new Save Slot.

At client level

Note: One of the latest updates made to the official JP servers SEGA decided to open all the areas in free exploration regardless of current gov quest progress (while still keeping track server side of their gov quest progress) but just left them open for a quicker exploration which is what we have now in the current Teth client. This is controlled by a flag set at client level (Similar to the ENG/JPN hidden switch) if you deactivate this flag the original behavior gets restored.

Note2: Most of the logic explained below is already controlled by the client which will verify the flags set by completing each of these quests so all you need to do is find that special hidden switch, disable it and let the client handle the rest of the logic.

-If a brand new player attempts to create a Normal Episode 1 room and goes straight into the main city teleporter will be presented with just the Forest 1 option to visit

![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/89f913ec-094e-401a-8a41-61042036ab66)

In order to unlock more areas in free exploration mode (and solo mode as well), the player must complete the first set of EP1 gov quests so, quests 1-1, 1-2 and 1-3, upon completing 1-3 will be granted access to the caves area like so

![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/0c7b979b-d54d-4aa6-8915-6a44e6f16d5e)

-If a 2nd player joins the room and this player has completed for example until gov quest 4-2 (so can visit up to Ruins area), this player will still be presented with the selection from Player 1 at the teleport so only Forest 1 will be available for them.

-If Player 2 creates the room instead and let's Player 1 go in, Player 1 will have access to the full teleport 
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/c17e8eb6-d96a-4f4c-9173-d49dd2636cc1)

-Episode 1 Solo mode Story quests are also affected by this, to make the next batch of quest appear in the Hunter's Guild the player must have had the next area unlocked in Free Exploration mode beforehand just like on PSOGC. 

Congratulations! newserv PSOBB support will be 100% complete!

**Comment by fuzziqersoftware** [comment]
Two new behaviors have been implemented, which I believe completes this system:
- Quests can now be made invisible based on players' quest flags. The government quests have all been configured to require the success flag from the previous government quest (except the first government quest in each episode, which have no requirements). The Solo mode quests don't have any flag requirements, because it's not obvious to me what the flag requirements should be for those quests. I've added a to-do list item to figure them out and add them.
- Players cannot join a game unless they have access to the quest being played in that game.

There is a license flag (permission) that allows players to ignore quest requirements; when this flag is on, that player will see all available quests even if they shouldn't be unlocked.

Finally, I chose not to filter the government quests by episode. I don't anticipate anyone adding a significant new amount of government categories, so I don't see much risk in allowing the player to choose quests from another episode at the government counter. The Hunter's Guild counter is still filtered by episode, however.
