### ISSUE TITLE
Dreamcast/PC: Save transfer

### ISSUE THREAD

**Issue by EvilMag** [fuzziqersoftware/newserv#242]
I noticed that newserv has an option that lets you save your character on the server and have it be transferred to BB. I'm curious if it could have something like that for DC and PC? (like transferring characters between versions)

**Comment by fuzziqersoftware** [comment]
Yeah, I intend to implement this sometime soon. I'll leave this open until it's implemented.

**Comment by fuzziqersoftware** [comment]
This has been added; the $savechar and $loadchar commands can be used on v1/v2 to save and restore basic player data (which does not include chat config or bank contents, unfortunately). $savechar can be used on any version, so technically you could even use it to convert v3 or BB players to v1/v2.
