### ISSUE TITLE
[Blue Burst] Unknown Sub command 6xCB while Sending Items to other Team Member

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#244]
It is possible to send items along a simple mail message to other members of the team, the items are delivered to the recipient's bank alongside a simple mail message.

Only Items can be sent, not Meseta

To send items to other member the sender must be in the city to do so, but the recipient can be in the lobby or in the city as the item will be deposited directly into their bank and will be notified by the simple mail message.

If the recipient's bank is full OR the recipient is checking their bank, an error message is shown stating the item could not be delivered. 

Currently on newserv the item can be sent but then it gets stuck in the "Sending..." message
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/657073b8-6064-4085-a21f-fd8aba008f9c)

```
psochar
I 7410 2023-11-29 22:12:52 - [Commands] Received from C-B (RUPIKA) (version=BB command=0060 flag=00000000)
0000 | 18 00 60 00 00 00 00 00 CB 04 00 00 02 00 01 00 |   `             
0010 | 01 00 00 00 E2 33 23 1B                         |      3#         
W 7410 2023-11-29 22:12:52 - [C-B] Unknown subcommand: CB (public)
I 7410 2023-11-29 22:13:17 - [C-C] Sending ping command
I 7410 2023-11-29 22:13:17 - [Commands] Sending to C-C (RHEA) (version=BB command=001D flag=00000000)
0000 | 10 00 1D 00 00 00 00 00 00 06 0B 51 00 FE 0A 3B |            Q   ;
I 7410 2023-11-29 22:13:18 - [Commands] Received from C-C (RHEA) (version=BB command=001D flag=00000000)
0000 | 08 00 1D 00 00 00 00 00                         |                 
I 7410 2023-11-29 22:13:22 - [C-B] Sending ping command

```

**Comment by fuzziqersoftware** [comment]
This is implemented in acb9c656.
