### ISSUE TITLE
[Blue Burst] [Feature Request] A command that takes you to the lobby

### ISSUE THREAD

**Issue by toiletman74** [fuzziqersoftware/newserv#246]
Pretty much just what the title said. Most bb private servers have the command "/lobby" that takes you out from your party and back to lobby 1. It would be a super welcome addition because it would make testing stuff have less walking :')

**Comment by Matt-Swift** [comment]
This already exists, it's `$exit`.

**Comment by toiletman74** [comment]
oh okay thanks
