### ISSUE TITLE
PSO DC works

### ISSUE THREAD

**Issue by Gedehamsen021** [fuzziqersoftware/newserv#25]
PSO DC have support on this server?

**Comment by fuzziqersoftware** [comment]
Unfortunately, newserv does not support PSO DC, mostly because I don't have that version of the game and therefore can't test it.

**Comment by fuzziqersoftware** [comment]
PSO DC (v1/v2) support has now been implemented. It's only tested on the US versions; if you have a non-US version, please provide a log from a connection attempt and I'll add support for it.

**Comment by Gedehamsen021** [comment]
> PSO DC (v1/v2) support has now been implemented. It's only tested on the US versions; if you have a non-US version, please provide a log from a connection attempt and I'll add support for it.

you have a tutorial or something to configure DC version to connect with server?

**Comment by fuzziqersoftware** [comment]
For some versions you should be able to point the DNS server address to newserv and it will connect. For other versions this won't work and you'll need a cheat code or patched game image... I remember seeing a tutorial somewhere on how to do this, but I can't seem to find it now.

**Comment by Gedehamsen021** [comment]
other question, the activation key need be unique?

**Comment by fuzziqersoftware** [comment]
Any serial number and access key that the game accepts should work with newserv.

**Comment by Gedehamsen021** [comment]
well no results with dns, i will try find a tutorial to patch
