### ISSUE TITLE
[Blue Burst] Bank issues

### ISSUE THREAD

**Issue by gered** [fuzziqersoftware/newserv#252]
Currently seeing a number of what looks like sync issues with depositing and withdrawing items from the character's bank/storage. This is using an un-modded Tethealla 1.25.13 client (except for the server IP address, of course).

For example, sometimes the wrong number of items get deposited (e.g. when depositing partial stacks of items), sometimes the wrong item is deposited entirely, and sometimes the client will even disconnect. I've noticed this mostly with deposits as that's what I've been doing the most, but also some withdrawals. I've not yet noticed a pattern, but I'm sure there is one.

I have yet to notice any items actually disappearing entirely from either the bank or my character's inventory. In each case when the inventory/bank sync issue manifests, a simple re-login fixes the display issue and both the bank and character inventory show the expected state.

---

If it helps at all, I did test this simple procedure to replicate one instance of the bug a few times now:

Create a brand new character and join a game.

```text
[PlayerInventory] Meseta: 0
[PlayerInventory] 5 items
[PlayerInventory]    0: [+00000008] 00010000 00000000 00000000 (00010000) 00000000 (Saber)
[PlayerInventory]    1: [+00000008] 01010000 00000000 00000000 (00010001) 00000000 (Frame)
[PlayerInventory]    2: [+00000008] 02000500 F4010000 00000000 (00010002) 28000012 (Mag LV5 5/0/0/0 40% 0IQ (costume))
[PlayerInventory]    3: [+00000000] 03000000 00040000 00000000 (00010003) 00000000 (Monomate x4)
[PlayerInventory]    4: [+00000000] 03010000 00040000 00000000 (00010004) 00000000 (Monofluid x4)
```

Go to the bank and deposit 2 Monomates. The server logs display this as the character inventory after this is done.

```text
[PlayerInventory] Meseta: 0
[PlayerInventory] 5 items
[PlayerInventory]    0: [+00000008] 00010000 00000000 00000000 (00010000) 00000000 (Saber)
[PlayerInventory]    1: [+00000008] 01010000 00000000 00000000 (00010001) 00000000 (Frame)
[PlayerInventory]    2: [+00000008] 02000500 F4010000 00000000 (00010002) 28000012 (Mag LV5 5/0/0/0 40% 0IQ (costume))
[PlayerInventory]    3: [+00000000] 03000000 00020000 00000000 (00010003) 00000000 (Monomate x2)
[PlayerInventory]    4: [+00000000] 03010000 00040000 00000000 (00010004) 00000000 (Monofluid x4)
```

However, if you view the character inventory right now in the game client, you should see zero Monomates in your inventory, but all other items should still be there.

Now check the items in the character's bank, and you should see 2 Monomates, as expected.

Disconnect and re-login, join a new game. View the character's inventory again and you should now see the expected inventory with only 2 Monomates. As well, viewing the items in the bank again should also still show 2 Monomates.

---

Also should add that when joining a new game and viewing the items in the bank, I've noticed that the list will usually not be sorted as PSO usually does. It seems the initial list will be sorted in what looks like the order that items were originally deposited in. However, after the first deposit or withdrawal, and then viewing the bank items again, the list will then be sorted. I've not tested this a ton, so there may be some cases where this doesn't happen _exactly_ as I've described here, but it seems to mostly be the case.

**Comment by fuzziqersoftware** [comment]
I've fixed one issue just now where the server would send the delete item command to everyone in the room (when it should instead send the command to everyone except the player depositing the item). The effect of this bug caused stackable items to be deleted twice, which fixed the example you described above.

Bank sorting was just never implemented in newserv; I've also implemented it just now.

The delete command bug should only affect stackable items when depositing less than the entire stack, so if you could come up with a test case showing the wrong item being deposited, that would be very helpful.

**Comment by gered** [comment]
Cool, I'll give this new code a try over the next couple days.

I'll definitely pay attention more closely to see if I actually do notice wrong items being deposited (I was thinking after I wrote the issue originally that I might have mis-remembered that ... not sure, as I was trying a lot of things once I noticed the bank issues)..

**Comment by gered** [comment]
This does seem *much* improved so far. However, I did notice the "wrong item being deposited" issue again and don't know exactly how it happened (ugh!). I'll try to put together a reproduction case for you. Might not be until tomorrow though, not sure I'll have time tonight unless I find it again real quick... but regardless thought I'd let you know in the mean time.

**Comment by fuzziqersoftware** [comment]
I suspect the withdraw issues happen if you deposit an item, then withdraw another item without leaving the bank menu. I've fixed an issue just now that could have occurred in that scenario where item IDs weren't assigned properly, and the wrong item could be withdrawn.

**Comment by fuzziqersoftware** [comment]
Thanks for testing again. I believe the bank issues are fully fixed, but feel free to reopen this if anything else goes wrong.
