### ISSUE TITLE
[Blue Burst] $bbchar issues

### ISSUE THREAD

**Issue by gered** [fuzziqersoftware/newserv#253]
I've noticed that using the `$bbchar` command to copy a Gamecube character (PSO Plus) mostly works, except at least for one major issue so far.

On the new BB character copy of the original, when you go into a game and look at your techniques list on the quick swap / shortcut window, you'll see "Foie" listed in every single slot. I noticed this across a number of different high-level characters that I used `$bbchar` on.

Note that viewing your character's "Techniques" list from the main in-game menu shows the correct list of learned techniques and levels. As well, it's possible to bind them to your action palette / keybinds and use them as normal. Only the quick swap / shortcut window's techniques list seems to be broken.

Also of note, the source character's bank is not copied to BB. I don't know if that is an accidental omission or just a limitation.

**Comment by Matt-Swift** [comment]
Regarding bank: Bank data is never sent to the server from a console character, so it cannot be transferred to BB by the server unfortunately as it has no knowledge of it.

**Comment by fuzziqersoftware** [comment]
I've rewritten most of the implementation of this command, and the quick menu should now be fixed. Please let me know if it works for you now.

**Comment by gered** [comment]
Seems fine to me, just re-imported a few characters again and the quick menu issue is gone. The only thing I noticed this time is the Meseta the source character had is not copied across. I thought it was previously, but might be mis-remembering. I don't think this is another technical limitation, is it?

**Comment by gered** [comment]
Sorry, I spoke too soon.

I noticed just now while playing on a freshly re-imported BB character that it felt noticeably harder to kill monsters and took a closer look at my character stats. They are off by the exact amount of materials I had used on the Gamecube character. This is despite the fact that `$matcount` on both the source and copy character shows the same numbers.

**Comment by fuzziqersoftware** [comment]
Both material import and Meseta import should be fixed now.
