### ISSUE TITLE
[Blue Burst] New accounts are created with incorrect Keyboard Mappings

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#259]
I think the PSOBB keyboard mappings are being created with the PSOPC original mappings, in PSOBB by default a new account and character should be created with the Equivalent mappings of the Default 1 preset so you control your character with the WASD keys rather than the Arrow Keys.

![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/09855779-8037-49c5-bdc4-e43a671ef83b)

**Comment by fuzziqersoftware** [comment]
This has been fixed by 04445dab.
