### ISSUE TITLE
[Blue Burst] Failed to load certain Enemy/NPC in TTF with 4 players

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#261]
Created a normal episode 1 room with 4 players at the same time, tested controlling the dragon it was unable to be moved but the attacks worked somehow, there's also some error messages loading a certain NPC or Enemy I'm not sure. But figured this would be a valuable log with 4 clients testing the quest at once. 

I was actually hunting for more missing sub commands for this one but please take a look see if you notice anything weird

[TTF4PlayerUnknownEntity.txt](https://github.com/fuzziqersoftware/newserv/files/13621723/TTF4PlayerUnknownEntity.txt)

**Comment by fuzziqersoftware** [comment]
I've added a case for the unknown enemy type warning in the log file, but I believe it was ultimately harmless. Is there another issue captured by this log, or is it just the unknown enemy type message?

**Comment by nolrinale** [comment]
just that (that i know of) i tried to use the dragon was unable to move it around but was able to do the actions i dont recall very well if you could move him around too.

Thats why i posted the full log maybe i was missing something else if not we can close this one too

**Comment by fuzziqersoftware** [comment]
I've never tested controlling the Dragon, but if attacks worked and movement did not, it's very unlikely to be an issue with the server. I wouldn't be surprised if the client ignores your keyboard or controller configuration in this case and uses some default values instead, for example.
