### ISSUE TITLE
[Blue Burst] 4 Player Cmode Area 2 wrong monster indexes and disconnections

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#262]
Starting a new Cmode room Episode 1 Stage 1, 4 players clients, cleared the Area 1 without any mayor issue (Player 1 had `$debug` running) Upon arriving to Area 2 after killing the monsters the monsters killed don't match with the monsters the server thinks were killed, this continued until the very end were I got to the Dragon, the dragon defeated the whole party and returned all characters to Pioneer 2

In Pionner 2 I selected `Try Again` started from Area 1 again, ran (as P1) to the first room to kill the Boomas again and this time I got disconnected with an Error 100 right after I killed it, Attempted to kill another booma with P2 and P2 stayed connected, then i manually disconnected P2 and P3 and left only P4, P4 got the weird Challenge Mode text explanation Box, then afterwards I manually disconected P4 as well and shutdown the server.

Heres the entire log of all the session it's very heavy this time.
[4PlayerCmodeDesync.txt](https://github.com/fuzziqersoftware/newserv/files/13622042/4PlayerCmodeDesync.txt)

**Comment by fuzziqersoftware** [comment]
This is fixed by 83166f1e and 86545557.
