### ISSUE TITLE
[Blue Burst] Error 100 after killing a Rappy while doing Quest 5-2

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#264]
Here's the Log of the whole session, got an error 100 after killing a rappy during gov quest 5-2.

[5-2RappyDced.txt](https://github.com/fuzziqersoftware/newserv/files/13627787/5-2RappyDced.txt)

**Comment by fuzziqersoftware** [comment]
It's not obvious to me what went wrong here. The last command sent is a 6x45 command, which isn't handled in any special way by the server, and there's no error message in the log either. Can you remember what exactly happened right before this disconnection?

**Comment by nolrinale** [comment]
I entered that room and monsters appeared, as I was approaching them to attack them I got an Error 100 box. 

It is possible might had been a network issue for this one but I will be re-running these quests later today just in case.

**Comment by nolrinale** [comment]
Closing this one as might be an issue related to the recovery item sync fix couple builds ago
