### ISSUE TITLE
[Blue Burst] Error 100 while doing End of Wilderness EP4 solo quest

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#265]
While doing To the end of Wilderness EP4 solo quest (quest36) got an Error 100 mid quest, was attemtping to kill an Astark

[EndOfWildsDCED.txt](https://github.com/fuzziqersoftware/newserv/files/13628599/EndOfWildsDCED.txt)

Attempted the quest again and got dced right after a Del Rappy appeared in the field
[EndOfWildsDCED2.txt](https://github.com/fuzziqersoftware/newserv/files/13628658/EndOfWildsDCED2.txt)

**Comment by fuzziqersoftware** [comment]
I believe this is fixed by 2f32e8ab. It seems an extra command sent when buying consumable items from the shop caused the client to think it had a larger quantity of the item than the server was aware of.
