### ISSUE TITLE
[Blue Burst] Error 100 upon killing monest

### ISSUE THREAD

**Issue by toiletman74** [fuzziqersoftware/newserv#266]
if you kill a monest, pipe back to town while the death animation is still playing, pipe back to forest, the monest will show up again and then upon killing the monest again, an error 100 will pop up.
![image](https://github.com/fuzziqersoftware/newserv/assets/91436591/34c3b570-65df-45ea-a3be-e4990fe6479e)

**Comment by fuzziqersoftware** [comment]
This is fixed by 2dc2f85b; you will no longer get disconnected for this. Only the first kill will give EXP; if you kill it again, you'll see "EXP+30" but you won't actually get any EXP.
