### ISSUE TITLE
[Blue Burst] Final Room Set boxes are wrong in Gov Quest 6-3

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#267]
Boxes before the final room in gov quest 6-3 should be set to drop recovery items before the final room. 

[6-2SetBoxError.txt](https://github.com/fuzziqersoftware/newserv/files/13653812/6-2SetBoxError.txt)

**Comment by fuzziqersoftware** [comment]
I checked both 6-2 and 6-3; neither quest has set boxes in the last couple of rooms. All of the 6xA2 (box item drop request) commands from those boxes have nonzero values for ignore_def, which means they're just generic boxes.
