### ISSUE TITLE
[Blue Burst] Loading and/or Clearing Quests 7-X's  breaks the CCA door flags in Free Exploration & Solo Mode

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#269]
Upon clearing gov quest 7-1 (which is the one that walks you through the Jungle and Jungle East area to find the first gate switch) and returning to the lobby I created a new EP2 room to begin doing 7-2 but before doing so I stopped by CCA in free exploration and I found out one of the door locks had already being deactivated.

Just to double check I returned to the lobby and created a new EP2 room this time in Solo Mode, went to CCA and found out the same result one of the locks had been permanently deactivated.

![pso1702494306](https://github.com/fuzziqersoftware/newserv/assets/5244595/4d118e44-1426-4d0b-9dd2-a0f5710bade8)

Update 1: Got to lv 30 and created a new EP2 room this time in Hard mode, the gate locks are all engaged as this is a new save data starting from quest 5-1

Update 2: I was able to fix the door flags by loading another episode 2 quest, in this case it was Phantasmal World 1, started the quest and then aborted it by returning to the lobby, then created another Episode 2 Free Room, went to check the gate and it had once again it's 3 locks engaged, then once again I created a solo room and the 3 locks were engaged as well. So it's indeed an issue with the 7-X quest series (and most likely 6-5 as well which spawns Elly and also controls the Lab Yellow door lock leading to CCA in free expl) messing around with the general episode 2 flags.

Update 3: You can modify the flags of the door at will by loading any of the Gov 7-x quests at different unlock points, with 7-4 unlocking the door entirely by just starting it on first load, or 7-1 restoring all the locks by loading and then aborting it. 

The correct behavior is that all 3 locks of the main gate should be always engaged in Free Exploration Mode/Solo Mode regardless of your progress via gov quests. 

The log is very long and includes the whole 7-1 session + free exploration session afterwards
[7-1ClearCCAFreeRoamIncorrectFlagSet.txt](https://github.com/fuzziqersoftware/newserv/files/13664774/7-1ClearCCAFreeRoamIncorrectFlagSet.txt)

**Comment by fuzziqersoftware** [comment]
This is fixed by b7604eb6. I've added a configuration option to forbid writes to specific quest flags, so make sure to update your config.json.
