### ISSUE TITLE
Connection stability - Item glitch causing disconnects.

### ISSUE THREAD

**Issue by clint-david** [fuzziqersoftware/newserv#27]
Version: 06bab574078d914a8738fdb4d697a7ed9865e937

Setup:
  Player 1 - LAN connection to main server
  Player 2 - LAN connection to proxy server which then connects to main server via internet 

I have been doing some stability testing, and the current server appears to be less stable than the pre proxy redesign version 20410e7a9451525d4b7c99a51b8fb538c3d84649. I have been tracking this for a few versions, and I do not believe it is the proxy server alone that is causing the issues as Player 1 is just as likely to get disconnects as Player 2. I reference the proxy split as it is the last known (to me) stable version. There may be some other bugs (I have had a few random disconnects), but the following is the only one I have isolated so far.

Stability is defined as ~2 hours of continuous playtime without any disconnects or issues.

With the new server after about 15 minutes of playtime, an item (appears to be any random item) will glitch out and cause the player who picks it up to immediately disconnect. Either player can pick the item up and it will immediately disconnect them. If the other player rejoins, the issue can be repeated multiple times by either player. Item is added to inventory before disconnect and remains in inventory after (basically a duplication glitch). If the item is left alone can continue playing without effect.

Only error that the server shows is:
`[Server] Error in client stream: item not present`

**Comment by fuzziqersoftware** [comment]
This is definitely a bug in the item tracking code, which was added around the same time as the proxy server. I can add an option to turn item tracking off for non-BB games, which would improve stability here (but obviously wouldn't fix the bug).

When an item gets "broken", is it a new item (just dropped from a box/monster), or has it been around for a while? The game automatically deletes older items on the ground when there are too many, and I think it's likely this logic that goes out of sync on the server side. If you can get a full log of a session in which this has happened and upload it here, that would be very helpful.

**Comment by clint-david** [comment]
It is a new item.

I will be just running through the game and go to pick up a newly dropped item and just disconnect all of a sudden. Since there are two players the session will stay active, I can rejoin and then either player can try that item again and it will do the same thing repeatably. If you continue on and leave the item there all future items work perfectly fine until the bug happens again.

Can do a posting a full log. I will have to make one though so it make take a day or two.

**Comment by clint-david** [comment]
When I tired to quickly collect a log with a single player the issue did not happen.

When I used a second player over proxy, we were able to get the issue to happen immediately, but this time in a different way. Player 0 dropped an item for Player 1 to use, Player 1 picked up the item (not issues), and then used it and was disconnected. From the log it looks like when Player 1 picked up the item the server actually added it to Player 0's inventory. Then when it was used, it was not present in Player 1's inventory and they were disconnected.

We tired a few more times to get the previous error, but got a few more random disconnects without any luck (the connection kept dropping constantly and acting very odd. Logs didn't really show anything). I will try again in a few days when I have time to try again.

Disconnect is the last thing in the file.

[output_usedmaterial.log](https://github.com/fuzziqersoftware/newserv/files/8972310/output_usedmaterial.log)

**Comment by fuzziqersoftware** [comment]
Thanks for the log - it was very helpful. You're correct; the server was indeed adding the item to the wrong player's inventory. This should be fixed by commit a3bfed6e. I'm pretty sure this is the only case where the leader does something on behalf of other players that we need to track, so hopefully this was the only missing piece of the puzzle.

**Comment by clint-david** [comment]
Sorry for the delay in testing. I was traveling and only just got a chance to test.

I ran the latest version of the server (ec20506) and it worked great. The item bug is all fixed. The server also was behaving much better. Was able to run for about 2 hours after we got past a few bugs we found (will post in new issue threads). Thanks!
