### ISSUE TITLE
[Feature request] Command to spawn meseta

### ISSUE THREAD

**Issue by toiletman74** [fuzziqersoftware/newserv#271]
Just as the title says, a command to spawn meseta would be awesome for testing purposes

**Comment by fuzziqersoftware** [comment]
You can use $item for this. You don't need to use a hex code with that command; you can just write e.g. "$item 100000 Meseta" and the server will create it for you. You'll have to enable cheat mode do to this.

**Comment by toiletman74** [comment]
ohhhhhhh I was writing $item meseta 100000
