### ISSUE TITLE
[Blue Burst] Dropping certain items in-game can affect $matcount

### ISSUE THREAD

**Issue by gered** [fuzziqersoftware/newserv#273]
Hello,

Took me a while to figure out what actually happened here once I noticed `$matcount` was reporting incorrect numbers on a character that had no such issues previously. I initially thought it was related to multiple characters in a game (as I had been transferring items between two different accounts, so couldn't use the new `$bank` stuff for that), but after some testing realized I could reproduce this error with just a single character alone in a game.

I think the exact type of items used here matter, as I didn't see this issue when I dropped a Scape Doll, full & partial stacks of consumables like Trifluid, Star Atomizer (for example), but I did see the issue occur when I dropped a Cure/Shock, in addition to the below items.

Steps to reproduce with one of my characters:

- Login with character
- Walk to counter, create new ep1/normal/normal game
- In game
- Type `$matcount`, shows correct numbers
- Drop "L&K14 Combat" from inventory
- Type `$matcount`, **now shows incorrect numbers**
- Pick up "L&K14 Combat" from ground
- Type `$matcount`, same numbers as last time
- Drop "Red Sword" from inventory
- Type `$matcount`, **shows different, but still incorrect numbers**
- Pick up "Red Sword" from ground
- Type `$matcount`, same numbers as last time

Server logs: [logs.txt](https://github.com/fuzziqersoftware/newserv/files/13693307/logs.txt)

The character sheet stats remain unaffected, this just _seems_ to be an issue with `$matcount`.

This was tested using the latest newserv code (as I write this, commit 2bd43391a6912db708d2c95416ada295b7fbe177), and an unmodified Tethealla 1.25.13 client.

EDIT: I suppose it's also worth noting that this is a character that was previously imported from Gamecube via the `$bbchar` command.

Let me know if there's any other info and/or testing I can provide to help.

**Comment by gered** [comment]
Was trying to see if I could put together some reproduction steps with a brand new character, but noticed something else odd along the way.

- Brand new Humar
- Create a game
- Enable `$cheat`
- Spawn 8 Power Materials via `$i 030b`
- Pick them all up
- Use them all in your inventory, **from the bottom up**
- Character sheet and `$matcount` shows expected numbers. (Base ATP at 61, Power Materials used 8)

Then try doing the same thing again, but this time use all 8 of the Power Materials in your inventory **from the top down**. After doing this my character sheet still shows base ATP at 61, but `$matcount` says only 4 Power Materials used.

Tried this a few times each, and it seems 100% reproducible to me. I'm going to guess that something about this _probably_ explains the behaviour I also saw with my other character.

**Comment by fuzziqersoftware** [comment]
Thanks for the detailed report. The problem here is that material usage is stored in unused bytes in the inventory item structure, so moving inventory items around by using or dropping them can corrupt that data if the server isn't careful about it. (This isn't a hack I did - this is how Sega stored the information originally.) This should be fixed by commit a9afab97.
