### ISSUE TITLE
[Blue Burst] Issues creating stackable items with the item_create commands

### ISSUE THREAD

**Issue by toiletman74** [fuzziqersoftware/newserv#274]
For an example if you are playing gallon's plan and you received the two photon tickets at the end of the quest, they will show up in your inventory just fine. But if you exit out of the game and log back in you will have only 1 photon ticket in your inventory. If you go back to gallon's plan and again get 2 more photon tickets your inventory will say 3 photon tickets, but again if you exit and relog you will only have 1 photon ticket.

Here's some of the log from when I did gallon's plan.

I 818 2023-12-16 18:30:09 - [Lobby:17] Creating item from box 008E (area 02)
I 818 2023-12-16 18:30:09 - [ItemCreator:BB_V4/Ep1/Nml/N/9] Box drop checks for area_norm 01; random state: 3BF3DF08 000000FE
I 818 2023-12-16 18:30:09 - [ItemCreator:BB_V4/Ep1/Nml/N/9] Box spec 00380000 did not produce item 030E1A
I 818 2023-12-16 18:30:09 - [ItemCreator:BB_V4/Ep1/Nml/N/9] Item class is 05
I 818 2023-12-16 18:30:09 - [ItemCreator:BB_V4/Ep1/Nml/N/9] Chose 10 Meseta from range [5, 15]
I 818 2023-12-16 18:30:09 - [Lobby:17] Entity 008E (area 02) created item 10 Meseta
I 818 2023-12-16 18:30:09 - [Lobby:17] Creating item 0081002C at 02:321.29,-340.36
I 818 2023-12-16 18:30:10 - [Lobby:17] Creating item from enemy 00FA (area 02)
I 818 2023-12-16 18:30:10 - [ItemCreator:BB_V4/Ep1/Nml/N/9] Enemy type: 5; random state: 3BF3DF08 00000101
I 818 2023-12-16 18:30:10 - [ItemCreator:BB_V4/Ep1/Nml/N/9] Drop chosen (80 < 100)
I 818 2023-12-16 18:30:10 - [ItemCreator:BB_V4/Ep1/Nml/N/9] Enemy spec 00090000 did not produce item 030D13
I 818 2023-12-16 18:30:10 - [ItemCreator:BB_V4/Ep1/Nml/N/9] Rare drop not chosen; item class determinant is 1; item class is 4
I 818 2023-12-16 18:30:10 - [ItemCreator:BB_V4/Ep1/Nml/N/9] Generating tool with class 00
I 818 2023-12-16 18:30:10 - [Lobby:17] Entity 00FA (area 02) created item Monomate x1
I 818 2023-12-16 18:30:10 - [Lobby:17] Creating item 0081002D at 02:366.181,-402.484
I 818 2023-12-16 18:31:35 - [Lobby:17] Player 0 dropped item 0001001C (Frame +1DEF +1EVP) at 0:(251.205, 317.857)
[PlayerInventory] Meseta: 197503
[PlayerInventory] 29 items
[PlayerInventory]    0: [+00000000] 01010000 00000000 00000000 (00010000) 00000000 (Frame)
[PlayerInventory]    1: [+00000000] 02000500 F4010000 00000000 (00010001) 28000012 (Mag LV5 5/0/0/0 40% 0IQ (costume))
[PlayerInventory]    2: [+00000000] 03010000 00050000 00000000 (00010002) 00000000 (Monofluid x5)
[PlayerInventory]    3: [+00000008] 01022700 00000000 00000000 (00010003) 00000000 (RED RING)
[PlayerInventory]    4: [+00000000] 01013F00 00000000 00000000 (00010004) 00000000 (SONICTEAM ARMOR)
[PlayerInventory]    5: [+00000008] 01013600 00040000 00000000 (00010005) 00000000 (BLACK HOUND CUIRASS (4 slots))
[PlayerInventory]    6: [+00000008] 01034900 00000000 00000000 (00010006) 00000000 (V101)
[PlayerInventory]    7: [+00000008] 0230C800 0000204E 00000000 (00010007) 00000000 (ELENOR LV200 0/200/0/0 0% 0IQ (red))
[PlayerInventory]    8: [+00000000] 004E0100 00000000 1F000600 (00010008) 00000000 (IRON FAUST !PC:1F00 !PC:0600)
[PlayerInventory]    9: [+00000000] 00670000 00000164 03640564 (00010009) 00000000 (BARANZ LAUNCHER 100/0/100/0/100)
[PlayerInventory]   10: [+00000000] 00BF0000 00000164 03640564 (0001000A) 00000000 (HEAVEN STRIKER 100/0/100/0/100)
[PlayerInventory]   11: [+00000000] 03030000 00090000 00000000 (0001000B) 00000000 (Sol Atomizer x9)
[PlayerInventory]   12: [+00000000] 03000100 00060000 00000000 (0001000C) 00000000 (Dimate x6)
[PlayerInventory]   13: [+00000000] 03070000 000A0000 00000000 (0001000D) 00000000 (Telepipe x10)
[PlayerInventory]   14: [+00000000] 03100000 00500000 00000000 (0001000E) 00000000 (Photon Drop x80)
[PlayerInventory]   15: [+00000000] 03020100 0F000000 00000000 (0001000F) 00000000 (Disk:Resta Lv.2)
[PlayerInventory]   16: [+00000000] 00120000 00000000 00000000 (00010010) 00000000 (SPREAD NEEDLE)
[PlayerInventory]   17: [+00000008] 001E0000 00000000 00000000 (00010011) 00000000 (HEAVEN PUNISHER)
[PlayerInventory]   18: [+00000008] 01035600 01000000 00000000 (00010012) 00000000 (Heavenly/Arms)
[PlayerInventory]   19: [+00000000] 03000000 00020000 00000000 (00010013) 00000000 (Monomate x2)
[PlayerInventory]   20: [+00000000] 00100700 00000564 00000000 (00010014) 00000000 (RAIKIRI 0/0/0/0/100)
[PlayerInventory]   21: [+00000000] 00060000 00000541 00000000 (00010015) 00000000 (Handgun 0/0/0/0/65)
[PlayerInventory]   22: [+00000000] 007F0A00 00008105 B1808000 (00010016) 00000000 (Hell NEEDLE (HELL))
[PlayerInventory]   23: [+00000000] 01035400 00000000 00000000 (00010017) 00000000 (Heavenly/Power)
[PlayerInventory]   24: [+00000008] 01035400 03000000 00000000 (00010018) 00000000 (Heavenly/Power)
[PlayerInventory]   25: [+00000008] 01034B00 02000000 00000000 (00010019) 00000000 (V502)
[PlayerInventory]   26: [+00000000] 000A0004 00000000 00000000 (0001001A) 00000000 (Cane +4)
[PlayerInventory]   27: [+00000000] 01010000 00000000 01000000 (0001001B) 00000000 (Frame +1EVP)
[PlayerInventory]   28: [+00000000] 03100400 00000000 00000000 (0001001D) 00000000 (Photon Ticket x0)
I 818 2023-12-16 18:31:46 - [Lobby:17] Deleted lobby

**Comment by fuzziqersoftware** [comment]
The issue here is that creating stackable items without specifying the stack size results in an x0 stack, which causes the client and server to behave in odd ways. I've changed the code to not allow creating x0 stacks.

**Comment by toiletman74** [comment]
I didn't even know you could specify a stack size, how do you do that?

**Comment by fuzziqersoftware** [comment]
The arguments to $item try to match the in-game item descriptions as closely as possible (though this still isn't perfect in some cases). So you can specify a stack size by saying (for example) `$item Trimate x5`.

**Comment by toiletman74** [comment]
Oh I thought you meant with the item_create command you could specify a stack size

**Comment by fuzziqersoftware** [comment]
With item_create2 you should be able to specify a stack size, since it allows you to specify all 12 bytes of the item data. The stack size would be the sixth byte (e.g. 03 00 02 00 00 05 is Trimate x5).

**Comment by PalasX** [comment]
A common modification to the client was to alter max stack size to 99 (or 127, or 254, or anything you wanted so long as it was 1 byte unsigned). If that modification is done on client, is it possible to use $i or item_create2 to create items in stacks larger than 10?

**Comment by fuzziqersoftware** [comment]
I haven't tried this; the server might create the item but you'll likely get an error when picking it up. I can add a configuration flag allows overriding the maximum stack size on BB to match what the client has; would that be useful? (If so, feel free to open a new issue so I won't forget.)
