### ISSUE TITLE
‘struct PPC32Emulator::AssembleResult’ has no member named ‘metadata_keys’

### ISSUE THREAD

**Issue by ZikZakFR** [fuzziqersoftware/newserv#277]
Compiling on Archlinux after compiling and installing phosg.

```
newserv/src/FunctionCompiler.cc: In function ‘std::shared_ptr<CompiledFunctionCode> compile_function_code(CompiledFunctionCode::Architecture, const std::string&, const std::string&, const std::string&)’:
newserv/src/FunctionCompiler.cc:140:37: error: ‘struct PPC32Emulator::AssembleResult’ has no member named ‘metadata_keys’
  140 |     for (const auto& it : assembled.metadata_keys) {
      |                                     ^~~~~~~~~~~~~
make[2]: *** [CMakeFiles/newserv.dir/build.make:440: CMakeFiles/newserv.dir/src/FunctionCompiler.cc.o] Error 1
```

**Comment by fuzziqersoftware** [comment]
This is due to a recent change in resource_dasm; you'll need to pull, rebuild, and reinstall it (or remove it and build without patch support).

**Comment by ZikZakFR** [comment]
Oh ok, when I updated phosg then newserv, resource_dasm didn't pull anything.
Now it does, and compiling it then newserv fail to compile in a more dramatic way, referring a lot to diff_dol_files.
I'll see to ignore resource_dasm.

**Comment by fuzziqersoftware** [comment]
What are the issues with diff_dol_files? That function uses code from resource_dasm which hasn't changed recently, so I'm surprised it doesn't build for you.

To build without resource_dasm even if it's installed, you can comment out the line `find_package(resource_file QUIET)` in CMakeLists.txt.

**Comment by ZikZakFR** [comment]
I'll eventually retry, for now this ticket is sort-of closed as I used ccmake to deactivate resource_dasm lib path.
I'll issue another one when I get the occasion to try once more with resource_dasm
