### ISSUE TITLE
Error after player creates a character, PSOBB

### ISSUE THREAD

**Issue by mileskanda** [fuzziqersoftware/newserv#278]
Hello @fuzziqersoftware.

Few days ago I built newserv on another machine, but got error.

After player creates a character, server shows an error:

I 1750 2023-12-19 07:13:44 - [C-6] Client is in the BB data server phase; disabling command data logging for the rest of this client's session
I 1750 2023-12-19 07:13:44 - Using loaded system file system/players/system_miles.psosys
I 1750 2023-12-19 07:13:44 - Using loaded Guild Card file system/players/guild_cards_miles.psocard
I 1750 2023-12-19 07:13:44 - [Server] Client disconnected: C-6 on fd 38
terminate called after throwing an instance of 'cannot_open_file'
  what():  can't open file system/players/system_miles.psosys: 2 (Unknown error)
Aborted (core dumped)

How this can be corrected? Thank you.

**Comment by mileskanda** [comment]
I have manually created directory "player" in system/ and logged in the server.

**Comment by fuzziqersoftware** [comment]
I was just writing a comment describing that that's what needs to be done. I'll make the server automatically create that directory on startup if it's missing, which should prevent this issue for others in the future.
