### ISSUE TITLE
GC: Quest menu disconnects

### ISSUE THREAD

**Issue by clint-david** [fuzziqersoftware/newserv#28]
Version: ec20506
Client: Gamecube

When attempting to launch quests, I am able to open the quest menu, but when selecting a type (in this case it was the Control Tower quest type), immediately get a disconnect (sub menu of Control Tower quests is not shown). Log file attached.
[output_quest-disconnect.log](https://github.com/fuzziqersoftware/newserv/files/9194534/output_quest-disconnect.log)

**Comment by fuzziqersoftware** [comment]
Thanks for the report. This was caused by some recent reverse-engineering I did; it appears the flag argument on the 10 command can't be trusted to reveal the command's format. This is fixed in ce2cf1b5.

**Comment by clint-david** [comment]
I tested the latest version and the issue is all fixed. Thank you!
