### ISSUE TITLE
GC: Grinders cause disconnects

### ISSUE THREAD

**Issue by clint-david** [fuzziqersoftware/newserv#29]
Version: https://github.com/fuzziqersoftware/newserv/commit/ec205062ad38eedce0318a5922ec2cd8f18a4974
Client: Gamecube

When using a grinder, the client immediately disconnects. All other players unaffected. 

From the log files it appears to indicate that the server thinks the player is not holding an item while using the grinder.

Log file attached. Let me know if you need a full log file. I can do a dedicated session to catch the issue.
[output-monogrinder.log](https://github.com/fuzziqersoftware/newserv/files/9194555/output-monogrinder.log)

**Comment by fuzziqersoftware** [comment]
Thanks for the report. I didn't attempt to reproduce this bug, but I'm 90% sure it's due to the server not tracking item equip state in non-BB games. This is fixed in 02e98008 and e6b05196.

**Comment by clint-david** [comment]
I tested the latest version and the issue is all fixed. Thank you!
