### ISSUE TITLE
[PC] Error processing client command: item not present

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#292]
A player recently had 3 disconnects with this error above doing various different actions, they say accessing the shop, typing, and mag feeding. Doesn't make too much sense but please find the below log of this, it's from lobby creation until the 3rd disconnect.

This all happened in one game hosted by someone who had no issues, but the same player disconnected from the same game each time.

[itemnotpresent.txt](https://github.com/fuzziqersoftware/newserv/files/13779810/itemnotpresent.txt)

**Comment by Matt-Swift** [comment]
The issue appears to be related to https://github.com/fuzziqersoftware/newserv/commit/7c9309f6c5d16506192a31cc714f560218208255, as the commit before it works fine, while players still disconnect on this one.

**Comment by fuzziqersoftware** [comment]
This should be fixed by 910555f2. The previous change to this logic included an attempt to fix behavior on DC NTE and 11/2000, but apparently broke some other versions in the process.
