### ISSUE TITLE
[Dreamcast/PC] Savechar/Loadchar don't seem to be working as intended

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#295]
Recently some people did a `$savechar` backup on V2 followed by a `$loadchar` backup.

It appears that a backup does not save any used materials (can it do this? I would assume it grabs the stats), so when reloading, all extra stats from Power, Mind, etc are all gone.

However, it appears to increase HP by quite a lot for some reason, even though `$matcount` appears to be returning the same value for HP materials used. On my character, HP increased from 840 or so to 1028 after reloading.

Here's a set of files using the system, before and after backup, plus the .psochar file generated by newserv.

[Archive.zip](https://github.com/fuzziqersoftware/newserv/files/13780099/Archive.zip)

**Comment by fuzziqersoftware** [comment]
I believe this will be fixed by f74b416c. The previous logic recomputed the player's stats in all cases, but this produces the wrong result for v1/v2 because non-HP/TP material usage isn't stored anywhere on those versions. Please try this again with the new code when you get a chance.

**Comment by Matt-Swift** [comment]
This all seems good now, thanks!
