### ISSUE TITLE
Hi I Have Bug Compile the server

### ISSUE THREAD

**Issue by lucashart90** [fuzziqersoftware/newserv#3]
I found this problem because I tried to compile and I used it so which dependencies I have to install Including which OS should I use to compile it? 
Congratulations on the project anyway! and great job that I played so much in this wonderful game

![020](https://user-images.githubusercontent.com/6928951/66960681-4c142180-f06d-11e9-9bc6-ef99a619a2d6.JPG)
![021](https://user-images.githubusercontent.com/6928951/66960682-4c142180-f06d-11e9-85b8-a6037b68d9a1.JPG)

**Comment by fuzziqersoftware** [comment]
I updated the project so it should now build in Ubuntu (15fb00f7), so try pulling master and building again. It might also build in other Linux flavors as well now; not sure which one you're using.

**Comment by lucashart90** [comment]
okay and I thank you for the correction and I solved the problem for the compile with ubuntu!!!!
