### ISSUE TITLE
[newserv] [feature request] Command to compress/decompress *.prc files.

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#300]
As far I know the only file of this kind that I know of is the `lobby_billboard.prc` file which controls the coordinates of the billboards shown at the lobby in PSOBB but might exist in other PSO versions as well.

**Comment by fuzziqersoftware** [comment]
This already exists, though it's not obvious how to do it... prc files are the same format as pr2 files, so you can use `./newserv decompress-pr2 lobby_billboard.prc` (and `compress-pr2` to compress/encrypt it again). I'll update the docs to make this clear.
