### ISSUE TITLE
[Blue Burst] Client Monsters desyncs while playing cmode & possibly other modes

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#302]
Created an EP1 challenge room, Stage 1, it was working fine until the party got wiped out once, selected Try Again upon returning to P2 and once in the first room one of the Rappys got desynced attacking one of the players while the other couldn't see nor attack it

![Screenshot from 2023-12-28 20-05-56](https://github.com/fuzziqersoftware/newserv/assets/5244595/26093d18-f8a9-4ef2-8639-7fedf755ce78)

Note: I've seem this same behavior happening sometimes in normal exploration while playing with other players after a while as well hence why I think it affects the whole game somehow...

Session Log
[CMODERetryMonsterDesync.txt](https://github.com/fuzziqersoftware/newserv/files/13788925/CMODERetryMonsterDesync.txt)

**Comment by fuzziqersoftware** [comment]
I don't think this is BB-specific; I've seen this on GC in free-roam as well, which means it's unlikely this is something the server can fix. There could be a Challenge-specific bug on BB that causes clients to generate different sets of random monsters upon retrying Challenge, but I think this is also unlikely.

To help me understand the log, did you do anything after you saw this? It's hard to tell which enemy ID this is unless it was the last enemy you interacted with before ending the session.

**Comment by Matt-Swift** [comment]
I also suspect that this is not a server issue either, as we've seen it countless times playing on numerous servers on numerous versions.

It's usually not obvious to most people, but PSO syncs very little things between players, so even small amounts of lag or latency can cause issues like this.

**Comment by nolrinale** [comment]
This is what I did 
- Started the server
- logged the 2 clients
- created the room and loaded the quest
- walked around and killed af ew monsters until i got killed
- returned to pioneer 2 and selected Try again
- went to the first room and is when the rappy thing happened you see on the screenshot
- logged out player 2 then logged out player 1 
- shutdown the server

**Comment by fuzziqersoftware** [comment]
I've looked into it a bit, but I'm pretty sure this is just normal PSO behavior and cannot be fixed without extensive client patches. Barely any enemy state is synced between clients normally, so it's common for clients to see enemies in different positions or doing different actions. It's even possible for enemies to appear dead or unspawned on one client and not on another (though this is less common).
