### ISSUE TITLE
[Prototypes] [Feature Request] Do not register serials for prototype versions of the game

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#303]
This is a passing thought and might not be worth it/possible, but it may be worth not registering a serial for anyone who plays any prototype or Trial Edition version of the game.

Most people will not take these versions "seriously" in any capacity, and are more likely to use serial numbers that are patterns and then get booted off the server or take up serials that other people could use for the retail versions of the game.

Some of the prototypes (namely NTE and 11/2000) request new serials for every single character as well, potentially clogging up more space on any public instances as people make new characters with new serials.

**Comment by fuzziqersoftware** [comment]
This is implemented by e89802f2. I've only tested it on Ep3 NTE, but it seems to work properly. The DC NTE functional test also seems to do what's intended, according to its log output.
