### ISSUE TITLE
[Blue Burst] [Gamecube/Xbox] Mag PBs arent being set correctly at evolution time 

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#306]
Reference Table:
https://www.pso-world.com/sections.php?op=viewarticle&artid=1240

Creating a Hucaseal/Skyly with a default baby mag with 5/0/0/0

- Feed the mag with Antidotes until becomes a Varuna (gets Farlla PB) OK!
- Feed the mag with Antidotes until at lv 35 becomes a Marutah (gets Pilla PB) OK!
- Feed the mag with Dimates until lv 50 becomes an Ila (gets Estlla PB) INCORRECT!

Ila shoulve gotten Mylla PB at the time of evolution.

**Comment by fuzziqersoftware** [comment]
This is fixed by 0f8dcd37. Before this change, the left-side photon blast was not assigned correctly; the mag would always get the lowest-numbered available photon blast instead of the one it should get.
