### ISSUE TITLE
Suggestion for a Rare drop Notification

### ISSUE THREAD

**Issue by EvilMag** [fuzziqersoftware/newserv#307]
Just a fun little QQL to suggest. Have Banner announce to you (and only you) that you got a rare drop. Would be kinda pointless for GC since they have a patch that plays a sound if you get one but would be nice for v1 and v2.

**Comment by fuzziqersoftware** [comment]
This has been added in c09bd56. The rare notification also tells you what the item is (which you could find out anyway with $what, but this is more convenient).
