### ISSUE TITLE
[Blue Burst] [Gamecube/Xbox] Baby Mags dropped from boxes are always Dark Grey

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#310]
REFERENCE: https://www.pso-world.com/sections.php?op=viewarticle&artid=1017

Creating a normal EP1 room and heading to a known area that drops Baby Mags such as Mines 1 by breaking several boxes you will notice all the mags dropped are grey color like this:

![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/433f3115-b1c2-43c7-badc-f3d68a1e266a)

The correct behavior should be that boxes drop a Mag of any of the colors from the PSOW list above regardless of character's costume color.

**Comment by fuzziqersoftware** [comment]
This should be fixed by efe2515a. On GC and BB, it looks like there are 18 different colors, but I don't know how many colors the game actually supports on v1 and v2. I guessed it was 14 (based on some suspicions from disassembly) but this could be wrong.

**Comment by nolrinale** [comment]
I ran a test on PSO GC (My version is EP1&2 Plus JP 1.05) and went to the Mines and farmed for like 2 hours and got 2 different colored mags from the boxes to confirm the correct behavior, hence why I created this issue as a general bug that could be affecting PSOGC, PSOX and PSOBB.

But it seems to be certain older PSO GC also have this bug in the game (non-plus maybe)
