### ISSUE TITLE
[Blue Burst] Battle Mode scores aren't being updated correctly and scores are being lost after relogin 

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#316]
Created a room with Battle Mode Rule 5 and rule 6 with 4 players noticed in both some of the parameters such as taken/received damage arent recorded properly either it always displays a 0
![Screenshot from 2024-01-04 00-45-12](https://github.com/fuzziqersoftware/newserv/assets/5244595/ec74728f-3870-404d-8188-d579c30b9ba8)

![Screenshot from 2024-01-04 00-45-26](https://github.com/fuzziqersoftware/newserv/assets/5244595/cdb1cdb3-88da-4dac-b806-c023e9183e10)

![Screenshot from 2024-01-04 00-49-29](https://github.com/fuzziqersoftware/newserv/assets/5244595/f9e6abce-ca6d-404b-ba84-8deb7d0dc1a6)

The log is very long and includes the session starting the server, logging on the 4 clients, then starting 3 battle modes 2 sessions of Battle 6 and 1 session of Battle 5
[4PLAYERBattleModeDMGandSCOREChecks.txt](https://github.com/fuzziqersoftware/newserv/files/13824435/4PLAYERBattleModeDMGandSCOREChecks.txt)

**Comment by fuzziqersoftware** [comment]
This may have been fixed by 0de3d273. Could you try again?

**Comment by nolrinale** [comment]
Tested with Battle Rule 7 and Battle Rule 4 
[BattleRule7and4WrongScores.txt](https://github.com/fuzziqersoftware/newserv/files/14055533/BattleRule7and4WrongScores.txt)



In the log search for Game:15 for Rule 7 and Game:16 for the Rule 4

Attached Screnies of Rule 4 

It is a meseta battle, the winner with most meseta wins, however in the final results I think it's saving total damage rather than total meseta, and the 2nd page which is meant to display total damages still displays 0 for all fields

![Screenshot from 2024-01-25 17-30-30](https://github.com/fuzziqersoftware/newserv/assets/5244595/e9a63048-e57c-4d72-8b62-8ac34edde107)
![Screenshot from 2024-01-25 17-30-15](https://github.com/fuzziqersoftware/newserv/assets/5244595/c933827a-7f28-4576-a73f-0216bca69ca1)


Attached Screenies of Rule 7

This one is a meseta battle but nothing in this map drops meseta, rather the kills are counted as meseta (will verify on PSOGC later) still the results look a little bit odd to me in both pages. 

![Screenshot from 2024-01-25 17-17-36](https://github.com/fuzziqersoftware/newserv/assets/5244595/9801b589-b285-488b-b6a1-7e9033490ebb)
![Screenshot from 2024-01-25 17-17-29](https://github.com/fuzziqersoftware/newserv/assets/5244595/b806f5f8-72ec-4b15-a50d-eedffadf4afa)

**Comment by nolrinale** [comment]
In the case of Battle Rule 5 player 1 got dced for breaking a box but the match was able to still end and in this case the mesetas were correctly counted for the main game, but the damages fields in 2nd page are all still 0 for everyone

Heres the log with just this session and screenies
[BattleRule5WrongScoreCheck2.txt](https://github.com/fuzziqersoftware/newserv/files/14055690/BattleRule5WrongScoreCheck2.txt)


![Screenshot from 2024-01-25 17-49-37](https://github.com/fuzziqersoftware/newserv/assets/5244595/66ffb4fc-9a15-4c45-a065-ee4fe3eae5e8)

![Screenshot from 2024-01-25 17-49-28](https://github.com/fuzziqersoftware/newserv/assets/5244595/2838fb23-b937-42d9-b73f-74a309a9834e)

**Comment by nolrinale** [comment]
Lastly, heres the full log of a full Battle Rule 6 session, I dont understand why the scores are always in negative and the damages seem different but a little bit odd still with such low numbers, in this case the party used a mixture of unarmed attacks, attacks with weapons, attack with techs.

This log also includes returning to the lobby were the F12 stats menu displays the current score but the W: and D: fields by pressing TAB still shows 0 for everyone regardless
[BattleRule6Check2ndAndLobbyStats.txt](https://github.com/fuzziqersoftware/newserv/files/14055883/BattleRule6Check2ndAndLobbyStats.txt)

![Screenshot from 2024-01-25 18-07-11](https://github.com/fuzziqersoftware/newserv/assets/5244595/1c34c6e1-1cb3-4952-baa3-3c9fe894e0e7)
![Screenshot from 2024-01-25 18-07-22](https://github.com/fuzziqersoftware/newserv/assets/5244595/0de31b76-3c97-40b2-b08a-bb2266350d76)
![Screenshot from 2024-01-25 18-08-17](https://github.com/fuzziqersoftware/newserv/assets/5244595/44db56c6-178d-448f-b537-f711992a4149)
![Screenshot from 2024-01-25 18-07-53](https://github.com/fuzziqersoftware/newserv/assets/5244595/8666b593-a000-45d4-b529-54684753599c)

**Comment by nolrinale** [comment]
@fuzziqersoftware tested it again in battle rule 4 in temple and I ended up first place with 150ish meseta, is not counted right at the end, an the damage counters are still all at 0 despite punching and using techs against eachother characters. 

![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/432c3f35-c64b-4a7c-a30a-2aead80c62c4)
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/389eab86-2d85-42c1-8797-d639034d617e)

Restarted the game with the same Rules and Player 2 rage quit on purpose, upon returning to lobby the disconnect counter remains at 0 

![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/39f4283e-1cfc-4a01-9360-72fc2fd8feed)

The whole session including rage quitting at the end

[BattleRule4Session3rdCheck.txt](https://github.com/fuzziqersoftware/newserv/files/14473036/BattleRule4Session3rdCheck.txt)

**Comment by nolrinale** [comment]
Tested with the latest build it seems to be the Damage Receive/Give counters arent still working after every match (the 2nd page) displays them as 0 or very low numbers (despite battling both characters with plenty of damage with and without weapons)

This time I tested with Battle Rule 07

And once the match finished in the Lobby the scores arent getting updated in the W: D: texts above the players heads 
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/6c5f8225-54f6-48c7-88d9-cd75debefc7f)

**Comment by fuzziqersoftware** [comment]
This has been fixed; battle mode results now save properly. I was unable to find any remaining problems with the in-battle score display.
