### ISSUE TITLE
[Blue Burst] Zalure/Jellen casted by Sinow Zelle is not synced between clients

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#318]
While encountering a Sinow Zelle or Spiggel which debuffs you and your party members with Zalure/Jellen theres a chance you will see some members debuffed in some clients whilst others arent in other clients.

I did a very long burning test in Seabed running PW3 stuck in an area with 2 Sinows debuffing the party of 4 for a while in different ways, and also killing and ressing several times.

Notice in the screenshots whos debuffed and whos not

![Screenshot from 2024-01-04 15-22-52](https://github.com/fuzziqersoftware/newserv/assets/5244595/910fd876-fd6a-4bb6-bdda-902b317097ea)
![Screenshot from 2024-01-04 15-28-34](https://github.com/fuzziqersoftware/newserv/assets/5244595/c7726b07-ba4e-4b75-82bb-6b597bc0c6c1)

Here's the log of that specific part which lasted for a few mins 
[4PlayerSinowZelleZalureJellenDesyncs.txt](https://github.com/fuzziqersoftware/newserv/files/13831228/4PlayerSinowZelleZalureJellenDesyncs.txt)

Just in case I'm also attaching the whole log of the whole session from the very beginning of the quest this one is very big
[4PlayerPhantasWorld3DesyncsMonstersSeabed.txt](https://github.com/fuzziqersoftware/newserv/files/13831408/4PlayerPhantasWorld3DesyncsMonstersSeabed.txt)

**Comment by Elixir70** [comment]
That's just PSO though. Your client sees a monster cast JZ on a player (could be local player or another player) and goes through the tech damage function. No damage packet is sent because the player class doesn't implement something like this (damage packets aren't even used for players). So you end up with desync.

**Comment by fuzziqersoftware** [comment]
Yeah, this is a pretty standard type of desync. It's not something the server can easily fix because it's an inherent result of the game's architecture.
