### ISSUE TITLE
[11/2000] Item not present when using technique disks

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#320]
Running this commit, just incase any future changes might have made a difference: https://github.com/fuzziqersoftware/newserv/commit/ec99dad8745399745e047f9b26ef1cbab90c4b5a

A player was on 11/2000 and bought a couple of discs (Deband and Jellen it looks like), but the server sees them as both the same disc, so when trying to use the other, they would disconnect.

Here are two logs:

[shop.txt](https://github.com/fuzziqersoftware/newserv/files/13833721/shop.txt)
[shop2.txt](https://github.com/fuzziqersoftware/newserv/files/13833725/shop2.txt)

**Comment by fuzziqersoftware** [comment]
This has been fixed by 612b5d28.
