### ISSUE TITLE
[Blue Burst] EP1 Totems aren't following Gov Quest progression in Solo/Free Modes

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#323]
The Totems found in the Episode 1 areas currently aren't following the progression in the main Gov questline, so that means you can freely go and enable them and they will stay enabled regardless if you had completed the quest that turns them on in order or not.

Each Totem should be initialized in a enabled state only if their specific quest had already been completed, and if that's not the case said Totem flag should be set to disabled until their quest is completed. this rule applies to Free Exploration and Free Exploration in Solo Mode as well. 

Currently I started an EP1 Hard solo room without doing any Gov quest in this difficulty, went to the Caves 2 found the Totem offline, I turned it on, logged out and created yet another EP1 Hard solo room 
Arrived to Caves 2 once again and now the Totem is active at all times
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/22e6f2e3-b601-49eb-85fc-28d607a17ade)

The correct behavior is that the Totem should be enabled by default in solo/free explo mode only if it's specific gov quest had already been completed in this case gov quest 2-2

So the Totem flag should be forced enabled after clearing these Gov quests:
1-2 - 1st Totem
2-2 - 2nd Totem
4-1 - 3rd Totem

**Comment by nolrinale** [comment]
Similar Issue 
https://github.com/fuzziqersoftware/newserv/issues/305

**Comment by fuzziqersoftware** [comment]
This has been implemented by 4a3b0118, but I was not able to test it at the time. Please check this behavior again when you have some time. There are some necessary config changes included in that commit (the QuestFlagRewrites fields); you'll have to add them to your config.json.

**Comment by nolrinale** [comment]
Can confirm its working as intended now, I will be closing this ticket
