### ISSUE TITLE
[BlueBurst] Error (No. 100) There's no connection available, please check your cable. 

### ISSUE THREAD

**Issue by Superdsg** [fuzziqersoftware/newserv#325]
I'm not sure if this was covered somewhere already. Error only happens on Single-Player quests when an event is triggered (on Magnitude of Steel, after having the first conversation with Eleanor and on Gallon's Plan, I think that's the name, at the beginning of the quest after having the first conversation). 
Quest data was added to the patch-bb/data folder on the server and patching the client was successful.
![Capture](https://github.com/fuzziqersoftware/newserv/assets/22509699/76d6b3c1-c314-4bb2-967d-a1d68c4c7187)

**Comment by fuzziqersoftware** [comment]
What appears in the server's console when this happens? There will likely be a message saying something like `[Server] Error processing client command`; please post that message here and as much of the preceding text as possible.

**Comment by Superdsg** [comment]
This is everything on the console from when the Gallon's Plan quest is started:
`I 189 2024-01-05 08:46:33 - [Commands] Received from C-6 (Karinka) (version=BB command=0060 flag=00000000)
0000 | 14 00 60 00 00 00 00 00 69 03 00 00 00 00 01 00 |   `     i
0010 | 00 00 10 00                                     |
I 189 2024-01-05 08:46:33 - [Commands] Received from C-6 (Karinka) (version=BB command=0060 flag=00000000)
0000 | 20 00 60 00 00 00 00 00 3F 06 01 00 00 00 71 7C |   `     ?     q|
0010 | 0F 00 00 00 00 00 76 43 00 00 00 00 00 80 B2 43 |       vC       C
I 189 2024-01-05 08:46:33 - [Commands] Received from C-6 (Karinka) (version=BB command=0060 flag=00000000)
0000 | 1C 00 60 00 00 00 00 00 24 05 01 00 71 7C 00 00 |   `     $   q|
0010 | 00 00 76 43 00 00 00 00 00 80 B2 43             |   vC       C
I 189 2024-01-05 08:46:33 - [Commands] Received from C-6 (Karinka) (version=BB command=0060 flag=00000000)
0000 | 14 00 60 00 00 00 00 00 69 03 64 00 01 00 DC 03 |   `     i d
0010 | 01 00 6B 00                                     |   k
I 189 2024-01-05 08:46:33 - [Commands] Received from C-6 (Karinka) (version=BB command=0060 flag=00000000)
0000 | 1C 00 60 00 00 00 00 00 24 05 00 00 00 00 00 00 |   `     $
0010 | 00 00 6D 43 00 00 00 00 00 80 A6 43             |   mC       C
I 189 2024-01-05 08:46:33 - [Commands] Received from C-6 (Karinka) (version=BB command=0060 flag=00000000)
0000 | 1C 00 60 00 00 00 00 00 2C 05 00 00 FF FF 00 00 |   `     ,
0010 | 00 00 6D 43 00 80 A6 43 00 00 00 00             |   mC   C
I 189 2024-01-05 08:46:36 - [Commands] Received from C-6 (Karinka) (version=BB command=001D flag=00000000)
0000 | 08 00 1D 00 00 00 00 00                         |
I 189 2024-01-05 08:46:38 - [Commands] Received from C-6 (Karinka) (version=BB command=0060 flag=00000000)
0000 | 0C 00 60 00 00 00 00 00 2D 01 00 00             |   `     -
I 189 2024-01-05 08:46:38 - [Commands] Received from C-6 (Karinka) (version=BB command=0060 flag=00000000)
0000 | 14 00 60 00 00 00 00 00 69 03 68 00 00 00 00 00 |   `     i h
0010 | 02 00 68 00                                     |   h
W 189 2024-01-05 08:46:38 - [Server] Error processing client command: cannot overwrite existing player with NPC
I 189 2024-01-05 08:46:38 - [Server] Client disconnected: C-6 on fd 37
I 189 2024-01-05 08:46:38 - [Lobby:00000015:FloorItems:00] Deleted 0 private items
I 189 2024-01-05 08:46:38 - [Lobby:00000015:FloorItems:01] Deleted 0 private items
I 189 2024-01-05 08:46:38 - [Lobby:00000015:FloorItems:02] Deleted 0 private items
I 189 2024-01-05 08:46:38 - [Lobby:00000015:FloorItems:03] Deleted 0 private items
I 189 2024-01-05 08:46:38 - [Lobby:00000015:FloorItems:04] Deleted 0 private items
I 189 2024-01-05 08:46:38 - [Lobby:00000015:FloorItems:05] Deleted 0 private items
I 189 2024-01-05 08:46:38 - [Lobby:00000015:FloorItems:06] Deleted 0 private items
I 189 2024-01-05 08:46:38 - [Lobby:00000015:FloorItems:07] Deleted 0 private items
I 189 2024-01-05 08:46:38 - [Lobby:00000015:FloorItems:08] Deleted 0 private items
I 189 2024-01-05 08:46:38 - [Lobby:00000015:FloorItems:09] Deleted 0 private items
I 189 2024-01-05 08:46:38 - [Lobby:00000015:FloorItems:0A] Deleted 0 private items
I 189 2024-01-05 08:46:38 - [Lobby:00000015:FloorItems:0B] Deleted 0 private items
I 189 2024-01-05 08:46:38 - [Lobby:00000015:FloorItems:0C] Deleted 0 private items
I 189 2024-01-05 08:46:38 - [Lobby:00000015:FloorItems:0D] Deleted 0 private items
I 189 2024-01-05 08:46:38 - [Lobby:00000015:FloorItems:0E] Deleted 0 private items
I 189 2024-01-05 08:46:38 - [Lobby:00000015:FloorItems:0F] Deleted 0 private items
I 189 2024-01-05 08:46:38 - [Lobby:00000015:FloorItems:10] Deleted 0 private items
I 189 2024-01-05 08:46:38 - [Lobby:00000015:FloorItems:11] Deleted 0 private items
I 189 2024-01-05 08:46:38 - [Lobby:15] Enqueued for deletion
I 189 2024-01-05 08:46:38 - [Lobby:15] Deleted
I 189 2024-01-05 08:46:38 - Saved system file system/players/system_pepe.psosys
I 189 2024-01-05 08:46:38 - Added 38 seconds to play time
I 189 2024-01-05 08:46:38 - Saved character file system/players/player_pepe_0.psochar
I 189 2024-01-05 08:46:38 - Saved Guild Card file system/players/guild_cards_pepe.psocard
I 189 2024-01-05 08:46:38 - [C-6] Deleted`

![Capture](https://github.com/fuzziqersoftware/newserv/assets/22509699/8e3d617f-4b3d-421e-986b-4601020e68c6)

**Comment by Superdsg** [comment]
This is the console from Magnitude of Steel when the correct answer is given to Eleanor:
![Capture](https://github.com/fuzziqersoftware/newserv/assets/22509699/f13b7616-415b-45e5-88c6-5273d3a60035)

**Comment by nolrinale** [comment]
This error isn't happening on my end, it seems to be you might be running and older version, can you build from source and try again?

**Comment by fuzziqersoftware** [comment]
This was fixed in commit b6cfb5b2; it will work if you build from the current master. There will be a new pre-built release sometime soon, but I can't give an exact date.

**Comment by KitBallard64** [comment]
Just snagged this and got this error while someone else was trying to join. Hope there's a pre-built release soon since I dono how to build from master. (Also Heya Fuzz! it's me, RydiaFromFF2 XD Can't believe I found you by accident XD)

**Comment by fuzziqersoftware** [comment]
Hey, good to see folks from old times :) I'm working on a sizable subproject right now, but I'll make sure to build a new release as soon as it's done - probably Saturday or Sunday.

**Comment by KitBallard64** [comment]
Really appreciate that Fuzz~♪ I've been looking around, since I use Visual Studio for a few VrChat things, and still at a loss how to build the project so I'll be glad to wait for the official build until then ^_^
