### ISSUE TITLE
[Blue Burst] Revival Cuirass spelled incorectly in USBB-Resources/unitxt_e.prs

### ISSUE THREAD

**Issue by MADrewry** [fuzziqersoftware/newserv#326]
I know this is trivial, and I was able to edit the file to fix it, but inside the unitxt_e.prs file in the USBB-Resources folder in the repository the item "Revival Cuirass" is spelled incorrectly as "Revial Curiass"
 Adding the unitxt_e.prs file to my patch-bb/data folder, this discrepancy was causing my server instance to fail with the following error:

terminate called after throwing an instance of 'std::runtime_error'
  what():  cannot parse item description "Revival Cuirass" (as text: item not found: revival cuirass) (as data: invalid item class)
Aborted

(and yes I do know my title is spelled incorrectly)

**Comment by nolrinale** [comment]
Copy to the patch server data folder the unitxt_e found in 'system/text-sets/bb-v4' and it should run just fine

**Comment by MADrewry** [comment]
@nolrinale thanks for the reminder. I've been trying to wrap my head around the localization files and copying various files in the patch-bb folder to see the results, but it was late and I didn't back up my folders before making changes and I couldn't remember where a working set of files were.

**Comment by nolrinale** [comment]
I updated the unitxt_e.prs in the usbb-loc folder with the latest one from the blueburst folder just in case someone might get confused by this issue later on. Will be available as soon the latest PR is merged. 

Feel free to close the ticket

**Comment by MADrewry** [comment]
Thanks! Closing as completed.
