### ISSUE TITLE
[Blue Burst] Cannot connect to server with existing or new account: Server is full message

### ISSUE THREAD

**Issue by MADrewry** [fuzziqersoftware/newserv#334]
Using the latest commit I am unable to connect to the server using an existing account, gets as far as the patch download screen but when I hit enter I get a "server is full" message.

**To reproduce**
1. Pulled and built the latest commit. 
2. Copied the new Coren map files to patch-bb/data, (also tried without copying map files with same result)
3. Connect to server using existing account, also tried creating new account.
4. Get to patch download screen
5. Hit enter to start game
6. Get "Server is full" message.

Game version  BB

**Server log output**
[log.zip](https://github.com/fuzziqersoftware/newserv/files/13897455/log.zip)

**Comment by fuzziqersoftware** [comment]
This should be fixed by commit 2dff814e. I'm not able to test right now, but I'm pretty confident it will fix the issue. I'll be able to test it tomorrow night, if you don't get to it by then.

**Comment by MADrewry** [comment]
Can confirm this is now working. Your work on this project is sincerely appreciated. My nostalgia level is over 9000!
