### ISSUE TITLE
[Blue Burst] Connecting with the latest 1.25.11 JPBB client

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#336]
Now that we have access to the latest JPBB client in a unmodified state which has been uploaded at https://archive.org/details/psobb_jp_setup_12511_20240109

I wanted to ask if you guys knew a way to prepare it to connect to newserv.

Similar to Tethealla ideally I would like to know what kind of tools or methods can be used to:

- Create an uncompressed copy of the psobb.exe or psobb.pat for easier manipulation
- Get rid of the GameGuard code
- Any other steps or modifications needed to make the client connect to newserv

I want to be able to know how to achieve all this to document it and add it to another PR into the usual notes folder so this information is always kept at hand as an alternative to the Tethealla client. 

I've been trying to do my own research but I keep hitting roadblocks everywhere or extremelly outdated information so any pointers on this woudl be really helpful!

**Comment by fuzziqersoftware** [comment]
Unpacking the executable is nontrivial. In ages long past, a program called stripper was used to do this, but it's difficult to find via search engines for obvious reasons. [This version of stripper](https://github.com/fuzziqersoftware/newserv/files/13929532/stripper_v207f.zip) works on 32-bit Windows 2000 and XP only (and not 64-bit); I'd recommend running it in an isolated qemu instance, since it likely won't work at all on any modern hardware.

After the executable is unpacked, patching out GameGuard is probably not hard. You could disassemble the Tethealla client and go to the address mentioned [here](https://github.com/Solybum/Blue-Burst-Patch-Project/blob/2c953645ecc570437f720e5461dc0c5ecf414928/Blue%20Burst%20Patch%20Project/globals.h), then search for a similar sequence in the unpacked, disassembled 1.25.11 executable to find the appropriate location for the patch.

Finally, changing the connection address is easy. Look in the unpacked executable for strings like ".jp" and ".com" and you'll probably find the connection addresses. You can then overwrite them with whatever you want.

I am not going to spend time working on this client myself, but would be willing to offer more thoughts like the above as needed.

**Comment by MADrewry** [comment]
I've done some preliminary research into unpacking the executable and have played with a few tools that look promising. I think unpacking is still possible, that being said it is not going to be a simple task. Unfortunately I will not have time to do any real work on this until after then end of January as all of my time is booked solid until then. But I take a crack at unpacking once my time is free and report any success or failure.

**Comment by nolrinale** [comment]
Have you guys managed to find anything interesting regarding this client lately?

**Comment by MADrewry** [comment]
I had just a little extra time before my busy push started so I decided to put this into a Windows XP development environment since some of the tools only seem to work there. While attempting to identify the packer both PeID and DIE now list the packing software as Yoda's Cryptor, which was different from what they identified in a Windows 10 environment. Further digging revealed what appear to be signatures for both Yoda's Cryptor and ASProtect within the code. I did make a couple of feeble attempts to find the OEP of the file but GameGuard would launch when I ran PSOBB.EXE in the debugger and appears to terminate the process before I can find the true entrypoint.
 To be honest my reverse engineering skills are practically nonexistent so any progress I can make would be slow, However I will continue to hammer at this as a learning project for myself once I finish with the big work project I am on now. I am willing to take any advice anyone may have on how to proceed.

**Comment by ShiftaDeband** [comment]
If it helps, you can always try to run `psobb.exe /1095189843` or possibly `psobb.exe /1397049153` to give the program some more time to load. 

First one should at least attempt to launch the game, but may still launch GameGuard, which will eventually throw an error, and second should show the credits. Not sure if credits are still GameGuard protected, though.

**Comment by nolrinale** [comment]
I tried to start it via command prompt with this command `PS C:\SEGA\PHANTASY STAR ONLINE Blue Burst> .\PsoBB.exe /1095189843` it begins to download the gameguard files, but since the gameguard servers are down it will attempt to connect several times (in the little gameguard window) until it displays an error message stating the gameguard cannot connect to the network. 

But the game never started 

The credits are protected too after all you are calling the same psobb.exe so same issue

**Comment by ShiftaDeband** [comment]
@fuzziqersoftware [used to have a little utility](https://web.archive.org/web/20111209135740/http://www.fuzziqersoftware.com/projects.php) that would attempt to bypass GameGuard, but I couldn't get it to work.

I have the [old utility](https://shiftadeband.com/etc/psobb-gameguard-launcher.zip) and [source](https://shiftadeband.com/etc/psobb-gameguard-launcher-source-only.zip), but you'll need to modify it (see below). Still posting it here in the event it could be helpful to someone.

> PSOBB Launcher - runs PSOBB and disables GameGuard. Make sure it's in the same directory as online.exe. (This version is for PSOBB v1.24.3; it can be built for other versions of PSOBB by changing the patch addresses in the source.)

--

I have a local legit XP machine that I've used to test newserv for PSOBB. I'll take a stab at this when possible as well.

**Comment by nolrinale** [comment]
Oh? This is created by fuzzi himself more than 10 years ago lol, I sadly cannot understand much about this tool, since you have a real XP machine laying around please give it a try whatever you get the chance.

Since this is a clean client I'm expecting first of all the game loading the correct title screen with the Episode IV subtitle which is a flag that either got disabled or got lost or got screwed up in the tethealla client but should look like this 

![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/3ed06358-6206-45ad-92e5-70e4cd9a9200)


Then if possible try to access the game and create an Episode 1 room and verify the main teleport only displays FOREST 1 (and not the other areas) to select, this is another flag that got enabled by SEGA to open all areas by default and got lost in the docs so i've been unable to find in the tethealla client to disable/enable it , and would really help me debug stuff like the offline story quests and Episode 2 yellow door issue at the lab


You guys are better than me at figuring stuff like this I honestly is very out of my current knowledge

**Comment by MADrewry** [comment]
@ShiftaDeband thanks for uploading @fuzziqersoftware's tool. I was aware that existed but could not find it myself. I just took a quick look at the source and it validated one of my thoughts on the PSOBB code. This may come in handy.

**Comment by nolrinale** [comment]
What is it you found out?

**Comment by MADrewry** [comment]
@nolrinale, Oh just some of the header info matched what I was seeing in the debugger so that makes me think I may be on the right track, or not too far off of it anyway. That was using 1.24.3 for my trials, but this code gives me a better idea of what to look for and where to look.

**Comment by MADrewry** [comment]
@nolrinale, using Fuzzi's launcher I was able to run this client and check the screens for you, but they are not as you expected. Take a look at the attached screenshots, you will see there is no Episode 4 subtitle, and I am able to go into all areas via the teleporter:
 
 
![psobb1](https://github.com/fuzziqersoftware/newserv/assets/40810747/60d8def6-98c1-4e5e-9a33-742659f8b2e3)
![psobb3](https://github.com/fuzziqersoftware/newserv/assets/40810747/887759b7-832d-4415-955e-4eab5367333e)

**Comment by ShiftaDeband** [comment]
For the specific Episode IV flag, you may want to look the the Episode IV DVD that was released at retail. I know its on Archive.org, this version was basically paid DLC that was free in the US. As you noted, I think it was free later in the PSOBB lifecycle, but I'm not sure they enabled the fancy Episode IV screen for this.

I have the disc as well if there's any issues, but I doubt that you'll have any.

(The following comes from memory and should be treated with a grain of salt.)

I know there are other flags that are undocumented. In the US, the client was released but only with Episode I. A little while later (week or month?), Episode II was released.

More time went by and Episode IV was released. This was also special in that each area, along with the respective government quests, were released at a time. When you'd get to the end of something like the Subterranean Desert, the warp to the next area would be fenced off.

I believe that each area _was_ in the client, and you could warp to 'restricted' areas by using something like Cheat Engine to progress. 

Regardless, I believe there should be flags to enable access to areas, probably on a per-level basis, and episodes as well. There's likely a very old US client out there that has these in them.

**Comment by nolrinale** [comment]
The EP IV screen appeared for everyone in the public client, in fact the picture I posted above is the same public client you downloaded from the archive copy.

What I think is happening here is that the one that controls which title screen appears and which one doesn't is the `online.exe` via special flag/argument, similar to how it also controls if it launchs the main game in game mode or credits mode.

As for the all areas opened I already confirmed they were also activated by the time sega posted this client in their site so might be necessary to keep checking for the hidden area switch in order to disable it. The client inside the Episode IV box which was also uploaded to the archive would be the best candidate to check for it https://archive.org/details/psobb

As for how EPIV was distributed I will explain for Japan and then for US

For JPBB,

The client initially launched with Episode I and Episode II only during the beta and for a while after the official service began, until late 2004 when EP IV launched as a very very short network trial, we began to receive EP IV assets via patch server but couldn't access them yet.

By the time formal EPIV was released (the box) you had to purchase it and inside there was a serial code you had to assign to your account via billing site, it changed your in-game name from white to golden and that meant you had the posibility to access Episode IV, at first you could only play with other orange name players, but during the PSO 5th anniv event they decided to make EP 1, 2 , 4 free for all and turned everyone in Orange names.

But since the very beginning it was 1 client for everyone it was all artificially limited via the serial code in the billing site.

for USBB:

USBB had a short beta with Episode I and II only, and by the time of the formal launch, they enabled EP IV, but this client was already the newest client we had in JPBB so it already had the EPIV assets preloaded into it, this is why you guys managed to hack it and teleport to the EPIV areas freely without much of an issue.

For this version SOA decided to maintain everyone with white names too as it wasnt necessary to do the extra step of getting an additional serial code to enable EPIV.

**Comment by MADrewry** [comment]
Ok, a bit of a surprise for me here: On a whim I decided to try and load PSOBB on a Windows 11 PC (using Fuzzi's launcher) To my surprise the boot screen came up with the Episode 4 subtitle. I was not able to go further because I currently don't have a connection to my server, but I am curious what is different about my Windows 11 install that triggered this, and what else may be different in-game. I will investigate further later this week when I get back to the home office.

![Episode4](https://github.com/fuzziqersoftware/newserv/assets/40810747/f90488a9-cfce-4f9a-8793-9c0f4ea0c983)

**Comment by MADrewry** [comment]
Thanks for that info, I was completely unaware of that behavior, I was wondering what the .pat version was used for. But that gives me something to investigate.

**Comment by nolrinale** [comment]
The .pat is how sega used to push client updates alongside other assets remotely in the patch update screen, in fact the patch server is capable of telling when the .pat file is being served, this is why after each patch the client closes entirely, then the online.exe would decompress and rename it into psobb.exe and start the game this all happens once you press GAME START in the launcher.

This launcher also requires for some reason to always have a psobb.exe present on it, even if it's an older version if you attempt to delete the original psobb.exe and leave only the .pat and start the game via the online.exe you will be presented witht he garbled text that just says that "It cannot find the original psobb.exe" 

The online.exe has different ways to start the game which I believe is what controls the title screens, there are other settings such as enabling the special login via the Hangame gateway as PSOBB was also distributed in Japan by Hangame as well, among other unknown stuff.

It might look like the online.exe is a simple program to start the game but I'm sure there's more than meets the eye with it too.

It's a relationship between psobb.pat, psobb.exe and online.exe

**Comment by nolrinale** [comment]
@MADrewry managed to launch the client under windows 10 and adjusted the HOST file to point to my server like the newserv readme says, but then I keep getting error 908 how did you managed to connect to your server with it? 

Im using these btw
```
127.0.0.1 psobb-ep4-db.segaonline.jp
127.0.0.1 psobb-ep4-patch.segaonline.jp
127.0.0.1 patch01.psobb.segaonline.jp
127.0.0.1 game01.psobb.segaonline.jp
```

**Comment by MADrewry** [comment]
I have the these additional entries in my host file:

db.psobb.cn
patch.psobb.cn
game01.us.segaonline.jp
patch01.us.segaonline.jp

I didn't think it was using any of those, as a packet trace only showed connection attempts to patch01.psobb.segaonline.jp, but those are all addresses I found in the file. give those a try anyway and see if that helps.

**Comment by nolrinale** [comment]
I tried it but didn't connected, I keep getting error 908

However I also tried to delete the exe and pat and just connect with the usual tethealla.exe that I know is working and I'm getting error 908 with that one too on Windows only, it connects to my server from Linux without issues.

I restored the host file to the default without any entry and now I cannot play under windows with neither the official nor tethealla...

**Comment by MADrewry** [comment]
I haven't tried running the server and client on the same box, so I'm not too sure. You may have to point your host file to the external IP of your box, and verify your newserv DNS settings as well.

**Comment by nolrinale** [comment]
Tried both in the main linux server and in the local one same thing 908, servers are all linux, is just the client running on windows

**Comment by nolrinale** [comment]
Alright the problem was with the ports in the config.json, i already sent a PR with the correct ones but you need to add these as the official client uses different ports than tethealla

```
    "bb-patch2":     [11100, "patch", "patch_server_bb"],
    "bb-init2":      [11101, "bb",    "login_server"],
```

**Comment by MADrewry** [comment]
Well that is curious. Mine has been working without those ports in my config.json. I wonder, is there something about Fuzzi's launcher that changes the client? How did you manage to run the client, are you using Fuzzi's launcher or another tool?

**Comment by nolrinale** [comment]
just the fuzzi launcher nothing else

**Comment by MADrewry** [comment]
Interesting. That makes me curious about my setup and why it's working. I may do a new clean setup and see what happens.

On a side note: after many frustrating unsuccessful attempts at unpacking the client via debuggers, I haven't been able to get past Gameguard yet so instead I managed to get a (mostly) unpacked client by running the client with Fuzzi's launcher, then dumping the process from memory to a file. Unfortunately I haven't been able to find the OEP of the original file and cannot fix the .dll imports correctly. So while I have an unpacked client it does not run because of missing .dll calls. I'm still taking potshots at cracking this puzzle as time permits but willing to take any advice anyone has.

**Comment by MADrewry** [comment]
I have managed to get a working version of the unpacked psobb.exe file. Although I can't take credit for it; after going bleary eyed looking at the code in the debugger I realized the answer was in front of me in an open tab on my browser the whole time: I had initially tried to use stripper to unpack the file, both the version fuzzi posted here and a newer version I already had. Both had failed so I abandoned the software and was looking at other methods. But syd had also created [this version](https://github.com/fuzziqersoftware/newserv/files/14075184/stripper_v207ht.zip) of stripper. The reference to it was sitting in an old forum post on an open page of my browser for days and I didn't notice it. I was able to locate the actual file via the wayback machine. This version successfully unpacked the file. So now we have a viable way of unpacking the file. I haven't posted the actual unpacked file because I am not sure if it is ok to do so here, but if fuzzi gives the go ahead I will upload it.

**Comment by nolrinale** [comment]
Please explain how to do it, just explaining the process how to do it from beginning to end is enough to document it. Is not necessary to post the unpacked file 

@fuzziqersoftware

**Comment by fuzziqersoftware** [comment]
It's fine to post the unpacked executable here. I can't promise I'll have time to figure out the GameGuard patch, but maybe someone else will be able to.

**Comment by MADrewry** [comment]
Here's the process I used to unpack the file:
This requires a 32 bit Windows OS, in my case I am using Windows XP Pro SP3 running in a VM. I am using Virtualbox on a LInux host to run my VMs. As a side note when using later versions of Virtualbox (past 5x) to run a VM you will not be able to actually run PSOBB in the Windows XP VM as the Virtualbox video driver no longer supports Direct3D. This tripped me up for a bit and I thought I had a bad PSOBB install. However if you attempt to run it and get the Gameguard window and error window pop up that is enough to show it is working.

In my XP VM I installed the PSOBB client as normal using the setup.exe.
I downloaded and extracted to it's own folder the version of stripper that I linked above. (v207ht)
I ran stripper.exe and loaded in PSOBB.EXE using the open dialog. I left all the settings at default and selected the "unpacking" button. After a few seconds the log showed a successful extraction of the file.
To test that I had a working version of PSOBB I copied the extracted file to a Windows 10 PC and ran it using fuzzi's launcher. I was able to attach to the server and create quests as normal.

An important note here, When I ran the extracted PSOBB the first time online.exe overwrote it with the .pat version, to prevent this you will need to move or delete the .pat version. Or you can extract the .pat version with stripper the same as above before running PSOBB.

The extracted file I got from this process runs and the code is viewable in a hex editor, however I noticed that opening in a debugger may complain that the entrypoint is outside of the code. 
I tried changing the options in stripper to see if any of them would make a difference to the extraction. but any of the other options either made no apparent difference or crashed strippper outright.

I hope this explanation is useful. Next steps for me (unless someone beats me to it) is to remove Gameguard and set the language switch to English

**Comment by nolrinale** [comment]
To complete the procedure it would be great to figure out the gameguard skip patch and the english switch setup, I think with these you guys should be able to enjoy the game with the vanilla client without any other weird issues beyond the ones that might remain to be fixed in the server side

**Comment by nolrinale** [comment]
Have you guys managed to discover anything new regarding the GG bypass or the ENG Lang switches? I've been unable to find the functions searching via the documented addresses.

I think the memory addresses might have shifted a bit since this is a different version so no clue, it's really out of my knowledge

**Comment by fuzziqersoftware** [comment]
The language function in the JP 1.25.11 client is identical to the function in the Tethealla client, except the call opcode at the beginning has a different offset. In the 1.25.11 client, search for E80319D9FF83F8017506B805000000C385C0750333C0C3B801000000C3 to find it. You can replace it with one of the values found in notes/psobb/english-client-setup.txt.

To disable GameGuard, it might suffice to search for 6844619900E8062307006878DC8400E8698BFEFF83C408C and replace the first byte with C3.

Fair warning - I did not test either of these.

**Comment by nolrinale** [comment]
I was able to find the first one but not the 2nd one... am I doing something wrong?

I'm searching for 6844619900E8062307006878DC8400E8698BFEFF83C408C to disable GG HxD says it cannot be found for some odd reason is the number correct?

**Comment by nolrinale** [comment]
This is all very interesting and is quite a very deep analisis and I'm sure @fuzziqersoftware will be glad to also have this information, however for the situation you mentioned, rather than creating a hook or DLL/external library of sorts and adding a extra file to keep track during the installation it seems to me that setting up PSOBB is becoming troublesome for some users already from other issue tickets i've been seeing, I came up with the idea to have a command that newserv can include that will pre-patch the original EXE with the most common basic settings to have the server up and running with the least headaches as possible for the final user.

I wrote more about it in this Feature Request
https://github.com/fuzziqersoftware/newserv/issues/442

I think for the overall users this should be a very simple setup that you can quickly provide the original psobb.exe and newserv does all the heavy lifting for you and spits out a fully functional psobb.exe ready to connect to your instance. How feasible this could be? I have no clue tbh...

But right now for the time being I think the most critical need would be to bypass the GG, set the client language and enable/disable IME. Even if its just modifying the classic way the client via hexedit we can provide the addreses in the notes folder for everyone to use in the meantime until an easier solution to setup PSOBB gets implemented later on.

Either way let us know if you manage to at least patch out the GG and run the game without it entirely! would be a huge win!, I already tried the language patch that fuzzi shared a few posts above and worked like a charm but sadly the GG is the most annoying step to overcome atm lol

**Comment by nolrinale** [comment]
Rather than discord, please continue explaining your whole approach here so the information doesnt get lost, as it might be another feasible solution to this and fuzzi can evaluate with you this approach too see if it can be included in the project or not.

**Comment by nolrinale** [comment]
4 files the final user has to keep track off vs 1 simple command that can auto generate a simple exe ready to run? well I think I would prefer the simple command option.

I also really dont like the idea of a custom .DLL being injected into the game at execution time as it can affect compatibility of the original game with older systems, on top of living in another repository that the final user will have to either download, or compile by themselves is yet another step that you are adding here that is not included in the default newserv installation.

The only benefit I see from this other approach is to just allow the game to be extendable with mods which I believe is the real reason why this approach exists in the first place.

**Comment by fuzziqersoftware** [comment]
This project intentionally does not sanction or endorse a specific PSOBB client; instead, we support almost all of the BB clients available on the Internet. I agree that it doesn't make sense for client modification tools to be part of this repository, since the use case of running a server or reverse-engineering the game vs. the use case of just playing the game are quite different, and this project focuses on the former. We accept client patches and notes on client internals under the reverse-engineering umbrella, but it makes sense for an installer/launcher to be a separate project in a separate repository. I'd be happy to link to such a project/repo in this project's readme and recommend it for new players.

**Comment by Repflez** [comment]
I am sorry for bumping this issue, but I saw this a few days ago when trying to spin up a newserv instance for local play and thought it would be interesting to make a way for the client to load without the need to edit the exe as stated earlier here. So far I made [this proxy dll](https://github.com/Repflez/AzureFlare) to make it work, but it only works with the unpacked exe [from this comment](https://github.com/fuzziqersoftware/newserv/issues/336#issuecomment-1913668701), as I'm not versed enough to work around ASProtect, but I hope it could work for the purposes of the issue.

**Comment by Repflez** [comment]
> You got around to this before I did! Either way, I am happy to lead you in the right direction with handling the packed binary and other items discussed above. Feel free to reach out to me on Discord (same username as here).

Hey @deviltti, I tried to contact you but I can't find you and neither I can't seem to add you as friend to contact you. I know this is not the place for personal issues, but still I wanted to let you know.

**Comment by Repflez** [comment]
I want to give an update to [my previous comment](https://github.com/fuzziqersoftware/newserv/issues/336#issuecomment-2059887891) about [my proxy dll](https://github.com/Repflez/AzureFlare) that it's now able to load an unmodified client like the one linked in the OP, and maybe other versions of the client (untested but in theory they should work). It also allows the same client to connect to a newserv instance just fine, like [how this comment from OP shows](https://github.com/fuzziqersoftware/newserv/issues/336#issuecomment-2010488617).

**Comment by nolrinale** [comment]
Congratulations guys, I guess I was too worried would be a solution with a weird launcher full of random tacky unneeded stuff (i really dont like custom crap lol) but looking at your repo and how you made it work it seems like its a very simple yet clean way to quickly set up the game.

Have you tried it on wine?, hopefully @fuzziqersoftware can check it out I think its a very simple method to set up the game which is kinda what I was hoping would be implemented on newserv.

And well hopefully can find the final switches to fix the IME issues and you can try the localization patch that fuzzi posted above that one works with 1.25.11 without issues, just make sure to load the game with all its required `_e` localized files so it doesnt crashes on you. 

I starred the repo too, the idea is excellent

**Comment by nolrinale** [comment]
I ran a quick test on Wine, I think I followed your instructions correctly but I just installed a fresh copy of the official client, and drag and dropped the 2 files of the launcher and replaced all the server strings with my server address and then I clicked the launcher.exe -> START GAME

The GG window appeared and I clicked cancel then the game sadly failed to launch
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/208355c0-dd3c-4a1a-ba5c-2d95e184e2fb)

**Comment by Matt-Swift** [comment]
To use custom .dlls on Wine, you have to use what is known as [DLL overrides](https://wiki.winehq.org/Wine_User%27s_Guide#DLL_Overrides).

In this case, you would need to tell Wine to use wsock32.dll as native, then builtin. They don't just work by being next to the executable.

**Comment by nolrinale** [comment]
What I like of this approach you guys decided to use is how invisible it feels, or at least, thats the impression I got when I tried to set it up over here, allowing the game to launch from its original launcher really makes it feel like its the real retail game working again.

And if for example a Japanese player requires the game in japanese, they can easily change the lang flag in the cfg and the game will naturally load all the assets in the desired language and vice versa with english, so you also remove the need of maintaining 2 exe's with different language settings.

If you happen to have a Linux machine or VM laying around give it a shot see if you can make it work over there too so we can test it out also on Wine (and on the Steam Deck)

**Comment by fuzziqersoftware** [comment]
I have added a reference to AzureFlare in the readme, which will help others get this set up as well.

**Comment by anzz1** [comment]
Is an unmodified 1.25.13 client available anywhere anymore? Or only the 1.25.11 one?
Are there any patch notes? Haven't been able to find any information whatsoever.

**Comment by fuzziqersoftware** [comment]
To my knowledge, the original 1.25.13 client isn't available anywhere on the Internet. There are a few different PSOBB installers on archive.org, but most don't say which version they are; you could try downloading and installing those to see if any are 1.25.13. I don't know what exactly the patches are in the Tethealla client either; I do know that the encryption algorithm was changed (newserv supports this, of course), GameGuard was disabled, and most of the Japanese language files were replaced with English language files. There may have been other patches too that I'm not aware of.

**Comment by anzz1** [comment]
Yeah I found this one https://archive.org/details/psosetup which is US 1.20.4, and some disc versions which I didn't try as I assumed they would not be the latest version.
There is also a chance that an installer for 1.25.13 never even existed, that maybe 1.25.11 was the latest setup and 1.25.13 never had one and was only distributed from the patch server as an update.

Someone must have the original 1.25.13 files saved though on their hard drive, which should be preserved before they're gone.
