### ISSUE TITLE
[Blue Burst] Cmode ranks/s-rank weapon aren't being updated in the Lobby after returning from cmode room

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#339]
**Describe the bug**
Pressing TAB whilst in the lobby cycles through different information from the characters including their cmode ranks, however upon completing Stage 1 cmode Episode 1 and earning a Ra-GOU rank this one isn't displayed at the lobby.

**Comment by nolrinale** [comment]
The issue persists even after the latest commits, what is happening is that you have to either relogin entirely from the game after returning to the lobby from the cmode room and after rejoining the lobby you will have your correct Rank displayed via TAB 

or

Create any room and leave back to lobby that works too 

It's possible this same behavior happens after earningt he S-rank weapon upon clearing the last Stage and returning to the lobby

**Comment by fuzziqersoftware** [comment]
This should be fixed by bd13950b.
