### ISSUE TITLE
PSO BB dressing room resetting player data

### ISSUE THREAD

**Issue by rumatsuki** [fuzziqersoftware/newserv#34]
After using the dressing room on the character select screen the character's inventory and bank contents get reset, EXP gets reset but not level. I'm not sure if this is intentional.

**Comment by fuzziqersoftware** [comment]
This should be fixed now.

**Comment by Gamizard** [comment]
It seems like inventory and bank no longer get wiped but EXP still does.

**Comment by fuzziqersoftware** [comment]
Sigh... I guess we just can't trust the client to do the right thing. This should be fixed now.

**Comment by Gamizard** [comment]
Apologies for not including this in my original comment, the person testing it found some problems after. Apparently after using the dressing room all of the items in their bank have broken displayed quantities, it says 10 according to them. Trying to withdraw all 10 just gives the correct quantity. I'll go compile the new commit now and test.

**Comment by Gamizard** [comment]
EXP no longer gets reset as of the latest commit.
