### ISSUE TITLE
[Blue Burst] Threading issues while more than 1 player access patch server affects players in-game

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#340]
**Describe the bug**
When theres a player connected to the server and another one is attempting to enter to the game but has to download a few patched files first, the game stops responding for everyone in the game ends up in Error 100, then both players get stuck at the patching screen if they attempt to relog at the same time. 

**To reproduce**

1. Connect to server
2. One player stays in the lobby whilst the other tries to download patched files at the patch screen
3. Player in-game begins to see weird behaviour such as the party window list not loading or directly getting Error 100
4. Attempting to relog might fail or might not fail with both players getting stuck at the patch download screen without being able to proceed

**Game version(s) (choose one or more of the following):**
BB

**Server log output**
Not sure if its required for this as I saw no error in the console

**Additional context**
Happens randomly

**Comment by ShiftaDeband** [comment]
Just noting that I believe this was noted as [an issue back here](https://github.com/fuzziqersoftware/newserv/issues/239) and it looks like the corresponding commit to resolve [was made here](https://github.com/fuzziqersoftware/newserv/commit/5192b5f615a6f21b78157cc72d50835b786beef6).

**Comment by nolrinale** [comment]
I have no clue it was very erratic, after a while we tried to login back and forth eventually we were able to start playing as usual but we were dealing with this for like 10 mins or so before starting the cmode session.

And i've been searching through the console anything related to an error of sorts but found nothing

**Comment by fuzziqersoftware** [comment]
The patch server sometimes requires some CPU-bound work to compute checksums for large files, which can block other clients. In general the server's single-threaded event-driven architecture works well for the game server, but not so well for serving patches. The solution is to split the patch server into a separate thread pool; I haven't gotten around to this yet.

**Comment by fuzziqersoftware** [comment]
This has been fixed by 1d42faac.
