### ISSUE TITLE
[newserv] Japanese text is not transpiled correctly by `decode-unicode-text-set`

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#346]
**Describe the bug**
The command `decode-unicode-text-set` is able to export the contents of the unitxt_e as a JSON correctly, however upon attempting to export the unitxt_j as a JSON the output ends up like this:

![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/6a91263d-adbe-4ff4-8218-901fdb0593ad)

**To reproduce**
Fill in steps to reproduce the behavior, such as:
1. run the command `decode-unicode-text-set` and export the unitxt_j.prs

**Game version(s) (choose one or more of the following):**
DC NTE, DC prototype, DC v1, DC v2, PC, GC Ep1&2, GC Ep3, Xbox, BB

**Comment by fuzziqersoftware** [comment]
This is technically correct behavior according to the JSON specification, but I agree it's not very useful if you want to edit non-English strings. The JSON parser can handle raw UTF-8, so I've updated the serializer to also support UTF-8 output. decode-unicode-text-set will now use that output mode.
