### ISSUE TITLE
[Blue Burst] Symbol Arts names are always initialized in English

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#349]
**Describe the bug**
If you create a new character using the client in Japanese mode the symbol arts assigned to that character are created with their english names, they should be initialized with their Japanese names instead, and vice versa in the case of the client in English mode (the current behavior) 

**Game version(s) (choose one or more of the following):**
BB

**Comment by fuzziqersoftware** [comment]
This has been fixed by 4e4ba565. All eight languages now have names for the default symbol chats, though I don't know how many of these are actually used in practice.

**Comment by nolrinale** [comment]
@fuzziqersoftware Checking in the japanese client and japanese char it seems to be it doesnt initialize all the symbols correctly, the first one which should be こんにちは is initialized as gibberish text
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/962b54df-2753-4ca1-8bcd-7b89a95139a7)

**Comment by fuzziqersoftware** [comment]
This one string had been accidentally double-encoded, and is now fixed.
