### ISSUE TITLE
Getting an error when making newserv

### ISSUE THREAD

**Issue by al3x78-777** [fuzziqersoftware/newserv#35]
Hello,

I'm getting the following errors using the make command for newserv:

[  2%] Building CXX object CMakeFiles/newserv.dir/src/ProxyCommands.cc.o
/home/devpi/newserv/src/ProxyCommands.cc: In function ‘HandlerResult process_server_60_62_6C_6D_C9_CB(std::shared_ptr<ServerState>, ProxyServer::LinkedSession&, uint16_t, uint32_t, std::string&)’:
/home/devpi/newserv/src/ProxyCommands.cc:691:24: error: comparison is always false due to limited range of data type [-Werror=type-limits]
  691 |     } else if (data[0] == -0x5E) { // A2
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/newserv.dir/build.make:368: CMakeFiles/newserv.dir/src/ProxyCommands.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/newserv.dir/all] Error 2
make: *** [Makefile:160: all] Error 2

I use to be able to build newserv on a raspberry pi with some of your older code. phosg is up and running so I'm not sure where the problem is. Any thoughts welcomed.

**Comment by fuzziqersoftware** [comment]
I had a similar error when writing that code, which is what led me to use -0x5E there in the first place. I pushed a change just now that should fix it for you. It's surprising that this error happens at all, though... presumably std::string's char_type should be char, which should be signed, so the existing code should work on all systems... right? One of those things must be false on a Raspberry Pi, I guess.

Oh well. Let me know if my change doesn't fix it.

**Comment by al3x78-777** [comment]
Thanks very much, all compiled and working now!
