### ISSUE TITLE
[Blue Burst] Level Up console stats are always in English

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#350]
**Describe the bug**
When you level up in the game you will notice on the right side of the screen a small console log appears displaying your newly improved stats such as ATA, ATP, DFP, MST, etc.

In the Japanese version of PSOBB and PSOGC/XB this console message should display the stats in Japanese (see the attached screenshot for reference) or you can check in PSOGC by setting the game to Japanese and leveling up too. 

攻撃力 = こうげきりょく = ATP	
防御力 = ぼうぎょりょく =DFP	
精神力 = せいしんりょく = MST	
命中力 = めいちゅうりょく = ATA	
回避力 = かいひりょく = EVP
運 = うん = LUCK

**Additional context**

![pso1186028553](https://github.com/fuzziqersoftware/newserv/assets/5244595/5944afa9-b9a4-45c5-9514-d27276e49293)

**Comment by fuzziqersoftware** [comment]
The level up stats delta message is generated by the client and is presumably based on the client's language setting; the server cannot affect this behavior.
