### ISSUE TITLE
[Blue Burst] [Feature Request] Extend Rare Notifications to use the PSOBB rare announcement system

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#354]
**Is your feature request related to a problem? Please describe.**
Extend the rare notification system to enable it as a global notification which scrolls at the top of the screen in PSOBB

Displaying firstly the Ship Name and Block/Lobby number, then the Room Name and lastly the Special Item name (see example below from the official server) 

I think this is a packet that includes all these fields and sends the message with this format automatically.

**Describe the solution you'd like**

Since this feature works across all ship every time a player get a certain rare this message will be broadcasted to everyone so I suggest to avoid less spam to limit it only for weapons of 10 star rarity or more (or configurable rarity via config.json)

And also configurable via config.json to disable it entirely

**Game version(s) (choose one or more of the following):**
BB

**Additional context**
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/5e4d8d51-3a85-4e78-aed3-cdbb58a3d676)

**Comment by fuzziqersoftware** [comment]
This has been added in acbebaeb. Rare notifications from NotifyGameForItemPrimaryIdentifiers and NotifyServerForItemPrimaryIdentifiers now use the scrolling message command on BB.
