### ISSUE TITLE
decode-gci-snapshot not working with Episode III Trial Edition screenshots

### ISSUE THREAD

**Issue by ShiftaDeband** [fuzziqersoftware/newserv#357]
**Describe the bug**
When trying to use the `decode-gci-snapshot` command with a PSO Episode III Trial Edition snapshot .gci file, newserv will return `libc++abi: terminating due to uncaught exception of type std::runtime_error: width is incorrect`

**To reproduce**
1. Create a snapshot file on the B memory card using PSO Episode III Trial
2. Export screenshot gci file
3. Try to decode the gci

**Game version(s):**
Seems to only impact the Episode III Trial Edition, not retail version.

**Server log output**
```
./newserv decode-gci-snapshot /Users/me/Desktop/8P-DPSJ-PSOC_SCREEN.gci

libc++abi: terminating due to uncaught exception of type std::runtime_error: width is incorrect
zsh: abort      ./newserv decode-gci-snapshot
```

**Additional context**
I was checking and backing up old memory cards in case any other download quests would be on them (like Game Informer was a couple years back) and stumbled upon an old screenshot file. I figured I'd use this utility to check if there was a screenshot on it. 

Unfortunately, it looks like it's the default image and nothing exciting.

I tested with a fresh/newly created screenshot and had the same result, but was able to get it to work with snapshots from Episode I&II and Episode III retail versions.

You can [download this very old screenshot here](http://shiftadeband.com/etc/8P-DPSJ-PSOC_SCREEN.gci) or generate your own if you'd like. The returned image seems to be this after testing on Dolphin:

![DPSJ8P_2024-01-26_00-32-43](https://github.com/fuzziqersoftware/newserv/assets/40249870/8eb44378-9550-4b83-80db-cda7dbea6f78)

**Comment by fuzziqersoftware** [comment]
I was afraid the format would be different or it would be encrypted, but it turns out the game just sets the width and height fields incorrectly, and the format is otherwise identical. I've fixed this in 90849102.
