### ISSUE TITLE
Choose default lobbies to drop players into

### ISSUE THREAD

**Issue by athendrix** [fuzziqersoftware/newserv#358]
I'd like to be able to add as an option in the config a default lobby to drop players on each system into.

For example, I might drop BB players into lobby 4 and Episode 3 into one of the CARD lobbies or something, to keep groups that can play together in different lobbies by default.

This would make a nice compliment to events too, for example, lobby 10 has a nice winter theme you can't get any other way, and it'd be nice to drop people there in the winter season.

Other lobbies also just look cool, and they're underused, and it'd be nice to mix things up. Maybe add a random lobby of the day option to keep things fresh all the time.

Alternatively, it might be nice to have a way to remap the lobbies or something. Though that may be more difficult.

All game versions
DC NTE, DC prototype, DC v1, DC v2, PC, GC Ep1&2, GC Ep3, Xbox, BB

**Comment by fuzziqersoftware** [comment]
This has been implemented; see the comments in config.example.json.
