### ISSUE TITLE
[Blue Burst] Saved cmode progress, time and ranks get deleted after a while again

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#359]
**Describe the bug**
We initially thought this got fixed in the latest commit mentioned here 
https://github.com/fuzziqersoftware/newserv/issues/337

The only thing that happened between these events was maybe playing with other characters doing quests in the meantime or restarting the server couple of times? 

**Game version(s) (choose one or more of the following):**
GC, Xbox, BB

**Comment by nolrinale** [comment]
We checked again and noticed the progress was deleted for my character TOUKA but not for Hana, in this case Hana's character is in Slot 1 and my character is in Slot 2 of the 4 slots available to create your character.

Could it be is not saving the cmode data to the correct slots other than slot 1???

![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/132476b5-0a58-44a7-8191-143bda0cb374)

**Comment by nolrinale** [comment]
@fuzziqersoftware have you managed to take a look at this one? It is a show stopper

**Comment by fuzziqersoftware** [comment]
I haven't been focused on BB recently, but this is the first issue I'll look at when I return to working on BB. In the meantime, you can use the the license flag to disable quest progression requirements, or temporarily edit the JSON files on the Challenge quests to not require the previous challenge to be completed.

**Comment by fuzziqersoftware** [comment]
This may have been fixed by bd13950b; I tested using $qcall but not by actually clearing a Challenge quest.

**Comment by nolrinale** [comment]
Will try to test it asap

**Comment by fuzziqersoftware** [comment]
I believe this has been fixed a while ago.
