### ISSUE TITLE
Issues running download quests in offline mode

### ISSUE THREAD

**Issue by RianovRV1** [fuzziqersoftware/newserv#36]
So far the server works perfectly as expected, got it running on my external IP with no issues with some port forwarding and running Ubuntu via Windows subsystem for Linux
Currently using real hardware.

The trouble I seem to be having is the game (PSO GC V1.01) cannot detect the quests on the memory card at all. They show up on the card with the correct description. but attempting to load them at the guild counter yields no results. Any thoughts on why this would be the case?

I have an action replay so if I need some special code to input it can be done.

**Comment by fuzziqersoftware** [comment]
It seems I broke this in a recent refactor. I've fixed it just now, so if you delete the unusable quest files, pull master, and rebuild newserv, you should be able to download working versions of the quests.

**Comment by RianovRV1** [comment]
Worked like a charm! 
performed a git pull master on the repo, 
reran cmake .
make
make install
rebooted the server and they work fine, thanks again for the fast work.
Come grab a burger with me sometime at St Johns.
