### ISSUE TITLE
Drawbacks not clear regarding new lobby customize feature

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#362]
In the latest feature added to the server, splitting lobbies in different events, how does this affects the original functions of the lobby event such as Easter, Xmas or Halloween that also affects in-game functions such as the special rappies that might appear while these events are running?

Also, the lobbies aren't implementing their complete behavior as the seasons shall include their specific quests tied to them, for example enabling the xmas/halloween lobby should instantly enable visibility for Pioneer Xmas/Halloween in EP2 Hunters Guild, whereas Valentines and White Day lobbies shall enable/disable their specific quests in EP1 if they are enabled or not. How this will work with this new feature?

However as a suggestion which probably wont be heard anyways, before commiting to modify the game too much,  try to evaluate the possible complications against the original game systems, I recommend to stay close to the vanilla behavior of the game if you mod the game too much might be difficult in the long run to debug stuff

**Comment by fuzziqersoftware** [comment]
The ability to have different events in different lobbies already existed with the $event command; the change was that individual lobby events are now configurable in config.json as well. It's still possible to change the entire server's event by changing all values in the config to the same event, or by using the $allevent command, so the previous functionality isn't lost.

Games inherit the holiday event from the lobby from which they were created. It's not possible to change the event of a game on the fly, unlike for lobbies, so we can't instantly update games when the lobby event changes.

Re: quest visibility based on events, this is not implemented, but seems like thing that would be useful; I'll leave this ticket open to track the implementation.

Re: vanilla behavior, one of the goals of this project is to preserve the game's vanilla behavior, but another is to provide a more modern experience. I try to support both, often via config options (as in this case), and these will both continue to be goals of the project going forward.

**Comment by fuzziqersoftware** [comment]
Events can now be used as quest visibility conditions.
