### ISSUE TITLE
[newserv] [Feature Request] disable/enable in-game commands for general usage via config.json

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#364]
I would like to have the option to disable via a small array certain commands in the server for the general player. Particularly commands like the common bank, change room password, server info, rare notifications, switch assist, etc. 

or if it's too difficult/annoying to implement a boolean to just disable all commands for normal players

**Comment by fuzziqersoftware** [comment]
It's still not clear to me why this would be useful, but I've added it anyway.
