### ISSUE TITLE
[BB] $edit secid greenill doesn't work

### ISSUE THREAD

**Issue by toiletman74** [fuzziqersoftware/newserv#366]
When you run that command it says no such id

**Comment by ShiftaDeband** [comment]
Try `Greennill`. (And oh my goodness, this is bringing me back to never being able to spell it. I'll check a client quick to be safe. [I don't even think Sonic Team had a consensus.](https://github.com/search?q=repo%3Afuzziqersoftware%2Fnewserv+greenill&type=code))

**Comment by fuzziqersoftware** [comment]
Sega was never good at language consistency.
![image](https://github.com/fuzziqersoftware/newserv/assets/187339/155ce018-391f-44c3-9e42-21ee611c481c)

I've now made the server accept both spellings for Greennill, just for ease of use.
