### ISSUE TITLE
[BB] Taking damage from a poison room doesn't sync hp across clients

### ISSUE THREAD

**Issue by toiletman74** [fuzziqersoftware/newserv#367]
Taking damage from a poison room doesn't sync hp across clients

So it will look as if your party member is taking no damage even though they're in the poison room and taking damage on their screen.

**Comment by fuzziqersoftware** [comment]
Where exactly did you observe this? (Which quest / free roam room?)

**Comment by toiletman74** [comment]
I believe it was free roam ruins. I'm not sure exactly which room, the next time it happens I'll write it down

**Comment by toiletman74** [comment]
I just ran into it again on Lower Seabed free roam Pattern 1 Variation 2 in the room with id 90
![seabedlowera2](https://github.com/fuzziqersoftware/newserv/assets/91436591/7ca2a55c-c962-49da-a686-aefd77eccc50)

**Comment by nolrinale** [comment]
@toiletman74 all these issues require the log of the whole session attached, these kind of command and client issues cannot be fixed without it. 

You can try VR Spaceship too for plenty of poison rooms

**Comment by nolrinale** [comment]
@fuzziqersoftware Tested this one in New Mod Up #3 poison room and indeed the 2P in either client isnt being affected by the poison.

[ClientPoisonTickNotWorking.txt](https://github.com/fuzziqersoftware/newserv/files/14472970/ClientPoisonTickNotWorking.txt)


![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/0e63d0ef-8bba-416a-a91c-2bce718b44b3)

**Comment by fuzziqersoftware** [comment]
This has been fixed by 3189b71d.
