### ISSUE TITLE
[BB] PB chain/donations aren't synched across clients

### ISSUE THREAD

**Issue by toiletman74** [fuzziqersoftware/newserv#369]
PB chain/donations aren't synched across clients. Example:
One person used twins, the other two donated. On the screen of the person who used twins, they saw no one donate. On the screens of both the donators they only saw themselves donate not the other. Also the shifta/deband levels match those situations.

Twins user:
![image](https://github.com/fuzziqersoftware/newserv/assets/91436591/b620e14b-4dd3-45b7-bc98-e4c5e719fd8b)

Donator 1:
![image](https://github.com/fuzziqersoftware/newserv/assets/91436591/04d5bfbd-5d60-49e6-a0ef-37177998ff08)

Donator 2:
![image](https://github.com/fuzziqersoftware/newserv/assets/91436591/c6b422e1-7c16-474f-8a66-353ad9b0b627)

**Comment by fuzziqersoftware** [comment]
Can you provide a server log for this? Issues are much easier to debug with the server output included.

**Comment by toiletman74** [comment]
which log settings do I need to have on to capture it?

**Comment by fuzziqersoftware** [comment]
If you have `"CommandData": "INFO"` in your config.json, the log should include the data I would need.

**Comment by Matt-Swift** [comment]
Since I'm aware that you run newserv in a tmux instance as advised, do the following to collect easy logs:
1. Create a folder called `logs` in the newserv directory
2. When you run newserv, run it with the following command `./newserv 2>&1 | tee >(multilog s10000000 n100 /path/to/newserv/logs)` (make sure to change `/path/to/newserv/logs` as appropriate, relative paths scare me so I haven't tried it, but it might work with just `logs`)

This will make all console output also be output to logs files in the `logs` folder, at a size of 10 MB per file, and up to 100 files (edit the s and n arguments if you want to change this). Once you reach 100 files in the log folder, it will delete the oldest ones.

If the command in step 2 doesn't work, you'll need to install `daemontools`

**Comment by toiletman74** [comment]
[current.txt](https://github.com/fuzziqersoftware/newserv/files/14135734/current.txt)
At the bottom here is where I did the PB and donation. The character called "twinkcast" did the PB and "shit rn" did the donation

**Comment by toiletman74** [comment]
After A little more testing it looks like PB chains work correctly just not donations

**Comment by nolrinale** [comment]
@toiletman74 This is a multistep test so requires to pay attention to a few things to ensure correct operation, if possible, could you check with your friends again the following?

- All players must have 100% PB gauge
- Mags have the correct/intended PBs, stats within their original parameters (level, synchro, etc)
- Player 1 attempts to do the first PB and the other players will donate by pressing Y button many times (the trailing sparkles should appear from their Nameplates pointing to the P1 Nameplate in the UI)
- All the players should benefit now of the increased stats bonuses (Everyone open the F12 menu and confirm the bonus stats)
- Bonus stats should dissapear once the PB effects are gone (the status effect badge) (again, everyone plz confirm via F12 menu)
- Attempt resurrection of a dead player via PB bonus donation. 

Additionally:
- Attempt to do different combinations of PB's and confirm correct operation of all their stats/effects against players or monsters
- Do a full chain PB and confirm all the effects/badges and stats changes via F12 menu.


And as usual, while performing this test make sure you are recording the whole log and if possible do it without the $debug flag on in-game, and post it here if you find anything strange, but as a rule of thumb it should be considered correct functionality if:

- UI effects behave correctly
- The improved stats are applied to all the players
- Dead players were resurrected
- Status ailments are removed

I honestly think these should work out of the box as this whole logic is usually handled by the client but i'm not sure at which point is handled by the client and which one is server side, but just in case lets do these tests. It's very difficult for me to find peers to try these so you are lucky to have a constant group that can play with you and check for these shenanigans with ease.

**Comment by nolrinale** [comment]
Will test later this specific one but seems related to https://github.com/fuzziqersoftware/newserv/issues/367

**Comment by fuzziqersoftware** [comment]
This has been fixed since 0de3d273. At the time this issue was opened, that commit wasn't included in any release, but it has since been included in the 2024-02-10 release.
