### ISSUE TITLE
[Dreamcast] [Feature Request] Allow certain serials to be flagged and not register a licence and be barred from using serial-based commands

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#370]
**Is your feature request related to a problem? Please describe.**
On the Dreamcast version of PSO, it's very common for people to have used shared serials for the entirety of their character's lives, as many people played the game without serials of their own, and the serial generators for Dreamcast are a relatively recent invention (props for that by the way).

What this means is that the people who have used shared serials for so long will struggle to get online, as the chance of their serial being used before on a public instance is very high, and it's likely for the access key to have not been used.

You can move your character to another serial, but unlike PC, this is a very lengthy process and players also most likely don't remember their old serials, so it's a bit of a non-starter for many people. With the Dreamcast itself also registering the serial, this means that moving to another serial is an even bigger process.

Instructions for people to fix this alone are at https://segaxtreme.net/resources/pso-tool-gui-by-razorx.224/ if anyone is to stumble across this.

**Describe the solution you'd like**
Ideally (if possible), it would be nice to be able to add a string of serials to config.json that will never generate a license file, and allow people to connect regardless of the access key. Of course, these players would need to be blocked from any serial-based commands like $savechar or $loadchar.

**Game version(s) (choose one or more of the following):**
DC NTE, DC Prototype, DC V1, DC V2

**Additional context**
This is a bit of a weird request and I understand if you don't want to do it - what's happened is that my public newserv instance got advertised on a public forum with some active Dreamcast players, and almost all of them ran into the Serial Number/Access Key issue and had to make new characters, which is not ideal.

Edit: I probably framed this issue badly, and just came out with an "idea", but basically some way for shared serials to co-exist, even if only for DC due to how serials work there, would solve the issue.

**Comment by fuzziqersoftware** [comment]
This has been added. The highest license flag (80000000) now marks a license as shared, which means anyone can log in with that serial number and any access key or password, but they will get a Guild Card number based on their access key and character name and they can't use $savechar or $loadchar. The flags field of the original license is used (so they will get any other permissions from the license, if you set any other flags) but no other fields are used - so they will always have 0 Meseta in Episode 3, for example.

I only had time to do a small amount of testing, so I'll leave this open until it's more well-tested.

**Comment by Matt-Swift** [comment]
I get the impression this works fine, as the group of players who had troubling playing prior are not having issues anymore.

Only forseeable issue I see is if moderation has to be taken against someone with a shared serial but I'll deal with that roadblock myself when I it happens!
