### ISSUE TITLE
Unable to build current server version on linux host

### ISSUE THREAD

**Issue by MADrewry** [fuzziqersoftware/newserv#373]
**Describe the bug**
Attempting to build latest newserv version on linux host generates the following error:

    /newserv1243/src/Episode3/Tournament.cc: In member function ‘void Episode3::TournamentIndex::save() const’:
    /newserv1243/src/Episode3/Tournament.cc:845:143: error: ‘ESCAPE_CONTROLS_ONLY’ is not a member of ‘JSON::SerializeOption’
      845 |   save_file(this->state_filename, json.serialize(JSON::SerializeOption::FORMAT | JSON::SerializeOption::HEX_INTEGERS | JSON::SerializeOption::ESCAPE_CONTROLS_ONLY));

**To reproduce**
1. git pull latest code
2. run cmake .
3. run make

**Comment by Matt-Swift** [comment]
Did you update [phosg](https://github.com/fuzziqersoftware/phosg)?

**Comment by MADrewry** [comment]
Nope, that's because I should have been sleeping after midnight instead of using brain cells. However, after installing the lastest phosg now it's even less happy. I get the following attempting to compile newserv. If it makes a difference this is on an aarch64 architecture:

/home/michael/newserv1243/src/FunctionCompiler.cc: In lambda function:
/home/michael/newserv1243/src/FunctionCompiler.cc:159:21: error: ‘AssembleResult’ is not a member of ‘EmulatorBase’
  159 |       EmulatorBase::AssembleResult ret;
      |                     ^~~~~~~~~~~~~~
/home/michael/newserv1243/src/FunctionCompiler.cc:162:77: error: no match for ‘operator=’ (operand types are ‘std::shared_ptr<CompiledFunctionCode>’ and ‘PPC32Emulator::AssembleResult’)
  162 |           ret = PPC32Emulator::assemble(load_file(asm_filename), get_include);
      |                                                                             ^
In file included from /usr/include/c++/10/memory:84,
                 from /home/michael/newserv1243/src/FunctionCompiler.hh:6,
                 from /home/michael/newserv1243/src/FunctionCompiler.cc:1:
/usr/include/c++/10/bits/shared_ptr.h:358:19: note: candidate: ‘std::shared_ptr<_Tp>& std::shared_ptr<_Tp>::operator=(const std::shared_ptr<_Tp>&) [with _Tp = CompiledFunctionCode]’
  358 |       shared_ptr& operator=(const shared_ptr&) noexcept = default;
      |                   ^~~~~~~~
/usr/include/c++/10/bits/shared_ptr.h:358:29: note:   no known conversion for argument 1 from ‘PPC32Emulator::AssembleResult’ to ‘const std::shared_ptr<CompiledFunctionCode>&’
  358 |       shared_ptr& operator=(const shared_ptr&) noexcept = default;
      |                             ^~~~~~~~~~~~~~~~~
/usr/include/c++/10/bits/shared_ptr.h:362:2: note: candidate: ‘template<class _Yp> std::shared_ptr<_Tp>::_Assignable<const std::shared_ptr<_Yp>&> std::shared_ptr<_Tp>::operator=(const std::shared_ptr<_Yp>&) [with _Yp = _Yp; _Tp = Compile
dFunctionCode]’
  362 |  operator=(const shared_ptr<_Yp>& __r) noexcept
      |  ^~~~~~~~
/usr/include/c++/10/bits/shared_ptr.h:362:2: note:   template argument deduction/substitution failed:
/home/michael/newserv1243/src/FunctionCompiler.cc:162:77: note:   ‘PPC32Emulator::AssembleResult’ is not derived from ‘const std::shared_ptr<_Tp>’
  162 |           ret = PPC32Emulator::assemble(load_file(asm_filename), get_include);
      |                                                                             ^
In file included from /usr/include/c++/10/memory:84,
                 from /home/michael/newserv1243/src/FunctionCompiler.hh:6,
                 from /home/michael/newserv1243/src/FunctionCompiler.cc:1:
/usr/include/c++/10/bits/shared_ptr.h:373:2: note: candidate: ‘template<class _Yp> std::shared_ptr<_Tp>::_Assignable<std::auto_ptr<_Up> > std::shared_ptr<_Tp>::operator=(std::auto_ptr<_Up>&&) [with _Yp = _Yp; _Tp = CompiledFunctionCode]’
  373 |  operator=(auto_ptr<_Yp>&& __r)
      |  ^~~~~~~~
/usr/include/c++/10/bits/shared_ptr.h:373:2: note:   template argument deduction/substitution failed:
/home/michael/newserv1243/src/FunctionCompiler.cc:162:77: note:   ‘PPC32Emulator::AssembleResult’ is not derived from ‘std::auto_ptr<_Up>’
  162 |           ret = PPC32Emulator::assemble(load_file(asm_filename), get_include);
      |                                                                             ^
In file included from /usr/include/c++/10/memory:84,
                 from /home/michael/newserv1243/src/FunctionCompiler.hh:6,
                 from /home/michael/newserv1243/src/FunctionCompiler.cc:1:
/usr/include/c++/10/bits/shared_ptr.h:382:7: note: candidate: ‘std::shared_ptr<_Tp>& std::shared_ptr<_Tp>::operator=(std::shared_ptr<_Tp>&&) [with _Tp = CompiledFunctionCode]’
  382 |       operator=(shared_ptr&& __r) noexcept
      |       ^~~~~~~~
/usr/include/c++/10/bits/shared_ptr.h:382:30: note:   no known conversion for argument 1 from ‘PPC32Emulator::AssembleResult’ to ‘std::shared_ptr<CompiledFunctionCode>&&’
  382 |       operator=(shared_ptr&& __r) noexcept
      |                 ~~~~~~~~~~~~~^~~
/usr/include/c++/10/bits/shared_ptr.h:390:2: note: candidate: ‘template<class _Yp> std::shared_ptr<_Tp>::_Assignable<std::shared_ptr<_Yp> > std::shared_ptr<_Tp>::operator=(std::shared_ptr<_Yp>&&) [with _Yp = _Yp; _Tp = CompiledFunctionCo
de]’
  390 |  operator=(shared_ptr<_Yp>&& __r) noexcept
      |  ^~~~~~~~
/usr/include/c++/10/bits/shared_ptr.h:390:2: note:   template argument deduction/substitution failed:
/home/michael/newserv1243/src/FunctionCompiler.cc:162:77: note:   ‘PPC32Emulator::AssembleResult’ is not derived from ‘std::shared_ptr<_Tp>’
  162 |           ret = PPC32Emulator::assemble(load_file(asm_filename), get_include);
      |                                                                             ^
In file included from /usr/include/c++/10/memory:84,
                 from /home/michael/newserv1243/src/FunctionCompiler.hh:6,
                 from /home/michael/newserv1243/src/FunctionCompiler.cc:1:
/usr/include/c++/10/bits/shared_ptr.h:398:2: note: candidate: ‘template<class _Yp, class _Del> std::shared_ptr<_Tp>::_Assignable<std::unique_ptr<_Up, _Ep> > std::shared_ptr<_Tp>::operator=(std::unique_ptr<_Up, _Ep>&&) [with _Yp = _Yp; _D
el = _Del; _Tp = CompiledFunctionCode]’
  398 |  operator=(unique_ptr<_Yp, _Del>&& __r)
      |  ^~~~~~~~
/usr/include/c++/10/bits/shared_ptr.h:398:2: note:   template argument deduction/substitution failed:
/home/michael/newserv1243/src/FunctionCompiler.cc:162:77: note:   ‘PPC32Emulator::AssembleResult’ is not derived from ‘std::unique_ptr<_Tp, _Dp>’
  162 |           ret = PPC32Emulator::assemble(load_file(asm_filename), get_include);
      |                                                                             ^
/home/michael/newserv1243/src/FunctionCompiler.cc:165:30: error: ‘assemble’ is not a member of ‘X86Emulator’
  165 |           ret = X86Emulator::assemble(load_file(asm_filename), get_include);
      |                              ^~~~~~~~
/home/michael/newserv1243/src/FunctionCompiler.cc:173:18: error: ‘class std::shared_ptr<CompiledFunctionCode>’ has no member named ‘code’
  173 |       return ret.code;
      |                  ^~~~
/home/michael/newserv1243/src/FunctionCompiler.cc: In function ‘std::shared_ptr<CompiledFunctionCode> compile_function_code(CompiledFunctionCode::Architecture, const string&, const string&, const string&)’:
/home/michael/newserv1243/src/FunctionCompiler.cc:182:17: error: ‘AssembleResult’ is not a member of ‘EmulatorBase’
  182 |   EmulatorBase::AssembleResult assembled;
      |                 ^~~~~~~~~~~~~~
/home/michael/newserv1243/src/FunctionCompiler.cc:184:5: error: ‘assembled’ was not declared in this scope
  184 |     assembled = PPC32Emulator::assemble(text, get_include);
      |     ^~~~~~~~~
/home/michael/newserv1243/src/FunctionCompiler.cc:186:5: error: ‘assembled’ was not declared in this scope
  186 |     assembled = X86Emulator::assemble(text, get_include);
      |     ^~~~~~~~~
/home/michael/newserv1243/src/FunctionCompiler.cc:186:30: error: ‘assemble’ is not a member of ‘X86Emulator’
  186 |     assembled = X86Emulator::assemble(text, get_include);
      |                              ^~~~~~~~
/home/michael/newserv1243/src/FunctionCompiler.cc:188:25: error: ‘assembled’ was not declared in this scope
  188 |   ret->code = std::move(assembled.code);
      |                         ^~~~~~~~~
make[2]: *** [CMakeFiles/newserv.dir/build.make:440: CMakeFiles/newserv.dir/src/FunctionCompiler.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/newserv.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
/usr/include/c++/10/bits/shared_ptr.h:382:7: note: candidate: ‘std::shared_ptr<_Tp>& std::shared_ptr<_Tp>::operator=(std::shared_ptr<_Tp>&&) [with _Tp = CompiledFunctionCode]’
  382 |       operator=(shared_ptr&& __r) noexcept
      |       ^~~~~~~~
/usr/include/c++/10/bits/shared_ptr.h:382:30: note:   no known conversion for argument 1 from ‘PPC32Emulator::AssembleResult’ to ‘std::shared_ptr<CompiledFunctionCode>&&’
  382 |       operator=(shared_ptr&& __r) noexcept
      |                 ~~~~~~~~~~~~~^~~
/usr/include/c++/10/bits/shared_ptr.h:390:2: note: candidate: ‘template<class _Yp> std::shared_ptr<_Tp>::_Assignable<std::shared_ptr<_Yp> > std::shared_ptr<_Tp>::operator=(std::shared_ptr<_Yp>&&) [with _Yp = _Yp; _Tp = CompiledFunctionCo
de]’
  390 |  operator=(shared_ptr<_Yp>&& __r) noexcept
      |  ^~~~~~~~
/usr/include/c++/10/bits/shared_ptr.h:390:2: note:   template argument deduction/substitution failed:
/home/michael/newserv1243/src/FunctionCompiler.cc:162:77: note:   ‘PPC32Emulator::AssembleResult’ is not derived from ‘std::shared_ptr<_Tp>’
  162 |           ret = PPC32Emulator::assemble(load_file(asm_filename), get_include);
      |                                                                             ^
In file included from /usr/include/c++/10/memory:84,
                 from /home/michael/newserv1243/src/FunctionCompiler.hh:6,
                 from /home/michael/newserv1243/src/FunctionCompiler.cc:1:
/usr/include/c++/10/bits/shared_ptr.h:398:2: note: candidate: ‘template<class _Yp, class _Del> std::shared_ptr<_Tp>::_Assignable<std::unique_ptr<_Up, _Ep> > std::shared_ptr<_Tp>::operator=(std::unique_ptr<_Up, _Ep>&&) [with _Yp = _Yp; _D
el = _Del; _Tp = CompiledFunctionCode]’
  398 |  operator=(unique_ptr<_Yp, _Del>&& __r)
      |  ^~~~~~~~
/usr/include/c++/10/bits/shared_ptr.h:398:2: note:   template argument deduction/substitution failed:
/home/michael/newserv1243/src/FunctionCompiler.cc:162:77: note:   ‘PPC32Emulator::AssembleResult’ is not derived from ‘std::unique_ptr<_Tp, _Dp>’
  162 |           ret = PPC32Emulator::assemble(load_file(asm_filename), get_include);
      |                                                                             ^
/home/michael/newserv1243/src/FunctionCompiler.cc:165:30: error: ‘assemble’ is not a member of ‘X86Emulator’
  165 |           ret = X86Emulator::assemble(load_file(asm_filename), get_include);
      |                              ^~~~~~~~
/home/michael/newserv1243/src/FunctionCompiler.cc:173:18: error: ‘class std::shared_ptr<CompiledFunctionCode>’ has no member named ‘code’
  173 |       return ret.code;
      |                  ^~~~
/home/michael/newserv1243/src/FunctionCompiler.cc: In function ‘std::shared_ptr<CompiledFunctionCode> compile_function_code(CompiledFunctionCode::Architecture, const string&, const string&, const string&)’:
/home/michael/newserv1243/src/FunctionCompiler.cc:182:17: error: ‘AssembleResult’ is not a member of ‘EmulatorBase’
  182 |   EmulatorBase::AssembleResult assembled;
      |                 ^~~~~~~~~~~~~~
/home/michael/newserv1243/src/FunctionCompiler.cc:184:5: error: ‘assembled’ was not declared in this scope
  184 |     assembled = PPC32Emulator::assemble(text, get_include);
      |     ^~~~~~~~~
/home/michael/newserv1243/src/FunctionCompiler.cc:186:5: error: ‘assembled’ was not declared in this scope
  186 |     assembled = X86Emulator::assemble(text, get_include);
      |     ^~~~~~~~~
/home/michael/newserv1243/src/FunctionCompiler.cc:186:30: error: ‘assemble’ is not a member of ‘X86Emulator’
  186 |     assembled = X86Emulator::assemble(text, get_include);
      |                              ^~~~~~~~
/home/michael/newserv1243/src/FunctionCompiler.cc:188:25: error: ‘assembled’ was not declared in this scope
  188 |   ret->code = std::move(assembled.code);
      |                         ^~~~~~~~~
make[2]: *** [CMakeFiles/newserv.dir/build.make:440: CMakeFiles/newserv.dir/src/FunctionCompiler.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/newserv.dir/all] Error 2
make: *** [Makefile:160: all] Error 2

**Comment by Matt-Swift** [comment]
Looks like you need to update [resource_dasm](https://github.com/fuzziqersoftware/resource_dasm) as those errors are directly related to it and when it had Xbox patch support added.

**Comment by MADrewry** [comment]
Yeah I noticed that shortly after posting my last comment. I forgot the No Computing Before Coffee rule. Definitely a PEBCAK issue. Everything is working as designed. Sorry to bother you with this.
