### ISSUE TITLE
[GameCube] Item not present error after retrying a Challenge stage

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#374]
**Describe the bug**
After retrying a Challenge stage and then using an item, the user is immediately disconnected. I suspect it probably occurs with other actions that track inventory.

**To reproduce**
1. Retry Challenge Stage
2. Use Monomate

It's possible a monomate has to be used before the retry as well so the inventory state is different.

**Game version(s) (choose one or more of the following):**
GC Ep1&2 (maybe others?)

**Server log output**
[itemnotpresent.txt](https://github.com/fuzziqersoftware/newserv/files/14159175/itemnotpresent.txt)

This log is from game creation to the error, although there's a lot of logs in the middle.

**Comment by fuzziqersoftware** [comment]
The server uses the 02DF command to know when a Challenge quest is retried, but that command doesn't exist on console versions, so it never recreated the player data overlays. This has been fixed; it now uses the 6x97 command for that purpose on non-BB versions.
