### ISSUE TITLE
[Dreamcast] backreference offset beyond beginning of output when downloading a Japanese quest

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#376]
**Describe the bug**
Trying to download a Japanese quest causes the above error. This happens regardless of language settings. Downloading an English quest in Spanish language for example also works.

This also only seems to happen on Dreamcast - on PC it downloads fine, on GC I didn't have the quests to test (oops).

**To reproduce**
1. Attempt to download a quest with Japanese characters in the title on Dreamcast

**Game version(s) (choose one or more of the following):**
DCv2, but might happen on others

**Server log output**
```
I 1197681 2024-02-07 17:30:11 - [Commands] Received from C-1F5 (version=DC_V2 command=10 flag=00)
0000 | 10 00 0C 00 55 01 01 55 46 00 00 00             |     U  UF       
W 1197681 2024-02-07 17:30:12 - [Server] Error processing client command: backreference offset beyond beginning of output
I 1197681 2024-02-07 17:30:12 - [Server] Client disconnected: C-1F5 on fd 44
I 1197681 2024-02-07 17:30:12 - [C-1F5] Deleted
```

**Comment by fuzziqersoftware** [comment]
Can you upload the relevant quest file(s), just in case I don't have them? It looks like the server is trying to decompress something that isn't valid PRS.

**Comment by Matt-Swift** [comment]
[Archive.zip](https://github.com/fuzziqersoftware/newserv/files/14199732/Archive.zip)
These should be part of newserv, they are Famitsu Cup, Dawn of e-Access, and Sunset at the Secret Base.

**Comment by fuzziqersoftware** [comment]
This has been fixed; I was able to download one of these quests (I forgot which one) and verified that the PVR file was downloaded along with it.
