### ISSUE TITLE
Instructions/Hints for Ephinea Client

### ISSUE THREAD

**Issue by TheCyberQuake** [fuzziqersoftware/newserv#377]
**Is your feature request related to a problem? Please describe.**
Write a clear and concise description of what the problem is. For example, "I'm always frustrated when [...]"
I would love details on what I need in order to get Ephinea client to connect without crashing. I know based on some closed issues that getting it to work is convoluted, but it's the only client I can find with "virtual fullscreen", which is the only way to get fullscreen working properly on my linux machine. I can pretty easily do any edits on both client or server, and I've tried but can't get it past crashing after patch server screen. Plus the ephinea client also has several QoL improvements that would be nice to have.

**Describe the solution you'd like**
Write a clear and concise description of what you want to happen.
Just some instructions at least pointing in the right direction of what to do to get ephinea client to connect without crashing.

**Game version(s) (choose one or more of the following):**
DC NTE, DC prototype, DC v1, DC v2, PC, GC Ep1&2, GC Ep3, Xbox, BB
BB

**Additional context**

**Comment by nolrinale** [comment]
That client is too heavily modified to work only with the Ephinea environments with custom DLLs and libraries bundled together, so your best bet would be to use the Tethealla client or the main vanilla client.

I actually run the game on linux via wine so if you require to play the game on full screen make sure to run wine in virtual desktop mode, set the game to run in a window at its maximum resolution of 1600x1200 and simply drag the window border all the way to the corner of your screen to fill the entire screen. 

Another alternative is changing your desktop main resolution to something below 1080p and attempt to run the game in full screen,wine will automatically stretch the game into a virtual desktop window which will cover all your screen as well. 

There might be other ways to run the game on full screen on linux but these are the ones I usually use havent had an problems with crashes either

**Comment by fuzziqersoftware** [comment]
This is a reasonable request, but there are a few reasons why we will not support the Ephinea client. The most important of these reasons is that supporting Ephinea's client would require reverse-engineering some of their custom modifications, and releasing the results of that as open-source would likely have negative effects on the existing community.

For QoL patches, you might find [Soly's BB patch project](https://github.com/Solybum/Blue-Burst-Patch-Project) useful. I don't know if a fullscreen patch is included there, though.
