### ISSUE TITLE
[Feature Request] [BB] Add configurable max stack size for x1, x10 classes of items.

### ISSUE THREAD

**Issue by PalasX** [fuzziqersoftware/newserv#378]
(https://github.com/fuzziqersoftware/newserv/issues/274#issuecomment-1907387165)
From this discussion, a helpful feature for the Blue Burst server would be having configurable max stack sizes.
It's done here in Teth's code:
https://github.com/PalasX/tethealla-cherry/blob/1d668dc5f2d3cac5a2edc94c4a4c6050b26c48db/src/ship_server/ship_server.c#L15066
There USED TO BE a whole thread about it on the Ephinia forums, but that got deleted for reasons unknown.

**Game version(s) (choose one or more of the following):**
BB

**Additional context**
I've been using Lee's PSOBB client patcher to impliment the client patches for the stack amounts. I can attach it here if needed.

**Comment by nolrinale** [comment]
In my opinion this deviates too much from the default behavior of the game, at this point is not a mod anymore but overriding a core part of the game system entirely with both client/server modifications in tandem.

I would just discard this idea entirely and enforce all the stacks to the default sizes no more nor less but again I don't call the shots here but I'm starting to see a very concerning snowball effect that might end up in the project getting derailed from the initial goal of an easy to use PSO server if these modifications continue to be added without second thought. (including polluting the config.json with more and more settings that will end up contradicting the easy to setup mantra)

**Comment by PalasX** [comment]
That's a very valid opinion. Upping the stack amount does have several cascade effects. You don't have to return to the ship nearly as often, you can have more than a total of 20 items between inventory and bank, and stacking materials means you can save and plan your mat usage more for the future instead of keeping track of them as you use them. It very much makes the game "easier" as well. Having a 99 stack of Sol Atomizers means that most other healing items are deprecated. Star and Moon atomizers make healing party members easier too, and can help mitigate the lack of a FOrce on the team.

Most of this can also be accomplished by using the $item command to spawn items directly, which is also an option that no one is forced to use. Leaving the config at default stack levels and not modifying the client is the easiest course of action, but giving the end user the choice would be a nice benefit, i think.

**Comment by fuzziqersoftware** [comment]
I've been clear about the goals of this project in other threads, and my position has not changed. newserv will support all vanilla behavior, and vanilla will be the default, but it will also support extensions and improvements that don't hide or prevent vanilla behavior. In this case, the presence of this feature would have no effect on servers that don't want to use it, so there is no reason to reject the idea. It's also a fairly common request, and a fairly common client modification, so we're going to add support for it.

That said, it might take a little while for me to implement this, since there are a couple of bugs ahead of it on my priority list.

**Comment by nolrinale** [comment]
Can you edit the title and change the tag to [Feature Request] ?

**Comment by fuzziqersoftware** [comment]
This has been implemented in 0383dc90. You can now override stack sizes for Meseta and tool items on any version of PSO (though I imagine this will only actually be useful for BB).

**Comment by PalasX** [comment]
Not to bump an old issue or anything, but i couldnt find this documented anywhere else.
These are the offsets in the Tethealla 12513 client for item stacks:
```
1x limit - 0x1D5857
10x limit - 0x1D5850
99x limit - 0x1D585E
```
When set to 1, 99, and 99 respectively, the hex is :
`63 00 00 00 5B C3 B8 01 00 00 00 5B C3 B8 63 00 00 00`

searching with the default values should help you find the offset in other clients if need be.

**Comment by fuzziqersoftware** [comment]
Thanks for sharing this finding. I wonder if this is something that https://github.com/Solybum/Blue-Burst-Patch-Project would accept as an addition?

**Comment by PalasX** [comment]
Maseta offset for same client is:
`Maseta 002C8E22`

Default is 3F 42 0F, which is 999,999dec

Ive noticed a weird side effect using Lee's Patcher 1.25.13, which is that all the red teleports auto-activate, instead of waiting for user input. The rest of the patches work as advertised, though i think the item stack patch on that program was incomplete? i vaguely remember it only working for inventory, and not for pickups or shops. The posted offsets for item stacking work as expected though.

I would do more A/B tests for each of the available patches in that program, but my x86 ASM is very weak, and edits such as "USA items" (which enables some extra items such as sonic team armor) and "full dressing room access" elude my understanding.

If it's okay, i've attached Lee's patcher here, in case anyone else wants to have a stab at documenting the various patch offsets.
[Pso Patch.zip](https://github.com/user-attachments/files/16500760/Pso.Patch.zip)

Additionall, i found my notes about draw distance modifications as well, at least for item/meseta objects and box/crates
```
0x001c3499 - float - item box and maseta draw distance - default 00004843hex, 200dec (modded to 800, 00004844)
0x0024d453 - float - box / crate view - default 300 float (modded to 800, 00004844)
```
looks like i also found the draw distance for the Savage Wolf mob:
`0x00520284 - float - wolf draw distance - default 310, 00009b43 hex`

I never found other objects like teleporters, buttons, doors, etc... Ideally i would've liked to find the function that checks for each of these and just have it return a constant instead of doing the actual lookup, but my ASM talents are woefully lacking.

Sorry if this got WAY off topic.

**Comment by PalasX** [comment]
> Thanks for sharing this finding. I wonder if this is something that https://github.com/Solybum/Blue-Burst-Patch-Project would accept as an addition?

Off topic, i could not get that project to compile either in Visual Studio or on linux with MinGW on an ubuntu 24lts distro. Did you have any luck? I'm submitting a bug report there, but the project isnt nearly as active as newserv.
