### ISSUE TITLE
[Episode 3 NTE] Unable to join open room if a battle has occurred previously

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#382]
**Describe the bug**
If a battle has occurred previously in a Trial Edition room, someone attempting to join will be disconnected, with the server reporting that a player cannot be added during a battle.

**To reproduce**
1. Play a battle
2. Have someone try to join after it ends

**Game version(s) (choose one or more of the following):**
Episode 3 NTE

**Server log output**
I could probably do with getting the battle end log here if it helps. This is a log of someone attempting to join.
```
I 1502953 2024-02-10 11:55:26 - [Commands] Received from C-17 (Matt) (version=GC_EP3_NTE command=10 flag=00)
0000 | 10 00 0C 00 44 00 00 44 16 00 00 00             |     D  D        
I 1502953 2024-02-10 11:55:26 - [C-17] Assigned inventory item IDs but did not mark IDs as used
[PlayerInventory] Meseta: 300
[PlayerInventory] 5 items
[PlayerInventory]    0: [+00000008] 00010000 00000000 00000000 (00210000) 00000000
[PlayerInventory]    1: [+00000008] 01010000 00000000 00000000 (00210001) 00000000
[PlayerInventory]    2: [+00000008] 02000500 F4010000 00000000 (00210002) 28000012
[PlayerInventory]    3: [+00000000] 03000000 00040000 00000000 (00210003) 00000000
[PlayerInventory]    4: [+00000000] 03010000 00040000 00000000 (00210004) 00000000
I 1502953 2024-02-10 11:55:26 - [C-17] Bank is empty
W 1502953 2024-02-10 11:55:26 - [Server] Error processing client command: cannot add player during battle
I 1502953 2024-02-10 11:55:26 - [Server] Client disconnected: C-17 on fd 39
```

**Comment by fuzziqersoftware** [comment]
This is caused by the battle recording not being cleared after the results screen on NTE. On Final, this happens when the next CA command is sent, but NTE doesn't send another CA command when loading into the Morgue. I've changed it to use 6F instead, which should fix this.
