### ISSUE TITLE
[BB] Error 100 on Connecting to Ship

### ISSUE THREAD

**Issue by KitBallard64** [fuzziqersoftware/newserv#383]
**Describe the bug**
Connecting from external IPs gives users Error 100 when selecting the "Go to Lobby" button.

**To reproduce**
*shrugs?*

**Game version(s) (choose one or more of the following):**
BB

**Server log output**
Not sure how far back I'll need to copy it...

**Additional context**
Seems this was the same error from before. Also, the dlls was missing from the official build so I pulled em from the previous one.
It could be possible I might of missed all the ports, since they are kind of everywhere in the doc ^_^¿

**Comment by ShiftaDeband** [comment]
My best guess is that you missed the port for your BB ship server. When using the default config, this port is `5112`. 

Is that port forwarded?

**Comment by KitBallard64** [comment]
5112? Crap I don't think so I'll check and edit this if I did or not.

**Comment by fuzziqersoftware** [comment]
Another thing to check: make sure ExternalAddress in config.json is set to the correct address (your public IPv4 address from e.g. https://www.whatismyip.com/).

**Comment by KitBallard64** [comment]
yeah that was the error. I some how missed port 5112 out of *all* of the other ports listed. Holy cow there's a lot. Solved!
