### ISSUE TITLE
[Episode 3] $dicerange issues

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#386]
**Describe the bug**
1. Looking at the source, $dicerange is looking for the d, a1, and d1 fields all at once or it will print back that dice ranges are reset to normal values (since it's `if no d, or if no d1, or if no a1`)
2. Successfully changing the dice (by doing all 3 fields, for example `$dicerange d:1-6 a1:4-6 d1:4-6`) will cause the solo member in a 2v1 to always roll 9-9 with a little glitchy graphic right before the role finalises.
3. Setting 2v1 dice ranges in rules has no effect if the regular dice is set to `FF`, but I suspect this might be unavoidable.

**To reproduce**
$dicerange entry:
1. Type `$dicerange d:1-6` for example and the server reports all values are set to normal.
2. The actual range you picked is not respected either.

Successful change:
1. Type `$dicerange d:1-6 a1:4-6 d1:4-6` and the server will report it's all fine
3. Play solo in a 2v1, see dice is always 9-9. Here is a 2v1 quest if you want to test: 
[q1001 - Nebula 1 2v1-e.bin.zip](https://github.com/fuzziqersoftware/newserv/files/14233056/q1001.-.Nebula.1.2v1-e.bin.zip)

Rules definition:
1. Change the quest rules to have something like 4-6 for the solo team with free dice rules (e.g. `FF FF` in the range fields)
2. Load as solo team in a 2v1, and see that your dice match whatever is set in the options. Here is a 2v1 quest like this if you want to test: 
[q1230 - Unguis Lapis 2v1-e.bin.zip](https://github.com/fuzziqersoftware/newserv/files/14233070/q1230.-.Unguis.Lapis.2v1-e.bin.zip)

**Game version(s) (choose one or more of the following):**
Episode 3

**Server log output**
I'm not sure what would be helpful here - command input, quest load, quest start, the roll itself? Let me know what would be useful and I will go fetch it.

**Additional context**
As an aside - it might be worth not using `:` as the character for the fields, as on a standard ASCII controller layout, this key is on the asterisk key on the numpad, which people emulating on Dolphin might not have access to if they have a 60% keyboard for example. It's accessible on the OSK of course, but `=` may be worth, as this is on `Shift+-` which people can find even if it might not be obvious; I have no great suggestions here.

**Comment by Matt-Swift** [comment]
We've been playing 2v1s since the fix for dice range, and it's actually been quite enjoyable being able to play Episode 3 with 3 players and not have the solo player just automatically lose (whether with or without COM), so thanks for that!

However, it does appear that the dice range set in the quest file is not respected since the fix, whether the rules for regular dice are set or FF.

**Comment by fuzziqersoftware** [comment]
It was originally a bug that the extended rules fields in the quest were respected at all, but I see how this could be a useful feature. I've changed the logic so that the quest's extended rules are used; if any fields are FF, then the fields from $dicerange's extended rules are used. (So for example, to disable 2v1 overrides in a quest, put zero in both of those fields in the Rules struct.)

**Comment by Matt-Swift** [comment]
This all seems to work as intended now, thanks for the feature, will be closing this issue.
