### ISSUE TITLE
Strange behavior in PSO GC parties when a player leaves

### ISSUE THREAD

**Issue by rumatsuki** [fuzziqersoftware/newserv#39]
It seems that whenever a player leaves a party, the rate of packets being sent slows to a crawl (compared to what it normally is). If the player reconnects, it returns to normal.

[Video of the problem](https://youtu.be/s5dipRfhYrM)

**Comment by fuzziqersoftware** [comment]
This led to an interesting discovery - I had assumed the 66 (leave game) and 69 (leave lobby) commands were the same, but they are actually different. In 66, there's an extra field that sets the disable_udp flag when a player leaves; newserv sends 0 there which enables UDP, which is not what we want (UDP is disabled everywhere else on newserv). This is fixed on master now.
