### ISSUE TITLE
[Blue Burst] Missing seasonal quests while setting Lobby Events

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#393]
**Describe the bug**

The functionality was added in a previous commit but I was never able to organize the correct order for all the event quests this is the updated list on how they should appear depending on which lobby event is enabled.

Valentine Lobby 

Valentine Day Quest (JP & EN)
https://qedit.info/index.php?title=BB:St._Valentine%27s_Day
https://qedit.info/index.php?title=BB:%E3%83%90%E3%83%AC%E3%83%B3%E3%82%BF%E3%82%A4%E3%83%B3%E3%82%A4%E3%83%99%E3%83%B3%E3%83%88

Category:
Episode 1 -> Solo Mode -> Event

Note: I don't know if solo mode currently supports the Event category but this quest should be enabled here.

Gallon's Shop (Valentine Edition) (Missing the english one)
https://qedit.info/index.php?title=BB:%E3%82%AC%E3%83%AD%E3%83%B3%E3%82%BA%E3%83%BB%E3%82%B7%E3%83%A7%E3%83%83%E3%83%97%EF%BC%88%E3%83%90%E3%83%AC%E3%83%B3%E3%82%BF%E3%82%A4%E3%83%B3%EF%BC%89

Note: It should disable the original Gallon Shop and replace it with the valentine event version.

Category:
Episode 2 -> Online Mode -> Shop

------------------------------------------------------

White Day Lobby

White Day Quest
https://qedit.info/index.php?title=BB:White_Day
https://qedit.info/index.php?title=BB:%E3%83%9B%E3%83%AF%E3%82%A4%E3%83%88%E3%83%87%E3%83%BC%E3%82%A4%E3%83%99%E3%83%B3%E3%83%88

Principals Gift (I can only find the original JP ver of this one but goes alongside White Day Quest)
https://qedit.info/index.php?title=BB:%E7%B7%8F%E7%9D%A3%E3%81%AE%E8%B4%88%E3%82%8A%E7%89%A9

Category:
Episode 1 -> Online Mode -> Event 

------------------------------------------------------

Summer Lobby

Festivity On The Beach
https://qedit.info/index.php?title=BB:Festivity_On_The_Beach
https://qedit.info/index.php?title=BB:%E6%B5%9C%E8%BE%BA%E3%81%AE%E7%A5%AD%E5%85%B8

Category:
Episode 2 -> Online Mode -> Event

------------------------------------------------------

Halloween Lobby

Pioneer Halloween
https://qedit.info/index.php?title=BB:Pioneer_Halloween
https://qedit.info/index.php?title=BB:%E3%83%91%E3%82%A4%E3%82%AA%E3%83%8B%E3%82%A2%E3%83%BB%E3%83%8F%E3%83%AD%E3%82%A6%E3%82%A3%E3%83%B3

Category:
Episode 2 -> Online Mode -> Event

------------------------------------------------------

Christmas Lobby

Pioneer Christmas
https://qedit.info/index.php?title=BB:Pioneer_Christmas
https://qedit.info/index.php?title=BB:%E3%83%91%E3%82%A4%E3%82%AA%E3%83%8B%E3%82%A2_%E3%82%AF%E3%83%AA%E3%82%B9%E3%83%9E%E3%82%B9

Category:
Episode 2 -> Online Mode -> Event

**Comment by fuzziqersoftware** [comment]
The metadata for these quests has been updated, except for Gallon's Shop, and the expression evaluator has been fixed. It should be easy to replace Gallon's Shop with the seasonal version, but only if it's available in all of the same languages (that is, we would need the English version of it too). If you come across the English version, please add it in a separate PR.
