### ISSUE TITLE
[newserv] [Feature Request] Schedule lobby events automatically via config.json

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#394]
**Is your feature request related to a problem? Please describe.**
To avoid manually setting up lobby events it would be great if you can set a defined date range for each one of them in the config json so the server knows when to enable/disable the lobby events/quests/monsters of that specific season automatically via fixed schedule.

Something like

New Years Lobby - From Jan 1st ~ Jan 15th
Valentines Lobby - Feb 1st ~ Feb 14th
White Day Lobby - March 1st ~ March 14th
Easter Lobby - March 20th ~ April 10th
Sakura Tree Lobby - April 11th ~ April 17th
Sakura Tree Lobby w/ Red & White Stripes Stage - April 18th ~ April 24th
Wedding Lobby - June 1st ~ June 30th *
Summer Lobby (Normal Lobby w/ Red & White Stripes Stage) - August 8th ~ August 27th
Autumm Lobby - September 28th ~ October 2nd
Halloween Lobby - October 16th ~ November 6th
Christmas Lobby - December 1st ~ December 25th

These dates are roughly the same ones used in the official servers for each one of the events so feel free to use them to preload the example config. 

*The wedding lobby is right now incorrect, the BB wedding lobby keeps the original decorations and original BGM of all the lobbies intact minus the decorations of the LOBBY 10 which spawns a huge white bell in the main stage and plays the Wedding BGM theme. 

![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/b47405a8-9101-419c-80b4-7b983c98022c)

**Comment by toiletman74** [comment]
This would be an awesome feature :O

**Comment by fuzziqersoftware** [comment]
I've decided not to implement this as a first-class feature in newserv. You can use an external script + signals to implement this, or change the config manually a few times per year.
