### ISSUE TITLE
[Blue Burst] Previously created Characters w/ Names >= 10 characters aren't being displayed anymore in-game

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#396]
**Describe the bug**
Character names whose length is the max allowed by BB (10 characters) created before the latest commits will end up with a weird symbol appended at the end making them 11 characters long and thus ending in the result shown in the screenshot below once they access in-game.

It seems to be this behavior was corrected by the latest commit, but at the price that any character previously created with japanese name or english name or a mixture of both with 10 chars long will end up with this weird corruption permanently.

The only way to fix this is by recreating the character from scratch and even if you decide to still have a 10 char long name the issue wont appear anymore, I tested this with the Tethealla and Vanilla clients with English and Japanese names alike.

**To reproduce**
Fill in steps to reproduce the behavior, such as:
1. If you happen to have a character with a 10 char length before the latest commit you will notice the corruption in the character select screen, the console output and the API output (posted example below).
2. Recreate the character with the same name and the issue should be fixed.

**Game version(s) (choose one or more of the following):**
 BB

**API Output**

The API returns this character name now as (notice the weird symbol appended at the end of the character making it 11 chars long) and the result in the screenshot below
```
{
    "ID": 35,
    "Class": "RAcaseal",
    "SerialNumber": 1647827165,
    "Name": "CELES-VSLI㠲",
    "Version": "BB_V4",
    "Language": "English",
    "Level": 5,
    "SectionID": "Oran",
    "LobbyID": 1
}
```

Tested again in 1.25.11 recreated the char from scratch and created a character with only japanese names, the weird appended symbol is gone and is still 10 char long

```
{
    "ID": 57,
    "Class": "RAcaseal",
    "SerialNumber": 1647827165,
    "Name": "☆すてら・ぷにぷに☆",
    "Version": "BB_V4",
    "Language": "Japanese",
    "Level": 1,
    "SectionID": "Greennill",
    "LobbyID": 1
}

```

**Additional context**
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/201cd3dc-32af-44f1-a292-bf3d727cd874)

**Comment by fuzziqersoftware** [comment]
This is likely fixed by 29baaf2d, but I don't have any existing players with long names and nonzero play time to test with.

**Comment by nolrinale** [comment]
I personally saw it fixed but I would like another person to chip in and let us know if the corruption dissappeared for your previous char....

**Comment by nolrinale** [comment]
Just verified with an old account I had with a very long japanese name character which got corrupted as well but didn't recreated the character, is not corrupted anymore after the latest commit https://github.com/fuzziqersoftware/newserv/commit/29baaf2d95cd808c88a5a197107398f20ec17d22
![Screenshot from 2024-02-22 11-39-34](https://github.com/fuzziqersoftware/newserv/assets/5244595/3a14f755-b9ae-4b8e-ab3a-0c3d6d7be688)



I'm closing this issue as fixed, if anyone by any chance still have this problem lets open a new ticket.

**Comment by MADrewry** [comment]
I know I'm late to the party here and commenting on another closed issue, but I just wanted to let you know that I confirmed that this is also working correctly on my old characters with 10 character names.
