### ISSUE TITLE
[Blue Burst] Player receives full EXP after tagging an enemy and letting an NPC kill them

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#397]
**Describe the bug**
In a quest where an NPCs that joins you to battle monsters like the Episode 4 solo quest "To The End of Wilderness" kills an enemy you had already tagged but not killed, you will end up receiving the full EXP bonus for the kill, despite the client saying you got less EXP as should be.

The correct behavior is, same as if you were playing with another player, if the other player is the one that does the kill they get the full exp and you get a lesser amount. 

**To reproduce**
Fill in steps to reproduce the behavior, such as:
1. Create an Episode 4 solo room and choose quest "To The end of Wilderness" (荒野の果てに)
2. Talk with ASH, BERNIE or RUPIKA to join your party, and then go down the teleport into the hunting area.
3. A few Bootas will appear, hit them once and let ASH finish them off
4. Notice you will get the full EXP for the kill if you enable $debug or check your F12 menu, whereas in the client you will see the correct EXP number popping out of the monster.

**Game version(s) (choose one or more of the following):**
BB, but maybe also GC and XBOX

**Additional context**
![Screenshot from 2024-02-20 17-12-54](https://github.com/fuzziqersoftware/newserv/assets/5244595/69d9be68-9be8-4a63-b271-f082f34bd5aa)
![Screenshot from 2024-02-20 17-15-50](https://github.com/fuzziqersoftware/newserv/assets/5244595/b8bd31e9-4642-496f-b76a-59c839adeebd)

**Comment by fuzziqersoftware** [comment]
This has been fixed.
