### ISSUE TITLE
[BB] Joining a party results in the party leader getting an error 100 on the latest commit

### ISSUE THREAD

**Issue by toiletman74** [fuzziqersoftware/newserv#398]
**Describe the bug**
Joining a party results in the party leader getting an error 100 on the latest commit

**To reproduce**
1. On player A create a party
2. On player B join the party
3. player A get 100'd
4. player A joins the party now that player B is the leader
5. player B gets 100'd

**Game version(s) (choose one or more of the following):**
BB

**Server log output**
[current.txt](https://github.com/fuzziqersoftware/newserv/files/14353299/current.txt) <- Log. I had falchion make the party and patra joins resulting in falchion getting an error 100

**Additional Info**
I was originally testing it with a client that has a fast loading patch, but I tested it again with a vanilla teth client and it gives the party leader a 100 as soon as the second player starts bursting

**Comment by toiletman74** [comment]
I tested again with commit e07f65eec5fc55dfba6bf162d901eadae4717872 and it does not give the party leader an error 100 upon joining the party

**Comment by nolrinale** [comment]
@toiletman74 Close the Ticket if its fixed please

**Comment by nolrinale** [comment]
Need to include the logs

**Comment by nolrinale** [comment]
@toiletman74 this one is fixed in the latest commit, can you please close this ticket?

**Comment by fuzziqersoftware** [comment]
This has been fixed by e2da4322.
