### ISSUE TITLE
Player.cc Compile Error

### ISSUE THREAD

**Issue by rotanigroc** [fuzziqersoftware/newserv#4]
Hi fuzziqer,

I just tried to make with the latest commit, but got a different compile error for the Player.cc file when using Ubuntu 18.04.3 LTS
`Player.cc:410:31: error: ‘<<’ in boolean context, did you mean ‘<’ ? [-Werror=int-in-bool-context]
   return (this->item_data1[0] << 16) || (this->item_data1[1] << 8) | this->item_data1[2];
          ~~~~~~~~~~~~~~~~~~~~~^~~~~~
cc1plus: all warnings being treated as errors
<builtin>: recipe for target 'Player.o' failed
make: *** [Player.o] Error 1`

I was able to resolve this by editing the file and changing line 410 to: 
`return (this->item_data1[0] < 16) || (this->item_data1[1] < 8) | this->item_data1[2];`

Also, I found another dependency you may want to call out in the readme: 'libevent-dev'.

Thanks for the hard work on this project.

**Comment by fuzziqersoftware** [comment]
Thanks for the report - strange that my compiler doesn't complain about that. Fixed in fa41dab1, and added libevent to the readme in 76c810c1.
