### ISSUE TITLE
[Blue Burst] Seabed Upper Levels always loads the same map variation for both online/solo games

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#402]
**Describe the bug**
It seems to affect specifically Seabed Upper Levels, it only loads 1 map variation of this area in both Online and Solo modes, in the case of Online mode always loads the Cross Hallway at the start variation and in Solo mode the one with the first room with 3 recoboxes (see screenies below)

**To reproduce**
Fill in steps to reproduce the behavior, such as:
1. Create a Online or Solo game EP2 any difficulty
2. Visit Seabed Upper Area ($warp 10 command)
3. Notice it never changes the variation of the map.

**Game version(s) (choose one or more of the following):**
BB

**Server log output**
[seabedUpperAreaCheck.txt](https://github.com/fuzziqersoftware/newserv/files/14389253/seabedUpperAreaCheck.txt)

**Additional context**
It always loads this one for Seabed Upper Online Mode
![Screenshot from 2024-02-23 20-11-48](https://github.com/fuzziqersoftware/newserv/assets/5244595/e3e8b72b-4bae-4041-ac09-686d975d786d)

And this one for Upper Solo Mode
![Screenshot from 2024-02-23 20-10-25](https://github.com/fuzziqersoftware/newserv/assets/5244595/cb32c8f3-bbff-4c35-b7fc-791c62aa2adf)

**Comment by nolrinale** [comment]
Why offer a command to override an internal system like this?

**Comment by fuzziqersoftware** [comment]
The $rand command is actually very important; I use it for debugging so I can see the behavior someone else saw, and it's used in replay testing so the replayed logs always see the same "random" behavior.
