### ISSUE TITLE
[newserv] [Feature Request] API endpoint to expose Drop Tables per version

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#403]
Create a new endpoint in the API to retrieve all the rare items drop tables for easier showcase via discord bots/websites

It would be a new endpoint called `y/drop-tables` that returns all tables for all versions, with the possibility of further refining it per version something like `y/drop-tables/bb-v4` to avoid overloading the server thread too much, it would then return the json with all the special item drop tables fields (item name, monster, rate, dar, area, difficulty, etc...) for this specific version.

**Comment by fuzziqersoftware** [comment]
This has been added. `/y/data/rare-tables` returns the list of available rare table names, and (for example) `/y/data/rare-tables/rare-table-v4` returns the contents of a specific rare table.
