### ISSUE TITLE
[GameCube] newserv appears to overload clients on the PPP stack to an unplayable state

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#404]
**Describe the bug**
When a client on the PPP stack using either Dolphin's tapserver modem or Devolution's emulated modem is connected in game and a lot of things start happening, the people on the PPP stack will indefinitely hang. (To be clear, Devolution was able to connect fine on the recently added `PPP_RAW` protocol)

Interestingly, they still send packets to the server fine, which are broadcasted immediately by the server, and things will happen on other clients that are not lagging, such as chat messages.

**To reproduce**
1. Get 3 players in the same lobby, with at least one connecting on a modem connection
2. Have all players run around for about 30 seconds
3. Players on modem will practically freeze network-wise

**Game version(s) (choose one or more of the following):**
GC NTE, GC Episode I & II, GC Episode III

**Server log output**
Would any of the logs on debug help at all? Currently only have a regular log of 6x40 / 6x42 packets which is not really useful.

**Additional context**
This might not be an issue with newserv and is more an issue with either the emulated modems or the Debian 12 VPS that is being used. The VPS itself has 1Gbps speeds with unlimited bandwidth, 2 vCores at 2.1 GHz, and 4 GB RAM. There are some other services running such as apache2, a search engine, an automated backup system etc...

Anyway, I put it here since it affected more than just the player on Dolphin or Devolution, but if it's not an issue with newserv itself, I can post this somewhere else / look into my VPS.

**Comment by fuzziqersoftware** [comment]
I believe this has been fixed by 14bf23c4, but will wait for others to confirm. That commit makes sending large commands to modem clients much faster, and it will apply to both tapserver and raw PPP connections.

**Comment by Matt-Swift** [comment]
I've given it a try and it's definitely not as bad as it used to be, but 4 player games are definitely completely unplayable.

You can definitely recover from a spike but multiplayer is not really possible right now.

**Comment by fuzziqersoftware** [comment]
Commit 2f5d547c may fix this, but I'll leave this open until you or someone else can confirm. We now only send TCP PSH frames when we've already received the last ACK from the client or the resend timeout expires. Before this change, we sent a PSH every time there was new data available from the server, and it seems AVE-TCP doesn't handle that well.

**Comment by Matt-Swift** [comment]
I gave this a try again with some other players, and everything seems to be working well, so can probably close this one, will mention if any issues.
