### ISSUE TITLE
[Xbox] Unable to compile Movement Patch

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#406]
**Describe the bug**
When the FunctionCompiler is compiling all the patches, it returns an unordered_map::at error for the movement patches.

**To reproduce**
1. Reload functions

**Game version(s) (choose one or more of the following):**
Xbox

**Server log output**
```
W 287187 2024-02-24 21:14:39 - [FunctionCompiler] Failed to compile function Movement.4OED.patch.s: (line 11) unordered_map::at                                                                                                             
W 287187 2024-02-24 21:14:39 - [FunctionCompiler] Failed to compile function Movement.4OEU.patch.s: (line 11) unordered_map::at                                                                                                             
W 287187 2024-02-24 21:14:39 - [FunctionCompiler] Failed to compile function Movement.4OJB.patch.s: (line 11) unordered_map::at                                                                                                             
W 287187 2024-02-24 21:14:39 - [FunctionCompiler] Failed to compile function Movement.4OJD.patch.s: (line 11) unordered_map::at                                                                                                             
W 287187 2024-02-24 21:14:39 - [FunctionCompiler] Failed to compile function Movement.4OJU.patch.s: (line 11) unordered_map::at                                                                                                             
W 287187 2024-02-24 21:14:39 - [FunctionCompiler] Failed to compile function Movement.4OPD.patch.s: (line 11) unordered_map::at                                                                                                             
W 287187 2024-02-24 21:14:39 - [FunctionCompiler] Failed to compile function Movement.4OPU.patch.s: (line 11) unordered_map::at  
```

**Additional context**
I rebuilt and re-installed phosg and resource_dasm just to be sure, and then rebuilt newserv, but the issue still persists.

I'm kind of suspecting this is due to something not working too well on Debian, which may explain why the item loss patch crashes me on Xemu as well.

**Comment by fuzziqersoftware** [comment]
This is because of an unpushed commit in resource_dasm that adds the `.deltaof` directive, which the movement patches use. I've pushed the relevant commit just now.

**Comment by fuzziqersoftware** [comment]
Re: the xemu crash on item loss patch, this might be possible to debug even though I can't reproduce it. xemu has support for gdbserver, so you can run `xemu -s` and then run `target remote localhost:1234` in gdb to connect to it. It might pause emulation when you connect; you can resume with the `c` command. Then when it crashes, hit ctrl-c if the gdb prompt hasn't appeared yet, and run `bt` to get a stacktrace, `info regs` to get the register values and `disassemble` to see the surrounding code. Hopefully the crash will be somewhere within the patch itself, and I'll be able to tell what's going on from the output of those commands.
