### ISSUE TITLE
Possible encryption algorithm differences with older PSO BB clients

### ISSUE THREAD

**Issue by Gamizard** [fuzziqersoftware/newserv#41]
I have a clean copy of PSO BB 1.20.4's data and a patched Tethealla client from the same version, when connecting I get a "none of the registered private keys are valid for this client" error. Are there any known ways to get the keys from the game executable?

**Comment by Gamizard** [comment]
After doing some looking with a hex editor I can find all of parts of tethealla.nsk in the game executable... not sure if the encryption algorithm was patched to make it easier or if newserv is at fault.

**Comment by Gamizard** [comment]
Just now tested it with a newer version of the client and it worked fine, seems more now that the algo was modified.

**Comment by fuzziqersoftware** [comment]
I think what's going on here is that 1.20.4 sends a shorter login command that newserv isn't expecting. Encryption detection works by attempting decryption with each private key until it finds one that successfully decrypts the first command sent by the client, resulting in the initial bytes B4 00 93 00 00 00 00 00. IIRC as of v1.20.4, the login command was shorter, so newserv should accept AC 00 93 00 00 00 00 00 as well. I made a change just now that might fix this... the 93 command handler looks like it should already work with the shorter login command format, but I haven't tested it.

**Comment by Gamizard** [comment]
Looks like that worked, thanks!
