### ISSUE TITLE
[Episode I & II] Incorrect item type for equip slot

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#410]
**Describe the bug**
A player was suddenly disconnected during Stage 9 of Challenge with the above error. The player was not actually sure what was occurring at the time - best guess is this occurred during a revive from a Scape Doll.

**To reproduce**
??? - Not actually sure

**Game version(s) (choose one or more of the following):**
GC Ep1&2

**Server log output**
Full log of the game to the error: 
[equip-slot.txt](https://github.com/fuzziqersoftware/newserv/files/14427100/equip-slot.txt)

Sorry it's not the best bug report - we didn't see this get reproduced.

**Comment by fuzziqersoftware** [comment]
This is a strange bug; the client's command says to equip a Cross Armor in the weapon slot, which is clearly wrong. I might just make the server ignore the client's chosen slot entirely unless the item is a unit... I'll get to this soon.

**Comment by fuzziqersoftware** [comment]
I didn't attempt to reproduce this, but I'm pretty sure it will be fixed by 424f191b.
