### ISSUE TITLE
[Blue Burst] Government Quests categories are not separated per Episode

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#413]
**Describe the bug**
Currently the Government Quest counters display all the categories regardless of episode selected, the correct behavior, similar to how if was fixed recently for Challenge Mode is that it should display only the Government Quest category of the current Episode the room was created.

- Hero in Red shall appear at Momoka's desk in Episode 1
- The Military Hero shall appear at Nol's desk in Episode 2
- Meteror Impact Accident shall appear at Momoka's desk in Episode 4

**Game version(s) (choose one or more of the following):**
 BB

**Additional context**
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/503ffa05-642f-4401-bd9b-9fa0cf91c6c5)

**Comment by fuzziqersoftware** [comment]
You can now specify in which categories quests should be filtered by episode. The default behavior is not to filter by episode except in the standard categories (so battle, challenge, solo, and government quests are available in all episodes by default), but you can change this by setting the high bit in the categories' flags in config.json.
