### ISSUE TITLE
[Blue Burst] Union Guard not applying defensive stats correctly

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#415]
**Describe the bug**
The Union Guard is a shield whose defensive stats increases dynamically depending on the amount of players currently enrolled in your Team, it also displays the Team Flag emblem and also has a Photon Color that changes dynamically depending on the Photon Jewel of the wielder.

The error in this case is that the system isnt applying the defense boost you get by having invited more members to your team. 

**To reproduce**
Fill in steps to reproduce the behavior, such as:
1. Create a Team in PSOBB and Purchase a Union Guard
2. Equip it preferably in a room with more than 2 players in the same Team
3. Verify the Union Guard DFP, it should increase depending on the amount of people you've invited to your team, in this case it stays in its default value of 155 DFP
4. Return to the Lobby and Dissolve the Team, create another room notice the union guard defensive stats remain the same. 

**Game version(s) (choose one or more of the following):**
 BB

**Additional context**
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/ef2b60f6-53ba-4415-b3a4-6ea7aaf9a0b9)

**Comment by fuzziqersoftware** [comment]
What exactly is the bug here? Is it that the shield color is wrong, the flag doesn't show, or the stat boost doesn't work?

**Comment by nolrinale** [comment]
I cannot purchase the union shield to try again all cases this one is blocking me https://github.com/fuzziqersoftware/newserv/issues/417

**Comment by nolrinale** [comment]
I tested the Item again just doing a $item UNION GUARD and can confirm it switches the color of the Photon correctly, and as far I know the Team Flag emblem display should work as well as its client side, the only thing I notice is not working are the stat changes. I tested with 1 member and with 2 members in the team. no change

**Comment by nolrinale** [comment]
@fuzziqersoftware  I will close the ticket as the behavior seems correct I suggest to remove from the config.example.json the TODO regarding this item in the team list and set the team system to provide the person purchasing the shield with the same ID as the one you get by typing $item UNION SHIELD

![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/cb9227ad-6265-40de-bbb7-dfef2e1fef4b)
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/0cda360b-cb79-4a58-abdc-c7a6254f2aed)
