### ISSUE TITLE
[Blue Burst] Player 1 gets Error 100 after another player joins the room

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#416]
**Describe the bug**
A regression in the Room system where If you try to access a room created by another player, you will join, but you will disconnect the host player with an error 100.

RELATED TO THIS
https://github.com/fuzziqersoftware/newserv/issues/398

**To reproduce**
Fill in steps to reproduce the behavior, such as:
1. Create any Episode room
2. A second player joins your room
3. You get an error 100 but the 2nd player is still in the room.
4. If you attempt to rejoin, you will disconnect the 2nd player and you will be in the room instead.

**Game version(s) (choose one or more of the following):**
 BB

**Server log output**

[2PRoomJoinError100.txt](https://github.com/fuzziqersoftware/newserv/files/14471113/2PRoomJoinError100.txt)

**Additional Context**
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/ccb27684-e86a-4a2f-80af-c0f86b6a6c29)

**Comment by nolrinale** [comment]
This issue blocks testing this other one https://github.com/fuzziqersoftware/newserv/issues/316

**Comment by fuzziqersoftware** [comment]
This has been fixed.
