### ISSUE TITLE
[DCNTE] Sending Guild Cards disconnects client

### ISSUE THREAD

**Issue by ShiftaDeband** [fuzziqersoftware/newserv#418]
**Describe the bug**
When a DC NTE client attempts to send a guild card to another player, the client disconnects. 

This behavior seems to affect clients with or without the temporary guild card setting enabled, `UseTemporaryLicensesForPrototypes`. Receiving guild cards from other versions works as expected. In addition, the `$gc` command works as well.

**To reproduce**
Fill in steps to reproduce the behavior, such as:
1. Connect to server with DC NTE.
2. With another player in the lobby, attempt to send a guild card to another player.
3. Be raptured.

**Game version(s):**
DC NTE

**Server log output**
Only including this snip as it seems to show what's occurring.
```
I 64128 2024-03-02 22:25:32 - [Commands] Received from C-13 (MacNalty) (version=DC_NTE command=62 flag=01)
0000 | 62 01 84 00 06 20 00 00 00 00 01 00 23 4A B2 0A | b           #J  
0010 | 4D 61 63 4E 61 6C 74 79 00 00 00 00 00 00 00 00 | MacNalty        
0020 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0030 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0040 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0050 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0060 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0070 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 |                 
0080 | 00 03 03 00                                     |                 
W 64128 2024-03-02 22:25:32 - [Server] Error processing client command: command too small (expected at least 0x84 bytes, received 0x80 bytes)
I 64128 2024-03-02 22:25:32 - [Server] Client disconnected: C-13 on fd 51
```

and another:

```
I 64196 2024-03-02 22:41:23 - [Commands] Received from C-D (CA) (version=DC_NTE command=62 flag=00)
0000 | 62 00 84 00 06 20 FA 8C 00 00 01 00 5D B4 9B 09 | b           ]   
0010 | 43 41 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | CA              
0020 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0030 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0040 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0050 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0060 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0070 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 |                 
0080 | 00 02 04 00                                     |                 
W 64196 2024-03-02 22:41:23 - [Server] Error processing client command: command too small (expected at least 0x84 bytes, received 0x80 bytes)
I 64196 2024-03-02 22:41:23 - [Server] Client disconnected: C-D on fd 51
```

**Additional context**
While I don't expect this to ever really be used, I'm submitting for the sake of completeness.

There was another issue with guild cards that I'm trying to reproduce -- I believe that had to do with language encoding being incorrect when sending a guild card from a Japanese client to an English one, but I cannot recall which version(s) were affected this at the moment.

EDIT: I felt pretty bad not adding full logs. [Here you go.](https://github.com/fuzziqersoftware/newserv/files/14471912/dcnte_gc.txt)

**Comment by fuzziqersoftware** [comment]
This has been fixed; I've tested sending Guild Cards between DC NTE and GC, and 11/2000 and GC in both directions. I've also tested Simple Mail in both directions in both scenarios. If you find a good repro case for the encoding issue, feel free to open another issue. (And it's fine to not include the full log for issues like these; generally if the misbehavior is localized to a single command and doesn't involve items or game state, all I really need to see is the command that caused the problem.)
