### ISSUE TITLE
[GameCube/Meta] The mysterious case of the ♥ character

### ISSUE THREAD

**Issue by ShiftaDeband** [fuzziqersoftware/newserv#419]
**Describe the bug**
The GameCube (and probably Xbox) Japanese on-screen keyboard includes a heart character. Back in the day, the other GameCube clients would be able to send and receive this character without an issue. On newserv, we are unable to send and receive this character due to iconv trying to parse it.

The character in question is `F0 40`, which is an invalid character code on the Shift-JIS [character](http://www.rikai.com/library/kanjitables/kanji_codes.sjis.shtml) [table](https://www.fileformat.info/info/charset/Shift_JIS/list.htm). When newserv calls iconv (and iconv tries to convert this character), it'll throw an exception. Using iconv locally to test this, we can see that this is the case:

```
echo '\xF0\x40' | iconv -f SHIFT_JIS -t UTF-8
iconv: iconv(): Illegal byte sequence
```

Since this character is not part of any official character table that I can see, it seems to always fail. That being said, the [UTF-8 character set](https://www.utf8-chartable.de/unicode-utf8-table.pl?start=9728&number=128&names=-&utf8=0x) includes a [heart character](https://www.compart.com/en/unicode/U+2665) `0xE2 0x99 0xA5`:

```
echo '\xE2\x99\xA5' | iconv -f UTF-8 -t UTF-8
♥
```

Of course, trying to change this to Shift JIS fails:

```
echo '\xE2\x99\xA5' | iconv -f UTF-8 -t SHIFT_JIS
iconv: iconv(): Illegal byte sequence
```

With all this being said, I'm not entirely sure that this character would still exist in other character sets. I'm more bringing it up just to see what solutions _could_ be done here.

For reference, I was able to add a small bit of code to change the character into a different, valid Shift JIS character, and that worked. However, there's really no suitable character in Shift JIS to replace it with.

One idea that I thought was to replace the character with a different Shift JIS character -- something that we'd never expect a client to send -- and then later re-replace that character with a heart in UTF-8, but I'm not sure the best way to proceed on this one. I also am not sure that this would work with other character encodings.

I also tried to use `//TRANSLIT` and `//TRANSLIT//IGNORE` which also didn't work.

**What this affects:**
When a game is created with the heart character, the game name is replaced with <?> as it cannot be converted.

When a chat message is sent, you'll see an error message both on the client and in the console.

I'm not sure what happens if this character is used in something like a guild card message, info board, etc.

**To reproduce**
Fill in steps to reproduce the behavior, such as:
1. Connect to server with a GameCube client in Japanese language (must not be GC NTE)
2. In the on-screen keyboard, select the heart and hit send.
3. See failed conversion message both on screen and in the console.

**Game version(s) (choose one or more of the following):**
GameCube mostly, thought it affects more than that depending on how it's solved. I would wager it's also on Xbox.

**Server log output**
[Whole log is here where we send a message and create a game with the character in question](https://github.com/fuzziqersoftware/newserv/files/14472082/gc_heart.txt). Here's the relevant snippet:

```
I 64448 2024-03-03 00:18:20 - [Commands] Received from C-2 (BZZZ) (version=GC_V3 command=06 flag=00)
0000 | 06 00 14 00 00 00 00 00 00 00 00 00 09 4A F0 40 |              J @
0010 | 00 00 00 00                                     |                 
W 64448 2024-03-03 00:18:20 - [C-2] Failed to decode chat message: untranslatable character at position 0
```

**Additional context**
This seems to be the _only_ character that doesn't work and/or get translated across all the versions I was able to test. The heart character seems to only exist on the GameCube versions (with the exception of the GC NTE).

When I tested sending this character to Dreamcast versions, I believe the NTE would display an empty character. I _believe_ that Dreamcast clients still displayed it, but I cannot recall at the moment.

**Comment by fuzziqersoftware** [comment]
Thanks for the detailed report! It seems that this is a vendor-specific extension to Shift-JIS, and is hopefully the only one in PSO. In TextTranscoder there is now an `on_untranslatable` function that can be used to handle custom sequences; I've implemented the heart symbol and verified that it works on PSO GC, and it also works when translated to UTF-16 for PC and BB clients. The heart symbol can't be translated to ISO8859, but I'm pretty sure it will never need to be - all clients that support ISO8859 also support Shift-JIS, and the server will use Shift-JIS (with the $J prefix) if the string can't be encoded in ISO8859. Still, if you see any place where this fix doesn't work, please do open another issue.
