### ISSUE TITLE
[Dreamcast/PC] [Feature Request] Ability to send different versions of quests to DCv2/PCv2 if DCv1 player in game

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#421]
**Is your feature request related to a problem? Please describe.**
Currently due to how things work, if crossplay is desired between V1/2 players in quests, the V2 quests must be made to match the V1 version 99% of the way, to avoid things like FSOD etc.

This means that if making a V2 quest, you can't do any unique V2 features with only V2 players if you want it to also be available for V1 players. You could do separate versions of quests but this would make the quest list very messy and possibly confusing.

**Describe the solution you'd like**
If a V1 player is in the room, can DCv2 receive the `d1` file instead, and perhaps a `p1` file can also be defined by server administrators that is sent to PC clients if a DCv1 player is in the room? I would guess that having the server take the DCv1 quest and re-encode would kind of suck - doing separate PCv1 quests is easy enough for administrators.

**Game version(s) (choose one or more of the following):**
DC V1, DC V2, PC

Thanks as usual. :upside_down_face:

**Comment by fuzziqersoftware** [comment]
Sending `d1` files to DCv2 clients is fairly easy, but implementing `p1` files would be somewhat tedious. Would it be OK to instead implement a cross-play condition in the JSON files, so you could have a V2-only version of the quest with something like `{"AvailableIf": "V_V1V2CrossPlay"}` in its JSON, and a V1-compatible version of the quest with `{"AvailableIf": "!V_V1V2CrossPlay"}`? This would mean that the two versions of the quest would need different numbers, but would be much easier to implement on the server side.

**Comment by Matt-Swift** [comment]
Yep, this is what I was suggesting actually.

**Comment by fuzziqersoftware** [comment]
I've added the V_V1Present token in JSON quest expressions, which evaluates to true if there's one or more V1 player in the game. Let me know if this allows you to get the behavior you want.
