### ISSUE TITLE
[newserv] [Feature Request] Print Devolution Phone Number somewhere.

### ISSUE THREAD

**Issue by ShiftaDeband** [fuzziqersoftware/newserv#422]
**Is your feature request related to a problem? Please describe.**
It's awesome to see that there's a new solution to getting Devolution to work without the need of another application like socat passing it off to pppd. 

I'd like to help simplify the process for getting a Devolution client set up with newserv for those who would wish to use Devolution (even though Nintendont is arguably better for most users.)

**Describe the solution you'd like**
If at all possible, I'd love it if there was an output during launch that would take the current configuration from `ppp_raw_addresses`, if present, and parse a valid IP address and port to a phone number. Of course, if it's not an IP address or invalid, do nothing.

Otherwise, other solutions would be fine if you're so inclined.

**Game version(s) (choose one or more of the following):**
GC Ep1&2 NTE, GC Ep1&2, GC Ep3 NTE, GC Ep3

**Additional context**
I noticed [this line](https://github.com/fuzziqersoftware/newserv/blob/0aedfcc17f87201e622e244b12e95321c6e3aa53/src/Main.cc#L2486) while trying to implement a solution:

`if (!state->ip_stack_addresses.empty() || !state->ppp_stack_addresses.empty()) {`

I believe this should be updated to:

`if (!state->ip_stack_addresses.empty() || !state->ppp_stack_addresses.empty() || !state->ppp_raw_addresses.empty()) {`

--

If you'd like to use/edit this and add it to your README (depending on whatever solution is implemented):

> ### PSO GC on a Wii/Wii U
> Using a Wii or Wii U to connect to newserv requires the Wii or vWii to be softmodded. Instructions on softmodding is beyond the scope of this document.
> 
> Nintendont includes BBA emulation and is compatible with all GameCube versions except the Episode I&II Trial Edition. To use, enable BBA emulation in Nintendont's settings and follow the instructions in [PSO GC on a real GameCube](#pso-gc-on-a-real-gamecube).
>
> Devolution includes modem emulation and is compatible with all GameCube versions including the Episode I&II Trial Edition. newserv can act as a PPP server for Devolution by enabling newserv's PPPRawListen according to the comments in config.json, starting newserv, and adjusting the game's network settings to dial out to the phone number output by newserv.

**Comment by Matt-Swift** [comment]
Just in case it isn't known, to create a Devolution phone number:

Convert your PPPRaw IP to decimal, then convert that to hexadecimal.
Convert your PPPRaw port to decimal, then convert that to hexadecimal.

Concatenate the two values (IP first, port second), then convert to decimal.

So, for an example, let's say you wanted to connect to 192.168.1.117:2572:

192.168.1.117 -> 3232235893 -> C0A80175
2572 -> A0C

Combine -> C0A80175A0C -> 13239238220300

**Comment by ShiftaDeband** [comment]
Thank you for that!

[I wrote up a small JS utility to do that as well before this feature was added](https://shiftadeband.github.io/Devolution-slirp-Modem-Emulation-Guide/phone-number-generator.html), but would love to make it as simple as possible without having to use any external tools (or math, oof) when possible.

**Comment by Matt-Swift** [comment]
I admit I wish I found your instructions on setting up socat and slirp for Devolution, I was struggling to figure out how to accept PPP connections and then fuzzi (bless him) decided to just add the PPP_RAW protocol, which just worked thankfully with both Dolphin and Devolution.

**Comment by fuzziqersoftware** [comment]
This has been implemented; thanks for writing up the instructions as well. I've also fixed the oversight you mentioned in the additional context section.
