### ISSUE TITLE
missing dll, cannot open newserv.exe

### ISSUE THREAD

**Issue by ButtonMash64** [fuzziqersoftware/newserv#429]
**Describe the bug**
hi im a newbie for create a private server, and try for pso newserv im missing one dll "cygevent-2-1-7.dll". because can't possible to open newser.exe :(

thanks for the help...

**Comment by ButtonMash64** [comment]
oh great thanks you very much for very fast response :)

**Comment by fuzziqersoftware** [comment]
I've published a new release that includes all the necessary dll files (notably, there were some new dependencies added recently).
