### ISSUE TITLE
PSO DC HELP

### ISSUE THREAD

**Issue by Gedehamsen021** [fuzziqersoftware/newserv#43]
after hours searching and test i cannot connect to the server, i already tried dns but no results

EMULATOR: flycast

**Comment by Gedehamsen021** [comment]
i just got "The line was disconnected due to network erro(s).
Please try connecting again later."

but DNS is fine all is fine

**Comment by Gedehamsen021** [comment]
![image](https://user-images.githubusercontent.com/25692637/189490360-639e1c01-a2e3-4faa-9d6e-b4284d3aadf8.png)
now this error, same in gamecube

**Comment by fuzziqersoftware** [comment]
I wrote a section in README.md about how to get Flycast to connect to a local newserv instance. The method described there works on macOS only, but the same concept should be possible on any OS using similar tools. For example, if you're using the Sylverant images, you can load PSO in Flycast, use Cheat Engine or scanmem to find all occurrences of "sylverant.net", and replace them with your machine's IP address (use its actual IP address - 127.0.0.1 won't work).

**Comment by Gedehamsen021** [comment]
i found this patcher and make some changes but i got only game over message instead connection error

https://github.com/Sylverant/pso_patcher

**Comment by sirdankz** [comment]
> i found this patcher and make some changes but i got only game over message instead connection error
> 
> https://github.com/Sylverant/pso_patcher

Flycast has build in DNS under the hood. 
To fix this you have to 
Step 1. delete the dc_flash.
Step 2. Edit the EMU.cfg file and edit the (DNS =xxx.xxx.xxx.xxx) to your
server and edit (Enable=yes)
Step 3. Right click on EMU.cfg. Go to properties then make the file (READ ONLY) and Apply.
Step 4.(may be optional not sure yet) Change the DNS in Quake3 to your server or using another way to edit the DNS save in the save file.

That should be all and you should be able to connect to your server after doing the steps above

**Comment by Gedehamsen021** [comment]
in the case my idea is make playable in android and IOS too

**Comment by sirdankz** [comment]
> in the case my idea is make playable in android and IOS too

You have to edit the files on those phones in a file manager or using your pc. Do the same thing as you would on flycast for pc. You just have to find the files.

**Comment by Gedehamsen021** [comment]
hi it's me again, the flycast method not working

**Comment by fuzziqersoftware** [comment]
The PSO DC instructions for Flycast have been updated recently and should now work on platforms other than macOS.
