### ISSUE TITLE
[Episode 3] Resta does not work on Hunter SCs that have items equipped

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#430]
title

**Comment by fuzziqersoftware** [comment]
I tested this online just now, and it seems to work. Are there any more details about the situation where it didn't work? Resta's targeting logic seems fairly straightforward, so the bug could be somewhere else in the code...

**Comment by Matt-Swift** [comment]
I haven't been able to replicate this at all, and it's been working fine online so unless I find reproduction steps, I'll keep this closed.
