### ISSUE TITLE
[Blue Burst] Selecting Patch Download ends in Error 906 cannot connect

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#431]
**Describe the bug**
Theres a regression in the latest commit where selecting "Patch Download" upon starting the BB client for the first time should download the required files from the server but now ended up in a disconnect error once again.

This was fixed many commits ago but it seems to be is back again.

**Comment by fuzziqersoftware** [comment]
I can't easily reproduce this. Can you post a log?

**Comment by nolrinale** [comment]
I was unable to reproduce it either again this morning, it's working now as intended in the local machine

I will clone the repo again just in case
