### ISSUE TITLE
[Blue Burst] command too large (expected at most 0x204 bytes, received 0x208 bytes) when joining a party

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#435]
**Describe the bug**
When attempting to join a party on Blue Burst, the above error will occur on the host's client and then they will be disconnected. The joining client will be booted back to lobby.

**To reproduce**
1. Create room
2. Join it

**Game version(s) (choose one or more of the following):**
BB

**Server log output**
[bbjoin.txt](https://github.com/fuzziqersoftware/newserv/files/14607382/bbjoin.txt)

**Comment by Matt-Swift** [comment]
Just a quick update to say that this is for all parties in BB (but you knew this already).

**Comment by fuzziqersoftware** [comment]
This has been fixed by d7783409.
