### ISSUE TITLE
[newserv] [Feature Request] Refine Party information window

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#437]
**Is your feature request related to a problem? Please describe.**
Currently the room information window looks like this
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/eec2acc6-0e50-4811-b729-2c02f8866a45)

It would be great if we could simplify this so it could match the official server style which is like this (at least for BB not sure if it was like this for PSOGC)
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/2662f27d-155d-4c90-a7fe-44f68004ff3c)

By default the fields to display should be:
[PLAYER NAME] (no color)
[Player Class] [Player Level] [Region] (no color)
[Start Time] (no color)
[Quest Name] (no color)

Since newserv also allows cheats pressing TAB again should then display additional fields like:
[Room Section ID] (no color)
[Cheats Status] (yellow color if ON or normal color if OFF) 
[any other information you consider important for debug and whatnot]

Information such as Episode, Game Type and Difficulty is already shown in the main table is not necessary to replicate it in the box

**Game version(s) (choose one or more of the following):**
DC NTE, DC prototype, DC v1, DC v2, PC, GC Ep1&2, GC Ep3, Xbox, BB

**Comment by fuzziqersoftware** [comment]
This has been implemented in 31edec70.
