### ISSUE TITLE
[newserv] [Feature Request] Display the required level to join a party in error prompt

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#438]
**Is your feature request related to a problem? Please describe.**
Currently, if a player creates a party for example in Ultimate Episode 1 and a lower level player attempts to join the lower level player sees the following window.

![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/5010425d-9a45-49bd-b12b-e152c02bb08b)

The correct situation to maintain the user experience is that this error prompt should tell the user the level required to join this room in this case it should be something among the lines of `you require level 90 to join this game` or something like that if possible would be great to change all these error messages to just plain white text as well.

**Comment by fuzziqersoftware** [comment]
This has been implemented in 31edec70.
