### ISSUE TITLE
[newserv] Choice Search returns junk data if no results, sometimes causing crashes

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#439]
**Describe the bug**
If using Choice Search and no results are found, the server sends back `04 00 C4 00` which lists No Player. However, the right-hand window displays nothing, or junk data which seems to be fetched from somewhere in memory.

Problem is, this sometimes causes the client to hard crash. This has been observed on PCv2, but perhaps it affects others.

**To reproduce**
1. Connect to server
2. Do a choice search
3. Get no results, look at right-hand window (or perhaps crash)

**Game version(s) (choose one or more of the following):**
PC

**Server log output**
This is just what the server is doing and probably not useful:
```
I 279819 2024-03-16 11:28:14 - [Commands] Received from C-338 (Matt) (version=PC_V2 command=C3 flag=00)
0000 | 1C 00 C3 00 00 00 00 00 01 00 00 00 02 00 00 00 |                  
0010 | 03 00 00 00 04 02 00 00 00 00 00 00             |                  
I 279819 2024-03-16 11:28:14 - [Commands] Sending to C-338 (Matt) (version=PC_V2 command=C4 flag=00)
0000 | 04 00 C4 00                                     |                  
```

**Additional context**
Here are a few images of what happens on the right window, I'm guessing that maybe the server should be sending something perhaps if no players are found for that window? PSO seems to want to display something.

First: Past Choice Search data is shown

![image](https://github.com/fuzziqersoftware/newserv/assets/33199242/d9507bb1-adc0-40d5-ad03-573a24a1774b)

Second: The trailing end of a chat message "hi matt" is shown in the window

![image](https://github.com/fuzziqersoftware/newserv/assets/33199242/c43419ad-5026-467a-b0b4-3720093f118e)

Third: Returning to lobby after the above caused Choice Search to show garbage

![image](https://github.com/fuzziqersoftware/newserv/assets/33199242/78b87544-3b0a-4ce2-b221-fd97ec8b4847)

**Comment by fuzziqersoftware** [comment]
This is a client bug; fortunately, it's easy to work around on the server side. This is done by 1a310df1.
