### ISSUE TITLE
[Episode 3] $saverec claims "No finished recording present" despite set Behaviour Flag

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#440]
**Describe the bug**
Despite having `Episode3BehaviorFlags` set to `0x0042`, `$saverec` currently throws out an error that no recording is present after a battle.

**To reproduce**
1. Finish Episode 3 battle
2. Use `$saverec`

**Game version(s) (choose one or more of the following):**
GC Ep3

**Server log output**
Will grab if needed but don't think it is!

**Additional context**
I had a rummage around and https://github.com/fuzziqersoftware/newserv/blob/1a310df17e29668a4a4c73b52863af2fa11c8f68/src/ServerState.cc#L761 seems a little strange to me, but I'm probably looking above my skill level here and this may not be related to the issue.

`this->ep3_behavior_flags = this->config_json->get_int("Episode3BehaviorFlags", false);`

get_int into a boolean (false) seems kinda weirdge.

**Comment by fuzziqersoftware** [comment]
I wasn't able to reproduce this, but I wonder if somehow the behavior flags field isn't being set properly for you. Do the other flags have any effect? (Maybe set to 0x00C2 and see if in-battle commands are sent without masking?)

**Comment by Matt-Swift** [comment]
This appears to have been fixed, but no actual clue why! Can't complain though.
