### ISSUE TITLE
[Blue Burst] Team Items can only be bought once

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#441]
**Describe the bug**
Purchasing Team Privileges which are Items such as the Commander Blade, Union Guard or the Team Point Tickets can be bought multiple times as long as there are enough points in the Team.

Currently this is not the case, as they are treated as a general team privilege (such as the Dressing Room, Member Extensions, Team Flag, Quests) which can only be bought once and their entry dissapears from the list entirely.

This is actually 2 bugs in one, the correct behavior is that the team privilege purchase window should always display all the privileges regardless if they have been bought or not, but greyed out if they had already been adquired in the case of team wide privilege.

And the Privileges that are Items can be purchased multiple times as long as you have enough points. 

**To reproduce**
Fill in steps to reproduce the behavior, such as:
1. Create a Team, Donate a few 5000 points with $item TEAM POINTS 5000
2. In the team menu at the lobby in the buying privileges window attempt to purchase the Union Guard, Commander Blade, or Team Points ticket
3. You will notice the entry of the item you bought had already dissapeared from the menu and thus you are unable to purchase it again for other team members

**Game version(s) (choose one or more of the following):**
BB

**Additional context**
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/59fe219a-32b9-4ba4-84bc-7fb1a014a0f3)
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/958992df-647a-435f-ae7b-2b6412ae796c)

The Items that can be bought multiple times
-Commander Blade
-Union Guard
-Union Field (this one was missing, it costs 100p like the Union Guard)
-Team Points Tickets

**Comment by fuzziqersoftware** [comment]
This has been fixed; item rewards may now be purchased multiple times. Union Field has also been added and the stat bonus effects of Union Field and Union Guard should now work too, though I did not test them.
