### ISSUE TITLE
[Episode 3] Necromancer error: array index out of bounds

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#444]
**Describe the bug**
A player attempted to use the 0108 "Necromancer" card, and was immediately disconnected with the above error.

**To reproduce**
1. Play the Necromancer card in a game

**Game version(s) (choose one or more of the following):**
GC Ep3

**Server log output**
[Necromancy.txt](https://github.com/fuzziqersoftware/newserv/files/14733651/Necromancy.txt)

Note that this log is quite long and has details from other versions/games on the server.

**Comment by fuzziqersoftware** [comment]
I wasn't able to reproduce this with a simple test, but from looking at the code, it appears `DeckState::draw_card_by_ref` is very broken when the card to be drawn is after the draw index (that is, the deck was just reshuffled), which is probably what happened in your case. I've rewritten the function to eliminate at least two bugs, and I think this is now fixed.

**Comment by Matt-Swift** [comment]
It might be a while before the scenario potentially comes up again, so I'll close this and re-open if for some reason it comes up again.
