### ISSUE TITLE
[Blue Burst] Quest 18 "Knowing One Heart" wont load client stays stuck at 100% progress

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#447]
**Describe the bug**
Attempting to load quest 18 Knowing One Heart from the Solo Mode EP1 story quests, the client begins loading the quest as usual but once it reaches 100% stays there stuck forever. Attached is the server console up to that point, the only solution is to quit the game or ALT+BACKSPACE to return to the title screen. 

**To reproduce**
Fill in steps to reproduce the behavior, such as:
1. Create Episode 1 Solo Room and load quest Knowing Ones Heart 
2. Will begin loading, then will stay stuck in 100%

**Game version(s) (choose one or more of the following):**
BB

**Server log output**
[quest18WontLoad.txt](https://github.com/fuzziqersoftware/newserv/files/14736895/quest18WontLoad.txt)

![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/7e6cb463-db73-4569-aa5d-88b22677329e)

**Comment by fuzziqersoftware** [comment]
There is a client bug that prevents a quest download from completing if one of the files' sizes is an exact multiple of 1024 bytes. cb05dce7 works around this issue.
