### ISSUE TITLE
[Blue Burst] Clearing Central Dome Fire Swirl doesn't mark the quest as Done (greyed out)

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#449]
**Describe the bug**
EP1 Solo Story quest Central Dome Fire Swirl once you clear it with the extended objective and return to lobby doesnt mark the quest as done like it should do with all the other Story Quests. 

The correct behavior is that the quest should be marked as done once it has been cleared. 

**To reproduce**
Fill in steps to reproduce the behavior, such as:
1. EP1 SOlo Room and Load Central Dome Fire Swirl
2. Finish the quest either with the normal or extended endings
3. Quest should appear Greyed Out like the other story mode quests once you complete them. 

**Game version(s) (choose one or more of the following):**
BB

**Comment by fuzziqersoftware** [comment]
I've heard conflicting information about this quest, and I don't know which is correct. At least one other person has said CDFS isn't supposed to be treated as a story quest (and hence shouldn't be grayed out). In GC PSO Plus, the unlocking criteria for CDFS are different, and in most versions before that, it's a download quest, so it can technically be unlocked at any time. It's possible they changed this in BB and it should be locked like the rest of the story quests; I haven't decided yet whether this should be the default behavior. I'll leave this open until I decide.

In the meantime, if you want to treat it as part of the main quest progression (and hence make it grayed out when completed, and require its completion along with all other quests to re-unlock it later), you can do the following:
1. In q026.json, add `"EnabledIf": "!F_009B || (F_0065 && F_0067 && F_0069 && F_006B && F_006D && F_006F && F_0071 && F_0073 && F_0075 && F_0077 && F_0079 && F_007B && F_007D && F_007F && F_0081 && F_0083 && F_0085 && F_0087 && F_0089 && F_008B && F_008D && F_008F && F_0091 && F_0093 && F_0095 && F_009B)"` (this makes CDFS grayed out if it's completed and not all of the other quests are completed)
2. In all the other json files with numbers lower than q026, add ` && F_009B` before the close parenthesis in `EnabledIf` (this adds CDFS to the set of quests which must be complete re-unlock the quest when the story is done)

**Comment by nolrinale** [comment]
Heres the video from the official server recorded back in 2009 
https://www.youtube.com/watch?v=mXPFTujavnU

In the Japanese Wiki and Fansites
https://wikiwiki.jp/psobb/%E3%82%AF%E3%82%A8%E3%82%B9%E3%83%88%E6%94%BB%E7%95%A5
https://seesaawiki.jp/w/c_lanje/d/%A5%B5%A5%A4%A5%C9%A5%B9%A5%C8%A1%BC%A5%EA%A1%BCEP1%B9%B6%CE%AC

**Comment by fuzziqersoftware** [comment]
These references show that CDFS was in the same category as the solo-story quests, but they don't show the unlock criteria or that it wasn't replayable until all other quests were cleared. Given the conflicting information, I'm going to leave the default as it is, but anyone who wants CDFS to behave like the other solo-story quests can make the changes I said above in their quest JSON files.

**Comment by nolrinale** [comment]
@fuzziqersoftware FYI
https://www.pioneer2.net/community/threads/side-story-quests-all-locked.22473/

**Comment by fuzziqersoftware** [comment]
I am not going to revisit this, even if Ephinea's behavior is different from the console versions. If you want to use Ephinea's behavior on your own instance of newserv, you are free to do so.

**Comment by nolrinale** [comment]
![](https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExamUxcHIybnc5NWpsNTNzNnFhaTlidm1vdDR4YjN4amFrc2c3Yjl6aSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3o6Zt2l7JNe272QpqM/giphy.gif)
