### ISSUE TITLE
Server Announcement for Level 200

### ISSUE THREAD

**Issue by LukaUrushibara** [fuzziqersoftware/newserv#454]
Requesting a feature for a server wide announcement across all versions that congratulates or makes note when a character hits level 200. Much like the rare drop system in #450 it should be bold and appear in all games and lobbies. 

Ideally it'd display somewhere the character name, guild card associated with it, and that this character is now level 200. 

Attached is an image from schtserv which has a similar feature.
![Screenshot_20240330_230526](https://github.com/fuzziqersoftware/newserv/assets/112583339/e2f03f93-eb95-4197-b63a-c695bdd5b438)

**Comment by fuzziqersoftware** [comment]
This has been added in d44b0b3d.
