### ISSUE TITLE
[Blue Burst] Mags dropped from containers should have the color of the current party leader's costume color

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#456]
**Describe the bug**
The Mags dropped by container boxes such as those in the Mines, shall always drop the mag color of the party leader current costume color.

After verifying the JPBB patch notes found here http://backup.segakore.fr/psobb.jp/news/maint32.html this change was added back in ver 1.12.2

**Game version(s) (choose one or more of the following):**
BB

**Comment by fuzziqersoftware** [comment]
I've decided not to implement this. Mags found in boxes will continue to have random colors.
