### ISSUE TITLE
[Xbox] Auto B2 patching

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#457]
**Describe the solution you'd like**
Would it be possible for the server to automatically send specific B2 patches when a player connects? Either defined by the server in config.json, or the license file of the player.

Ideally the latter would be "best" but I suspect that is work. The main consideration here is the item loss patch for Xbox, which is most widely used from server patches than executable patching, and I suspect many players would forget to apply it and then lose their items.

This could apply to other versions of course but Xbox is a bit more involved that people are less likely to do client patches.

**Game version(s) (choose one or more of the following):**
Xbox

**Comment by fuzziqersoftware** [comment]
This has been added. I've tested it on two versions of GC and one Xbox version, and it seems to work well. Patch settings are scoped to accounts, so they will apply to all versions that the account has licenses for.

**Comment by Matt-Swift** [comment]
From what I'm able to tell from other players testing, this seems to work quite well (other than some actual issues with patches). I'll close this and report individual issues if they occur.

Thanks a lot!
