### ISSUE TITLE
Implement option to enable auto EXP sharing on BB

### ISSUE THREAD

**Issue by fuzziqersoftware** [fuzziqersoftware/newserv#459]

**Comment by gortr** [comment]
This would definitely be an amazing feature to see added. Whether it be through a chat command, server config file or in-game like Ephinea does upon lobby setup. Definitely will be a nice QoL option for players.

**Comment by fuzziqersoftware** [comment]
This has been implemented. See BBEXPShareMultiplier in config.example.json for more information.
