### ISSUE TITLE
[Dreamcast V2] Japanese decryption files seem to be different (and therefore don't work)

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#469]
**Describe the bug**
Maybe I have a bad dump here, although I've tried a couple along with a couple of different ways to extract the data, but the Japanese version of Ver. 2 seems to have KATSUO.SEA and IWASHI.SEA files which are different sizes (both less than 1 KiB), not allowing the decryption to happen.

**To reproduce**
1. Extract data from JPv2
2. Attempt to decrypt executable with the appropriate files

**Game version(s) (choose one or more of the following):**
DCv2

**Server log output**
```
matt@debian-pc:~/Work/git/newserv$ ./newserv decrypt-dcv2-executable --executable=DP_ADDRESS.JPN --indexes=KATSUO.SEA --values=IWASHI.SEA
terminate called after throwing an instance of 'std::out_of_range'
  what():  end of string
Aborted (core dumped)
```

**Additional context**
That being said, I did try to use a re-encrypted KATSUO.SEA file along with the IWASHI.SEA file from a modified EUv2 ISO, and that seems to have actually worked to decrypt the file, although I'm a little worried this isn't going to work in the long run and I'm missing something here. (I haven't tried to repack with these larger files, suspecting it won't work)

Here's all the files from the root of the JPv2 disc: [Archive.zip](https://github.com/fuzziqersoftware/newserv/files/15137749/Archive.zip)

All in all, I'm mostly just suspecting this is a case of "bad extraction", but everything else seems intact so it is kind of weird.

**Comment by Matt-Swift** [comment]
Messed around a little more:

1. Using EU/US .SEA files straight doesn't work when decrypting
2. Using either EU/US .SEA files with one re-encrypted by newserv does work when decrypting
3. When re-encrypting using the same files in Step 2, if you just replace the executable on the disc (and leave the smaller .SEA files alone), it just works.

**Comment by fuzziqersoftware** [comment]
It appears that the Japanese version doesn't have any intermediate step; the encryption is just straight pr2. So for the Japanese version you should be able to use decompress-pr2 and compress-pr2 with DP_ADDRESS.JPN and not bother with the other files at all.

**Comment by Matt-Swift** [comment]
This does appear to be the case, what the hell did I make earlier then... ? Time to redo!
