### ISSUE TITLE
[newserv] Internal API segfaults server when calling any path

### ISSUE THREAD

**Issue by Repflez** [fuzziqersoftware/newserv#472]
**Describe the bug**
When calling the internal API server to get stats of the users, the entire server segfaults.

**To reproduce**
1. Start server
2. Call `/y/summary`
3. Server will segfault

**Game version(s) (choose one or more of the following):**
None

**Server log output**
None, terminal just outputs `Segmentation fault`

**Additional context**
Server was built from source on the latest commit (31616954cc47d6babc73e40cbcc9e25ffa587d61 at the time of writing this issue) in Debian 11.

**Comment by fuzziqersoftware** [comment]
The HTTP server assumes that the proxy server is enabled; if you have it disabled, it will crash. I've fixed this oversight in the latest push. If this doesn't fix the issue for you, please post your configuration file so I can reproduce the issue.

**Comment by Repflez** [comment]
It works now (using commit dfeeed2b1ad854c95f09662197dde71cdda98974), called the route and I haven't got another segfault. Will reopen if I experience this issue again, thanks for the quick fix!
