### ISSUE TITLE
[General] Ability to define specific quest numbers to be loaded with $quest without $debug

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#473]
**Is your feature request related to a problem? Please describe.**
I recently wrote a set of solo challenge quests for myself, but of course they cannot be loaded without a second client present due to the client-sided check for the quest counter.

**Describe the solution you'd like**
Rather than requiring any sort of client-side patches or B2 patching for the above specific scenario, a more elegant solution would be allowing players to use $quest for specific quest numbers only which are allowed to be remotely loaded; so in this instance, $quest 88111 would be allowed without $debug as an example providing other availability is met.

There may also be more use cases for this, although can't think of any off the top of my head (DC NTE can't remotely load quests, right?).

**Game version(s) (choose one or more of the following):**
DC NTE, DC prototype, DC v1, DC v2, PC, GC Ep1&2, GC Ep3, Xbox, BB

**Additional context**
Thanks as always :3

**Comment by fuzziqersoftware** [comment]
This has been implemented; see b88001.json for usage information.
