### ISSUE TITLE
[BB]Unable to connect full server

### ISSUE THREAD

**Issue by lazurit** [fuzziqersoftware/newserv#475]
**Describe the bug**
when connecting via the "Tethealla" client in localhost, it is not possible for me to connect to the server. I have information that the server is full

**To reproduce**
Fill in steps to reproduce the behavior, such as:
1. Connect to the server
2. register user
3. select the start game
4. error is displayed

**Game version(s) (choose one or more of the following):**
Client BB Tethealla 12510 and 12513

[server-log.txt.txt](https://github.com/fuzziqersoftware/newserv/files/15174938/server-log.txt.txt)

PS : sorry in advance for my basic English, I am French and not necessarily good with English, thank you for your help ^^

**Comment by Matt-Swift** [comment]
Looks to me like the server is trying to send you to 255.255.255.255, which is why it's not working. Did you change the LocalAddress field in your `config.json` file?

**Comment by lazurit** [comment]
oh my god... yes that's right, I left the field empty thinking that this was a default variable, thank you for your help !!!
