### ISSUE TITLE
[Blue Burst] Adjust the login process to silently update the quests languages depending on current client lang setting

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#476]
**Describe the bug**
With the new launcher for the official 1.25.11 client Repflez made shown here https://github.com/fuzziqersoftware/newserv/issues/336
It is now easier than ever to set up a working PSOBB client via a simple config file that easily switches between English/Japanese modes by adjusting a simple flag

However while creating a character in either Japanese mode (set 0) or English (set 1) the language setting remains permanent in that specific character (not the account), which affects the language of the quests being displayed in-game.

I am aware of the command $edit language but I wanted to know if it was possible to adjust the login process so it could somehow detect the current language flag and update the character lang settings on the fly without requiring a special account or yet another command more like a seamless thing being done in the background somehow that the player wouldn't notice or require to do as an extra step.

If its too difficult to implement another simpler solution to this would be to add maybe a Quest Language setting in the Lobby Overhead menu screen (where Go to Lobby and Disconnect appears) as an extra option for the player to decide which language they prefer to play their quests on.

**To reproduce**
Fill in steps to reproduce the behavior, such as:
1. Using the Repflez launcher and a stock 1.25.11 client edit the psobb.cfg with the language setting 0 for japanese 
2. The game starts in its default Japanese mode
3. Create a new character and go to the lobby verify quests in-game load in japanese
4. Close the game and edit the psobb.cfg this time to lang setting 1 for english, try again the previous steps the quests you will notice the quests are still in japanese for that previous character but if you create a brand new one or recreate that one the quests will appear in english

**Game version(s) (choose one or more of the following):**
BB

**Comment by fuzziqersoftware** [comment]
It would be fairly easy to override the character's saved language with the client's language every time a character is loaded, which I think will make the behavior more predictable/intuitive. I'll implement this soon.

**Comment by fuzziqersoftware** [comment]
This should be fixed by cf884559.

**Comment by nolrinale** [comment]
Amazing!!, can confirm it's working as intended, I will close this one
