### ISSUE TITLE
[Blue Burst] Evolving a Mag with a special kit and equipping it afterwards ends up in Error100

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#479]
**Describe the bug**
Got a Rappy Beak while playing EP4, decided to use it on my Ila mag which was lv 74, upon using the Rappy Beak the mag turned into a Rappy mag in the inventory, upon equipping the mag I got an Error100

After evolving the base mag DEF stat also changed and seems incorrect went from 5 to 2 and the level went down to 71(can see in the server output too).

**To reproduce**
Fill in steps to reproduce the behavior, such as:
1. Use a Rappy Beak in a high level mag
2. The mag turns into a Rappy mag
4. Equip the mag and get Error 100

**Game version(s) (choose one or more of the following):**
BB

**Server log output**
[MagUnitEvolveError100.txt](https://github.com/fuzziqersoftware/newserv/files/15211269/MagUnitEvolveError100.txt)

**Additional context**
Logging back on I can equip/unequip the mag normally

**Comment by fuzziqersoftware** [comment]
This has been fixed. The client's logic for when an item is unequipped while applying an item combination is inconsistent; it seems most combinations actually unequip the item, but some do not. I did not test all the possible combinations; there are 406 of them.

**Comment by nolrinale** [comment]
Did it also affected the mag level getting downgraded and the base stats changing?

**Comment by fuzziqersoftware** [comment]
That has also been fixed now.
