### ISSUE TITLE
[Episode I & II] Incorrect icon used at quest category menu

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#480]
**Describe the bug**
I was mooching around and saw a video from vanilla which looked like this (glorious 240p!):

![image](https://github.com/fuzziqersoftware/newserv/assets/33199242/73f8d574-bcfc-4c16-a8c6-dfdb22864a26)

However, the quest category menu uses the incorrect icons when accessing it on newserv, as below:

![image](https://github.com/fuzziqersoftware/newserv/assets/33199242/0e53e301-6d5b-495d-9000-a24122cd8aed)

Interestingly, the download quest menu uses the correct icon for categories.

**Game version(s) (choose one or more of the following):**
GC Ep1&2, Xbox

**Additional context**
This may also be a problem on Blue Burst. Unfortunately without the correct icon, the game is unplayable. :/

Just kidding, this is whatever and just something I felt like writing down when I saw it lol

**Comment by nolrinale** [comment]
This is correct, for the categories should be these arrows 
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/cd665781-f04f-445f-affa-01b0cfe4e709)

for EP1 quests the current green square arrows no need to change those

and for the EP2 and EP4 quests the orange square arrows like these
![pso1198075787](https://github.com/fuzziqersoftware/newserv/assets/5244595/98d82139-35cf-44f5-9c1f-4bd4136a26e8)

**Comment by fuzziqersoftware** [comment]
This has been fixed.
