### ISSUE TITLE
[newserv] Quest disassembler appears to have issues with diacritics (é, ö, ç, etc) for GC quests

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#481]
**Describe the bug**
When disassembling GC quests (maybe others, but DC seems fine), the console spits out an error saying there are untranslatable characters, and they will appear as junk in the quest script disasm.

**To reproduce**
1. `./newserv disassemble-quest-script qXXX-gc.bin --gc`
2. Observe the disasm

**Server log output**
Here's some examples of what the console outputs:

```
W 17581 2024-05-05 13:06:27 - Undecodable text: untranslatable character at position 30
W 17581 2024-05-05 13:06:27 - Undecodable text: untranslatable character at position 35
```

**Additional context**
Here's Magnitude of Metal from DCv1 and GC, with their disasms next to them: [q001.zip](https://github.com/fuzziqersoftware/newserv/files/15212882/q001.zip)

**Comment by fuzziqersoftware** [comment]
This quest has its language field in the header set to Japanese, which is why the strings decode incorrectly. I've added a --language option in disassemble-quest-script, so you can pass e.g. --language=4 for Spanish, and these will disassemble correctly.
