### ISSUE TITLE
[Feature request] Removing class/gender/race restrictions

### ISSUE THREAD

**Issue by user18081972** [fuzziqersoftware/newserv#482]
**Is your feature request related to a problem? Please describe.**
I would like to remove class restrictions.
Or in some other way shape or form, play as a class, that can equip any weapon, item, and cast any spell.

Basically, i wanna be able to play through the game with 1 character in 1 play-through, and be able to experience all items and play styles.

**Describe the solution you'd like**
Removing the restrictions on the weapon item side.
Or flagging a class as human,newman,android,male,female all at once.

**Game version(s) (choose one or more of the following):**
BB

**Comment by fuzziqersoftware** [comment]
Item equip restrictions are handled by the client; the server does not check these flags. If you're using PSOBB TethVer12513, you can disable equip restrictions by opening psobb.exe in a hex editor, searching for 33FF85C00F84FC01000083F8010F84C9000000, and replacing it with 33FFE9A700000001000083F8010F84C9000000.

**Comment by PalasX** [comment]
Server does not check for or prevent local god/equip hack?
In case anyone ever asks you to change this behavior, "to stop the hackers", please dont. I dont think the original sega servers ever did.
I think there was some logic in Tethealla that would drop your connection on area warp if you had something equipped that you shouldnt, but i dont remember if it was reading equip flags from item.gsl or what. either way, awesome to know! thanks for sharing.
Is there somewhere we can gather as many client edit offsets as possible, both static and ASM like this, so that they dont get lost to the ages?

**Comment by fuzziqersoftware** [comment]
It seems there isn't a good place for BB client patches that are explicitly cheats, like this one. I've been directing people who ask to https://github.com/Solybum/Blue-Burst-Patch-Project, but that project doesn't have cheat patches either. I don't think we should include them in system/client-functions by default, but I've been collecting my own client patches in notes/ar-codes.txt and I think they could be added there. I've added this patch there as well.

**Comment by PalasX** [comment]
i saw the ar-codes file, but thats all related to console versions of the client, and not psobb. i flirted with the idea of trying to port any of the codes posted at gcforever over to a cheat engine table for blueburst, but i was WOEFULLY underskilled for that endeavor.  even checked out the code for "Improved Draw Distance of most objects" to try and figure out where in the ASM to look for the psobb client, but the cube being a risc chip didnt at all help the matter.

So yeah, ANY extra notes, direct patches, find and replaces, or just musings you can add about unpacked PSOBB clients or any flavor, that would be amazing!

**Comment by user18081972** [comment]
@fuzziqersoftware Hey me again 2 years later, and thanks again btw, i've been using this in my private server and its made my singleplayer run alot more fun!

i was wondering if there was a similar way to also disable the stats ATP,ATA,MST etc restrictions, so items can be equiped quicker?
playing as a FOnewearl some of these stats seem to rise rather slow.
