### ISSUE TITLE
[General] Options for IS_CLIENT_CUSTOMIZATION flag

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#483]
**Is your feature request related to a problem? Please describe.**
0x3A was added recently to the `sub_version`, and sets the `IS_CLIENT_CUSTOMIZATION` flag and is segregated from other sub versions, which is great. The creator has agreed to patch their game with this, however, I'm thinking it might be best if there were some other minor options for it.

**Describe the solution you'd like**
I don't except super granular control here, however it would be nice to send anyone with `IS_CLIENT_CUSTOMIZATION` to a different default lobby order or give them a different name colour. I'm fine with just the same lobby/colour for all client customisations if it wouldn't be worth being able to set specific versions different colours/lobbies.

**Game version(s) (choose one or more of the following):**
DC NTE, DC prototype, DC v1, DC v2, PC, GC Ep1&2, GC Ep3, Xbox, BB

**Additional context**
This isn't really important, if the labour isn't worth it, don't bother. :P Was just thinking it'd be nice to be able to make customisations stand out as another version similar to how all the other PSO versions do.

**Comment by fuzziqersoftware** [comment]
I've added a name color for this flag, but not a lobby order yet. I will likely add a lobby order option soon.

**Comment by fuzziqersoftware** [comment]
Lobby ordering for client customizations has been added.
