### ISSUE TITLE
problem with psoBB

### ISSUE THREAD

**Issue by ButtonMash64** [fuzziqersoftware/newserv#484]
**Describe the bug**
Hello, I have tried to create a private server for psoBB.

I've downloaded the teth Version 12513, with the link in the FAQ. 

I modified the ip address with a hexadecimal editor

the server detects the connection, but as soon as it tries to connect, it displays an error message 906 server is full. even though there's nobody on the server since it's just been created.

I've also opened all the ports indicated in the config.json file. 

I tried with pso 1&2 on gamecube and it works.

I don't know what to do ...

**To reproduce**
Fill in steps to reproduce the behavior, such as:
1. Connect to server

**Game version(s) (choose one or more of the following):**
PSO BB

**Comment by fuzziqersoftware** [comment]
It's likely that LocalAddress and/or ExternalAddress is set incorrectly in config.json. Please upload the server log output here from when you try to connect.

**Comment by ButtonMash64** [comment]
Hello, I can't find the output log file. But the ip address is correct. Since for episode 1, 2 & 3 on gamecube works with this server. Me and my friends manage to connect. I only have the error with pso BB.

**Comment by ButtonMash64** [comment]
yes ip address 10.0.0.13 is the ip address enter in local ip address line:

here's my config.json file
[config.json](https://github.com/fuzziqersoftware/newserv/files/15283108/config.json)

**Comment by Matt-Swift** [comment]
Change LocalAddress to 172.29.82.2 - I don't really know why you have 10.0.0.13 there when your local IP address range appears to be 172.29.X.X.

**Comment by ButtonMash64** [comment]
oh wow thanks it worked :)
thanks a lot
