### ISSUE TITLE
[Blue Burst] Team flag loses transparency on server restart

### ISSUE THREAD

**Issue by Repflez** [fuzziqersoftware/newserv#487]
**Describe the bug**
When restarting newserv, the team flag will lose its transparency

**To reproduce**
1. Add a team flag with transparency (denoted by any fully black pixel on the bmp, [sample file included](https://github.com/fuzziqersoftware/newserv/files/15285391/flag.zip)) to any team with team flag privileges purchased
2. Restart newserv
3. Go to lobby and switch the character overhead to show the team flag

**Game version(s) (choose one or more of the following):**
BB

**Server log output**
None

**Additional context**
Joining the lobby between server restarts shows the team flag properly.

**Comment by nolrinale** [comment]
Loading a flag with Transparent Background
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/c8f9b7a2-0c95-4217-94df-f64651e8b3d3)

Returning to Title Screen and Relogin to Lobby Displays the Flag correctly
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/68fe86ac-dd7f-4b6d-a9b7-855172272f88)

Restarting the Server Process and Relogin into the game again 
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/e7c1f375-14c0-44df-abef-aa845f3400dc)

**Comment by fuzziqersoftware** [comment]
This has been fixed.
