### ISSUE TITLE
Verify/fix loading save files on GC

### ISSUE THREAD

**Issue by fuzziqersoftware** [fuzziqersoftware/newserv#488]
Specifically, verify that data2 within items is correct and mat counts are preserved through a $loadchar

**Comment by Matt-Swift** [comment]
Example files that caused some issues: [Archive.zip](https://github.com/fuzziqersoftware/newserv/files/15290223/Archive.zip)

For the BB character: Material counts were not preserved (although the stats were), mag was also a present.
For the GC character: Material counts were preserved, mag was a present

**Comment by fuzziqersoftware** [comment]
Mags should be fixed now. Importing Tethealla material counts is not yet implemented, so I'll leave this open until that's done.

**Comment by fuzziqersoftware** [comment]
Importing material counts should be working now.

**Comment by Matt-Swift** [comment]
These appear to have been resolved now, can't say too much about other cross-platform weirdness though.
