### ISSUE TITLE
[Blue Burst] Wrong Quest icons for EP4 Hunter's Guild Quests

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#490]
**Describe the bug**
Quest icons for hunter's guild EP4 quests should be the orange variation ones for both one-person and online modes, they are currently the green ones used in EP1 and EP2 quests (see attached pics below) 

![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/94117a50-e455-431f-a1bf-e60515e641fb)
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/716208bd-d381-4d30-8350-782b1260dbba)

**Game version(s) (choose one or more of the following):**
BB

**Additional context**
online-mode
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/9b5135d2-3f12-412e-8a89-e589c76bcdb9)

one-person mode
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/6661263d-0165-46c8-91e4-0f6fc93ee32a)

**Comment by fuzziqersoftware** [comment]
This has been fixed.
