### ISSUE TITLE
How to disable or hide the Patches menu on BB?

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#491]
This new menu that appears in the Tethealla client
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/b13c4146-3e63-486f-bf5a-a1fa97863e61)

I've tried nuking the whole client-patches folder but then the server refused to start

**Comment by fuzziqersoftware** [comment]
The server should hide the patch menus if there are no patches for the client's version. So, it should suffice to delete all the 59NL (BB) files in the subdirectories of system/client-functions/.
