### ISSUE TITLE
[Dreamcast V2] Extended $loadchar causes FSOD on hardware

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#493]
**Describe the bug**
Yep... guessing this one might be hard to fix, since it doesn't happen on emulator. The Dreamcast locks up entirely and requires a hard reset after using $loadchar. The version check works fine, but sending and overwriting the character does not.

**To reproduce**
1. Connect to server
2. Use $loadchar

**Game version(s) (choose one or more of the following):**
DCv2

**Server log output**
Hardware: [hardware.txt](https://github.com/fuzziqersoftware/newserv/files/15299566/hardware.txt)
Flycast: [flycast.txt](https://github.com/fuzziqersoftware/newserv/files/15299568/flycast.txt)

**Comment by fuzziqersoftware** [comment]
The only thing I can think of that might break on hardware but not emulator is an invalid delay slot instruction. Can you try it on hardware again using this version of SetExtendedPlayerInfo? (Renamed to .txt to appease GitHub)
[SetExtendedPlayerInfoDC.sh4.inc.s.txt](https://github.com/fuzziqersoftware/newserv/files/15302394/SetExtendedPlayerInfoDC.sh4.inc.s.txt)

**Comment by fuzziqersoftware** [comment]
Yeah, this was probably the issue. When the SH-4 executes a call or branch instruction, it executes the instruction after the call or branch before actually going to the branch destination, but there are some restrictions on what that second instruction can be. Specifically, it appears the `mov.l  r6, [part2_size]` is not allowed in that situation, so it must happen before the relevant `calls  memcpy`.
<img width="714" alt="Screenshot 2024-05-13 at 9 08 54 PM" src="https://github.com/fuzziqersoftware/newserv/assets/187339/2e4ab00a-6aca-4f15-b9c9-a80bafafe304">

**Comment by Matt-Swift** [comment]
Just to confirm this now works, so all sorted with the above fix, thank you!
