### ISSUE TITLE
[Xbox] $loadchar causes FSOD when loading character data from other platforms

### ISSUE THREAD

**Issue by Break1988** [fuzziqersoftware/newserv#494]
**Describe the bug**
When using $loadchar on Xbox to load saved character data from any other platform, opening up the quick select menu and scrolling to the techniques page will cause the system to FSOD. This has been tested with DC v2, PCv2, and GC native characters.

**To reproduce**
Fill in steps to reproduce the behavior, such as:
1. Connect to server on any platform other than Xbox (Account / serial must be linked with xbox)
2. $savechar slot#
3. Connect to server on Xbox (Must have account linked with serial from the platform $savechar was used on)
4. $loadchar slot#
5. Make a game
6. Go down to ragol and open the quick menu (RT & Y)
7. Scroll to the Techniques page with RT button

**Game version(s) (choose one or more of the following):**
Xbox

**Comment by fuzziqersoftware** [comment]
I believe this has been fixed; the issue was that tech_menu_shortcut_entries was big-endian on Xbox due to a copy/paste error. Quest counters were also affected by this and have also been fixed.
