### ISSUE TITLE
[DC V2] $loadchar provides an error when attempting to load a saved v3 character

### ISSUE THREAD

**Issue by Break1988** [fuzziqersoftware/newserv#495]
**Describe the bug**
Using $loadchar on v2 when attempting to import a full v3 save causes the error "item parameter table is required to encode v2 data" and fails to import. Assumed issue was bank related but still occurs even with a completely empty bank.

**To reproduce**
1. Connect to server on GC/XB with a SNAK shared with DC
2. $savechar slot#
3. Connect to server on DC v2 with a SNAK shared with GC/XB
4. $loadchar slot#

**Game version(s) (choose one or more of the following):**
DC v2

**Comment by fuzziqersoftware** [comment]
This has been fixed - we don't need to v1-encode item data when we send it to v2 clients.
