### ISSUE TITLE
[Xbox] Clients freeze if container objects are broken on a different floor

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#499]
**Describe the bug**
If a container item is broken on a different floor that the Xbox client is on, the Xbox client will immediately freeze.

**To reproduce**
1. Have Xbox player and another in the same game (other player can be GameCube or Xbox)
2. The other player breaks a box on any other floor
3. Xbox player freezes

**Game version(s) (choose one or more of the following):**
Xbox

**Server log output**
Here's a couple of outputs:

Xbox player on same floor (does not crash):
[xboxsamefloor.txt](https://github.com/fuzziqersoftware/newserv/files/15370332/xboxsamefloor.txt)

Xbox player on different floor (crashes):
[xboxdifffloor.txt](https://github.com/fuzziqersoftware/newserv/files/15370333/xboxdifffloor.txt)

Let me know if you need anything else.

**Comment by Matt-Swift** [comment]
Quick update to this: The crash only occurs if an item is generated - I need to go get another log for the same floor non-crash.

**Comment by Matt-Swift** [comment]
Log of same floor item generation: 
[samefloor2.txt](https://github.com/fuzziqersoftware/newserv/files/15371068/samefloor2.txt)

**Comment by fuzziqersoftware** [comment]
I think I need more information here; I tried reproducing this in Forest 1/2 and couldn't get it to crash. Things that might be useful:
* Which Episode and floors were used in this test?
* Was there a quest in progress? (Which one?)
* Did either client have any patches applied?

**Comment by Matt-Swift** [comment]
Now that you've mentioned patches - it's the rare alert patch. Take that off and the freezes stop.

**Comment by fuzziqersoftware** [comment]
The problem with the patch is that eax is null in the sound hook if the generated item isn't on the same floor. The patch incorrectly relies on a side effect of another function, which actually returns void, so we can't trust eax upon its return. I'll fix this soon.

**Comment by fuzziqersoftware** [comment]
Fix has been pushed. Please test again when you have a chance.

**Comment by Matt-Swift** [comment]
This appears to be fine now, and nobody has reported any sort of freezing issues since. Will open a new ticket if something else appears to occur.
