### ISSUE TITLE
PSO PC and BB login fails

### ISSUE THREAD

**Issue by lucashart90** [fuzziqersoftware/newserv#5]
Other Bug that I noticed while logging into the server automatically is immediately logged out I tried in all versions and above all does not access the lobby and including missing the map dat for the gamecube
![022](https://user-images.githubusercontent.com/6928951/67043360-2ef15880-f12a-11e9-8541-d1cfe44c3e1f.JPG)
![023](https://user-images.githubusercontent.com/6928951/67043362-2ef15880-f12a-11e9-9f92-97f7177ca5e1.JPG)

**Comment by fuzziqersoftware** [comment]
PSO PC and BB aren't yet supported. I'm going to leave this open until I can test them and get login working. PSO GC should work fairly well now.

**Comment by fuzziqersoftware** [comment]
Cleaning up old issues - this has been fixed at some point; PC and BB are now supported (though games on BB are still buggy).
