### ISSUE TITLE
[General] Telepipe state is not sent to joining player if used during a quest load

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#500]
**Describe the bug**
If a player creates a pipe while a player is loading a quest after joining a joinable quest, the telepipe state is not sent to the joining player once they're done loading.

**To reproduce**
1. Begin joinable quest
2. Have someone join
3. Create pipe while other player is loading

**Game version(s) (choose one or more of the following):**
DC v1, DC v2, PC, GC Ep1&2, Xbox, BB

**Server log output**
uhhhh, this seems like it would'nt be useful but I'll get one if you think it is

**Additional context**
I have no idea if this thing would be fixable and is some sort of client limitation, it keeps catching people out though as you gain control before the other person is done loading.

**Comment by fuzziqersoftware** [comment]
This is fixable; there's even a TODO about it in the code. This happens because the server generates all the game state commands after the quest loads, but the server doesn't currently track telepipe state. Will add this soon.

**Comment by fuzziqersoftware** [comment]
This should be fixed now.
