### ISSUE TITLE
[Blue Burst] Weapons should not drop with negative attributes

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#507]
**Describe the bug**
Theres a chance the weapon can drop with negative attributes, this shouldn't be possible

In this case it happened with an untekked autogun while playing in the Underground Desert area normal difficulty online mode

UPDATE: It looks like I'm also getting almost always weapons with 90% attributes in each monster drop in EP4 areas on normal, not sure if its also related to the negatives issue

![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/0c8f4407-8441-4343-9b2d-6df164c814f5)

**Game version(s) (choose one or more of the following):**
BB

**Comment by nolrinale** [comment]
More reports from other players weapons with too high %, related to this issue, it only happens in EP4 tho

![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/ca3fd103-f6a2-453e-b81a-d6723834f630)
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/dd2bc654-45b4-4c01-a10f-747283324702)
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/30032ca9-f1a7-482d-9809-077e5be6d0f6)

**Comment by fuzziqersoftware** [comment]
This has been fixed.
