### ISSUE TITLE
[newserv] Named registers for the quest assembler

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#508]
**Is your feature request related to a problem? Please describe.**
I've been writing some helper functions that make it easy to just insert code into a quest script; newserv is very useful for this due to its function naming system and using numbers that are not explicitly defined, however right now named registers have to be find+replaced, and figuring out exactly what registers are explicitly free can be a bit of a pain in bigger scripts.

**Describe the solution you'd like**
It would be extremely cool if the assembler could allow named registers and then use explicitly unused registers for this. Would make inserting helper functions into quests much easier!

**Additional context**
newserv's quest disassembler and assembler is very cool :3 Thank you for making this! It's become my go-to method for modifying quest scripts.

**Comment by fuzziqersoftware** [comment]
This has been added; see system/quests/retrieval/q058-gc-e.bin.txt for details and examples. There are many cases to consider (mostly caused by sequential-register opcodes), and I'm not confident I handled all of them properly. Please try it and let me know if you see any problems.

**Comment by Matt-Swift** [comment]
This seems to work well, although I did have one issues but it's possible this isn't meant to work:

I had a quest which had used r251, and then later in the script I tried to define `r:name@251`, and the assembler advised that 251 was already used elsewhere, but the goal was for all instances of `r:name` to explicitly be 251 and related to the original r251. This isn't a huge issue as I can just find and replace, though I can understand if this is also an anti-stupidity measure as well to make sure people are using unique registers.

**Comment by fuzziqersoftware** [comment]
No, this is supposed to work. Can you post the quest script here or send it to me on Discord?

**Comment by fuzziqersoftware** [comment]
I believe this has been fixed now - the script you sent to me now assembles correctly.

**Comment by Matt-Swift** [comment]
This seems to work well now, thank you very much!
