### ISSUE TITLE
[Blue Burst] EP1 Side Story quests stay greyed out after completing them all

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#510]
**Describe the bug**
Finishing all the EP1 side story quests including CDFS with the changes mentioned in https://github.com/fuzziqersoftware/newserv/issues/449 should allow the player to replay them all after finishing up all of them.

Instead they stay greyed out unable to be repeated in that difficulty anymore, the correct behavior is that they should go back to their original selectable setting after finishing them all

**To reproduce**
Fill in steps to reproduce the behavior, such as:
1. Complete all 26 Solo Side Story EP1 quests
2. All the quest are greyed out
3. Unable to start any quest again

**Game version(s) (choose one or more of the following):**
BB
![IMG_2482](https://github.com/fuzziqersoftware/newserv/assets/5244595/d8489dd7-45ba-4e9f-b2b7-4d02c6c2938c)

**Comment by fuzziqersoftware** [comment]
This has been fixed.
