### ISSUE TITLE
Save Profiles Character ?

### ISSUE THREAD

**Issue by ButtonMash64** [fuzziqersoftware/newserv#512]
Hello, I was wondering if it would be possible to know where the accounts and characters of each player is saved please?

I'm using PSO BB on pc and I've seen in the “system” folder a folder called “licenses” & another called “players”. Are these the right folders?

thanks in advance for your help :)

**Comment by fuzziqersoftware** [comment]
Yes, account data is saved in system/licenses and characters are saved in system/players. You generally should not move or edit these files manually unless you know what you're doing; if you want to make account changes, use the server shell instead.

**Comment by ButtonMash64** [comment]
ok thank you very much, it was to be able to make backups in case one day my computer that serves as my server crashes.
