### ISSUE TITLE
[Blue Burst] My Guild Card comments are being deleted after relogin.

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#514]
**Describe the bug**
Under your MY GUILDCARD setting in-game you should be able to add a custom comment to customize your guild card to share with other people.

If you attempt to write a comment on your card and then quit the game, the text is not saved and your card comment field appears empty upon the next login.

The correct behavior is the guild card  comment should persist all the time. 

![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/999edf73-4294-4a78-a670-62db496ba886)

**Game version(s) (choose one or more of the following):**
BB

**Comment by fuzziqersoftware** [comment]
This has been fixed.
