### ISSUE TITLE
[Blue Burst] EP1 Solo Quests aren't getting marked as completed anymore in 2nd run

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#515]
**Describe the bug**
A continuation of the previous bug which was fixed on https://github.com/fuzziqersoftware/newserv/issues/510 this time upon checking the quest list again all the EP1 Story quests were available again as intended.

However upon clearing one of them this 2nd time, it doesnt get marked as complete anymore they just stay white all the time.

The correct behavior is, same as the first run, they should get marked and greyed out with the yellow icon as you complete them again.

**To reproduce**
Fill in steps to reproduce the behavior, such as:
1. Finish up all the EP1 solo Story quests
2. Return to lobby and create a new EP1 solo room
3. You will notice all the quests are white and available to choose again
4. Clear one of them
5. Create a new room again
6. The quest you just cleared didn't got marked as completed they all stayed white and selectable regardless

**Game version(s) (choose one or more of the following):**
BB

**Comment by fuzziqersoftware** [comment]
When the solo quest progression is completed, all quests are unlocked again and can be replayed at any time, and they never become locked again for that character. This is the offline quest behavior on non-BB versions, and Sega did not change this for BB. Even if they did change it, it's a better player experience to be able to replay the quests at any time, and I'm not going to change the current behavior.
