### ISSUE TITLE
[Blue Burst] Recovery Items given by NPCs in Quest 9-2 ends up in Err.100 'Stack too Large' Missing Client Command

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#517]
**Describe the bug**
During the course of EP4 quest 9-2 the NPC guarding the laser fences can also give you recovery items if you takl to them, however in this case you end up with Error 100 and a `Stack too Large` error in the console.

**To reproduce**
Fill in steps to reproduce the behavior, such as:
1. Start Quest 9-2
2. Kill a few monsters and progress a bit
3. Eventually you will meet BEN or ASH or RUPIKA
4. Talk to any of them to oepn the laser fence, then talk to them again to receive a recovery item
5. Get Error. 100 and Disconnected

**Game version(s) (choose one or more of the following):**
 BB

**Server log output**
[92StackTooLargeErr100.txt](https://github.com/user-attachments/files/15748611/92StackTooLargeErr100.txt)

**Comment by fuzziqersoftware** [comment]
This has been fixed.
