### ISSUE TITLE
[Blue Burst] Server Send Error while talking to Coren if there are more than 2 players in the room using him

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#519]
**Describe the bug**
Write a clear and concise description of what the bug is, and what you expected to happen instead.

**To reproduce**
Fill in steps to reproduce the behavior, such as:
1. 3 players in a room
2. Player 2 or 3 use coren
3. Receive SERVER SEND ERROR from coren
4. Player 1 can receive Coren rewards as usual

**Game version(s) (choose one or more of the following):**
BB

**Server log output**

[Koren2PlayerServerSendErr.txt](https://github.com/user-attachments/files/15795708/Koren2PlayerServerSendErr.txt)
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/8bbb4839-f2d9-4c45-ae13-e3b1ea5dc4bd)

**Comment by fuzziqersoftware** [comment]
This has been fixed.
