### ISSUE TITLE
Dolphin And Pso

### ISSUE THREAD

**Issue by thom2305** [fuzziqersoftware/newserv#52]
Hi,
Im trying to setup a test server for pso on a vm and testing it on dolphin (Os Main Windows - VM guest debian)

But it cannot connect and gives me an error 102 and the server gives no logs about the game connecting.

Thank You for helping.

**Comment by fuzziqersoftware** [comment]
It's likely that your Dolphin instance isn't connecting to the right IP address. You probably want to use the HLE BBA type in Dolphin, and configure its DNS server address to point to your VM. (The correct address will depend on which VM software you're using - for Parallels, it would be something like 10.211.55.2, but for other software you'll have to check its documentation.) You'll also need to enter that address in newserv's ExternalAddress field in config.json.

**Comment by thom2305** [comment]
Hey Thanks That Works but i still have an question.
Witch port do i open from the router so it can works online for my friends?
and if you need my config file just say it.

Thanks
Thom

**Comment by sirdankz** [comment]
> Hey Thanks That Works but i still have an question. Witch port do i open from the router so it can works online for my friends? (PSO GC Episode 1 & 2)
> 
> Thanks Thom

I have a server up with some rare long lost quest I got from messaging some OG pso players. If you want you can and your friends can join :)

**Comment by ShiftaDeband** [comment]
> Hey Thanks That Works but i still have an question. Witch port do i open from the router so it can works online for my friends? (PSO GC Episode 1 & 2)
> 
> Thanks Thom

If you're looking to just do Episode I&II support, forward ports 53, 9000, 9001, 9064, 9100, 9200, 9201, 9202. That would support those versions of the game (which would also include if they're using a different region game for some reason). 

If you're looking to do more, depending on your configuration, like Episode 3 support, you'll want to forward the ports as outlined in the "PortConfiguration" in config.json.

**Comment by thom2305** [comment]
> > Hey Thanks That Works but i still have an question. Witch port do i open from the router so it can works online for my friends? (PSO GC Episode 1 & 2)
> > 
> > Thanks Thom
> 
> If you're looking to just do Episode I&II support, forward ports 53, 9000, 9001, 9064, 9100, 9200, 9201, 9202. That would support those versions of the game (which would also include if they're using a different region game for some reason). 
> 
> If you're looking to do more, depending on your configuration, like Episode 3 support, you'll want to forward the ports as outlined in the "PortConfiguration" in config.json.

Hey thanks this solved everything I needed!
Now I can mark this a solved
