### ISSUE TITLE
[Blue Burst] Meseta quest rewards are given only to the party leader after a quest

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#520]
**Describe the bug**
In a party of 3 people doing TTF after clearing it everyone should get the reward, instead only the current party leader gets the meseta reward while the others dont get it and are all sent to lobby. 

**To reproduce**
Fill in steps to reproduce the behavior, such as:
1. Complete TTF 3 player
2. Everyone get the reward a the counter
3. Only the leader gets the reward

**Game version(s) (choose one or more of the following):**
 BB

**Server log output**
[TTFNoReward2ndPlayer.txt](https://github.com/user-attachments/files/15796104/TTFNoReward2ndPlayer.txt)

**Comment by Matt-Swift** [comment]
Looking at this, the players VIVIANE and Darkrai both received the meseta, but MS Zaku did not.

This is most likely not a server issue, as a quest deciding to give a player meseta is controlled entirely by the quest script which is client-sided; the quest clear flag is not synchronised in TTF and each player must speak to Tyrell at the end of the quest to have the quest clear for them to get the meseta. If MS Zaku did not speak to Tyrell, they won't clear the quest and therefore get no meseta if they choose to leave at the counter, even if someone else spoke to Tyrell first.

I checked the TTF quest script as well and there is no issue with it when it comes to giving the reward to all players.

**Comment by Matt-Swift** [comment]
Actually I re-read it again, all players got the 5,000 meseta, there doesn't appear to be an issue here.

**Comment by fuzziqersoftware** [comment]
Yeah, we can see all three players request Meseta rewards with the following commands:

```
I 327693 2024-06-12 00:09:03 - [Commands] Received from C-36 (MS Zaku) @ ipv4:68.47.160.88:52551 (version=BB command=0062 flag=00000001)
0000 | 10 00 62 00 01 00 00 00 C9 02 FF FF 88 13 00 00 |   b

I 327693 2024-06-12 00:09:03 - [Commands] Received from C-40 (VIANNE) @ ipv4:79.117.246.24:60032 (version=BB command=0062 flag=00000001)
0000 | 10 00 62 00 01 00 00 00 C9 02 FF FF 88 13 00 00 |   b

I 327693 2024-06-12 00:09:05 - [Commands] Received from C-3B (Darkrai' ) @ ipv4:82.8.94.35:50275 (version=BB command=0062 flag=00000001)
0000 | 10 00 62 00 01 00 00 00 C9 02 FF FF 88 13 00 00 |   b
```

After each one, the server sends a 6xBE command to all players to add the Meseta to the requesting player's inventory.

What did you see in-game that made it look like this wasn't working?

**Comment by nolrinale** [comment]
At the moment we were playing one mentioned havent received the reward, then he did a relogin and the reward appeared in his wallet afterwards, but im starting to think maybe he was just confused 

More quests have been played after this and i never ever heard about this issue again so i think this one might be a bogus report
