### ISSUE TITLE
[Blue Burst] Cmode palletes are overwriting the main game ones

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#521]
**Describe the bug**
A player completed 1c1 and afterwards their progress wasnt kept after a relogin, this time the affected player was P1, so it looks like it saves the progress correctly for P2,P3,P4 but not the host..... 

UPDATE: We've played until 1c4 and confirmed correct operation, we reloged and also restarted the server after each run and the results, ranks and times persisted between logins

Their action pallete used by cmode overwrote their main game pallete (both action keys and number keys) so they are back to the default empty for all number keys and, Heavy, Normal, Monomate for the arrow key ones

**Game version(s) (choose one or more of the following):**
BB

**Comment by nolrinale** [comment]
This bug is also affecting this ticket 
https://github.com/fuzziqersoftware/newserv/issues/359

**Comment by fuzziqersoftware** [comment]
This has been fixed.
