### ISSUE TITLE
[Blue Burst] Love Rappy appears in VR Temple without any events going on

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#522]
**To reproduce**
Fill in steps to reproduce the behavior, such as:
1. Happened during quest 5-4
2. Love Rappy Appeared!
3. Server has no seasonal events loaded whatsoever

**Game version(s) (choose one or more of the following):**
 BB

**Server log output**
[LoveRappyNoEvent.txt](https://github.com/user-attachments/files/15826253/LoveRappyNoEvent.txt)

![pso1718298024](https://github.com/fuzziqersoftware/newserv/assets/5244595/fed1babe-98e9-45c9-9105-fd732036bdeb)

**Comment by Matt-Swift** [comment]
Love Rappy is the normal rare Rappy for VR Temple when Easter, Halloween, or Christmas is not running, so this is not an issue.

**Comment by fuzziqersoftware** [comment]
The server does not control which rare rappy appears; it only controls whether a rare rappy appears at all. So, if we prevented Love Rappies from appearing outside of a holiday event, there would be no rare rappies in Episode 2 at all.
