### ISSUE TITLE
relativ path of system folder

### ISSUE THREAD

**Issue by SMHRambo** [fuzziqersoftware/newserv#523]
**Describe the bug**
I dont know if this is on purpos, but the system folder path is relativ to the path of execution.

**Expected behavior**
newserv looks for files and folders relativ from its position

**To reproduce**
self compiled version an linux (tested on debian and alpine)
create a folder named /app
copy "newserv" and the "system" folder into /app
go into /app and call "./newserv --config=/app/system/config.example.json" <- this works
go into / and call "/app/newserv --config=/app/system/config.example.json" <- this doesnt work

**suggestion**
add also a paramter for the system folder

**Comment by SMHRambo** [comment]
I have looked at the code.
I wrote a small function based on your function get_config_filename(Arguments& args).
Where is the best place to store the path?
I have found many functions that require the path, where is a safe place to call the function to provide the path to the program.

```
<filesystem>
std::string get_system_path(Arguments& args) {
  string system_path_default = canonical( std::filesystem::path("/proc/self/exe") ).parent_path().string() + "/system/"
  string system_path = args.get<string>("system");
  return system_path.empty() ? string system_path_default : system_path;
}
```
https://en.cppreference.com/w/cpp/header/filesystem

**Comment by fuzziqersoftware** [comment]
The use of /proc/self/exe is not portable; it would not work on macOS or Linux. In general, allowing the path to the system directory to be changed would complicate the code in ways that I think shouldn't be necessary. Are you working in an environment where you can't change the working directory before running newserv? (Does running `(cd /app && ./newserv)` not work for you?)

**Comment by SMHRambo** [comment]
I have tested my above code on Linux with "/proc/self/exe" and it works.
I've tested some init systems with "cd /app && ./newserv", some work, some don't.
I also wrote a patch for newserv that adds a new --system argument and also uses "/proc/self/exe".
I have compiled the patch for Windows (Cygwin) and Linux (Debian) and it works.

**Comment by fuzziqersoftware** [comment]
I meant to say above that /proc/self/exe would not work on macOS or Windows. You're correct that it does actually work on Windows via Cygwin, but it will not work on macOS, and since I primarily develop newserv on macOS, this is a requirement. As stated above, I don't think we should add a --system argument because it complicates the code, and I don't see a strong need for it since you can change the working directory before running newserv.

**Comment by SMHRambo** [comment]
I will also test my code on Macos and how do you know if my added code will be complicated.
