### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by UserGit-2021** [fuzziqersoftware/newserv#525]
I followed the instructions, but the game does not start.
![изображение](https://github.com/fuzziqersoftware/newserv/assets/91757058/ffa357ae-d884-402e-8664-817b13528533)

**Comment by gortr** [comment]
Let's get a process of elimination going to narrow down what it could be.
- Does the newserv server application launch and run without issue?
- Does the client open and then close?
- If the client does not do the above, does it give a connection issue to the patch server upon attempting a connection?
- Do neither of the applications run or remain open?
This will help figure out what could be going on in regards to your current issue.

**Comment by UserGit-2021** [comment]
> Let's get a process of elimination going to narrow down what it could be.
> 
>     * Does the newserv server application launch and run without issue?
> 
>     * Does the client open and then close?
> 
>     * If the client does not do the above, does it give a connection issue to the patch server upon attempting a connection?
> 
>     * Do neither of the applications run or remain open?
>       This will help figure out what could be going on in regards to your current issue.

The client opens and closes.

Version: psobb_jp_setup_12511 (original)

**Comment by Matt-Swift** [comment]
This isn't an issue with newserv - the client immediately closing means that the resolution the game is trying to open with is not supported by your GPU/monitor, and you should pick a different one which is supported in the options.

**Comment by UserGit-2021** [comment]
> This isn't an issue with newserv - the client immediately closing means that the resolution the game is trying to open with is not supported by your GPU/monitor, and you should pick a different one which is supported in the options.

![изображение](https://github.com/fuzziqersoftware/newserv/assets/91757058/a70f1d2d-ba6b-42e4-9158-d2f72cb72b7c)

**Comment by fuzziqersoftware** [comment]
It looks like you didn't do this step:
> Edit the config.example.json file in the system folder as needed, then rename it to config.json.

**Comment by UserGit-2021** [comment]
> It looks like you didn't do this step:
> 
> > Edit the config.example.json file in the system folder as needed, then rename it to config.json.

And after that it closes.
![изображение](https://github.com/fuzziqersoftware/newserv/assets/91757058/da094903-3f01-4085-9905-35f79ec50ded)

**Comment by fuzziqersoftware** [comment]
Go into config.json and remove the "Tablet" entries from the lists where it appears. I've made a change that will make this unnecessary, but I haven't built a new release yet.

**Comment by UserGit-2021** [comment]
> Go into config.json and remove the "Tablet" entries from the lists where it appears. I've made a change that will make this unnecessary, but I haven't built a new release yet. It still gives errors. I deleted everything that gave an error one by one.

![изображение](https://github.com/fuzziqersoftware/newserv/assets/91757058/da72736b-3319-4d0a-8e6b-e14a6dd84963)

**Comment by UserGit-2021** [comment]
![изображение](https://github.com/fuzziqersoftware/newserv/assets/91757058/cf38d275-a041-44d8-99c3-3ea9619ffbda)

**Comment by gortr** [comment]
This seems to be doing it on the Coren npc prizes, I had this issue the other day when trying to run the server on a separate Windows system I have on my server rack and I had to delete the whole folder and reimport it to then run it all again to fix the issue. Are you attempting to build the newserv on the Windows platform with cygwin? May need to test with all the coren items commented or removed out to make sure it's not just that section within the config file.

**Comment by UserGit-2021** [comment]
> This seems to be doing it on the Coren npc prizes, I had this issue the other day when trying to run the server on a separate Windows system I have on my server rack and I had to delete the whole folder and reimport it to then run it all again to fix the issue. Are you attempting to build the newserv on the Windows platform with cygwin? May need to test with all the coren items commented or removed out to make sure it's not just that section within the config file.

Followed the steps.
1) Installed the game Phantasy Star Online Blue Burst Japanese Client Setup 1.25.11
2) downloaded release.zip and unpacked it into the game folder.
3) I launch newserv-windows.exe and it closes. Various errors.

**Comment by Repflez** [comment]
Did you added the required files to the `system/patch-bb/data` folder [the readme explicitly mentions?](https://github.com/fuzziqersoftware/newserv?tab=readme-ov-file#client-patch-directories)

I'm under the assumption the folder only has the `system/patch-bb/data/newserv-test-bb.txt` file in it and not the required ones for your instance to start properly.

**Comment by UserGit-2021** [comment]
> Did you added the required files to the `system/patch-bb/data` folder [the readme explicitly mentions?](https://github.com/fuzziqersoftware/newserv?tab=readme-ov-file#client-patch-directories)
> 
> I'm under the assumption the folder only has the `system/patch-bb/data/newserv-test-bb.txt` file in it and not the required ones for your instance to start properly.

Yes, I did this from the very beginning. When I created this topic.
![изображение](https://github.com/fuzziqersoftware/newserv/assets/91757058/564db8ac-f376-4021-a082-7b5367228b18)

**Comment by UserGit-2021** [comment]
The new version works. (2024-06-18) macOS / Windows.
![изображение](https://github.com/fuzziqersoftware/newserv/assets/91757058/5b9bf0f0-8c14-47f1-942c-4eb848a6edc5)

**Comment by UserGit-2021** [comment]
Thanks for the help and correction!
Can you tell me where to start? How to start the game, the gameguard window pops up.
![изображение](https://github.com/fuzziqersoftware/newserv/assets/91757058/14045489-933b-4bd2-9f07-b7a69889fb9b)

**Comment by nolrinale** [comment]
Since you are using the official client use the azureflare drop in patch, it has a psobb.cfg where you can set the server url by default points to localhost, and also allows to switch the client language on the fly.

The launcher and options cannot be changed to english as this client is the official japanese one, but you can source the english versions from the tethealla client and replace the originals.

Setting the option of 'AllowUnregisteredUsers' set to True in the config.json allows acounts to be created automatically upon login.

**Comment by UserGit-2021** [comment]
> Since you are using the official client use the azureflare drop in patch, it has a psobb.cfg where you can set the server url by default points to localhost, and also allows to switch the client language on the fly.
> 
> The launcher and options cannot be changed to english as this client is the official japanese one, but you can source the english versions from the tethealla client and replace the originals.
> 
> Setting the option of 'AllowUnregisteredUsers' set to True in the config.json allows acounts to be created automatically upon login.

Can you give more details? Where and how exactly to write?
![изображение](https://github.com/fuzziqersoftware/newserv/assets/91757058/456f1120-22d3-4486-a874-71e921bb735e)

**Comment by nolrinale** [comment]
you just need to change all the patch/game servers values to just `"localhost"` and you should be able to connect to your server

**Comment by UserGit-2021** [comment]
> you just need to change all the patch/game servers values to just `"localhost"` and you should be able to connect to your server
> 
> Read the instructions, its all very clearly explained

Yes, I did, but for some reason the server was full.
![изображение](https://github.com/fuzziqersoftware/newserv/assets/91757058/047b7177-88df-4fd5-a11f-1f1f234e2c8d)

**Comment by UserGit-2021** [comment]
> you just need to change all the patch/game servers values to just `"localhost"` and you should be able to connect to your server
> 
> Read the instructions, its all very clearly explained

Thank you. Is there a widescreen mode and resolution change? Can you tell me where to download for the original version? Jap 1.25.11

**Comment by nolrinale** [comment]
PSO is not a widescreen game, you already have the original version.

Please close this ticket as resolved
