### ISSUE TITLE
[Blue Burst] Unable to get special mag colors at character creation

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#526]
**Describe the bug**
I'm trying to create a random character to steal their mag color, in this case I'm creating a FOnewn with costume color 4 of the 2nd row (green) and I keep getting this mag 
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/91f045ef-c700-470c-809e-69e283285f0e)

I've tried to recreate him several times but looks like this color is fixed to this costume,

The Mag Color PSOW guide mentions theres a chance I can get either (I'm looking for the 2nd)
https://www.pso-world.com/sections.php?op=viewarticle&artid=1017
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/a227b95d-6291-4f49-a214-af2ca5132da0)
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/9fbb65dc-b584-4089-9564-068897942888)

I jumped to PSOGC and i attempted to create the same character with the same costume and I was able to get both mag variations after a few tries.

Unless I'm being extremelly unlucky at the moment of character creation in PSOBB this behavior seems broken in this version, please check it on your side with your favorite colors. 

The correct behavior here is that theres a random chance you should be able to get the slighly lighter version of the color of the mag at the time of character creation. 

----------------------------------------------------

2nd case:

I attempted to create several times the same FOnenwn this time with Costume Color 4 Row 1 (the other green) and I obtained this mag
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/2425ba50-78c7-4849-b991-4240d219282d)

I tried to recreate him several times and i kept getting this same mag, the situation with this dark green mag is that this one only can be obtained from a special costume color
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/71b7c88b-260a-4c25-82b4-057a4fa6f622)

So once again I jumped to PSOGC and tried with this costume and I got the original green variations posted in the 1st case as intended.

So I think theres a problem with the costume colors and the mags overall for PSOBB

**To reproduce**

I am aware this was tested before but maybe not enough, so before you dismiss once again this report at the very least try to create a character with the same specs in both PSOGC/PSOBB so you get to see it with your own eyes. 

1. Create a new FOnewn
2. Select the Costume 4 from Row 2 (green)
3. Verify Mag color in PSOGC/PSOBB
4. Repeat the step a few times (try to recreate it 10 times or so in both versions) 

**To reproduce 2nd case**

1. Create a new FOnewn
2. Select the Costume 4 from Row 1 (green)
3. Verify Mag color in PSOGC/PSOBB
4. Repeat the step a few times (try to recreate it 10 times or so in both versions) 

**Game version(s) (choose one or more of the following):**
 BB

**Comment by Matt-Swift** [comment]
This will be because Blue Burst does not follow the same system as other versions when it comes to generating mag colours on new characters, so there is most likely nothing to fix here (I haven't looked at the mag colour assignment in newserv for BB).

On Blue Burst, each outfit is assigned a specific mag colour rather than it rolling between 2 colours (for outfits 1-7) or all colours (outfits 8/9). The examples you have shown is the correct behaviour, and since you're using PSO-World as a source, I'm surprised you didn't see this which shows this in action (if you scroll to the bottom, it shows you that a regular outfit also has a set colour): https://www.pso-world.com/sections.php?op=viewarticle&artid=2308

**Comment by nolrinale** [comment]
Feel free to close it then, Just in case I would recommend to take a look at the way the BB system works again in case something was missing or wasnt implemented correctly but is just a recommendation at this point

**Comment by fuzziqersoftware** [comment]
The mag color table `static const array<array<uint8_t, 25>, 12> mag_colors` in `PSOBBCharacterFile::create_from_config` was taken from the PSOBB client, and the logic using it was reverse-engineered from `default_mag_color_for_char_class_and_costume` within the PSOBB client, so it's presumably correct. The logic indeed does not match PSOGC's logic.
