### ISSUE TITLE
[Blue Burst] Mag PBs/Triggers are getting messed up after using a Mag Cell Item

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#527]
**Describe the bug**
I was farming EP4 and a rappy dropped a "Rappy Beak" this rappy beak is a mag cell item that evolves your mag into a cute rappy by using it.

The problem here is that by using it the PB's of your original mag are corrupted and replaced with incorrect ones, for example, I used this one in my current FO mag which was a Kabanda with Leilla and Mylla & Youla, they both got replaced by 2 Farllas when I reloged back into the game after using the Cell

Note: I haven't verified if the PB triggers (Boss/HP/100) are correct either but would be wise to check those too after using a Mag Cell kit

**To reproduce**
Fill in steps to reproduce the behavior, such as:
1. Use a Rappy Beak in a 3rd Evolution Mag
2. The mag turns into a Rappy Mag
3. Verify Stats and PBs (They will look correct)
4. Relogin
5. Verify Stats and PBs again (The PBs will be messed up or replaced with others)

**Game version(s) (choose one or more of the following):**
BB

**Server log output**
[RappyBeakWrongPB.txt](https://github.com/user-attachments/files/15876593/RappyBeakWrongPB.txt)

**Additional context**
List of Cells
https://wiki.pioneer2.net/w/Mags#Cell_Mags

**Comment by fuzziqersoftware** [comment]
This has been fixed.
