### ISSUE TITLE
Cant Login with PSOBB client

### ISSUE THREAD

**Issue by Sancaros** [fuzziqersoftware/newserv#53]
I 1410974 2023-01-05 04:53:41 - [Commands] Sending to C-2 (version=Patch command=13 flag=00)
0000 | 70 01 13 00 09 00 43 00 37 00 6E 00 65 00 77 00 | p     C 7 n e w 
0010 | 73 00 65 00 72 00 76 00 20 00 70 00 61 00 74 00 | s e r v   p a t 
0020 | 63 00 68 00 20 00 73 00 65 00 72 00 76 00 65 00 | c h   s e r v e 
0030 | 72 00 0A 00 0A 00 54 00 68 00 69 00 73 00 20 00 | r     T h i s   
0040 | 73 00 65 00 72 00 76 00 65 00 72 00 20 00 69 00 | s e r v e r   i 
0050 | 73 00 20 00 6E 00 6F 00 74 00 20 00 61 00 66 00 | s   n o t   a f 
0060 | 66 00 69 00 6C 00 69 00 61 00 74 00 65 00 64 00 | f i l i a t e d 
0070 | 20 00 77 00 69 00 74 00 68 00 2C 00 20 00 73 00 |   w i t h ,   s 
0080 | 70 00 6F 00 6E 00 73 00 6F 00 72 00 65 00 64 00 | p o n s o r e d 
0090 | 20 00 62 00 79 00 2C 00 20 00 6F 00 72 00 20 00 |   b y ,   o r   
00A0 | 69 00 6E 00 20 00 61 00 6E 00 79 00 0A 00 6F 00 | i n   a n y   o 
00B0 | 74 00 68 00 65 00 72 00 20 00 77 00 61 00 79 00 | t h e r   w a y 
00C0 | 20 00 63 00 6F 00 6E 00 6E 00 65 00 63 00 74 00 |   c o n n e c t 
00D0 | 65 00 64 00 20 00 74 00 6F 00 20 00 53 00 45 00 | e d   t o   S E 
00E0 | 47 00 41 00 20 00 6F 00 72 00 20 00 53 00 6F 00 | G A   o r   S o 
00F0 | 6E 00 69 00 63 00 20 00 54 00 65 00 61 00 6D 00 | n i c   T e a m 
0100 | 2C 00 20 00 61 00 6E 00 64 00 20 00 69 00 73 00 | ,   a n d   i s 
0110 | 20 00 6F 00 77 00 6E 00 65 00 64 00 0A 00 61 00 |   o w n e d   a 
0120 | 6E 00 64 00 20 00 6F 00 70 00 65 00 72 00 61 00 | n d   o p e r a 
0130 | 74 00 65 00 64 00 20 00 63 00 6F 00 6D 00 70 00 | t e d   c o m p 
0140 | 6C 00 65 00 74 00 65 00 6C 00 79 00 20 00 69 00 | l e t e l y   i 
0150 | 6E 00 64 00 65 00 70 00 65 00 6E 00 64 00 65 00 | n d e p e n d e 
0160 | 6E 00 74 00 6C 00 79 00 2E 00 00 00 00 00 00 00 | n t l y .       
I 1410974 2023-01-05 04:53:41 - [Commands] Sending to C-2 (version=Patch command=0B flag=00)
0000 | 04 00 0B 00                                     |                 
I 1410974 2023-01-05 04:53:41 - [Commands] Sending to C-2 (version=Patch command=09 flag=00)
0000 | 44 00 09 00 2E 00 00 00 00 00 00 00 00 00 00 00 | D   .           
0010 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0020 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0030 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0040 | 00 00 00 00                                     |                 
I 1410974 2023-01-05 04:53:41 - [Commands] Sending to C-2 (version=Patch command=09 flag=00)
0000 | 44 00 09 00 64 61 74 61 00 00 00 00 00 00 00 00 | D   data        
0010 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0020 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0030 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
0040 | 00 00 00 00                                     |                 
I 1410974 2023-01-05 04:53:41 - [Commands] Sending to C-2 (version=Patch command=0C flag=00)
0000 | 28 00 0C 00 00 00 00 00 6E 65 77 73 65 72 76 2D | (       newserv-
0010 | 74 65 73 74 2D 62 62 2E 74 78 74 00 00 00 00 00 | test-bb.txt     
0020 | 00 00 00 00 00 00 00 00                         |                 
I 1410974 2023-01-05 04:53:41 - [Commands] Sending to C-2 (version=Patch command=0A flag=00)
0000 | 04 00 0A 00                                     |                 
I 1410974 2023-01-05 04:53:41 - [Commands] Sending to C-2 (version=Patch command=0A flag=00)
0000 | 04 00 0A 00                                     |                 
I 1410974 2023-01-05 04:53:41 - [Commands] Sending to C-2 (version=Patch command=0D flag=00)
0000 | 04 00 0D 00                                     |                 
I 1410974 2023-01-05 04:53:41 - [Commands] Received from C-2 (version=Patch command=0F flag=00)
0000 | 10 00 0F 00 00 00 00 00 B0 5F 40 D1 33 00 00 00 |          _@ 3   
I 1410974 2023-01-05 04:53:41 - [Commands] Received from C-2 (version=Patch command=10 flag=00)
0000 | 04 00 10 00                                     |                 
I 1410974 2023-01-05 04:53:41 - File newserv-test-bb.txt is up to date
I 1410974 2023-01-05 04:53:41 - [Commands] Sending to C-2 (version=Patch command=12 flag=00)
0000 | 04 00 12 00                                     |                 
I 1410974 2023-01-05 04:53:41 - [Server] Client disconnected: C-2 on fd 35

**Comment by fuzziqersoftware** [comment]
Without a description of the issue, this log isn't sufficient to diagnose the problem. Please open another issue if the problem persists.
