### ISSUE TITLE
[newserv] `reload config` is not working anymore

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#532]
**Describe the bug**
I tried today to run the local server and upon using `reload config` I was getting parsing errors with some of the new items added in the recent Coren PR so I fixed the item names verifying they load correctly in-game and created this other https://github.com/fuzziqersoftware/newserv/pull/531 PR with the correct values

However after fixing the item names I tried again to do `reload config` and this time it didn't throw me any parsing error but it gets stalled on "Creating Menus" and i'm not really sure where the error could be in the config.json, im not even sure if its a config.json issue to begin with.

Killing the whole server process and starting it again loads all the values correctly tho it's just with the `reload config` menu that I get this output

```
newserv> I 79045 2024-06-26 12:13:51 - [Config] Loading configuration
I 79045 2024-06-26 12:13:51 - [Config] Added local address: 192.168.1.100
I 79045 2024-06-26 12:13:51 - [Config] Added external address: 10.0.1.5
I 79045 2024-06-26 12:13:51 - [Config] Creating menus
```

The server continues normal operation tho

Couple things I tried with no success:
-replace all the elements within the arrays of the coren rewards with the sole hex code of a saber (thinking that maybe the textual item name parser might have an issue)
-removed the whole section related to coren rewards
-removed extra commas at the end of the final element of the arrays and objects

**Comment by fuzziqersoftware** [comment]
This is correct behavior; the config was reloaded and the server continued serving. After reloading, did you see any evidence that the configuration was not actually reloaded?

**Comment by nolrinale** [comment]
everything seemed fine, is just that i was expecting more verbosity from the console maybe?

like it does in the initial run setup that does a huge log of all the quests is preloading , etc, etc.

**Comment by fuzziqersoftware** [comment]
The config has a diverse set of options, including fields that affect other parts of the server (e.g. quest categories), but most of these fields individually don't warrant log messages, so loading the config doesn't result in much log output. The server doesn't automatically reload things that depend on these fields, so short log output is expected in this case.

**Comment by nolrinale** [comment]
give it a try with the latest PR and if you see it fine feel free to close this one then
