### ISSUE TITLE
[Blue Burst] Withdrawing max grinded weapons in the Bank ends up removing the grind on inventory but keeping (and increasing +1) in the bank

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#533]
**Describe the bug**

Depositing a Max grinded weapon in the bank such as a Visk +15 ends up increasing it's value +1 (beyond bounds) if you withdraw and deposit it several times (check sequence below)

**To reproduce**

1. $item VISK-235W
2. Grind it to +14 
3. Deposit it in the bank
4. Withdraw from the bank
5. Use a trigrinder for the final grind and grind it to +15
6. Deposit in the bank again
7. Withdraw it from the bank
8. It's in your inventory as +0 grind
9. Deposit it in your bank again
10. Check the Bank Item Box
11. Should appear as +17 or +0
12. Repeat till you have it in your inventory
13. Use a grinder
14. Get Error 100

**Game version(s) (choose one or more of the following):**
BB & GC (Maybe...)

**Server log output**
[OvergrinderError100.txt](https://github.com/user-attachments/files/15994865/OvergrinderError100.txt)

**Comment by nolrinale** [comment]
Attempted to replicate it on the test server using trigrinders and 1 digrinder to go from +14 -> +17 
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/37037aa6-d376-4a1f-93ce-b79b60cd0495)

Weapon ended with +15 as intended , no dced either
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/f00c6901-92a7-4195-aada-401af98d8e09)

**Comment by fuzziqersoftware** [comment]
This has been fixed.
