### ISSUE TITLE
[Blue Burst] Incorrect Ep2 event quest visibility after enabling "Summer" event

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#535]
**Describe the bug**
Enabling summer event should make the quest "Festivity On The Beach" visible for all users, however, in addition to this one it also enables "Pioneer Christmas" 

However the xmas quest appears only if you make a room alone, as soon as a 2nd player joins the room the xmas event dissapears from the Event quest list.

**To reproduce**
Fill in steps to reproduce the behavior, such as:
1. Enable Summer event in the server
2. Create EP2 room, check under Events and both Festivities and Pioneer Christmas should be there
3. Invite another player to the room
4. Check the quest list again and Pioneer Christmas should be gone displaying only Festivities at the Beach as intended.

**Game version(s) (choose one or more of the following):**
BB

**Additional context**
Theres also a problem with the Summer event, in the lobby it turns the trees into pink trees, this one is incorrect as they belong to the Spring season event it should display the variation with the normal Green trees and the White/Red Stripes Stage behind instead. 

With 1 player
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/9b89dc49-9996-4700-b40b-1a95187cf40f)

With 2 player
![image](https://github.com/fuzziqersoftware/newserv/assets/5244595/477e1df4-55e4-416e-9d81-4c28f8e58a9c)

**Comment by fuzziqersoftware** [comment]
This has been fixed.
