### ISSUE TITLE
[Blue Burst] Quest meseta rewards arent visually given if you skip the final dialog too fast.

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#537]
**Describe the bug**
This one was reported previously at https://github.com/fuzziqersoftware/newserv/issues/520 before and was unable to recreate it until today. 

This is a very strange situation so first you need to have a mix of a bad connection between the client <> server and also be extremelly fast skipping the dialogs after clearing the quest.

For example I was having wifi issues at the moment of clearing the East tower on normal, so I went to the hunters guild NPC and quickly skipped the dialog stating i received 5000 meseta as a reward then returned to lobby.

Upon returning to lobby I noticed I had only my original 3k meseta I was expecting to have 8k

So I quit the game and relogged back on, then I had my 8k mesetas already in the inventory.

It is a visual error rather than a logic but i'm not sure if an additional check can be done at the moment of returning to lobby to avoid this issue?

**Game version(s) (choose one or more of the following):**
BB

**Comment by fuzziqersoftware** [comment]
This is because the quest reward and return to lobby sequence all happens client-side, so by the time the Meseta reward command is sent back by the server, the player has already returned to the lobby and the client rejects the command. It's not possible for the server to detect this case and work around it since it involves commands crossing paths on the network.

**Comment by nolrinale** [comment]
But this behavior is not normal, shall we check it out on Ephinea and other servers? in fact, in the official servers people would hd complained a lot for this too if its really only the client's fault

**Comment by fuzziqersoftware** [comment]
Well, I don't know what to tell you here - the log in the other issue clearly shows the server giving all players the quest reward, and the 98 commands sent by the clients show the correct Meseta amounts at the time they leave the game. So unless you have a log showing a client sending a 98 command with the wrong Meseta amount after a quest reward, this isn't a server issue.

**Comment by nolrinale** [comment]
Again, it is a visual issue, the meseta seems fine the reward is not lost and is sent by the server is just that is not updated on the client's meseta counter after returning to the lobby if you skip the messages too fast

Look here I just cleared a quest on Ephinea and to my surprise it was even faster the transition between the game and the lobby, yet the meseta counter got updated properly
https://github.com/fuzziqersoftware/newserv/assets/5244595/a9f8603f-6ff2-4873-93f3-783a7d2c316e

Since they are your friends, maybe you can ask them too for more insight about this

**Comment by fuzziqersoftware** [comment]
I'm not going to work on this.
