### ISSUE TITLE
Array subscript 16 is outside array bounds

### ISSUE THREAD

**Issue by rumatsuki** [fuzziqersoftware/newserv#54]
Attempting to build as release causes the following error.

```
In file included from /home/me/newserv/src/PSOEncryption.hh:11,
                 from /home/me/newserv/src/ProxyServer.hh:15,
                 from /home/me/newserv/src/ProxyCommands.cc:1:
/home/me/newserv/src/Text.hh: In function ‘HandlerResult S_65_67_68(std::shared_ptr<ServerState>, ProxyServer::LinkedSession&, uint16_t, uint32_t, std::str                                                                                                                                                                ing&) [with CmdT = S_JoinLobby_DC_GC_65_67_68_Ep3_EB]’:
/home/me/newserv/src/Text.hh:54:11: warning: array subscript 16 is outside array bounds of ‘ptext<char, 16> [1]’ [-Warray-bounds]
   54 |   for (; s[ret] != 0 && ret < count; ret++) { }
      |          ~^
/home/me/newserv/src/ProxyCommands.cc:1244:25: note: while referencing ‘name’
 1244 |       ptext<char, 0x10> name = cmd.entries[x].disp.name;
      |                         ^~~~
```

**Comment by fuzziqersoftware** [comment]
Which OS/platform are you building on? I haven't seen this error on macOS or Ubuntu.
I've pushed a change just now that may fix it for you, but I can't verify since this error doesn't arise for me.

**Comment by rumatsuki** [comment]
I'm building on Debian 11 amd64.

**Comment by rumatsuki** [comment]
I've tried to build again with the new changes and still get the same error. Changing `ret < count` to `ret < count + 1` seems to fix it, but I'm not sure if that's a good fix.

**Comment by fuzziqersoftware** [comment]
I must not have been fully awake when I "fixed" it earlier today - the issue is that the conditions were in the wrong order. (Note to self: don't write code when sleep-deprived.) It should be actually fixed now.

**Comment by rumatsuki** [comment]
Seems to work now, thanks!
