### ISSUE TITLE
[Blue Burst] LOGiN Presents Match Race fails to load while in a party fo 4 players

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#541]
**Describe the bug**
Attempting to load the quest Login Match Race in a normal Episode 4 room under the Event category ends with the host client stuck in the loading prompt without the loading progress bar being displayed and the other clients either disconnected or stuck as shown in the screenshot

![image](https://github.com/user-attachments/assets/4f686beb-f66b-41b9-a204-d5bd60d59646)

**To reproduce**
Fill in steps to reproduce the behavior, such as:
1. Connect 4 clients to the game and create an EP4 normal room (this quest requires 4 players to start)
2. Load the quest LOGiN Match Race
3. The quest fails to load

**Game version(s) (choose one or more of the following):**
BB

**Server log output**
[LOGINPresentsStuckLoading4P.txt](https://github.com/user-attachments/files/16196204/LOGINPresentsStuckLoading4P.txt)

**Additional context**
This same error also happens from time to time with other EP4 quests when the network environment isnt stable enough (Wifi)

**Comment by fuzziqersoftware** [comment]
This has been fixed.
