### ISSUE TITLE
Cant Connect to the server

### ISSUE THREAD

**Issue by legochad3** [fuzziqersoftware/newserv#542]
**Describe the bug**
For Some Reason i cant connect to the server using TethVer12513_English
it gives me a NO916
![Screenshot 2024-07-18 140726](https://github.com/user-attachments/assets/8b67bf70-138a-495e-928a-48aa7781f943)

**Game version(s) (choose one or more of the following):**
 BB

**Server log output**
I 1879 2024-07-18 14:02:28 - [Server] Client connected: C-1 on fd 40 via 32 (TG-12000-BB_V4-bb-init-login_server)
I 1879 2024-07-18 14:02:28 - [Commands] Sending to C-1 @ ipv4:127.0.0.1:65310 (version=BB command=0003 flag=00000000)
0000 | 7C 01 03 00 00 00 00 00 50 68 61 6E 74 61 73 79 | |       Phantasy
0010 | 20 53 74 61 72 20 4F 6E 6C 69 6E 65 20 42 6C 75 |  Star Online Blu
0020 | 65 20 42 75 72 73 74 20 47 61 6D 65 20 53 65 72 | e Burst Game Ser
0030 | 76 65 72 2E 20 43 6F 70 79 72 69 67 68 74 20 31 | ver. Copyright 1
0040 | 39 39 39 2D 32 30 30 34 20 53 4F 4E 49 43 54 45 | 999-2004 SONICTE
0050 | 41 4D 2E 00 00 00 00 00 00 00 00 00 00 00 00 00 | AM.
0060 | 00 00 00 00 00 00 00 00 5E 81 A8 41 AD D0 8F 20 |         ^  A
0070 | 75 5C FF 3F 8F C1 43 3F 2D BA 5B F2 2D C3 B7 E1 | u\ ?  C?- [ -
0080 | 5C F5 34 99 BA B2 5A 49 58 A4 32 38 20 6E E2 DA | \ 4   ZIX 28 n
0090 | 00 50 69 45 9E 77 3F 18 D0 EE 01 33 AD AE 04 BB |  PiE w?    3
00A0 | 7D A2 D3 D1 6D 01 CF 66 5F C3 97 6C 6C 2A CC 71 | }   m  f_  ll* q
00B0 | 13 10 10 EA E2 03 2B 4F 18 A4 FC 3B CE EF 86 6A |       +O   ;   j
00C0 | 8C DB DB F5 D4 47 94 B9 54 68 69 73 20 73 65 72 |      G  This ser
00D0 | 76 65 72 20 69 73 20 69 6E 20 6E 6F 20 77 61 79 | ver is in no way
00E0 | 20 61 66 66 69 6C 69 61 74 65 64 2C 20 73 70 6F |  affiliated, spo
00F0 | 6E 73 6F 72 65 64 2C 20 6F 72 20 73 75 70 70 6F | nsored, or suppo
0100 | 72 74 65 64 20 62 79 20 53 45 47 41 20 45 6E 74 | rted by SEGA Ent
0110 | 65 72 70 72 69 73 65 73 20 6F 72 20 53 4F 4E 49 | erprises or SONI
0120 | 43 54 45 41 4D 2E 20 54 68 65 20 70 72 65 63 65 | CTEAM. The prece
0130 | 64 69 6E 67 20 6D 65 73 73 61 67 65 20 65 78 69 | ding message exi
0140 | 73 74 73 20 6F 6E 6C 79 20 74 6F 20 72 65 6D 61 | sts only to rema
0150 | 69 6E 20 63 6F 6D 70 61 74 69 62 6C 65 20 77 69 | in compatible wi
0160 | 74 68 20 70 72 6F 67 72 61 6D 73 20 74 68 61 74 | th programs that
0170 | 20 65 78 70 65 63 74 20 69 74 2E 00             |  expect it.
I 1879 2024-07-18 14:02:28 - [Commands] Received from C-1 @ ipv4:127.0.0.1:65310 (version=BB command=0093 flag=00000000)
0000 | B4 00 93 00 00 00 00 00 00 00 01 00 00 00 00 00 |
0010 | 41 00 00 00 00 FF 00 00 00 00 00 00 6C 65 67 6F | A           lego
0020 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |
0030 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |
0040 | 00 00 00 00 00 00 00 00 00 00 00 00 31 32 33 34 |             1234
0050 | 35 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | 5
0060 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |
0070 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |
0080 | 00 00 00 00 81 01 01 51 57 C1 01 09 54 65 74 68 |        QW   Teth
0090 | 56 65 72 31 32 35 31 33 00 00 00 00 00 00 00 00 | Ver12513
00A0 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |
00B0 | 00 00 00 00                                     |
I 1879 2024-07-18 14:02:28 - [C-1] Client is TethVer subtype; forcing English language
I 1879 2024-07-18 14:02:28 - [Commands] Sending to C-1 @ ipv4:127.0.0.1:65310 (version=BB command=00E6 flag=00000000)
0000 | 44 00 E6 00 00 00 00 00 00 00 00 00 00 00 01 00 | D
0010 | 88 55 4D 2D 00 00 00 00 32 AC 99 83 4C 4E 39 35 |  UM-    2   LN95
0020 | FF FF FF FF FF FF FF FF 00 96 00 04 20 00 00 00 |
0030 | 00 00 00 00 00 00 00 00 00 00 FF FF 80 FF FF FF |
0040 | 01 01 00 00                                     |
I 1879 2024-07-18 14:02:28 - [Commands] Sending to C-1 @ ipv4:127.0.0.1:65310 (version=BB command=0019 flag=00000000)

**Comment by fuzziqersoftware** [comment]
Did you set LocalAddress and ExternalAddress in config.json?

**Comment by legochad3** [comment]
![image](https://github.com/user-attachments/assets/1916df4f-2b8c-4b77-aaae-0118b088e00e)

**Comment by Shade53** [comment]
I'm encountering a similar issue, at least I think it is similar, but a different error. I'm getting error "No903", "Patch server connection failed". Client is "TethVer12513", English.

I have all logs set to "DEBUG" level, here are the logs as follows:
```I 4036722 2024-08-13 12:24:04 - [Config] DNS server is disabled
I 4036722 2024-08-13 12:24:04 - [Config] Opening sockets
I 4036722 2024-08-13 12:24:04 - [Config] Starting proxy server
I 4036722 2024-08-13 12:24:04 - [ProxyServer:T-5120] Listening on TCP port 5120 (DC_V2) on fd 8
I 4036722 2024-08-13 12:24:04 - [Config] Starting game server
I 4036722 2024-08-13 12:24:04 - [Server] Listening on TCP interface 5112 on fd 9 as TG-5112-BB_V4-bb-lobby-lobby_server
I 4036722 2024-08-13 12:24:04 - [Server] Listening on TCP interface 9204 on fd 10 as TG-9204-GC_V3-gc-eu3-60b-login_server
I 4036722 2024-08-13 12:24:04 - [Server] Listening on TCP interface 5111 on fd 11 as TG-5111-PC_V2-pc-lobby-lobby_server
I 4036722 2024-08-13 12:24:04 - [Server] Listening on TCP interface 5110 on fd 12 as TG-5110-GC_V3-console-lobby-lobby_server
I 4036722 2024-08-13 12:24:04 - [Server] Listening on TCP interface 9100 on fd 13 as TG-9100-PC_V2-gc-us10-pc_console_detect
I 4036722 2024-08-13 12:24:04 - [Server] Listening on TCP interface 12004 on fd 14 as TG-12004-BB_V4-bb-data1-login_server
I 4036722 2024-08-13 12:24:04 - [Server] Listening on TCP interface 9000 on fd 15 as TG-9000-GC_V3-gc-jp10-login_server
I 4036722 2024-08-13 12:24:04 - [Server] Listening on TCP interface 9201 on fd 16 as TG-9201-GC_V3-gc-eu11-login_server
I 4036722 2024-08-13 12:24:04 - [Server] Listening on TCP interface 9003 on fd 17 as TG-9003-GC_V3-gc-jp3-login_server
I 4036722 2024-08-13 12:24:04 - [ProxyServer:T-5124] Listening on TCP port 5124 (BB_V4) on fd 18
I 4036722 2024-08-13 12:24:04 - [Server] Listening on TCP interface 9203 on fd 19 as TG-9203-GC_V3-gc-eu3-60a-login_server
I 4036722 2024-08-13 12:24:04 - [Server] Listening on TCP interface 9200 on fd 20 as TG-9200-GC_V3-gc-eu10-login_server
I 4036722 2024-08-13 12:24:04 - [Server] Listening on TCP interface 9064 on fd 21 as TG-9064-GC_V3-gc-us12t1-login_server
I 4036722 2024-08-13 12:24:04 - [Server] Listening on TCP interface 5105 on fd 22 as TG-5105-XB_V3-xb-lobby-login_server
I 4036722 2024-08-13 12:24:04 - [ProxyServer:T-5122] Listening on TCP port 5122 (GC_V3) on fd 23
I 4036722 2024-08-13 12:24:04 - [ProxyServer:T-5123] Listening on TCP port 5123 (XB_V3) on fd 24
I 4036722 2024-08-13 12:24:04 - [Server] Listening on TCP interface 12005 on fd 25 as TG-12005-BB_V4-bb-data2-login_server
I 4036722 2024-08-13 12:24:04 - [ProxyServer:T-5121] Listening on TCP port 5121 (PC_V2) on fd 26
I 4036722 2024-08-13 12:24:04 - [Server] Listening on TCP interface 9202 on fd 28 as TG-9202-GC_V3-gc-eu3-50-login_server
I 4036722 2024-08-13 12:24:04 - [Server] Listening on TCP interface 9103 on fd 29 as TG-9103-GC_V3-gc-us3-login_server
I 4036722 2024-08-13 12:24:04 - [Server] Listening on TCP interface 9002 on fd 30 as TG-9002-GC_V3-gc-jp3te-login_server
I 4036722 2024-08-13 12:24:04 - [Server] Listening on TCP interface 9001 on fd 31 as TG-9001-GC_V3-gc-jp11-login_server
I 4036722 2024-08-13 12:24:04 - [Config] Starting PC_V2 patch server
I 4036722 2024-08-13 12:24:04 - [Server] Listening on TCP interface 10000 on fd 36 as TU-10000-pc-patch-patch2
I 4036722 2024-08-13 12:24:04 - [Server] Listening on TCP interface 12000 on fd 37 as TG-12000-BB_V4-bb-init-login_server
I 4036722 2024-08-13 12:24:04 - [Config] Starting BB_V4 patch server
I 4036722 2024-08-13 12:24:04 - [Server] Listening on TCP interface 11000 on fd 42 as TU-11000-bb-patch-patch4
I 4036722 2024-08-13 12:24:04 - [Server] Listening on TCP interface 5101 on fd 43 as TG-5101-PC_V2-pc-login-login_server
I 4036722 2024-08-13 12:24:04 - [Server] Listening on TCP interface 9500 on fd 44 as TG-9500-XB_V3-xb-login-login_server
I 4036722 2024-08-13 12:24:04 - [Server] Listening on TCP interface 5100 on fd 45 as TG-5100-GC_V3-console-login-login_server
I 4036722 2024-08-13 12:24:04 - [Server] Listening on TCP interface 11101 on fd 46 as TG-11101-BB_V4-bb-init2-login_server
I 4036722 2024-08-13 12:24:04 - [Server] Listening on TCP interface 13000 on fd 47 as TU-13000-bb-patch4-patch4
I 4036722 2024-08-13 12:24:04 - [Server] Listening on TCP interface 14000 on fd 48 as TG-14000-BB_V4-bb-init4-login_server
I 4036722 2024-08-13 12:24:04 - [Server] Listening on TCP interface 9300 on fd 49 as TG-9300-PC_V2-pc-login_server
I 4036722 2024-08-13 12:24:04 - [Server] Listening on TCP interface 11200 on fd 50 as TU-11200-bb-patch-hg-patch4
I 4036722 2024-08-13 12:24:04 - [Server] Listening on TCP interface 11100 on fd 51 as TU-11100-bb-patch2-patch4
I 4036722 2024-08-13 12:24:04 - [Config] Starting HTTP server
I 4036722 2024-08-13 12:24:04 - [Server] Listening on TCP interface 192.168.100.10:51036 on fd 57 (HTTP)
I 4036722 2024-08-13 12:24:04 - [Config] Ready
newserv> I 4036722 2024-08-13 12:24:11 - [C-1] Created
I 4036722 2024-08-13 12:24:11 - [Server] Patch client connected: U-1 on fd 58 via 42 (TU-11000-bb-patch-patch4)
I 4036722 2024-08-13 12:24:11 - [Server] Client disconnected: C-1
```

My address settings are as follows, but with public address censored:
![image](https://github.com/user-attachments/assets/f11ca1df-5561-479e-a4ab-11a6e87ca7f6)

Oddly enough, when testing other devices to see if they had the same issue I found that only local clients couldn't connect using the local IP address, but when connecting my laptop to my cell data and connecting using the external address I was successful. This only started happening with newer builds starting with the build that introduced material count resets, but the older version, that I have not replaced with the new build yet, works with no issues.

I have no way of testing if an internal client with the public IP address can connect or not as our ISP modem/router doesn't support "Hairpin NAT".

Let me know if this is different enough to need its own issue or if you need more details as I will be happy to test and provide more data. Also, if there is a way I don't know of to get the program to generate log files then that would be great as the usual "./newserv > server.log 2>&1" doesn't seem to work.

Oh! And thanks for your work on this server, it's actually pretty cool and feature-ful!

**Comment by fuzziqersoftware** [comment]
A few questions...
* Are you using a release build, or are you building from source yourself?
* Which OS are you running on? There may be issues with the patch server on Windows; I primarily run on macOS, and there's no automated testing for Windows since the build environment is very different and hard to set up.
* If you pick "Patch download" from the title screen menu, does you get the same result?
* Could you capture another log with HideDownloadCommands set to false, if it isn't already?

**Comment by Shade53** [comment]
Sure!

- I am building from source.
- I am running the server on a Debian 12, KDE system. This is also the build system.
- Yes, I was getting the same error when selecting "Patch download"
- This was set to false to limit logging data, set it to true, this actually helped me a lot XD

After setting HideDownloadCommands to true I noticed I was getting a bunch of authentication issues. I thought that was odd since I had copied the player folder from the live server to the build folder, but turns out I had forgotten the license keys. Oops.

After copying the licenses folder over I was able to successfully connect to the new test build. It even fixed the quests that were soft-locking my local clients similar to the other issue! I'll be sure to remember that there is very useful debug data at times in the download commands and remember to turn them on if I am ever not seeing an issue in the normal debug level logs.

You can consider this issue resolved, but one last question if you don't mind:
Any chance you could provide a list of what folders and files I should be transferring over to the live server when I am ready to update it from a build? As I can't seem to spot any kind of manifest I can recognize in the make files, though I do admit I may be overlooking it likely.

For now I will be using the .gitignore to direct me as to what NOT to copy over to the live server.

**Comment by fuzziqersoftware** [comment]
The files and directories which you probably want to avoid accidentally overwriting are:
* system/ep3/tournament-state.json
* system/ep3/battle-records/
* system/licenses/
* system/players/
* system/teams/

All other files in system/ are static; they are only read and never written by the server.
