### ISSUE TITLE
[Blue Burst] Reset Materials via commands

### ISSUE THREAD

**Issue by LilyRosen** [fuzziqersoftware/newserv#543]
**Is your feature request related to a problem? Please describe.**
There is no method to reset material counts, and manually adjusting stats through the edit command does not affect material count.

**Describe the solution you'd like**
A command to reset the Material usage and stats from said materials on a character, except for HP and TP.

**Game version(s) (choose one or more of the following):**
BB

**Comment by fuzziqersoftware** [comment]
This has been added; there is now `$edit mat reset <which>` (see README for details).
