### ISSUE TITLE
[Blue Burst] Certain quests (incl. Gallon's Shop) get stuck at loading

### ISSUE THREAD

**Issue by frognard** [fuzziqersoftware/newserv#544]
Running localhost on teth12513. 
Most quests load and play ok, but some, namely ep2 GALLON'S SHOP, or ep4 WARRIOR'S PRIDE get stuck at loading.

**Comment by fuzziqersoftware** [comment]
This has been fixed on master. If you're building from source, you'll have to pull master from phosg, resource_dasm (if you built with it), and newserv, and rebuild all of them. There probably won't be a new release for a while, so if you're using a release, you may want to build from source instead.
