### ISSUE TITLE
[BB][Feature Request] Omnispawn exp bug

### ISSUE THREAD

**Issue by toiletman74** [fuzziqersoftware/newserv#550]
I put this in a feature request since support for omnispawn probably doesn't align with newserv's goals

**Is your feature request related to a problem? Please describe.**
Currently using omnispawn with cross episode enemies (ex. goran in ep2) loads up most battle parameters correctly but doesn't seem to load exp

**Game version(s) (choose one or more of the following):**
BB

**Additional context**
As far as I can tell using omnispawn with enemies normally in the episode (ex. sinow beat in forest) exp works correctly

**Comment by fuzziqersoftware** [comment]
a9b816c5 may fix this, if I understand how omnispawn actually works. I wasn't able to test this; I don't have an appropriate build environment set up for the BB patch project. Please try it and let me know if it works.

**Comment by toiletman74** [comment]
I'll update the server tonight when less people are online and test it. Thanks for looking into this!

**Comment by toiletman74** [comment]
it appears to be working! thanks again
