### ISSUE TITLE
[BB] Falz, Olga, and Saint-million don't drop anything

### ISSUE THREAD

**Issue by toiletman74** [fuzziqersoftware/newserv#553]
**Describe the bug**
Killing dark falz, olga flow, or saint-million yields no drops. I also noticed in the itemPT they all have their drop anything rate set to 0, not sure if that has anything to do with it or not.

**Game version(s) (choose one or more of the following):**
BB

**Comment by Matt-Swift** [comment]
This is absolutely the reason they're dropping nothing, as it always fails the drop rate check. You will need to modify the ItemPT to give them drop rates.

For reference, the drop rates for BB on private servers are taken directly from GameCube (since we don't have any knowledge of the BB rates), and GameCube had 0% DAR for both Dark Falz and Olga Flow, while the Episode 4 extension to the drop files was taken from another episode, giving Saint-Milion 0% DAR as well.

**Comment by fuzziqersoftware** [comment]
Matt is correct; this is not a bug. If you have lobby logging enabled, you should see messages in the terminal after killing the bosses that indicate drop checks are occurring but DAR is causing no item to be created. You can edit the ItemPT files using Soly's ItemPT editor; the file ItemPT-gc-v3.gsl is used for both v3 and BB. This file has been manually modified to include Episode 4, however, and I've never used Soly's tools so I'm not sure if it will work with this format.

**Comment by toiletman74** [comment]
it still isn't working even with the DAR set to 100. Here's a capture of the log.

I 559430 2024-08-17 05:50:03 - [Game:D3] Creating item from final boss (DARK_FALZ_2)
I 559430 2024-08-17 05:50:03 - [Game:D3] Found enemy E-6CF on floor E
I 559430 2024-08-17 05:50:03 - [Game:D3] Creating item from enemy 06CF (area 0E)
I 559430 2024-08-17 05:50:03 - [ItemCreator:BB_V4/Ep1/Nml/N/9] Enemy type: 2F
I 559430 2024-08-17 05:50:03 - [ItemCreator:BB_V4/Ep1/Nml/N/9] Drop chosen (0 < 100)
I 559430 2024-08-17 05:50:03 - [ItemCreator:BB_V4/Ep1/Nml/N/9] Rare drop not chosen; item class determinant is 1; item class is 4
I 559430 2024-08-17 05:50:03 - [ItemCreator:BB_V4/Ep1/Nml/N/9] Generating tool with class 03
I 559430 2024-08-17 05:50:03 - [Game:D3] Entity 06CF (area 0E) created item Monofluid x1
I 559430 2024-08-17 05:50:03 - [Game:D3] Creating item CC000000 at 0E:10160.6,0 for C-1D1 (GooG) @ ipv4:72.198.217.172:50179
I 559430 2024-08-17 05:50:03 - [Lobby:000000D3:FloorItems:0E] Added floor item CC000000 at 10160.6, 0 with drop number 0 with flags 1001
I 559430 2024-08-17 05:50:03 - [Lobby:000000D3:FloorItems:0E] Evicted 0 items

**Comment by toiletman74** [comment]
the default itemPT should probably have the DAR set to 100(? not sure what its meant to be at) for those bosses to avoid confusion
