### ISSUE TITLE
[newserv] Error phosg::phosg target library not found while building under Debian 12

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#560]
**Describe the bug**
Attempting to build the server as usual by doing `cmake . && make` fails with a error message stating the `phosg::phosg` library can not be found.

The specific issue is in this line of the cmake list file
https://github.com/fuzziqersoftware/newserv/blob/075c5761163d2cb0c453b665d6bda4ecac593772/CMakeLists.txt#L138

The workaround is to replace at line 138 within the parenthesis the current phosg target of `phosg::phosg` to just `phosg`  then just do `cmake . && make` and it should build the server as usual.

There's also a situation on Debian 12 where cmake currently 3.25 is not supported by these cmake files (including phosg and resource_dasm) anymore and are asking for at least version 3.27 in order to compile, to solve this you must install the very latest cmake 3.30 from the `bookworm-backports` by adjusting your APT sources file accordingly.

This issue also affects the cmake of resource_dasm, just fix the same line on that one and should build without problems too.

**Comment by fuzziqersoftware** [comment]
Did you pull, rebuild, and install phosg as well as resource_dasm?

**Comment by nolrinale** [comment]
Yeah everything, less than 10 mins ago I did the whole procedure from scratch

**Comment by fuzziqersoftware** [comment]
I used a clean Debian 12 VM and phosg, resource_dasm, and newserv do indeed build without any problems. I don't know what's happening on your machine, but it's not a systemic issue. You could try deleting our CMakeCache.txt files and building all three projects again, but I don't know how likely that is to be the issue.

**Comment by Repflez** [comment]
I got this exact issue a bit ago and solved it by doing `rm -rf CMakeFiles/ CMakeCache.txt cmake_install.cmake` to ensure there wasn't anything that could break it. It worked. It also works if you clone the repos again and build like normal.

**Comment by nolrinale** [comment]
Okay I've deleted everything and cloned the 3 projects again
ran the usual `apt update && apt upgrade` just to make sure its up to date
uninstalled the previous cmake from backports and installed the original one from the default apt it reports now ver 3.25.1 by doing `cmake --version`

I start by building phosg and i get the error that is requiring cmake 3.27 or above
the same thing happens with resource and newserv 

Which commands you ran to install the required dependencies in your Debian 12 VM?

**Comment by fuzziqersoftware** [comment]
Either use the latest CMake as Repflez said, or use the backports source as you said originally. The only other package you should have to install manually is libevent-dev, which you presumably already have.

**Comment by nolrinale** [comment]
Just gave it a try again I guess i had very outdated files here, its building as intended now by installing the backports version.

So for this ticket the real issue is to just either adjust the minimum required cmake version or add an entry in the readme to let people know they might need at least version 3.27 onwards of cmake if they happen to be using debian.
