### ISSUE TITLE
[Blue Burst] Using $edit npc command changes your class

### ISSUE THREAD

**Issue by Bluuzeus** [fuzziqersoftware/newserv#563]
I just made a local server and made a FOnewm character. Noticed that after changing to Rico I could no longer equip the starting cane, and turns out it changed my class to HUnewearl. Same with Elly.

I do not remember this being an issue the other times I have played PSOBB, or on my previous Tethealla server.

**Comment by fuzziqersoftware** [comment]
This is intentional because some combinations of classes cause the client to crash when using certain NPCs; see #551 for details. The server changes your character to HUnewearl for the Rico and Elly NPCs, or HUmar for the Ninja and Flowen NPCs.

**Comment by toiletman74** [comment]
Should probably make it so that if a player tries one of the combinations that would crash just don't change the skin instead of changing the character's class. Otherwise you effectively get whatever class you started as + HUney & HUmar all in one if you know that it changes the classes
