### ISSUE TITLE
Port 53 open and free but newserv wont listen

### ISSUE THREAD

**Issue by sirdankz** [fuzziqersoftware/newserv#57]
I freed up port 53 by using

Sudo nano /etc/systemd/resolved.conf

 Editing 
#dns= to dns=127.0.0.1
#DNSStublistener=YES to DNSStublistener=NO

 I created a symbolic link using

Sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resovl.conf

Rebooted

Using lsof -I :53 
I see port 53 is now free to use

Running sudo ./newserv to get the server running

I used netstat -lntu to see what ports are set to LISTEN 
Out of all ports needed for Newserv only port 53 is not set to LISTEN.

I've also made sure to allow port 53 through my Ubuntu firewall with 

sudo ufw allow 53

**Comment by fuzziqersoftware** [comment]
DNS is a UDP protocol, so the socket shouldn't have a TCP state (e.g. LISTEN) at all. Does it respond to DNS queries from other clients correctly? (You can test by running `dig @<newserv-ip-addr> gc01.st-pso.games.sega.net` on another machine.)

**Comment by sirdankz** [comment]
> 
I also tested throught portcheck websites. All the ports show as open but not port 53
I don't have another linux machine to test this. I can connect locally though on another machine but once i try to use a VPN and use the external adresses as the public ip along with local set to 127.0.0.1 I cannot connect. I do have extra usbs so I can probably install linux on those to text this out.

**Comment by sirdankz** [comment]
I made some edits above.
I'm not sure if you get a notification when comments are edited.
