### ISSUE TITLE
[Blue Burst] [Question] client/server map object spawn controls

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#570]
**Describe the bug**
I'm not sure if its client related or server related, but theres a very subtle bug in the way the game loads the map objects that if you by any chance get far away enough you wont see those animated objects anymore unless you reset the map entirely.

The only reason why I'm writing this is because as far I know, the map files are also accompanied by their object with all those files that end in o's such as `map_city02_00_00o.dat` these files are also handled by the server at the time of load the area in the file: 
https://github.com/fuzziqersoftware/newserv/blob/b9fd52c6c1a3a04fd4a010321bd6f6d3686064c3/src/Map.cc#L1705

So I want to confirm with you if this visual bug is just totally client based or theres some sort of lost unimplemented server function that constantly scans and refreshes the objects visibility in the map depending how far away the player are from them?

**To reproduce**
I've been able to reproduce this in various areas but the the easiest way to see this in action:

1. Create an EP1 room and run straight to the Shopping area entrance (reference pics posted below)
2. Notice the moving Orbs in the colunms to the sides
3. Run back to the Medical Center counter
4. Then run all the way back to the Shopping entrance again
5. Notice the moving Orbs aren't there anymore
6. Go to the main portal and port to Forest 1
7. Return to P2 via the usual teleport or telepipe
8. Run back to the Shopping entrance and the orbs will be moving again.

**Game version(s) (choose one or more of the following):**
BB

**Additional context**
Before (Just entering the room from the lobby and running to the shopping area)
![image](https://github.com/user-attachments/assets/2de4668f-77e3-4808-8517-ad61db31a07a)

After (went to the medical center, returned to shopping area)
![image](https://github.com/user-attachments/assets/34550930-f459-43c0-9abe-aa0220efdeaa)

**Comment by fuzziqersoftware** [comment]
This is entirely handled by the client; the server doesn't affect object visibility. The reason the server loads object lists is so it can know which item boxes contain specific items vs. random items.
