### ISSUE TITLE
Newserv no longer building on Raspberry Pi

### ISSUE THREAD

**Issue by fishscene** [fuzziqersoftware/newserv#574]
**Describe the bug**
Newserv no longer building on Raspberry Pi (Might be an unsupported device?) after the following merges:

- https://github.com/fuzziqersoftware/newserv/commit/21f1c40408d900c7c51fe861b19a22d4460dbed6 - (https://github.com/fuzziqersoftware/newserv/issues/572)
- https://github.com/fuzziqersoftware/newserv/commit/a7d436a89497aadb3ea5a5c0222d967590f24887 - (https://github.com/fuzziqersoftware/newserv/issues/571)

*EDIT*
This appears to be related to: https://github.com/fuzziqersoftware/newserv/commit/080a9ebac4a8c925ed36807a0ca624fe9e885c5d#diff-3014bc3768151caff9de6f7b3dd51d348fbf9609191d45fd6dc834a6a2365d12

I have not tested in any other environment (x86/x64/docker/etc..)

**To reproduce**
Fill in steps to reproduce the behavior, such as:
On rPi:
```
cd ~
git clone https://github.com/fuzziqersoftware/newserv.git
cd newserv
cmake . 
make
CMake Warning at CMakeLists.txt:145 (message):
  resource_file not found; disabling patch support


-- Configuring done (0.1s)
-- Generating done (0.1s)
-- Build files have been written to: /home/pi/newserv
[  1%] Generating src/Revision.cc, src/__Revision__.cc
[  1%] Built target newserv-Revision-cc
[  2%] Generating src/Revision.cc, src/__Revision__.cc
[  3%] Building CXX object CMakeFiles/newserv.dir/src/Revision.cc.o
[  5%] Building CXX object CMakeFiles/newserv.dir/src/DownloadSession.cc.o
/home/pi/newserv/src/DownloadSession.cc:870:2: error: missing initializer for member ‘DownloadSession::GameConfig::gov’ [-Werror=missing-field-initializers]
  870 | });
      |  ^
/home/pi/newserv/src/DownloadSession.cc:870:2: error: missing initializer for member ‘DownloadSession::GameConfig::gov’ [-Werror=missing-field-initializers]
/home/pi/newserv/src/DownloadSession.cc:870:2: error: missing initializer for member ‘DownloadSession::GameConfig::gov’ [-Werror=missing-field-initializers]
/home/pi/newserv/src/DownloadSession.cc:870:2: error: missing initializer for member ‘DownloadSession::GameConfig::gov’ [-Werror=missing-field-initializers]
/home/pi/newserv/src/DownloadSession.cc:870:2: error: missing initializer for member ‘DownloadSession::GameConfig::gov’ [-Werror=missing-field-initializers]
/home/pi/newserv/src/DownloadSession.cc:870:2: error: missing initializer for member ‘DownloadSession::GameConfig::gov’ [-Werror=missing-field-initializers]
/home/pi/newserv/src/DownloadSession.cc:870:2: error: missing initializer for member ‘DownloadSession::GameConfig::gov’ [-Werror=missing-field-initializers]
/home/pi/newserv/src/DownloadSession.cc:870:2: error: missing initializer for member ‘DownloadSession::GameConfig::gov’ [-Werror=missing-field-initializers]
/home/pi/newserv/src/DownloadSession.cc:870:2: error: missing initializer for member ‘DownloadSession::GameConfig::gov’ [-Werror=missing-field-initializers]
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/newserv.dir/build.make:279: CMakeFiles/newserv.dir/src/DownloadSession.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:110: CMakeFiles/newserv.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Game version(s) (choose one or more of the following):**
N/A

**Server log output**
N/A

**Additional context**
I realize rPi probably isn't a supported environment, but wanted to get this out there in case I'm doing something wrong (feel free to point it out!) or if a bug somehow snuck in here.

**Comment by Elune-M** [comment]
I have same issue.
I'm not sure if this fix is correct, but this worked for me:

[DownloadSession.cc:860]
> const std::vector<DownloadSession::GameConfig> DownloadSession::game_configs({
>    {.mode = GameMode::NORMAL, .episode = Episode::EP1, **.gov = false,** .v1 = true, .v2 = true, .v3 = true},
>    {.mode = GameMode::NORMAL, .episode = Episode::EP2, **.gov = false,** .v1 = false, .v2 = false, .v3 = true},
>    {.mode = GameMode::NORMAL, .episode = Episode::EP4, **.gov = false,** .v1 = false, .v2 = false, .v3 = false},
>    {.mode = GameMode::BATTLE, .episode = Episode::EP1, **.gov = false,** .v1 = false, .v2 = true, .v3 = true},
>    {.mode = GameMode::CHALLENGE, .episode = Episode::EP1, **.gov = false,** .v1 = false, .v2 = true, .v3 = true},
>    {.mode = GameMode::CHALLENGE, .episode = Episode::EP2, **.gov = false,** .v1 = false, .v2 = false, .v3 = true},
>    {.mode = GameMode::SOLO, .episode = Episode::EP1, **.gov = false,** .v1 = false, .v2 = false, .v3 = false},
>    {.mode = GameMode::SOLO, .episode = Episode::EP2, **.gov = false,** .v1 = false, .v2 = false, .v3 = false},
>    {.mode = GameMode::SOLO, .episode = Episode::EP4, **.gov = true,** .v1 = false, .v2 = false, .v3 = false}
>});

Note: My environment is Windows 11, use cygwin.

**Comment by fuzziqersoftware** [comment]
This has been fixed.
