### ISSUE TITLE
[Feature Request] Split config file into smaller separate ones

### ISSUE THREAD

**Issue by nolrinale** [fuzziqersoftware/newserv#575]
As more granular support is added for more custom features as newserv evolves the config file is starting to look very bloated, would it be easier to split the configs into separate files such as a file dedicated to ports, other for items, other for quest, for episode 3 ,for lobby events, for cheating, and so on...?

**Comment by fuzziqersoftware** [comment]
I think separating the config into multiple files would just make it harder to work with, since it would no longer be straightforward to search a single file for configuration keys to modify.
