### ISSUE TITLE
Rare quests needs titles

### ISSUE THREAD

**Issue by sirdankz** [fuzziqersoftware/newserv#58]
I have some rare old quests I got after messaging some OG pso players. 
The issue is in some of the quests there is no title name when looking at the quest in the quest counter in game. If I upload the quests would you be able to fix this?

**Comment by ShiftaDeband** [comment]
You may be interested in exploring a program called "[QEdit](https://www.qedit.info/index.php?title=Main_Page)." This program would let you edit the titles and other things in the quests, then export them to [newserv](https://github.com/fuzziqersoftware/newserv#installing-quests).

What are the quests you've been able to find?

**Comment by sirdankz** [comment]
> you've

Some Japanese quests and some quests people made from back in the day. I'm not too sure on the names since some are just numbers but they do work.

Wanna come try?

**Comment by fuzziqersoftware** [comment]
This is probably not hard to fix; If you upload the files here, I can take a look.

**Comment by sirdankz** [comment]
> This is probably not hard to fix; If you upload the files here, I can take a look.

Thank you. I just uploaded them. Some  of the files with titles but not in game. If the file has no title you can give it a generic quest name.
