### ISSUE TITLE
[newserv] Using $si command segfaults the server if the proxy server is disabled

### ISSUE THREAD

**Issue by Repflez** [fuzziqersoftware/newserv#580]
**Describe the bug**
When connected to the server, using the `$si` chat command when the proxy server is disabled, it segfaults the server

**To reproduce**
1. Disable the proxy server in the config
2. Connect to server
3. Send the `$si` chat command

**Game version(s) (choose one or more of the following):**
All

**Server log output**
None, server outputs `Segmentation fault`

**Additional context**
I assume it's the same cause as https://github.com/fuzziqersoftware/newserv/issues/472 (Command expects the proxy server is enabled to work)

**Comment by toiletman74** [comment]
Doesn't happen on BB, I use $si all the time without proxy enabled

**Comment by Repflez** [comment]
> Doesn't happen on BB, I use $si all the time without proxy enabled

Weird because it does for me. I'm including my config file here and a server log (Which ends as soon I do the command) [here](https://gist.github.com/Repflez/8a1cda578a77a7bdc844d6aa7883eee4)

**Comment by PalasX** [comment]
Just tested on fresh pull and build, using $si with proxy disabled crashed server, either in lobby or in game on [a59a2d7](https://github.com/fuzziqersoftware/newserv/commit/a59a2d7cd33f430942158bc81b12880c1af59afb)

What do i need to do for logs?

**Comment by fuzziqersoftware** [comment]
Using tmux or screen should work for that. You could send the log data to a file, like `./newserv 2>&1 | tee newserv.log`; maybe the cause of the problem you're seeing will be written to the log before it dies.

**Comment by PalasX** [comment]
oh god, ignore me. i was running the wrong copy of the server the entire time. i had a dev copy running from a different directory. everything works fine.
