### ISSUE TITLE
Error with newserv.exe after compiling with Cywin64. Windows 11

### ISSUE THREAD

**Issue by Tetee11** [fuzziqersoftware/newserv#582]
**Describe the bug**
i got this error after compiling and run the newserv.exe

**To reproduce**
1. just run the newserv.exe after compiling it.

**Additional context**
![error](https://github.com/user-attachments/assets/82c79be1-f577-4e8d-872e-a8da76b681c1)

**Comment by fuzziqersoftware** [comment]
When you run a program via the Cygwin shell, the environment is different than when you run it via Windows Explorer, so it can't find the correct DLLs in the latter case. Either run newserv from the Cygwin shell, or copy the relevant DLL files from your Cygwin installation to the same folder as newserv.exe. You can look at one of the release builds to see which DLL files you'll have to copy.

**Comment by Tetee11** [comment]
I see! I just ran the .exe from the Cygwin terminal and it worked perfectly. Thanks for the information. Now I will see what DLL files are missing to run it outside of Cygwin shell. Again thanks and sorry for the inconvenience.
