### ISSUE TITLE
[Feature request] Add additional information to the "GameServer" log

### ISSUE THREAD

**Issue by pblue3** [fuzziqersoftware/newserv#583]
Is it possible to add additional information to the "GameServer" part of the logs?
For now it displays when a client connects or disconnects.
Could we add the account id or name as well?
Maybe even some character informations (level?)
Thanks a lot!

**Comment by fuzziqersoftware** [comment]
I don't think it makes sense for this to be in the GameServer log, but I'll add these things to the Clients log. The messages will appear with tags like [C-1], [C-2], etc.

Keep in mind that the primary purpose of these logs is debugging, so some of the messages refer to internal details of the server. Also note that on most PSO versions, the server checks the client's credentials multiple times during the login sequence, so you'll likely see multiple login messages for the same client. If you're just reading the server log manually, I assume this will be fine, but if you want client information for some external integration, the HTTP server is probably a better way to access it.

**Comment by pblue3** [comment]
Thank you very much for these additions! Indeed, your observations make complete sense.💯🙏
