### ISSUE TITLE
Bug 2 Failed Login Gamecube

### ISSUE THREAD

**Issue by lucashart90** [fuzziqersoftware/newserv#6]
Failed Connection Gamecube This is Error
![immagine](https://user-images.githubusercontent.com/6928951/67391381-d80ed780-f59e-11e9-85e7-70911fcda34a.png)

**Comment by fuzziqersoftware** [comment]
This is because the license wasn't found; I didn't spend any time fixing the error message. You can use add-license in the server's shell or enable AllowUnregisteredUsers in the configuration.
