### ISSUE TITLE
make error at chat commands 

### ISSUE THREAD

**Issue by jwalabas** [fuzziqersoftware/newserv#60]
pi@raspberrypi:~/newserv $ make
[  1%] Building CXX object CMakeFiles/newserv.dir/src/ChatCommands.cc.o
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [CMakeFiles/newserv.dir/build.make:108: CMakeFiles/newserv.dir/src/ChatCommands.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/newserv.dir/all] Error 2
make: *** [Makefile:160: all] Error 2

Unable to get past the ChatCommands portion.

**Comment by fuzziqersoftware** [comment]
This looks like either a compiler bug or out-of-memory condition. To check for the latter, look in /var/log/syslog to see if something like `Out of memory: Kill process ...` appears when you try to compile. If you don't see a message like that, try upgrading your OS and compiler to the latest versions.

**Comment by jwalabas** [comment]
I actually had to reimage and not update to get it to work... strange solution but it seemed to do the trick.  Thanks!
