### ISSUE TITLE
Downloaded .VMI quest to convert ?

### ISSUE THREAD

**Issue by sirdankz** [fuzziqersoftware/newserv#62]
Is it possible to download .VMI files that are dreamcast quests from pso-world.com and use them in the server?

**Comment by fuzziqersoftware** [comment]
Currently it's not possible, but it might be feasible to add support for this. Can you upload an example file, or post a link to a page where these can be downloaded?

**Comment by sirdankz** [comment]
https://www.pso-world.com/download.php?cat=Download+Quests

**Comment by fuzziqersoftware** [comment]
Unfortunately it looks like it won't be possible to add support for these because the .vmi files don't actually contain the quest data. If you can find .vms files for these quests, it may be possible to add support for them.

**Comment by sirdankz** [comment]
https://dreamcastlive.net/phantasy-star-online-v-1-dlc/

https://dreamcastlive.net/phantasy-star-online-v-2-dlc/

Thanks for all the work you've been putting in!

**Comment by fuzziqersoftware** [comment]
This should work now - you can decode VMS files with `./newserv decode-vms <file>.vms`. DCv1 VMS files can be decoded quickly, but DCv2 VMS files are encrypted with a key not included in the VMS file itself. This means that if you try to decode a DCv2 VMS file, newserv will run a brute-force search for the key, which takes several hours on a reasonably fast machine.
