### ISSUE TITLE
Adding licenses not working

### ISSUE THREAD

**Issue by sirdankz** [fuzziqersoftware/newserv#63]
I've used the 

---------------------------------------------------------------------------------------
 add-license serial=xxxxxxx access key=xxxxxxxxx gc=password=xxxxxxxxx privileges=admin
 --------------------------------------------------------------------------------------
 I get back 
 
 --------------------------------------------------------------------------------------
 License added 
 -------------------------------------------------------------------------------------- 

 but it doesn't make me an admin.
 Even if i restart the server nothing changes.

**Comment by fuzziqersoftware** [comment]
I tested just now - adding a license with admin privileges does work, but this doesn't enable all features (e.g. admins can't use debug commands). Perhaps what you want is root instead of admin.

**Comment by ryu777mtg** [comment]
This may need to be re-opened

```
newserv> add-license gc-password=1 access-key=111111111111 serial=1111111111 privileges=root
FAILED: incorrect field: privileges=root
```
```
newserv> add-license gc-password=1 access-key=111111111111 serial=1111111111 flags=root
FAILED: basic_string::substr: __pos (which is 11) > this->size() (which is 10)
```

Maybe I'm doing it wrong...
