### ISSUE TITLE
Editing StaticGameData.cc

### ISSUE THREAD

**Issue by jwalabas** [fuzziqersoftware/newserv#64]
I'm trying to make a QoL update to the server and change the inventory item stack size from 10 to 99.  I found a line in the file StaticGameData.cc to change the stack size, but when I edit the line on my local copy, it doesn't appear to make any apparent change in game.   

Am I just misunderstanding the purpose of the file and the actual player inventory stack sizes are hardcoded into the game image?

**Comment by fuzziqersoftware** [comment]
Unfortunately yes - StaticGameData is only a copy of tables and rules that are hardcoded into the game. newserv only uses this to keep its data in sync with the client.
