### ISSUE TITLE
Setting event causes you not to connect back to main lobby

### ISSUE THREAD

**Issue by sirdankz** [fuzziqersoftware/newserv#66]
Having an event set causes you not be able to load back into the main lobby after you created a team. I've tested this on the sonic event. Not the other events.

**Comment by fuzziqersoftware** [comment]
Which version(s) does this affect? Can you share a session log?

**Comment by sirdankz** [comment]
Pso episode 2 GC
I'm having trouble recreating the issue now. Maybe ot only happens when multiple people are connected and you have an event set.

**Comment by sirdankz** [comment]
1114409 2023-02-03 21:58:35-[Commands) Sending to C-3C (Selky) (version-GC command-88

flag-01)

0000 | 88 01 10 00 00 00 01 00 61 AE 46 22 00 00 00 00 | a F

1114409 2023-02-03 21:58:35-[Commands] Received from C-3C (Selky) (version GC command-60

flag-00)

0000 | 60 00 10 00 0D 03 00 00 01 00 00 00 00 00 00 00 |

1114409 2023-02-03 21:58:39-[Commands ] Received from C-3C (Selky) (version GC command=60

flag-00)

0000 | 60 00 14 00 40 04 00 00 5A 88 A8 36 00 00 FE 42@ 76 B

1114409 2023-02-03 21:58:40-[Commands ] Received from C-3C (Selky) (version CC command-60

flag-00)

0000 | 60 00 14 00 40 04 00 00 0E 11 DE 38 00 00 EE 421 @ 8 B

1 114409 2023-02-03 21:58:40 - [Commands) Received from C-3C (Selky) (version GC command-60

flag-00)

0000 | 60 00 14 00 40 04 00 00 C7 CC 58 39 00 00 DE 421 @ X9 B

1114409 2023-02-03 21:58:40-[Commands] Received from C-42 (Maybin0) (version-GC command-84 flag-001

0000 | 84 00 0C 00 33 00 00 33 01 00 00 00

33 W 114409 2023-02-03 21:58:40-[Server] Error processing client command: un translatable unicode character

1114409 2023-02-03 21:58:40-[Server] Client disconnected: C-42 on fd 36

I 114409 2023-02-03 21:58:40-[Commands] Sending to C-3C (Sciky) (version-GC co

**Comment by fuzziqersoftware** [comment]
Many changes have taken place since this issue was opened; if it's still a problem, please upload a full log (starting from the server's startup) of the problem occurring.
