### ISSUE TITLE
Force quite save x+b+start lobby doesnt get deleted

### ISSUE THREAD

**Issue by sirdankz** [fuzziqersoftware/newserv#67]
If you and a team are doing a quest then you all force quit save instead of leaving the game normally this causes the lobby to remain open even when no players are present.

**Comment by fuzziqersoftware** [comment]
When this happens, does the game still appear in the menu with "0/4" on the right? If it appears with something else (e.g. "1/4") then there's probably nothing newserv can do about it - it has to wait until the TCP connection gets closed, which usually takes a few minutes.
