### ISSUE TITLE
Error code 100 when character selects difficultly higher than theyre lvl

### ISSUE THREAD

**Issue by sirdankz** [fuzziqersoftware/newserv#68]
0000 | 60 00 10 00 52 03 00 00 00 00 00 00 D1 8E 00 00 | R

136878 2023-02-02 23:37:55 - [Commands] Received from C-1A7 (Ridge Cut) (version=CC command-C1 flag-03)

E!

0000 C10330 CÓ ĐÓ 00 00 0Ó CÓ ĐÓ CÓ ĐỘ 09 45 21 00 0

W 36878 2023-02-02 23:37:55-[Server] Error processing client command: level too low for difficulty 136878 2023-02-02 23:37:55 - [Server] Client disconnected: C-1A7 on fd 42

**Comment by fuzziqersoftware** [comment]
This is fixed now.
