### ISSUE TITLE
Challenge mode rank not displaying in main lobby

### ISSUE THREAD

**Issue by sirdankz** [fuzziqersoftware/newserv#69]
When you press R on the gamecube controller to change the display of names/level or name alone. Nothing is displayed where the challenge mode rank is suppose be. There is 2 blank spaces.

**Comment by fuzziqersoftware** [comment]
This is a known issue; the server doesn't forward challenge mode rank data correctly. Unfortunately I don't know the format of this data, so the server can't convert it between game versions, which is why it's missing. I'll leave this open until it's implemented.
