### ISSUE TITLE
I try to remove the license management system for gc clients but failed

### ISSUE THREAD

**Issue by neonzhang** [fuzziqersoftware/newserv#7]
Is there any way to modify the server to allow_Unregistered_Users  like the old version.There are so many codes need to be changed...
I try to rewrite SendCommands.cc and ReceiveCommands.cc
...

**Comment by neonzhang** [comment]
Created rooms are also not automatically released after the player leaves, a BUG that will take time to resolve

**Comment by fuzziqersoftware** [comment]
Both of these should be fixed now - you can now use AllowUnregisteredUsers in the configuration file.
