### ISSUE TITLE
Playing challenge mode GC disconnect players everytime..

### ISSUE THREAD

**Issue by sirdankz** [fuzziqersoftware/newserv#70]
0000 | 60 00 10 00 42 03 00 00 8F CE B4 44 96 4A B6 431 B DJC

136878 2023-02-03 21:39:40 - [Commands] Received from C-1D7 (S2J) (version GC command-60

flag-00)

0000 | 60 00 0C 00 27 02 00 00 21 00 01 00

W 36878 2023-02-03 01:39:40 - [Server] Error processing client command: item not present

136878 2023-02-03 01:39:40 - [Server] Client disconnected: C-1D7 on fd 47

136878 2023-02-03 01:39:40 - [Commands] Sending to C-1D3 (DANKZ) (version GC command 66

flag-00)

0000 | 66 00 08 00 00 01 01 00

136878 2023-02-03 01:39:44 - [Commands] Received from C-1D3 DANKZ) (version GC

command-60 flag-00)

0000 | 60 00 0C 00 80 02 E6 4C 19 00 02 00

L

136878 2023-02-03 01:39:53 - [Commands] Received from C-1D3 DANKZ) (version GC

command=ID flag=00)

0000 | 1D 00 04 00

**Comment by fuzziqersoftware** [comment]
This should be fixed now.
