### ISSUE TITLE
FSOD on retrospective tomorrow fighting dragon

### ISSUE THREAD

**Issue by sirdankz** [fuzziqersoftware/newserv#73]
1114409 2023-02-03 23:21:12-[Commands] Sending to C-56 (DANKZ) (version=GC command=60

flag-00)

0000 160 00 10 00 42 03 00 00 9B 64 03 43 5B CF 30 43 B dC[OC

I 114409 2023-02-03 23:21:12-[Commands] Sending to C-51 (Subway) (version GC command-60

flag-00) 0000 | 60 00 10 00 42 03 00 00 9B 64 03 43 5B CF 30 43 B dC[OC

1114409 2023-02-03 23:21:12-[Commands] Received from C-53 (PokeEms) (version GC command-60 flag-00)

0000 | 60 00 10 00 42 03 00 00 36 BC FA 42 6E 3D 35 43 B 6 Bp-5C

1 114409 2023-02-03 23:21:12-1Commands] Sending to C-56 (DANKZ) (version CC command=60

flag-00)

0000 | 60 00 10 00 42 03 00 00 36 BC FA 42 6E 3D 35 43 B 6 Bn-5C

1 114409 2023-02-03 23:21:12-[Commands] Sending to C-51 (Subway) (version GC command-60

flag-00)

000060 00 10 00 42 03 00 00 36 BC FA 42 6E 3D 35 43 B 6 Bp-5C

I 114409 2023-02-03 23:21:12-[Server] Client disconnected: C-51 on fd 37

?

**Comment by fuzziqersoftware** [comment]
This log isn't sufficient to diagnose the problem. If it still occurs, please upload a full log of the session (starting from the server's startup) and describe exactly what happened when the client crashed.
