### ISSUE TITLE
when client auto disconnect from server,the Saved player data function still on working even client not online

### ISSUE THREAD

**Issue by Sancaros** [fuzziqersoftware/newserv#74]
I 4178178 2023-02-06 13:10:27 - Saved player data file system/players/player_sancaros_1.nsc to filesystem
I 4178178 2023-02-06 13:10:37 - Saved account data file system/players/account_sancaros.nsa to filesystem
I 4178178 2023-02-06 13:10:37 - Added 60 seconds to play time
I 4178178 2023-02-06 13:10:37 - Saved player data file system/players/player_sancaros_1.nsc to filesystem
I 4178178 2023-02-06 13:10:49 - Saved account data file system/players/account_sancaros.nsa to filesystem
I 4178178 2023-02-06 13:10:49 - Added 59 seconds to play time
I 4178178 2023-02-06 13:10:49 - Saved player data file system/players/player_sancaros_1.nsc to filesystem
I 4178178 2023-02-06 13:11:00 - Saved account data file system/players/account_sancaros.nsa to filesystem

when client auto disconnect from server,the Saved player data function still on working even client not online

**Comment by fuzziqersoftware** [comment]
Can you provide more of the log? What happens right before the client disconnects - does it send a command? If you want for ~10 minutes, does the session eventually get closed?

**Comment by Sancaros** [comment]
my fault,setting problem
