### ISSUE TITLE
PSO PC version disconnects line using materials 

### ISSUE THREAD

**Issue by sirdankz** [fuzziqersoftware/newserv#75]
Using any materials on PSO PC versions makes your line disconnect in game.
Materials as in HP materials, Power materials etc..

**Comment by fuzziqersoftware** [comment]
It turns out that this affects all items that can be consumed (including Monomates, etc.). PSO PC's behavior is the same as DC, but newserv was handling it as if it were GC. This is fixed now.

**Comment by sirdankz** [comment]
> It turns out that this affects all items that can be consumed (including Monomates, etc.). PSO PC's behavior is the same as DC, but newserv was handling it as if it were GC. This is fixed now.

Ive tried to build 2 times from the updated Newserv_master.zip but it keeps failing at 45% outputting error on "invalid use of non-static member function gamecube"

**Comment by fuzziqersoftware** [comment]
I apparently pushed a broken build; it should be actually fixed now.
