### ISSUE TITLE
Handling Serials as uint32 Leads to Overflows

### ISSUE THREAD

**Issue by TheDiscordian** [fuzziqersoftware/newserv#77]
I've been exploring this code-base and I noticed quite quickly that serials are stored as uint32. A serial can easily be understood as a length 10 string where each character can be a number between 1 and 9 (the way it's entered in PSOep1&2Plus). The uint32 maximum is 0xFFFFFFFF or 4994967295 (10 digits). This results in any serial being specified over 4994967295 overflowing and resulting in a completely different serial.

For example:

```
add-license serial=4994967296 access-key=000000000000 gc-password=0
license added
list-licenses
License(serial_number=700000000, access-key=000000000000, gc-password=0, privileges=0)
```

When building things like a registration system, this is quite the thing to stumble on. I assume this is a bug.

**Comment by fuzziqersoftware** [comment]
This is a reasonable observation, but this is actually intended. The game internally stores serial numbers as 32-bit integers, and it also overflows internally if you enter a serial number above 42-9496-7295. If you specify the serial number 44-4444-4444 in PSO, for example, the serial number it sends to the server will be 01-4947-7148.

**Comment by TheDiscordian** [comment]
Wow that is super interesting! Thank you for that fact. I suppose this isn't a bug then and I'll close this issue, thank you for your work and response, and I hope to submit a PR to this project one day.
