### ISSUE TITLE
Undeclared identifier "parse_netloc()'

### ISSUE THREAD

**Issue by anaya05** [fuzziqersoftware/newserv#8]
I'm getting compile issues with this function. I've tried locating it in phosg to check if it was from there but it couldn't find it. Is it from libevent or declared some where in newserv?
<img width="494" alt="Screen Shot 2020-02-21 at 6 45 32 PM" src="https://user-images.githubusercontent.com/32380101/75082697-82115880-54da-11ea-860b-92105b6147f7.png">

**Comment by fuzziqersoftware** [comment]
Sorry about that - this is due to an unpushed change in phosg. I've pushed it just now; if you pull, rebuild, and reinstall phosg it should work. Feel free to reopen this if it doesn't.
