### ISSUE TITLE
Error when executing in terminal: ./newserv. Ubuntu 22.04.2

### ISSUE THREAD

**Issue by pmasterBR** [fuzziqersoftware/newserv#81]
![Captura de tela em 2023-03-20 08-47-47](https://user-images.githubusercontent.com/11383183/226330601-39285a4e-f646-41ce-9151-020b85b957ed.png)

**Comment by fuzziqersoftware** [comment]
This looks like the config file is missing. Did you copy config.example.json to config.json, and edit it? (See the readme and comments in config.example.json for more details.)

**Comment by pmasterBR** [comment]
> This looks like the config file is missing. Did you copy config.example.json to config.json, and edit it? (See the readme and comments in config.example.json for more details.)

Thanks, the problem was the same, I renamed the file and it worked. I would like to ask if there is any command that allows Dreamcast and gamecube players to connect together in the city, just for testing. I remember that the sylverant server had this command in the old days. This project is amazing! =,)

**Comment by fuzziqersoftware** [comment]
There isn't a command to do this; I haven't tried it in 10+ years. If you're up for building newserv yourself, you can remove the `if (l->version != c->version()) { continue; }` in `send_game_menu_t` in SendCommands.cc (this will show games for different versions in the game menu), and remove the 6-line block starting with `if ((game->version != c->version()) ||` in `on_10` in ReceiveCommands.cc (this will let you join games for a different PSO version). Even if you do this, the game will likely behave strangely or crash if you get DC and GC clients in the same game.

**Comment by pmasterBR** [comment]
> There isn't a command to do this; I haven't tried it in 10+ years. If you're up for building newserv yourself, you can remove the `if (l->version != c->version()) { continue; }` in `send_game_menu_t` in SendCommands.cc (this will show games for different versions in the game menu), and remove the 6-line block starting with `if ((game->version != c->version()) ||` in `on_10` in ReceiveCommands.cc (this will let you join games for a different PSO version). Even if you do this, the game will likely behave strangely or crash if you get DC and GC clients in the same game.

I think it's too complex for me, since I'm not a programmer, just curious hahaha. But at the time when the command worked I recorded a small video: https://www.youtube.com/watch?v=kJ5_ipnAZhw&t
