### ISSUE TITLE
Loading homebrew GBA demo succed but displays "Download failed"

### ISSUE THREAD

**Issue by omn14** [fuzziqersoftware/newserv#82]
I was playing with GBA homebrew development and made a demo. I modified the Pioneer Warehouse quest to load the demo file I created. Using dolphin with the built in mGBA emulator link (built in GBA under controller settings in port 4, GBA_BIOS downloaded to folder specified), I tried to load my homebrew demo .gba file and it works! Only issue is after 16 seconds the GC displays an error saying the download failed. This error does not appare whan loading the SEGA demos.

I can play my homebrew demo just fine, so I think the GC client expects some signal from the GBA ROM that the download completed successfully.

quest and gba-demo in this commit: https://github.com/omn14/newserv/commit/c57914fd5e620b48c48f6d3e5bc7ef718aeaab95

Any ideas what it needs? How does the GBA link work?

**Comment by fuzziqersoftware** [comment]
I haven't looked into how PSO and the GBA communicate with each other before, but I could poke around a bit sometime soon and see if I can figure anything out.

To make my testing easier, are there any preconditions for loading the GBA demo in your testing quest? (Do I need to set any flags / have any items / etc.?)

**Comment by omn14** [comment]
Nice of you to look into this. If what I'm wondering is true, that the GBA can send data to the GC (dl complete or whatever), what else might be possible..

I found this documenting the GBA com protocol. I dont know if it is what PSO uses: 
http://problemkaputt.de/gbatek-gba-communication-ports.htm

Preconditions (using Dolphin emulator):
GBA_bios 
Download from: https://emulation.gametechwiki.com/index.php/Emulator_files#Game_Boy_Advance_.2F_e-Reader
put in folder:
![image](https://user-images.githubusercontent.com/27871331/228286012-8e2c51f6-5ebf-40af-81de-3066b0b02336.png)

No flag needed for my homebrew app. You might want a flag for i.e puyo_e.gba to compare loading the official demos. 

Puyo Pop
https://www.pso-world.com/sections.php?op=viewarticle&artid=918
--
Go online and load the "Gallon's Shop" quest under Shops.          
Go to the Medical Center area and you will see a shiny thing on the floor.         
Pick it up and you will get a question         
Select yes and you will get the key item for Puyo Pop         
Finish the quest.

To load the GBA demo: 
Load up the quest in my fork. Go talk to the lady second door to the left, then the GBA console.

**Comment by omn14** [comment]
Seems like the official demos indeed tries to communicate.

Debug log from puyo pop

`[DEBUG] GBA Serial I/O:	Switching mode from JOYBUS to GPIO
[DEBUG] GBA Serial I/O:	Switching mode from GPIO to JOYBUS
[DEBUG] GBA Serial I/O:	JOY write: STAT <- 0000
[DEBUG] GBA Serial I/O:	JOY write: TRANS_LO <- 0000
[DEBUG] GBA Serial I/O:	JOY write: TRANS_HI <- 0000
[DEBUG] GBA Serial I/O:	JOY write: CNT <- 0047
[DEBUG] GBA BIOS:	SWI: 05 r0: 02007AE3 r1: 03002D78 r2: 00000000 r3: 00000000
[DEBUG] GBA BIOS:	SWI: 05 r0: 02007AE3 r1: 03002D78 r2: 00000000 r3: 00000000
[DEBUG] GBA Serial I/O:	JOY poll: 08 (40)
[DEBUG] GBA BIOS:	SWI: 05 r0: 02007AE3 r1: 03002D78 r2: 00000000 r3: 00000000
[DEBUG] GBA BIOS:	SWI: 05 r0: 02007AE3 r1: 03002D78 r2: 00000000 r3: 00000000
[DEBUG] GBA BIOS:	SWI: 05 r0: 02007AE3 r1: 03002D78 r2: 00000000 r3: 00000000
[DEBUG] GBA BIOS:	SWI: 05 r0: 02007AE3 r1: 03002D78 r2: 00000000 r3: 00000000
[DEBUG] GBA Serial I/O:	JOY poll: 08 (40)
[DEBUG] GBA BIOS:	SWI: 05 r0: 02007AE3 r1: 03002D78 r2: 00000000 r3: 00000000
[DEBUG] GBA BIOS:	SWI: 05 r0: 02007AE3 r1: 03002D78 r2: 00000000 r3: 00000000
[DEBUG] GBA BIOS:	SWI: 05 r0: 02007AE3 r1: 03002D78 r2: 00000000 r3: 00000000
[DEBUG] GBA BIOS:	SWI: 05 r0: 02007AE3 r1: 03002D78 r2: 00000000 r3: 00000000
[DEBUG] GBA Serial I/O:	JOY poll: 08 (40)
[DEBUG] GBA BIOS:	SWI: 05 r0: 02007AE3 r1: 03002D78 r2: 00000000 r3: 00000000
[DEBUG] GBA BIOS:	SWI: 05 r0: 02007AE3 r1: 03002D78 r2: 00000000 r3: 00000000
[DEBUG] GBA Serial I/O:	Switching mode from JOYBUS to GPIO
[DEBUG] GBA Serial I/O:	Switching mode from GPIO to JOYBUS
[DEBUG] GBA Serial I/O:	JOY write: STAT <- 0000
[DEBUG] GBA Serial I/O:	JOY write: TRANS_LO <- 0000
[DEBUG] GBA Serial I/O:	JOY write: TRANS_HI <- 0000
[DEBUG] GBA Serial I/O:	JOY write: CNT <- 0047
[DEBUG] GBA BIOS:	SWI: 05 r0: 02007AE3 r1: 03002D78 r2: 00000000 r3: 00000000
[DEBUG] GBA BIOS:	SWI: 05 r0: 02007AE3 r1: 03002D78 r2: 00000000 r3: 00000000
[DEBUG] GBA Serial I/O:	JOY poll: 08 (40)
[DEBUG] GBA BIOS:	SWI: 05 r0: 02007AE3 r1: 03002D78 r2: 00000000 r3: 00000000`

**Comment by omn14** [comment]
![image](https://user-images.githubusercontent.com/27871331/229371886-042f607c-04e9-4ecc-875b-97fcf19df7a5.png)

I found a solution. I looks like the GC-GBA link is using the JOY BUS Mode. ref http://problemkaputt.de/gbatek-sio-joy-bus-mode.htm

Added these lines(tonc lib #defines) to my GBA demo and it now works. 
`REG_RCNT = R_MODE_JOYBUS;
REG_JOYCNT = 0x0000;
 REG_JOY_TRANS = 0x504F5047; //download complete `

The PSO opcode 0xf8c3, "get_gba_state?" seem to be involved some how...

**Comment by fuzziqersoftware** [comment]
For others finding this discussion in the future: GBA loading works using a sequence of several quest opcodes.
1. The quest uses either F8C2 (prepare_gba_rom_from_download) or F929 (prepare_gba_rom_from_disk) to load a GBA file
2. Optionally, the quest may use F92F (gba_write_identifiers) if the GBA file needs some information about the PSO save file and current time
3. The quest uses F8C3 (update_gba_state) repeatedly to send the file to the GBA, until that opcode returns success or failure
4. During that process, the quest uses F935 (gba_create_dl_graph), F936 (gba_destroy_dl_graph), and F937 (gba_update_dl_graph) to show the progress bar to the player

When loading is done, the GC and GBA exchange PSO's game ID (e.g. "GPOE") via the serial port to verify that loading is done. This is what those lines at the end of the previous comment do.

Unfortunately, there appears to be no quest opcode that allows the GC and GBA to communicate after the loading process is done.
