### ISSUE TITLE
Real dreamcast no connect to server with modem BBA or dialup.

### ISSUE THREAD

**Issue by pmasterBR** [fuzziqersoftware/newserv#83]
I tried in several ways to connect to the server, both local and public, but I was unsuccessful. I set my DNS in the settings using a real BBA modem or dialup modem with dreamPI, but it doesn't connect to my server. Is there any tool I can use to patch the game with my DNS?. It's weird the real dreamcast can't connect even changing the dns in the game settings. Thanks

**Comment by fuzziqersoftware** [comment]
DIsclaimer: I've only tested PSO DC on an emulator, so I can't be sure what a working setup should look like with real hardware.

According to Sylverant's connection guide (https://sylverant.net/connecting-to-sylverant/), if you're using a BBA, you should be able to just set the game's DNS server address to your server's address and it should work. If it doesn't work, you could post your network configuration here (server IP address, and all the fields in PSO DC's network config) and I'll see if I notice anything that looks like it needs to be changed.

If you're using a modem, you'll have to patch the disc image or use a cheat code. Sylverant has some codes that you could modify for your own use (paste them into a hex editor and you'll see the server's address in the text view - replace that text with your server's IP address to make your own code).
