### ISSUE TITLE
Invalid mocb1.nsk size

### ISSUE THREAD

**Issue by supermahars** [fuzziqersoftware/newserv#84]
When trying to run newserv I get this error:
terminate called after throwing an instance of 'std::runtime_error'
  what():  size of system/blueburst/keys/mocb1.nsk is incorrect
Aborted

I've tried replacing mocb1.nsk with a known-working copy and redownloading it from git but the error persists

**Comment by fuzziqersoftware** [comment]
What architecture are you building on? I suspect this happens because the compiler pads the KeyFile struct unnecessarily, which makes it not be the same size as the .nsk files. If this is actually the issue, I've pushed a change just now that should fix it.

**Comment by supermahars** [comment]
Arm 32bit. I'm trying to put it on a Raspberry Pi. After updating to newest commit it's still giving the same error. What exactly are the nsk files?

**Comment by fuzziqersoftware** [comment]
.nsk files are Blue Burst private keys. If you're not serving Blue Burst clients, you should be able to delete them all (but leave the directory) and newserv should work. However, the possibility that the struct is still the wrong size is confusing... can you run newserv under gdb or lldb and run the following commands?

    print sizeof(PSOBBEncryption::KeyFile)
    print sizeof(PSOBBEncryption::KeyFile::initial_keys)
    print sizeof(PSOBBEncryption::KeyFile::private_keys)
    print sizeof(PSOBBEncryption::KeyFile::subtype)

**Comment by supermahars** [comment]
I got this result:

`(gdb) print sizeof(PSOBBEncryption::KeyFile)`
`$1 = 4176`
`(gdb) print sizeof(PSOBBEncryption::KeyFile::initial_keys)`
`$2 = 72`
`(gdb) print sizeof(PSOBBEncryption::KeyFile::private_keys)`
`$3 = 4096`
`(gdb) print sizeof(PSOBBEncryption::KeyFile::subtype)`
`$4 = 8`

**Comment by fuzziqersoftware** [comment]
This is (finally!) fixed. The issue is that fstat appears to return an incorrect file size in some scenarios; the relevant function in phosg no longer uses fstat.
