### ISSUE TITLE
cant connect to my own server

### ISSUE THREAD

**Issue by apatuka** [fuzziqersoftware/newserv#85]
Hello,

I installed dolphin dev edition and i have the newserv binaries for windows i downloaded from Releases sections

I changed everything on config.json, i check if the DNS server is working using nslookup, it works.
But when i create game Profile, network profile on Slot A (All using Memory Card and not GCI) it fails. (I havent changed anything on Network setup inside the game)

The Network Adapter is HLE with my LAN ip address on DNS.

The console of newserv doesn't return anything.

**Comment by thom2305** [comment]
Can you send screenshots so I could help me figure it out with you

**Comment by fuzziqersoftware** [comment]
You could also try using 127.0.0.1 as the DNS server address in Dolphin's HLE BBA settings. If this is still an issue, feel free to reopen this.
