### ISSUE TITLE
PSO on dolphin

### ISSUE THREAD

**Issue by Gedehamsen021** [fuzziqersoftware/newserv#86]
Hi i tried join on my localserver on same pc, and i have no idea what i making wrong, i put the local ip of my pc on dolphin and in server but just returning Error 102.

No console logs, nothing
[config.txt](https://github.com/fuzziqersoftware/newserv/files/11426875/config.txt)

Windows 11 PRO

**Comment by fuzziqersoftware** [comment]
You're using the HLE BBA setting in Dolphin, right? It's hard to know what's wrong here from this information... if you can get a packet log (e.g. via Wireshark) of a connection attempt, we can see if the DNS query is being sent to the right address.

Another thing you could try that might work with HLE BBA - set Dolphin's DNS server address to 127.0.0.1, and set LocalAddress to 127.0.0.1 in config.json. Theoretically this could work, but I've never tried it.

**Comment by Gedehamsen021** [comment]
![image](https://github.com/fuzziqersoftware/newserv/assets/25692637/fe05b911-f9be-4bd4-9868-ffe8f015645e)
![image](https://github.com/fuzziqersoftware/newserv/assets/25692637/b3af08b7-7f36-49c5-8608-6a2c54e8ec03)
and the config
![image](https://github.com/fuzziqersoftware/newserv/assets/25692637/06a9e3fc-3246-44dd-9ff1-5730c1af42b3)

**Comment by Gedehamsen021** [comment]
i changed to dolphin 5.0-17038 and works

**Comment by Gedehamsen021** [comment]
the last version cannot connect to the game
