### ISSUE TITLE
discord server

### ISSUE THREAD

**Issue by Mistik** [fuzziqersoftware/newserv#88]
Hi

does this project have a discord server?

**Comment by fuzziqersoftware** [comment]
There currently aren't Discord servers for any of my projects. I generally prefer to just work on my projects when I have the time and energy, and I fear having a Discord server would change that. Also, community management isn't one of my strengths, and I've seen other Discord servers have to deal with spam attacks, moderation problems, etc. and I'd prefer to not have to think about issues like those.

**Comment by Mistik** [comment]
Ah ok, well is there any place I could contact you? With a live chat?

**Comment by fuzziqersoftware** [comment]
Not really - I don't have any kind of live chat setup for my projects, since I work on them at irregular times. Usually GitHub issues are the best way to contact me about my projects.
