### ISSUE TITLE
Error building newserv on Ubuntu 22.04

### ISSUE THREAD

**Issue by gofastlily** [fuzziqersoftware/newserv#93]
I'm running into the following error when trying to build newserv on Ubuntu 22.04 running on `x86_64`.

I've verified that `config.json` exists in the `system` folder.  I've also tried just copy/pasting an unedited `config.sample.json`.

I noticed this issue https://github.com/fuzziqersoftware/newserv/issues/56 but I haven't been able to identify any errors in my config file.

Output of `cmake . && make`
```
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at CMakeLists.txt:104 (message):
  libresource_file not found; disabling patch support


-- Configuring done
-- Generating done
-- Build files have been written to: /newserv/newserv
[  1%] Building CXX object CMakeFiles/newserv.dir/src/CatSession.cc.o
[  3%] Building CXX object CMakeFiles/newserv.dir/src/Channel.cc.o
[  5%] Building CXX object CMakeFiles/newserv.dir/src/ChatCommands.cc.o
[  7%] Building CXX object CMakeFiles/newserv.dir/src/Client.cc.o
[  9%] Building CXX object CMakeFiles/newserv.dir/src/Compression.cc.o
[ 11%] Building CXX object CMakeFiles/newserv.dir/src/DNSServer.cc.o
[ 13%] Building CXX object CMakeFiles/newserv.dir/src/Episode3/AssistServer.cc.o
[ 15%] Building CXX object CMakeFiles/newserv.dir/src/Episode3/BattleRecord.cc.o
[ 16%] Building CXX object CMakeFiles/newserv.dir/src/Episode3/Card.cc.o
[ 18%] Building CXX object CMakeFiles/newserv.dir/src/Episode3/CardSpecial.cc.o
[ 20%] Building CXX object CMakeFiles/newserv.dir/src/Episode3/DataIndex.cc.o
[ 22%] Building CXX object CMakeFiles/newserv.dir/src/Episode3/DeckState.cc.o
[ 24%] Building CXX object CMakeFiles/newserv.dir/src/Episode3/MapState.cc.o
[ 26%] Building CXX object CMakeFiles/newserv.dir/src/Episode3/PlayerState.cc.o
[ 28%] Building CXX object CMakeFiles/newserv.dir/src/Episode3/PlayerStateSubordinates.cc.o
[ 30%] Building CXX object CMakeFiles/newserv.dir/src/Episode3/RulerServer.cc.o
[ 32%] Building CXX object CMakeFiles/newserv.dir/src/Episode3/Server.cc.o
[ 33%] Building CXX object CMakeFiles/newserv.dir/src/Episode3/Tournament.cc.o
/newserv/newserv/src/Episode3/Tournament.cc: In member function ‘void Episode3::TournamentIndex::save() const’:
/newserv/newserv/src/Episode3/Tournament.cc:703:41: error: ‘using element_type = class JSONObject’ {aka ‘class JSONObject’} has no member named ‘format’
  703 |   save_file(this->state_filename, json->format());
      |                                         ^~~~~~
make[2]: *** [CMakeFiles/newserv.dir/build.make:314: CMakeFiles/newserv.dir/src/Episode3/Tournament.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/newserv.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by fuzziqersoftware** [comment]
It looks like you're building an older version of newserv with a newer version of phosg - is your master branch up to date? The format() function was removed recently in phosg; that line in newserv should now call `json->serialize(JSONObject::SerializeOption::FORMAT)` instead.

**Comment by gofastlily** [comment]
I've made sure I've got the newest version of `newserv` checked out and things build fine but I'm now getting an error when binding to port 53.

I'm going to check and see what's running on that port, though I don't recall installing anything on this server that uses 53.  I set up this server to host newserv and a few other games and newserv is the only one that relies on port 53 as far as I know.

Have you run across this error before?

(excerpt of logs)
```
I 3056265 2023-08-01 22:23:38 - [Config] Compiling client functions
I 3056265 2023-08-01 22:23:38 - [FunctionCompiler] Function compiler is not available
I 3056265 2023-08-01 22:23:38 - [Config] Loading DOL files
I 3056265 2023-08-01 22:23:38 - [FunctionCompiler] Function compiler is not available
I 3056265 2023-08-01 22:23:38 - [Config] Creating menus
I 3056265 2023-08-01 22:23:38 - [Config] Starting DNS server
terminate called after throwing an instance of 'std::runtime_error'
  what():  can't bind socket to 0.0.0.0:53: 13 (Unknown error)
```

**Comment by fuzziqersoftware** [comment]
newserv runs its DNS server on port 53, which is a convenience feature for the console PSO versions (DC and GC) to easily connect to the server by just putting the server's address as their network config's DNS server address field. Error 13 I believe is EACCES, which happens because the kernel prevents non-privileged processes from listening on ports 1-1023. 

You can get around this in a few ways:
* You could start newserv with sudo. It will open the DNS socket, then drop privileges to the user specified in config.json so it won't retain root permissions when communicating with clients.
* You could change the DNS port to 5353 (or any other open port above 1023), but then you'd have to have something else forward DNS traffic from port 53 to newserv's DNS port, since the consoles will always try to talk to port 53.
* You could disable the DNS server entirely by setting DNSServerPort to 0 in config.json if you don't need it (e.g. if you don't intend to have DC or GC players on your server, or if you use a method other than DNS to route their connections to your server).

**Comment by gofastlily** [comment]
That was it, thanks!  I forgot my `supervisorctl` setup would cause problems with privileged ports.

In case anyone is reading this in the future, I resolved it with this command.
`setcap 'cap_net_bind_service=+ep' /path/to/newserv`

Thank you so much for you help!
