### ISSUE TITLE
Cannot Connect Dolphin PSO Ep1&2 Local Client to Newserv, Win10

### ISSUE THREAD

**Issue by APPARENTLYSORN** [fuzziqersoftware/newserv#95]
Hello,

I am having difficulty connecting both external and internal clients who use Dolphin-emulated PSO 1&2 GCN on a newserv instance running on Win10. Currently, I have not been able to get a local client to connect to my server on the same PC, and I have not tried getting a remote client to connect to the server.
I am running the 2023-03-02 macOS/Win Release of newserv, and have edited/renamed the .json config file. I'm not confident in my config settings for internal/external IP addresses, however, and I'm not able to make sense of the readme included both on the git and the release in regards to this specific set up.
In the .json, I have tried editing line 109 of the config,json to both my internal/external addresses with port 53 included, and "/tmp/dolphin-tap," with no success in connecting a local client. Using "/tmp/dolphin-tap" on line 109 and changing PSO client IP/Subnet/Gateway/DNS to dummy values, and appropriate values.
I have tried setting Dolphin's emulated BBA to both TAP (with the default mac address), and HLE (with my public IP specified).
I have forwarded all the ports that would be applicable for the server to accept (53, 9000-9202), and adding exceptions under Win Firewall for those ports/ranges. 
I apologize if this has been addressed elsewhere, but I am at a loss of how to resolve this issue.
I'd appreciate any assistance with the matter, thank you for reading, and have a good day.

**Comment by fuzziqersoftware** [comment]
Theoretically, everything should work if you do this:
* Set LocalAddress in config.json to your PC's local IPv4 address (usually something like 192.168.x.x or 10.0.x.x)
* Set ExternalAddress in config.json to your public IPv4 address (from e.g. whatismyip.com)
* In Dolphin, use the HLE BBA type and set its DNS server IP address your local IP address
* If that doesn't work, try using 127.0.0.1 for Dolphin's DNS server address instead

To get remote clients to connect, you'll probably also have to forward ports in the 5100-5124 range (see the last part of PortConfiguration in config.json), and make sure port 53 is forwarded as UDP and not TCP (the others should all be TCP). Then remote clients should be able to connect by using HLE BBA in Dolphin, and using your external address as Dolphin's DNS server address. Remote clients on real GameCubes should be able to connect by putting your external address in PSO's DNS server field during network configuration.

The IPStackListen field in config.json is used for Dolphin's tapserver BBA interface, which (somewhat confusingly) is not the same as the TAP BBA interface. tapserver is unfortunately only supported on macOS; this might change in the future, but it would take a lot of effort to get it to work in Windows.

**Comment by APPARENTLYSORN** [comment]
Thank you for the fast reply, I will try your suggestions and report back with results.

**Comment by APPARENTLYSORN** [comment]
Hello again, 

Thank you again for the previous post. While I haven't been able to fully connect a Dolphin client onto the server, I am able to get both external and internal clients to briefly ping the server before disconnecting. 

I believe the error is that my newserv config.json is not configured to allow unregistered clients.

When I change line 201of the config.json, "AllowUnregisteredUsers," from "false" to "true," or "yes," newserv.exe fails to launch.

This is the terminal read out on the server when I briefly connect my client to the server

https://pastebin.com/KaYpXiTA

On the client, I get error No.100, with the text box reading "The line was disconnected. Game over. PRESS START."

The Dolphin BBA settings were changed to HLE, targetting my public IP without port. The newserv settings are the same as the OP. Network settings within the client did not have an effect on the error code or quality of connection. 

All router ports you mentioned in your post are opened, appropriately as UDP/TCP as you specified. 
I have tried a number of different configurations of the Dolphin BBA emulator, as well as targetted IP addresses, and IPStackListen flags. These tests can be seen in this pastebin. While the formatting is poor, the results were that every configuration other than setting Dolphin BBA to my public IP resulted in error No.102, and failed to even ping the server.

https://pastebin.com/xeKTT9UX

I believe that getting the config.json to change line 201 to "true," or "yes," will solve my issues, but I can't change the setting without the server crashing on start. How can I allow unregistered users? Thank you again for the help. It has taken a while to diagnose this issue, but I am feeling excited about getting this to work.

**Comment by APPARENTLYSORN** [comment]
Hello.

I got it working! The issue was that I had a line incorrectly entered in the config.json file. I reset the config to default, made sure to only change the IP addresses and line 201 to "true," and was able to get the server working. The Dolphin BBA is currently targeting my public IP address. I will now try to get external clients to connect.

Thank you again so much for the help!
