### ISSUE TITLE
[General] Names beyond 10 characters are truncated to 10

### ISSUE THREAD

**Issue by Matt-Swift** [fuzziqersoftware/newserv#99]
See below, this is displayed in Episode 3, but the server logs also show this truncated name.

![image](https://github.com/fuzziqersoftware/newserv/assets/33199242/01820c23-0e99-4bd5-a7db-db296a69b242)

**Comment by fuzziqersoftware** [comment]
This is fixed now. The issue was that we always added a language marker before names when storing them internally, but these take up two extra bytes, which ends up truncating names longer than 10 characters.
